C:/Dev/Techstorm-v5/src/engine/modding/add_on/scriptdictionary/scriptdictionary.h File Reference
#include <angelscript.h>
#include <string>
#include <map>
Classes
class CScriptDictValue
class CScriptDictionary
class CScriptDictionary::CIterator
Macros
#define AS_USE_STLNAMES 0
Typedefs
typedef std::string dictKey_t
Functions
void RegisterScriptDictionary (asIScriptEngine *engine)
void RegisterScriptDictionary_Native (asIScriptEngine *engine)
void RegisterScriptDictionary_Generic (asIScriptEngine *engine)
Variables
END_AS_NAMESPACE typedef std::map< dictKey_t, AS_NAMESPACE_QUALIFIER CScriptDictValue > dictMap_t
Macro Definition Documentation
AS_USE_STLNAMES
#define AS_USE_STLNAMES 0
Definition at line 53 of file scriptdictionary.h.
Typedef Documentation
dictKey_t
typedef std::string dictKey_t
Definition at line 17 of file scriptdictionary.h.
Function Documentation
RegisterScriptDictionary()
void RegisterScriptDictionary (asIScriptEngine * engine)
Definition at line 1061 of file scriptdictionary.cpp.
References RegisterScriptDictionary_Generic(), and RegisterScriptDictionary_Native().
RegisterScriptDictionary_Generic()
void RegisterScriptDictionary_Generic (asIScriptEngine * engine)
Definition at line 1148 of file scriptdictionary.cpp.
References SDictionaryCache::Cleanup(), CScriptDictionary_opIndex_const_Generic(), CScriptDictionary_opIndex_Generic(), CScriptDictionaryGetKeys_Generic(), CScriptDictValue_Construct_Generic(), CScriptDictValue_Destruct_Generic(), CScriptDictValue_EnumReferences_Generic(), CScriptDictValue_FreeValue_Generic(), CScriptDictValue_opAssign_double_Generic(), CScriptDictValue_opAssign_Generic(), CScriptDictValue_opAssign_int64_Generic(), CScriptDictValue_opCast_Generic(), CScriptDictValue_opConvDouble_Generic(), CScriptDictValue_opConvInt_Generic(), CScriptDictValue_opCopyAssign_Generic(), DICTIONARY_CACHE, ScriptDictionaryAddRef_Generic(), ScriptDictionaryAssign_Generic(), ScriptDictionaryDelete_Generic(), ScriptDictionaryDeleteAll_Generic(), ScriptDictionaryEnumReferences_Generic(), ScriptDictionaryExists_Generic(), ScriptDictionaryFactory_Generic(), ScriptDictionaryGet_Generic(), ScriptDictionaryGetFlt_Generic(), ScriptDictionaryGetGCFlag_Generic(), ScriptDictionaryGetInt_Generic(), ScriptDictionaryGetRefCount_Generic(), ScriptDictionaryGetSize_Generic(), ScriptDictionaryIsEmpty_Generic(), ScriptDictionaryListFactory_Generic(), ScriptDictionaryRelease_Generic(), ScriptDictionaryReleaseAllReferences_Generic(), ScriptDictionarySet_Generic(), ScriptDictionarySetFlt_Generic(), ScriptDictionarySetGCFlag_Generic(), ScriptDictionarySetInt_Generic(), and SDictionaryCache::Setup().
Referenced by RegisterScriptDictionary().
RegisterScriptDictionary_Native()
void RegisterScriptDictionary_Native (asIScriptEngine * engine)
Definition at line 1069 of file scriptdictionary.cpp.
References CScriptDictValue_Construct(), CScriptDictValue_Destruct(), CScriptDictValue_opAssign(), CScriptDictValue_opCast(), CScriptDictValue_opConvDouble(), CScriptDictValue_opConvInt(), ScriptDictionaryFactory_Generic(), ScriptDictionaryListFactory_Generic(), and SDictionaryCache::Setup().
Referenced by RegisterScriptDictionary().
Variable Documentation
dictMap_t
END_AS_NAMESPACE typedef std::map<dictKey_t, AS_NAMESPACE_QUALIFIER CScriptDictValue> dictMap_t
Definition at line 33 of file scriptdictionary.h.