SDictionaryCache Struct Reference
Static Public Member Functions
static void Setup (asIScriptEngine *engine)
static void Cleanup (asIScriptEngine *engine)
static void Setup (asIScriptEngine *engine)
static void Cleanup (asIScriptEngine *engine)
Public Attributes
asITypeInfo * dictType
asITypeInfo * arrayType
asITypeInfo * keyType
Detailed Description
Definition at line 21 of file scriptdictionary.cpp.
Member Function Documentation
Cleanup() [1/2]
static void SDictionaryCache::Cleanup (asIScriptEngine * engine) [inline], [static]
Definition at line 44 of file scriptdictionary.cpp.
References DICTIONARY_CACHE.
Referenced by RegisterScriptDictionary_Generic(), and Setup().
Cleanup() [2/2]
static void SDictionaryCache::Cleanup (asIScriptEngine * engine) [inline], [static]
Definition at line 44 of file scriptdictionary.cpp.
References DICTIONARY_CACHE.
Setup() [1/2]
static void SDictionaryCache::Setup (asIScriptEngine * engine) [inline], [static]
Definition at line 28 of file scriptdictionary.cpp.
References arrayType, Cleanup(), DICTIONARY_CACHE, dictType, and keyType.
Referenced by RegisterScriptDictionary_Generic(), and RegisterScriptDictionary_Native().
Setup() [2/2]
static void SDictionaryCache::Setup (asIScriptEngine * engine) [inline], [static]
Definition at line 28 of file scriptdictionary.cpp.
References arrayType, Cleanup(), DICTIONARY_CACHE, dictType, and keyType.
Member Data Documentation
arrayType
asITypeInfo * SDictionaryCache::arrayType
Definition at line 24 of file scriptdictionary.cpp.
Referenced by CScriptDictionary::GetKeys(), and Setup().
dictType
asITypeInfo * SDictionaryCache::dictType
Definition at line 23 of file scriptdictionary.cpp.
Referenced by CScriptDictionary::Init(), and Setup().
keyType
asITypeInfo * SDictionaryCache::keyType
Definition at line 25 of file scriptdictionary.cpp.
Referenced by CScriptDictionary::CScriptDictionary(), and Setup().
The documentation for this struct was generated from the following files:
C:/Dev/Techstorm-v5/src/application/add_on/scriptdictionary/scriptdictionary.cpp
C:/Dev/Techstorm-v5/src/engine/modding/add_on/scriptdictionary/scriptdictionary.cpp