C:/Dev/Techstorm-v5/src/application/add_on/scriptdictionary/scriptdictionary.cpp File Reference
#include <assert.h>
#include <string.h>
#include "scriptdictionary.h"
#include "../scriptarray/scriptarray.h"
Classes
struct SDictionaryCache
Functions
void ScriptDictionaryFactory_Generic (asIScriptGeneric *gen)
void ScriptDictionaryListFactory_Generic (asIScriptGeneric *gen)
void ScriptDictionaryAddRef_Generic (asIScriptGeneric *gen)
void ScriptDictionaryRelease_Generic (asIScriptGeneric *gen)
void ScriptDictionaryAssign_Generic (asIScriptGeneric *gen)
void ScriptDictionarySet_Generic (asIScriptGeneric *gen)
void ScriptDictionarySetInt_Generic (asIScriptGeneric *gen)
void ScriptDictionarySetFlt_Generic (asIScriptGeneric *gen)
void ScriptDictionaryGet_Generic (asIScriptGeneric *gen)
void ScriptDictionaryGetInt_Generic (asIScriptGeneric *gen)
void ScriptDictionaryGetFlt_Generic (asIScriptGeneric *gen)
void ScriptDictionaryExists_Generic (asIScriptGeneric *gen)
void ScriptDictionaryIsEmpty_Generic (asIScriptGeneric *gen)
void ScriptDictionaryGetSize_Generic (asIScriptGeneric *gen)
void ScriptDictionaryDelete_Generic (asIScriptGeneric *gen)
void ScriptDictionaryDeleteAll_Generic (asIScriptGeneric *gen)
void RegisterScriptDictionary (asIScriptEngine *engine)
void RegisterScriptDictionary_Native (asIScriptEngine *engine)
void RegisterScriptDictionary_Generic (asIScriptEngine *engine)
Variables
const asPWORD DICTIONARY_CACHE = 1003
Function Documentation
RegisterScriptDictionary()
void RegisterScriptDictionary (asIScriptEngine * engine)
Definition at line 1061 of file scriptdictionary.cpp.
References RegisterScriptDictionary_Generic(), and RegisterScriptDictionary_Native().
RegisterScriptDictionary_Generic()
void RegisterScriptDictionary_Generic (asIScriptEngine * engine)
Definition at line 1148 of file scriptdictionary.cpp.
References SDictionaryCache::Cleanup(), DICTIONARY_CACHE, ScriptDictionaryAddRef_Generic(), ScriptDictionaryAssign_Generic(), ScriptDictionaryDelete_Generic(), ScriptDictionaryDeleteAll_Generic(), ScriptDictionaryExists_Generic(), ScriptDictionaryFactory_Generic(), ScriptDictionaryGet_Generic(), ScriptDictionaryGetFlt_Generic(), ScriptDictionaryGetInt_Generic(), ScriptDictionaryGetSize_Generic(), ScriptDictionaryIsEmpty_Generic(), ScriptDictionaryListFactory_Generic(), ScriptDictionaryRelease_Generic(), ScriptDictionarySet_Generic(), ScriptDictionarySetFlt_Generic(), ScriptDictionarySetInt_Generic(), and SDictionaryCache::Setup().
Referenced by RegisterScriptDictionary().
RegisterScriptDictionary_Native()
void RegisterScriptDictionary_Native (asIScriptEngine * engine)
Definition at line 1069 of file scriptdictionary.cpp.
References ScriptDictionaryFactory_Generic(), ScriptDictionaryListFactory_Generic(), and SDictionaryCache::Setup().
Referenced by RegisterScriptDictionary().
ScriptDictionaryAddRef_Generic()
void ScriptDictionaryAddRef_Generic (asIScriptGeneric * gen)
Definition at line 453 of file scriptdictionary.cpp.
References CScriptDictionary::AddRef().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionaryAssign_Generic()
void ScriptDictionaryAssign_Generic (asIScriptGeneric * gen)
Definition at line 465 of file scriptdictionary.cpp.
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionaryDelete_Generic()
void ScriptDictionaryDelete_Generic (asIScriptGeneric * gen)
Definition at line 545 of file scriptdictionary.cpp.
References CScriptDictionary::Delete().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionaryDeleteAll_Generic()
void ScriptDictionaryDeleteAll_Generic (asIScriptGeneric * gen)
Definition at line 552 of file scriptdictionary.cpp.
References CScriptDictionary::DeleteAll().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionaryExists_Generic()
void ScriptDictionaryExists_Generic (asIScriptGeneric * gen)
Definition at line 523 of file scriptdictionary.cpp.
References CScriptDictionary::Exists().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionaryFactory_Generic()
void ScriptDictionaryFactory_Generic (asIScriptGeneric * gen)
Definition at line 442 of file scriptdictionary.cpp.
References CScriptDictionary::Create().
Referenced by RegisterScriptDictionary_Generic(), and RegisterScriptDictionary_Native().
ScriptDictionaryGet_Generic()
void ScriptDictionaryGet_Generic (asIScriptGeneric * gen)
Definition at line 498 of file scriptdictionary.cpp.
References CScriptDictionary::Get().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionaryGetFlt_Generic()
void ScriptDictionaryGetFlt_Generic (asIScriptGeneric * gen)
Definition at line 515 of file scriptdictionary.cpp.
References CScriptDictionary::Get().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionaryGetInt_Generic()
void ScriptDictionaryGetInt_Generic (asIScriptGeneric * gen)
Definition at line 507 of file scriptdictionary.cpp.
References CScriptDictionary::Get().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionaryGetSize_Generic()
void ScriptDictionaryGetSize_Generic (asIScriptGeneric * gen)
Definition at line 538 of file scriptdictionary.cpp.
References CScriptDictionary::GetSize().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionaryIsEmpty_Generic()
void ScriptDictionaryIsEmpty_Generic (asIScriptGeneric * gen)
Definition at line 531 of file scriptdictionary.cpp.
References CScriptDictionary::IsEmpty().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionaryListFactory_Generic()
void ScriptDictionaryListFactory_Generic (asIScriptGeneric * gen)
Definition at line 447 of file scriptdictionary.cpp.
References CScriptDictionary::Create().
Referenced by RegisterScriptDictionary_Generic(), and RegisterScriptDictionary_Native().
ScriptDictionaryRelease_Generic()
void ScriptDictionaryRelease_Generic (asIScriptGeneric * gen)
Definition at line 459 of file scriptdictionary.cpp.
References CScriptDictionary::Release().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionarySet_Generic()
void ScriptDictionarySet_Generic (asIScriptGeneric * gen)
Definition at line 473 of file scriptdictionary.cpp.
References CScriptDictionary::Set().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionarySetFlt_Generic()
void ScriptDictionarySetFlt_Generic (asIScriptGeneric * gen)
Definition at line 490 of file scriptdictionary.cpp.
References CScriptDictionary::Set().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionarySetInt_Generic()
void ScriptDictionarySetInt_Generic (asIScriptGeneric * gen)
Definition at line 482 of file scriptdictionary.cpp.
References CScriptDictionary::Set().
Referenced by RegisterScriptDictionary_Generic().
Variable Documentation
DICTIONARY_CACHE
const asPWORD DICTIONARY_CACHE = 1003
Definition at line 16 of file scriptdictionary.cpp.
Referenced by CScriptDictionary::CScriptDictionary(), CScriptDictionary::GetKeys(), CScriptDictionary::Init(), and RegisterScriptDictionary_Generic().