Atlas::Logger Class Reference
#include <Logging.h>
Public Member Functions
void init (LoggerConfig config)
void log (std::string message, ELogLevel level=ELogLevel::DEBUG, const std::source_location &location=std::source_location::current())
Static Public Member Functions
static void RaylibLogCallback (int logLevel, const char *message, va_list args)
Static Public Member Functions inherited from Atlas::Singleton< Logger >
static Logger & Instance ()
Retrieves the current singleton instance as a reference. If you need to create a class that has a single static instance, use this class.
Private Member Functions
void InitSpdlog ()
Private Attributes
LoggerConfig mConfig
spdlog::logger * mLogger
Detailed Description
Definition at line 74 of file Logging.h.
Member Function Documentation
init()
void Atlas::Logger::init (LoggerConfig config) [inline]
Definition at line 77 of file Logging.h.
References InitSpdlog(), log(), and mConfig.
Referenced by Atlas::IProject::preInit().
InitSpdlog()
void Atlas::Logger::InitSpdlog () [inline], [private]
Definition at line 169 of file Logging.h.
References Atlas::LoggerConfig::fileLogLevel, Atlas::LoggerConfig::format, Atlas::GetSpdlogLevel(), Atlas::LoggerConfig::logFile, Atlas::LoggerConfig::loggerLevel, mConfig, mLogger, and Atlas::LoggerConfig::terminalLogLevel.
Referenced by init().
log()
void Atlas::Logger::log (std::string message, ELogLevel level = ELogLevel::DEBUG, const std::source_location & location = std::source_location::current()) [inline]
Definition at line 83 of file Logging.h.
Referenced by Atlas::FileSystemRegistry::init(), init(), Atlas::Log(), and RaylibLogCallback().
RaylibLogCallback()
static void Atlas::Logger::RaylibLogCallback (int logLevel, const char * message, va_list args) [inline], [static]
Definition at line 140 of file Logging.h.
References Atlas::Singleton< Logger >::Instance(), and log().
Member Data Documentation
mConfig
LoggerConfig Atlas::Logger::mConfig [private]
Definition at line 163 of file Logging.h.
Referenced by init(), and InitSpdlog().
mLogger
spdlog::logger* Atlas::Logger::mLogger [private]
Definition at line 165 of file Logging.h.
Referenced by InitSpdlog().
The documentation for this class was generated from the following file:
C:/Dev/Techstorm-v5/src/engine/dbg/Logging.h