C:/Dev/Techstorm-v5/src/engine/modding/add_on/scriptany/scriptany.cpp File Reference
#include "scriptany.h"
#include <new>
#include <assert.h>
#include <string.h>
Functions
static BEGIN_AS_NAMESPACE void ScriptAnyFactory_Generic (asIScriptGeneric *gen)
static void ScriptAnyFactory2_Generic (asIScriptGeneric *gen)
static CScriptAny & ScriptAnyAssignment (CScriptAny *other, CScriptAny *self)
static void ScriptAnyAssignment_Generic (asIScriptGeneric *gen)
static void ScriptAny_Store_Generic (asIScriptGeneric *gen)
static void ScriptAny_StoreInt_Generic (asIScriptGeneric *gen)
static void ScriptAny_StoreFlt_Generic (asIScriptGeneric *gen)
static void ScriptAny_Retrieve_Generic (asIScriptGeneric *gen)
static void ScriptAny_RetrieveInt_Generic (asIScriptGeneric *gen)
static void ScriptAny_RetrieveFlt_Generic (asIScriptGeneric *gen)
static void ScriptAny_AddRef_Generic (asIScriptGeneric *gen)
static void ScriptAny_Release_Generic (asIScriptGeneric *gen)
static void ScriptAny_GetRefCount_Generic (asIScriptGeneric *gen)
static void ScriptAny_SetFlag_Generic (asIScriptGeneric *gen)
static void ScriptAny_GetFlag_Generic (asIScriptGeneric *gen)
static void ScriptAny_EnumReferences_Generic (asIScriptGeneric *gen)
static void ScriptAny_ReleaseAllHandles_Generic (asIScriptGeneric *gen)
void RegisterScriptAny (asIScriptEngine *engine)
void RegisterScriptAny_Native (asIScriptEngine *engine)
void RegisterScriptAny_Generic (asIScriptEngine *engine)
Function Documentation
RegisterScriptAny()
void RegisterScriptAny (asIScriptEngine * engine)
Definition at line 134 of file scriptany.cpp.
References RegisterScriptAny_Generic(), and RegisterScriptAny_Native().
RegisterScriptAny_Generic()
void RegisterScriptAny_Generic (asIScriptEngine * engine)
Definition at line 171 of file scriptany.cpp.
References ScriptAny_AddRef_Generic(), ScriptAny_EnumReferences_Generic(), ScriptAny_GetFlag_Generic(), ScriptAny_GetRefCount_Generic(), ScriptAny_Release_Generic(), ScriptAny_ReleaseAllHandles_Generic(), ScriptAny_Retrieve_Generic(), ScriptAny_RetrieveFlt_Generic(), ScriptAny_RetrieveInt_Generic(), ScriptAny_SetFlag_Generic(), ScriptAny_Store_Generic(), ScriptAny_StoreFlt_Generic(), ScriptAny_StoreInt_Generic(), ScriptAnyAssignment_Generic(), ScriptAnyFactory2_Generic(), and ScriptAnyFactory_Generic().
RegisterScriptAny_Native()
void RegisterScriptAny_Native (asIScriptEngine * engine)
Definition at line 142 of file scriptany.cpp.
References ScriptAnyAssignment(), ScriptAnyFactory2_Generic(), and ScriptAnyFactory_Generic().
Referenced by RegisterScriptAny().
ScriptAny_AddRef_Generic()
static void ScriptAny_AddRef_Generic (asIScriptGeneric * gen) [static]
Definition at line 90 of file scriptany.cpp.
References CScriptAny::AddRef().
ScriptAny_EnumReferences_Generic()
static void ScriptAny_EnumReferences_Generic (asIScriptGeneric * gen) [static]
Definition at line 120 of file scriptany.cpp.
References CScriptAny::EnumReferences().
ScriptAny_GetFlag_Generic()
static void ScriptAny_GetFlag_Generic (asIScriptGeneric * gen) [static]
Definition at line 114 of file scriptany.cpp.
References CScriptAny::GetFlag().
ScriptAny_GetRefCount_Generic()
static void ScriptAny_GetRefCount_Generic (asIScriptGeneric * gen) [static]
Definition at line 102 of file scriptany.cpp.
References CScriptAny::GetRefCount().
ScriptAny_Release_Generic()
static void ScriptAny_Release_Generic (asIScriptGeneric * gen) [static]
Definition at line 96 of file scriptany.cpp.
References CScriptAny::Release().
ScriptAny_ReleaseAllHandles_Generic()
static void ScriptAny_ReleaseAllHandles_Generic (asIScriptGeneric * gen) [static]
Definition at line 127 of file scriptany.cpp.
References CScriptAny::ReleaseAllHandles().
ScriptAny_Retrieve_Generic()
static void ScriptAny_Retrieve_Generic (asIScriptGeneric * gen) [static]
Definition at line 65 of file scriptany.cpp.
References CScriptAny::Retrieve().
ScriptAny_RetrieveFlt_Generic()
static void ScriptAny_RetrieveFlt_Generic (asIScriptGeneric * gen) [static]
Definition at line 82 of file scriptany.cpp.
References CScriptAny::Retrieve().
ScriptAny_RetrieveInt_Generic()
static void ScriptAny_RetrieveInt_Generic (asIScriptGeneric * gen) [static]
Definition at line 74 of file scriptany.cpp.
References CScriptAny::Retrieve().
ScriptAny_SetFlag_Generic()
static void ScriptAny_SetFlag_Generic (asIScriptGeneric * gen) [static]
Definition at line 108 of file scriptany.cpp.
References CScriptAny::SetFlag().
ScriptAny_Store_Generic()
static void ScriptAny_Store_Generic (asIScriptGeneric * gen) [static]
Definition at line 40 of file scriptany.cpp.
References CScriptAny::Store().
ScriptAny_StoreFlt_Generic()
static void ScriptAny_StoreFlt_Generic (asIScriptGeneric * gen) [static]
Definition at line 57 of file scriptany.cpp.
References CScriptAny::Store().
Referenced by RegisterScriptAny_Generic().
ScriptAny_StoreInt_Generic()
static void ScriptAny_StoreInt_Generic (asIScriptGeneric * gen) [static]
Definition at line 49 of file scriptany.cpp.
References CScriptAny::Store().
ScriptAnyAssignment()
static CScriptAny & ScriptAnyAssignment (CScriptAny * other, CScriptAny * self) [static]
Definition at line 25 of file scriptany.cpp.
ScriptAnyAssignment_Generic()
static void ScriptAnyAssignment_Generic (asIScriptGeneric * gen) [static]
Definition at line 30 of file scriptany.cpp.
ScriptAnyFactory2_Generic()
static void ScriptAnyFactory2_Generic (asIScriptGeneric * gen) [static]
Definition at line 16 of file scriptany.cpp.
ScriptAnyFactory_Generic()
static BEGIN_AS_NAMESPACE void ScriptAnyFactory_Generic (asIScriptGeneric * gen) [static]
Definition at line 9 of file scriptany.cpp.