Atlas::GameCamera::DirectionalInput Class Reference
Directional input.
Public Member Functions
DirectionalInput (float value)
Initializes a new instance of the DirectionalInput class.
DirectionalInput ()=default
Initializes a new instance of the DirectionalInput class.
void reset ()
Resets the value associated with this input.
void set (float value)
Sets mValue to the specified floating point value.
void add (float value)
Adds mValue with the specified value.
float getValue () const
Gets the value.
operator float () const
Implements the operator float.
DirectionalInput & operator= (float value)
This operator sets mValue to the value parameter value.
DirectionalInput & operator+= (float value)
This just increments mValue by the value parameter value.
Private Attributes
float mValue = 0.0f
the underlying value that is associated with this direction.
std::mutex mMutex
The mutex that ensures that this input is thread safe.
Detailed Description
Directional input.
Since
v0.0.8
Note
This is currently not used, but there is plans for it to be used in the future, hence it is still here and not deprecated.
Todo
Todo Implement this in mDirectionalInput.
Definition at line 32 of file GameCamera.h.
Constructor & Destructor Documentation
DirectionalInput() [1/2]
Atlas::GameCamera::DirectionalInput::DirectionalInput (float value) [inline]
Initializes a new instance of the DirectionalInput class.
Parameters
value The floating point value to associate with this input.
Since
v0.0.8
Definition at line 54 of file GameCamera.h.
DirectionalInput() [2/2]
Atlas::GameCamera::DirectionalInput::DirectionalInput () [default]
Initializes a new instance of the DirectionalInput class.
Remarks
This is the default constructor.
Since
v0.0.8
Member Function Documentation
add()
void Atlas::GameCamera::DirectionalInput::add (float value) [inline]
Adds mValue with the specified value.
Parameters
value the delta to add mValue with.
Note
This is thread safe and locks the mutex.
Since
v0.0.8
Definition at line 90 of file GameCamera.h.
References mMutex, and mValue.
Referenced by operator+=().
getValue()
float Atlas::GameCamera::DirectionalInput::getValue () const [inline]
Gets the value.
Remarks
This only returns a float, not a reference.
Returns
The current value of mValue.
Since
v0.0.8
Definition at line 101 of file GameCamera.h.
References mValue.
operator float()
Atlas::GameCamera::DirectionalInput::operator float () const [inline]
Implements the operator float.
Returns
The result of the operator.
Since
v0.0.8
Definition at line 108 of file GameCamera.h.
References mValue.
operator+=()
DirectionalInput & Atlas::GameCamera::DirectionalInput::operator+= (float value) [inline]
This just increments mValue by the value parameter value.
Remarks
This is thread safe and locks the mutex. Additionally, it returns a reference to this object after it has ADDED to mValue. In other words, this works the same way as the add function
Parameters
value The value to ADD to mValue.
Returns
Since
v0.0.8
Definition at line 130 of file GameCamera.h.
References add().
operator=()
DirectionalInput & Atlas::GameCamera::DirectionalInput::operator= (float value) [inline]
This operator sets mValue to the value parameter value.
Remarks
This is thread safe and locks the mutex.
Parameters
value The value to SET mValue to.
Returns
A reference to this object after setting mValue.
Since
v0.0.8
Definition at line 117 of file GameCamera.h.
References set().
reset()
void Atlas::GameCamera::DirectionalInput::reset () [inline]
Resets the value associated with this input.
Note
This is thread safe and locks the mutex.
Since
v0.0.8
Definition at line 68 of file GameCamera.h.
References mMutex, and mValue.
set()
void Atlas::GameCamera::DirectionalInput::set (float value) [inline]
Sets mValue to the specified floating point value.
Parameters
value What float to set mValue to.
Note
This is thread safe and locks the mutex.
Since
v0.0.8
Definition at line 79 of file GameCamera.h.
References mMutex, and mValue.
Referenced by operator=().
Member Data Documentation
mMutex
std::mutex Atlas::GameCamera::DirectionalInput::mMutex [private]
The mutex that ensures that this input is thread safe.
Since
v0.0.8
Definition at line 45 of file GameCamera.h.
Referenced by add(), reset(), and set().
mValue
float Atlas::GameCamera::DirectionalInput::mValue = 0.0f [private]
the underlying value that is associated with this direction.
Since
v0.0.8
Definition at line 39 of file GameCamera.h.
Referenced by add(), getValue(), operator float(), reset(), and set().
The documentation for this class was generated from the following file:
C:/Dev/Techstorm-v5/src/engine/renderer/GameCamera.h