CScriptDictValue Class Reference
#include <scriptdictionary.h>
Public Member Functions
CScriptDictValue ()
CScriptDictValue (asIScriptEngine *engine, void *value, int typeId)
~CScriptDictValue ()
void Set (asIScriptEngine *engine, void *value, int typeId)
void Set (asIScriptEngine *engine, const asINT64 &value)
void Set (asIScriptEngine *engine, const double &value)
void Set (asIScriptEngine *engine, CScriptDictValue &value)
bool Get (asIScriptEngine *engine, void *value, int typeId) const
bool Get (asIScriptEngine *engine, asINT64 &value) const
bool Get (asIScriptEngine *engine, double &value) const
const void * GetAddressOfValue () const
int GetTypeId () const
void FreeValue (asIScriptEngine *engine)
void EnumReferences (asIScriptEngine *engine)
Protected Attributes
xx xx xx xx xx xx xx xx xx
union {
 asINT64 m_valueInt
 double m_valueFlt
 void * m_valueObj
};
int m_typeId
Friends
class CScriptDictionary
Detailed Description
Definition at line 62 of file scriptdictionary.h.
Constructor & Destructor Documentation
CScriptDictValue() [1/2]
CScriptDictValue::CScriptDictValue ()
Definition at line 614 of file scriptdictionary.cpp.
References m_typeId, and m_valueObj.
CScriptDictValue() [2/2]
CScriptDictValue::CScriptDictValue (asIScriptEngine * engine, void * value, int typeId)
Definition at line 620 of file scriptdictionary.cpp.
References m_typeId, m_valueObj, and Set().
~CScriptDictValue()
CScriptDictValue::~CScriptDictValue ()
Definition at line 627 of file scriptdictionary.cpp.
References FreeValue(), m_typeId, and m_valueObj.
Referenced by CScriptDictValue_Destruct().
Member Function Documentation
EnumReferences()
void CScriptDictValue::EnumReferences (asIScriptEngine * engine)
Definition at line 656 of file scriptdictionary.cpp.
References m_typeId, and m_valueObj.
Referenced by CScriptDictValue_EnumReferences_Generic().
FreeValue()
void CScriptDictValue::FreeValue (asIScriptEngine * engine)
Definition at line 642 of file scriptdictionary.cpp.
References m_typeId, and m_valueObj.
Referenced by CScriptDictValue_Destruct(), CScriptDictValue_FreeValue_Generic(), Set(), and ~CScriptDictValue().
Get() [1/3]
bool CScriptDictValue::Get (asIScriptEngine * engine, asINT64 & value) const
Definition at line 897 of file scriptdictionary.cpp.
References Get().
Get() [2/3]
bool CScriptDictValue::Get (asIScriptEngine * engine, double & value) const
Definition at line 902 of file scriptdictionary.cpp.
References Get().
Get() [3/3]
bool CScriptDictValue::Get (asIScriptEngine * engine, void * value, int typeId) const
Definition at line 727 of file scriptdictionary.cpp.
References m_typeId, m_valueFlt, m_valueInt, and m_valueObj.
Referenced by CScriptDictValue_opCast(), CScriptDictValue_opCast_Generic(), CScriptDictValue_opConvDouble_Generic(), CScriptDictValue_opConvInt_Generic(), Get(), and Get().
GetAddressOfValue()
const void * CScriptDictValue::GetAddressOfValue () const
Definition at line 885 of file scriptdictionary.cpp.
References m_typeId, and m_valueObj.
GetTypeId()
int CScriptDictValue::GetTypeId () const
Definition at line 907 of file scriptdictionary.cpp.
References m_typeId.
Set() [1/4]
void CScriptDictValue::Set (asIScriptEngine * engine, const asINT64 & value)
Definition at line 713 of file scriptdictionary.cpp.
References Set().
Set() [2/4]
void CScriptDictValue::Set (asIScriptEngine * engine, const double & value)
Definition at line 722 of file scriptdictionary.cpp.
References Set().
Set() [3/4]
void CScriptDictValue::Set (asIScriptEngine * engine, CScriptDictValue & value)
Definition at line 698 of file scriptdictionary.cpp.
References Set().
Set() [4/4]
void CScriptDictValue::Set (asIScriptEngine * engine, void * value, int typeId)
Definition at line 667 of file scriptdictionary.cpp.
References FreeValue(), m_typeId, m_valueInt, and m_valueObj.
Referenced by CScriptDictValue(), CScriptDictValue_opAssign(), CScriptDictValue_opAssign(), Set(), Set(), and Set().
Friends And Related Symbol Documentation
CScriptDictionary
friend class CScriptDictionary [friend]
Definition at line 98 of file scriptdictionary.h.
Member Data Documentation
[union]
union { ... } CScriptDictValue [protected]
m_typeId
int CScriptDictValue::m_typeId [protected]
Definition at line 106 of file scriptdictionary.h.
Referenced by CScriptDictValue(), CScriptDictValue(), EnumReferences(), FreeValue(), Get(), GetAddressOfValue(), GetTypeId(), Set(), and ~CScriptDictValue().
m_valueFlt
double CScriptDictValue::m_valueFlt
Definition at line 103 of file scriptdictionary.h.
Referenced by Get().
m_valueInt
asINT64 CScriptDictValue::m_valueInt
Definition at line 102 of file scriptdictionary.h.
Referenced by Get(), and Set().
m_valueObj
void* CScriptDictValue::m_valueObj
Definition at line 104 of file scriptdictionary.h.
Referenced by CScriptDictValue(), CScriptDictValue(), EnumReferences(), FreeValue(), Get(), GetAddressOfValue(), Set(), and ~CScriptDictValue().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/application/add_on/scriptdictionary/scriptdictionary.h
C:/Dev/Techstorm-v5/src/application/add_on/scriptdictionary/scriptdictionary.cpp