Atlas::IProject Class Reference
This is the interface for the user's project. This is the only interface that Atlas will call.
#include <Project.h>
Classes
class ProjectReference
Represents a polymorphic singleton reference to the user's project instance through a pointer of Atlas::IProject. This is mandatory for Atlas to run the user's engine.
Public Member Functions
ScriptingLibraryRegistry & getLuaLibraries ()
Returns the currently active libraries for lua.
ScriptingFunctionRegistry & getLuaFunctions ()
Gets the lua functions.
WindowDecorations & getWindowDecorations ()
Gets the window decorations. This includes the window title, icon, size, etc.
void setWindowDecorations (WindowDecorations &windowDecorations)
Sets the window decorations.
Renderer & getRenderer ()
Gets the renderer instance.
template<typename T >
void setProject (T *project)
This function is used to set the ProjectReference singleton to the project.
virtual void preInit ()
This is the first function that will be called on startup.
virtual void init (int argc, char *argv[])
Initializes your project. This will be called after preInit and window initialization, meaning that this is the earliest point that you can use raylib. THIS MUST BE OVERRIDEN BY YOUR PROJECT CLASS!
virtual void postInit ()
Does a post initialization of the project. This is empty because it is not neccesary to override.
virtual void initRenderer ()
Initializes the renderer and should be called after initWindow.
virtual int run (int argc, char *argv[])
Runs the actual game and is called after the init functions.
virtual int update ()
virtual int prePhysicsUpdate ()
Pre-update step that is called in the physics or update thread (depending on thread count)
virtual int physicsUpdate ()
This is where the actual physics update happens. Please note that this will run on the physics thread!
virtual int postPhysicsUpdate ()
Post physics update that is called after physicsUpdate() in the physics or update thread (depending on thread count).
virtual int preObjectUpdate ()
Any preparation code for updating the scene's game objects. Use this if you need to do something after the physics update, but before the GameObject update. Please note that this will run on the update thread!
virtual int objectUpdate ()
This is where the actual GameObject update happens, and is called after preObjectUpdate(). Please note that this will run on the update thread!
virtual int postObjectUpdate ()
Called right after objectUpdate(). Use this to do anything after the GameObject update. Please note that this will run on the update thread!
virtual int texture ()
Textures all GameObjects before render() is called and after update functions are called. This is essentially where the scene is rendered. Please note that this will run on the render thread!
virtual int render ()
Assuming that the FBO is enabled, this will render the FBO and apply any post-processing effects to the FBO. Please note that this will run on the update thread!
virtual int cleanup (int exitCode)
Cleans up anything that may need to be cleaned up.
Static Public Member Functions
static IProject * GetProject ()
Gets the current project instance.
Public Attributes
GameSettings settings
Protected Attributes
Renderer mRenderer
WindowDecorations mWindowDecorations
ScriptingLibraryRegistry mLuaLibraries
ScriptingFunctionRegistry mLuaFunctions
Detailed Description
This is the interface for the user's project. This is the only interface that Atlas will call.
This is an abstract interface singleton that all projects must implement and set the ProjectReference singleton to their project. In terms of functionality, this interface just holds the functions and variables that Atlas will call (besides some initialization).
Note
If this boilerplate code is not done, Atlas will not know what to run.
Warning
Do not directly call window code in here or your project will crash!
Definition at line 33 of file Project.h.
Member Function Documentation
cleanup()
int Atlas::IProject::cleanup (int exitCode) [virtual]
Cleans up anything that may need to be cleaned up.
Parameters
exitCode The code that the engine has exited with
Returns
The cleanup exit code.
Definition at line 84 of file Project.cpp.
getLuaFunctions()
ScriptingFunctionRegistry & Atlas::IProject::getLuaFunctions () [inline]
Gets the lua functions.
Returns
A reference to mLuaFunctions
Definition at line 68 of file Project.h.
References mLuaFunctions.
getLuaLibraries()
ScriptingLibraryRegistry & Atlas::IProject::getLuaLibraries () [inline]
Returns the currently active libraries for lua.
Returns
A reference to mLuaLibraries
Definition at line 62 of file Project.h.
References mLuaLibraries.
GetProject()
IProject * Atlas::IProject::GetProject () [static]
Gets the current project instance.
Returns
An IProject pointer of the current project reference instance
Definition at line 86 of file Project.cpp.
getRenderer()
Renderer & Atlas::IProject::getRenderer () [inline]
Gets the renderer instance.
Returns
This project's mRenderer variable
Definition at line 87 of file Project.h.
References mRenderer.
getWindowDecorations()
WindowDecorations & Atlas::IProject::getWindowDecorations ()
Gets the window decorations. This includes the window title, icon, size, etc.
Returns
A reference to mWindowDecorations
Definition at line 6 of file Project.cpp.
References mWindowDecorations.
init()
void Atlas::IProject::init (int argc, char * argv[]) [virtual]
Initializes your project. This will be called after preInit and window initialization, meaning that this is the earliest point that you can use raylib. THIS MUST BE OVERRIDEN BY YOUR PROJECT CLASS!
Parameters
argc Command line argument count int
argv Command line arguments array
Definition at line 33 of file Project.cpp.
References Atlas::PhysicsEngine::init(), and Atlas::Singleton< PhysicsEngine >::Instance().
initRenderer()
void Atlas::IProject::initRenderer () [virtual]
Initializes the renderer and should be called after initWindow.
Definition at line 47 of file Project.cpp.
objectUpdate()
int Atlas::IProject::objectUpdate () [virtual]
This is where the actual GameObject update happens, and is called after preObjectUpdate(). Please note that this will run on the update thread!
Returns
The exit code of the step
Definition at line 70 of file Project.cpp.
physicsUpdate()
int Atlas::IProject::physicsUpdate () [virtual]
This is where the actual physics update happens. Please note that this will run on the physics thread!
Returns
The exit code of the step
Definition at line 61 of file Project.cpp.
References Atlas::Singleton< PhysicsEngine >::Instance(), and Atlas::PhysicsEngine::update().
postInit()
void Atlas::IProject::postInit () [virtual]
Does a post initialization of the project. This is empty because it is not neccesary to override.
Reimplemented in SamplesProject.
Definition at line 41 of file Project.cpp.
postObjectUpdate()
int Atlas::IProject::postObjectUpdate () [virtual]
Called right after objectUpdate(). Use this to do anything after the GameObject update. Please note that this will run on the update thread!
Returns
Definition at line 72 of file Project.cpp.
postPhysicsUpdate()
int Atlas::IProject::postPhysicsUpdate () [virtual]
Post physics update that is called after physicsUpdate() in the physics or update thread (depending on thread count).
Returns
The exit code of the step
Definition at line 66 of file Project.cpp.
preInit()
void Atlas::IProject::preInit () [virtual]
This is the first function that will be called on startup.
Reimplemented in Project.
Definition at line 10 of file Project.cpp.
References Atlas::AddFileRegistryLoadFunction(), ATLAS_GAME_DIR, Atlas::Logger::init(), Atlas::InitializeFileRegistry(), Atlas::Singleton< Logger >::Instance(), and Atlas::Log().
preObjectUpdate()
int Atlas::IProject::preObjectUpdate () [virtual]
Any preparation code for updating the scene's game objects. Use this if you need to do something after the physics update, but before the GameObject update. Please note that this will run on the update thread!
Returns
The exit code of the step
Definition at line 68 of file Project.cpp.
prePhysicsUpdate()
int Atlas::IProject::prePhysicsUpdate () [virtual]
Pre-update step that is called in the physics or update thread (depending on thread count)
Returns
The exit code of the step
Definition at line 59 of file Project.cpp.
render()
int Atlas::IProject::render () [virtual]
Assuming that the FBO is enabled, this will render the FBO and apply any post-processing effects to the FBO. Please note that this will run on the update thread!
Returns
An integer that is the exit code for this rendering frame.
Definition at line 79 of file Project.cpp.
run()
int Atlas::IProject::run (int argc, char * argv[]) [virtual]
Runs the actual game and is called after the init functions.
Parameters
argc Command line argument count int
argv Command line arguments array
Returns
The game loop's exit code
Definition at line 50 of file Project.cpp.
setProject()
template<typename T >
void Atlas::IProject::setProject (T * project) [inline]
This function is used to set the ProjectReference singleton to the project.
Template Parameters
T The typename for what the user's project is
Parameters
project The pointer to the user's project
Definition at line 214 of file Project.h.
References Atlas::Singleton< ProjectReference >::Instance(), and Atlas::IProject::ProjectReference::setProjectReference().
setWindowDecorations()
void Atlas::IProject::setWindowDecorations (WindowDecorations & windowDecorations)
Sets the window decorations.
See also
Atlas::WindowDecorations
Parameters
windowDecorations The window decorations.
Definition at line 8 of file Project.cpp.
texture()
int Atlas::IProject::texture () [virtual]
Textures all GameObjects before render() is called and after update functions are called. This is essentially where the scene is rendered. Please note that this will run on the render thread!
Returns
An integer that is the exit code for this texturing frame.
Definition at line 74 of file Project.cpp.
update()
int Atlas::IProject::update () [virtual]
Reimplemented in SamplesProject.
Definition at line 54 of file Project.cpp.
Member Data Documentation
mLuaFunctions
ScriptingFunctionRegistry Atlas::IProject::mLuaFunctions [protected]
Definition at line 38 of file Project.h.
Referenced by getLuaFunctions().
mLuaLibraries
ScriptingLibraryRegistry Atlas::IProject::mLuaLibraries [protected]
Definition at line 37 of file Project.h.
Referenced by getLuaLibraries().
mRenderer
Renderer Atlas::IProject::mRenderer [protected]
Definition at line 35 of file Project.h.
Referenced by getRenderer().
mWindowDecorations
WindowDecorations Atlas::IProject::mWindowDecorations [protected]
Definition at line 36 of file Project.h.
Referenced by getWindowDecorations().
settings
GameSettings Atlas::IProject::settings
Definition at line 56 of file Project.h.
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/Project.h
C:/Dev/Techstorm-v5/src/engine/Project.cpp