Atlas::Counter Class Reference
#include <Common.h>
Public Member Functions
Counter (int64_t count, int64_t max)
ATLAS_EXPLICIT Counter (int64_t count)
Counter ()=default
bool isCapped () const
bool hasReachedMax () const
void increment (int64_t count)
void increment ()
void decrement (int64_t count)
void decrement ()
void reset ()
int64_t getCount () const
int64_t getMaxCount () const
int64_t getRemainingCount () const
void setCount (int64_t count)
void setMaxCount (int64_t max)
void setCountAndMaxCount (int64_t count, int64_t max)
Private Attributes
int64_t mCount = 0
int64_t mMaxCount = -1
bool mbIsCapped = false
Detailed Description
Definition at line 412 of file Common.h.
Constructor & Destructor Documentation
Counter() [1/3]
Atlas::Counter::Counter (int64_t count, int64_t max) [inline]
Definition at line 418 of file Common.h.
Counter() [2/3]
ATLAS_EXPLICIT Atlas::Counter::Counter (int64_t count) [inline]
Definition at line 420 of file Common.h.
Counter() [3/3]
Atlas::Counter::Counter () [default]
Member Function Documentation
decrement() [1/2]
void Atlas::Counter::decrement () [inline]
Definition at line 444 of file Common.h.
References decrement().
Referenced by decrement().
decrement() [2/2]
void Atlas::Counter::decrement (int64_t count) [inline]
Definition at line 440 of file Common.h.
References mCount.
getCount()
int64_t Atlas::Counter::getCount () const [inline]
Definition at line 454 of file Common.h.
References mCount.
getMaxCount()
int64_t Atlas::Counter::getMaxCount () const [inline]
Definition at line 458 of file Common.h.
References mMaxCount.
getRemainingCount()
int64_t Atlas::Counter::getRemainingCount () const [inline]
Definition at line 462 of file Common.h.
References mCount, and mMaxCount.
hasReachedMax()
bool Atlas::Counter::hasReachedMax () const [inline]
Definition at line 428 of file Common.h.
References mbIsCapped, mCount, and mMaxCount.
increment() [1/2]
void Atlas::Counter::increment () [inline]
Definition at line 436 of file Common.h.
References increment().
Referenced by increment().
increment() [2/2]
void Atlas::Counter::increment (int64_t count) [inline]
Definition at line 432 of file Common.h.
References mCount.
isCapped()
bool Atlas::Counter::isCapped () const [inline]
Definition at line 424 of file Common.h.
References mbIsCapped.
reset()
void Atlas::Counter::reset () [inline]
Definition at line 448 of file Common.h.
References mbIsCapped, mCount, and mMaxCount.
setCount()
void Atlas::Counter::setCount (int64_t count) [inline]
Definition at line 466 of file Common.h.
References mCount.
Referenced by setCountAndMaxCount().
setCountAndMaxCount()
void Atlas::Counter::setCountAndMaxCount (int64_t count, int64_t max) [inline]
Definition at line 480 of file Common.h.
References setCount(), and setMaxCount().
setMaxCount()
void Atlas::Counter::setMaxCount (int64_t max) [inline]
Definition at line 470 of file Common.h.
References mbIsCapped, and mMaxCount.
Referenced by setCountAndMaxCount().
Member Data Documentation
mbIsCapped
bool Atlas::Counter::mbIsCapped = false [private]
Definition at line 416 of file Common.h.
Referenced by hasReachedMax(), isCapped(), reset(), and setMaxCount().
mCount
int64_t Atlas::Counter::mCount = 0 [private]
Definition at line 414 of file Common.h.
Referenced by decrement(), getCount(), getRemainingCount(), hasReachedMax(), increment(), reset(), and setCount().
mMaxCount
int64_t Atlas::Counter::mMaxCount = -1 [private]
Definition at line 415 of file Common.h.
Referenced by getMaxCount(), getRemainingCount(), hasReachedMax(), reset(), and setMaxCount().
The documentation for this class was generated from the following file:
C:/Dev/Techstorm-v5/src/engine/core/Common.h