Atlas::VulkanInstanceWrapper Class Reference
Acts as a wrapper for VkInstance and it's debug messenger. Furthermore, this class handles it's own initialization and shutdown.
#include <VulkanInstance.h>
Classes
struct InitConfiguration
Public Member Functions
VulkanInstanceWrapper (vkb::InstanceBuilder instanceBuilder)
VulkanInstanceWrapper (InitConfiguration const &initConfiguration=InitConfiguration{})
~VulkanInstanceWrapper ()
uint16_t init ()
void shutdown ()
VkInstance & getInstance ()
VkDebugUtilsMessengerEXT & getDebugMessenger ()
vkb::Instance & getVulkanBootstrapInstance ()
operator const VkInstance & () const
Static Private Member Functions
static vkb::InstanceBuilder CreateInstanceBuilder (InitConfiguration const &initConfiguration)
Private Attributes
vkb::Instance mVulkanBootstrapInstance
VkInstance mVulkanInstance { VK_NULL_HANDLE }
According to the Khronos specification, VkInstance is an opaque handle to a Vulkan instance. By default, this is set to VK_NULL_HANDLE.
VkDebugUtilsMessengerEXT mDebugMessenger { VK_NULL_HANDLE }
InitConfiguration mInitConfiguration
Version mVulkanVersion
bool mbEnableValidationLayers { ATLAS_ENABLE_VALIDATION_LAYERS }
Friends
class VulkanRenderingBackend
Detailed Description
Acts as a wrapper for VkInstance and it's debug messenger. Furthermore, this class handles it's own initialization and shutdown.
Since
v0.0.1
Definition at line 39 of file VulkanInstance.h.
Constructor & Destructor Documentation
VulkanInstanceWrapper() [1/2]
Atlas::VulkanInstanceWrapper::VulkanInstanceWrapper (vkb::InstanceBuilder instanceBuilder) [explicit]
VulkanInstanceWrapper() [2/2]
Atlas::VulkanInstanceWrapper::VulkanInstanceWrapper (InitConfiguration const & initConfiguration = InitConfiguration{}) [explicit]
Definition at line 49 of file VulkanInstance.cpp.
~VulkanInstanceWrapper()
Atlas::VulkanInstanceWrapper::~VulkanInstanceWrapper ()
Definition at line 55 of file VulkanInstance.cpp.
Member Function Documentation
CreateInstanceBuilder()
vkb::InstanceBuilder Atlas::VulkanInstanceWrapper::CreateInstanceBuilder (InitConfiguration const & initConfiguration) [inline], [static], [private]
Definition at line 25 of file VulkanInstance.cpp.
References Atlas::VulkanInstanceWrapper::InitConfiguration::applicationName, Atlas::VulkanInstanceWrapper::InitConfiguration::atlasVersion, Atlas::VulkanInstanceWrapper::InitConfiguration::bEnableValidationLayers, Atlas::DefaultVulkanDebugCallback(), Atlas::VulkanInstanceWrapper::InitConfiguration::engineName, Atlas::Version::major, Atlas::Version::minor, Atlas::VulkanInstanceWrapper::InitConfiguration::optionalDebugMessengerCallback, Atlas::Version::patch, and Atlas::VulkanInstanceWrapper::InitConfiguration::vulkanVersion.
getDebugMessenger()
VkDebugUtilsMessengerEXT & Atlas::VulkanInstanceWrapper::getDebugMessenger ()
Definition at line 125 of file VulkanInstance.cpp.
getInstance()
VkInstance & Atlas::VulkanInstanceWrapper::getInstance ()
Definition at line 121 of file VulkanInstance.cpp.
getVulkanBootstrapInstance()
vkb::Instance & Atlas::VulkanInstanceWrapper::getVulkanBootstrapInstance ()
Definition at line 129 of file VulkanInstance.cpp.
Referenced by Atlas::PhysicalDevice::selectDevice().
init()
uint16_t Atlas::VulkanInstanceWrapper::init ()
Definition at line 78 of file VulkanInstance.cpp.
References Atlas::VulkanInstanceWrapper::InitConfiguration::applicationName, ATLAS_ASSERT, Atlas::VulkanInstanceWrapper::InitConfiguration::atlasVersion, Atlas::VulkanInstanceWrapper::InitConfiguration::bEnableValidationLayers, Atlas::DefaultVulkanDebugCallback(), Atlas::VulkanInstanceWrapper::InitConfiguration::engineName, Atlas::Version::major, Atlas::Version::minor, Atlas::VulkanInstanceWrapper::InitConfiguration::optionalDebugMessengerCallback, Atlas::Version::patch, and Atlas::VulkanInstanceWrapper::InitConfiguration::vulkanVersion.
operator const VkInstance &()
Atlas::VulkanInstanceWrapper::operator const VkInstance & () const [explicit]
Definition at line 133 of file VulkanInstance.cpp.
shutdown()
void Atlas::VulkanInstanceWrapper::shutdown ()
Definition at line 115 of file VulkanInstance.cpp.
Friends And Related Symbol Documentation
VulkanRenderingBackend
friend class VulkanRenderingBackend [friend]
Definition at line 53 of file VulkanInstance.h.
Member Data Documentation
mbEnableValidationLayers
bool Atlas::VulkanInstanceWrapper::mbEnableValidationLayers { ATLAS_ENABLE_VALIDATION_LAYERS } [private]
Definition at line 78 of file VulkanInstance.h.
mDebugMessenger
VkDebugUtilsMessengerEXT Atlas::VulkanInstanceWrapper::mDebugMessenger { VK_NULL_HANDLE } [private]
Definition at line 69 of file VulkanInstance.h.
mInitConfiguration
InitConfiguration Atlas::VulkanInstanceWrapper::mInitConfiguration [private]
Definition at line 71 of file VulkanInstance.h.
mVulkanBootstrapInstance
vkb::Instance Atlas::VulkanInstanceWrapper::mVulkanBootstrapInstance [private]
Definition at line 57 of file VulkanInstance.h.
mVulkanInstance
VkInstance Atlas::VulkanInstanceWrapper::mVulkanInstance { VK_NULL_HANDLE } [private]
According to the Khronos specification, VkInstance is an opaque handle to a Vulkan instance. By default, this is set to VK_NULL_HANDLE.
See also
https://registry.khronos.org/vulkan/specs/latest/man/html/VkInstance.html
Since
v0.0.1
Definition at line 67 of file VulkanInstance.h.
mVulkanVersion
Version Atlas::VulkanInstanceWrapper::mVulkanVersion [private]
Definition at line 76 of file VulkanInstance.h.
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/graphics/VulkanInstance.h
C:/Dev/Techstorm-v5/src/engine/graphics/VulkanInstance.cpp