Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD > Class Template Reference
This class wraps a variable (specified by T_VARIABLE_TYPE) and makes it thread-safe.
#include <ThreadSafeVariable.h>
Public Member Functions
ThreadSafeVariable ()
The default constructor. This will first check if the variable's type (T_VARIABLE_TYPE) can be default constructed. If it can, it will do so. If it cannot, it will throw an exception that the variable cannot be constructed because this class has no idea how to construct it.
ThreadSafeVariable (T_VARIABLE_TYPE const &initialValue)
This EXPLICIT constructor takes a variable of type T_VARIABLE_TYPE and sets mValue to the value of that variable. Keep in mind that this is a copy constructor for the wrapped variable. While setting the variable, this operation will lock the mutex.
ThreadSafeVariable (ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD > &other)
The class's copy constructor that takes another ThreadSafeVariable as a parameter, and copies the variable wrapped by that class. Keep in mind that this operation is thread-safe because it locks the mutex.
T_VARIABLE_TYPE get ()
This function returns the variable that is wrapped by this class (mValue). There is no need to lock the mutex in this function because it is not being modified, and it is being copied. Should you need a reference to the variable, you can use the getAsReference() function.
T_VARIABLE_TYPE & getAsReference ()
Similar to get(), but returns a reference to the variable instead of simply copying it. Please refer to the remarks section below for info on why this function is not preferred.
void set (const T_VARIABLE_TYPE &newValue)
This is one of the most important functions in this class because it allows you to set the mValue of the variable without having to deal with race conditions or locks. When this is called, it will automatically lock the mutex with whatever T_LOCK_GUARD is specified as within the template parameters. Then it will lock and then set the variable (mValue) to newValue.
T_LOCK_GUARD & lock ()
Locks the mutex variable and returns a reference to T_LOCK_GUARD.
bool isLocked ()
Check to see if the mutex is locked by calling std::mutex::try_lock(). If it is locked, it returns true, otherwise it returns false. The mValue returned is the opposite of what std::mutex::try_lock() returns. See the documentation (more specifically the note below) for why the opposite is returned. Additionally, See the remark below the note for info on how this function can be useful for you.
void execute (std::function< void(ThreadSafeVariable< T_VARIABLE_TYPE > &)> function)
Executes a lambda function while locking the mutex.
ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD > & operator= (const ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD > &other)
This is the copy assignment operator, it only copies the mValue of the variable, not the mutex. Keep in mind that this LOCKS.
T_VARIABLE_TYPE operator() ()
Equivalent to the get() function.
T_VARIABLE_TYPE operator-> ()
This is equivalent to get() and operator()(). It also works in the same way that the -> operator in a shared_ptr works.
Private Attributes
T_VARIABLE_TYPE mValue
This is the variable that is wrapped by this class.
T_MUTEX mMutex
Detailed Description
template<typename T_VARIABLE_TYPE, typename T_MUTEX = std::mutex, typename T_LOCK_GUARD = std::lock_guard<T_MUTEX>>
class Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >
This class wraps a variable (specified by T_VARIABLE_TYPE) and makes it thread-safe.
When ThreadSafeVariable::execute() is called, it will lock this variable and execute the function that is passed to it. Furthermore, it will also lock when the set() function, is called.
Warning
The variable that is wrapped by this class must have a default constructor. If the variable does not have a default constructor, then this class will throw an exception (MissingDefaultConstructorException).
Template Parameters
T_VARIABLE_TYPE The type of variable to wrap. This is used as a variable in mValue.
T_MUTEX What type of mutex to use. This defaults to std::mutex
T_LOCK_GUARD What type of lock_guard to use. This defaults to std::lock_guard<T_MUTEX>
Since
v0.0.9
Definition at line 40 of file ThreadSafeVariable.h.
Constructor & Destructor Documentation
ThreadSafeVariable() [1/3]
template<typename T_VARIABLE_TYPE , typename T_MUTEX = std::mutex, typename T_LOCK_GUARD = std::lock_guard<T_MUTEX>>
Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::ThreadSafeVariable () [inline]
The default constructor. This will first check if the variable's type (T_VARIABLE_TYPE) can be default constructed. If it can, it will do so. If it cannot, it will throw an exception that the variable cannot be constructed because this class has no idea how to construct it.
Remarks
This constructor is useful for initializing the variable. Below is an example of what NOT to do when using this constructor
class MyClass {
public:
    int x;
    MyClass() = delete;
};
// in a function
ThreadSafeVariable<MyClass> x;
Warning
If the variable cannot be default constructed, an exception will be thrown!
Exceptions
MissingDefaultConstructorException if the variable does not have a default constructor
Since
v0.0.9
Definition at line 90 of file ThreadSafeVariable.h.
References Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::mValue.
ThreadSafeVariable() [2/3]
template<typename T_VARIABLE_TYPE , typename T_MUTEX = std::mutex, typename T_LOCK_GUARD = std::lock_guard<T_MUTEX>>
Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::ThreadSafeVariable (T_VARIABLE_TYPE const & initialValue) [inline], [explicit]
This EXPLICIT constructor takes a variable of type T_VARIABLE_TYPE and sets mValue to the value of that variable. Keep in mind that this is a copy constructor for the wrapped variable. While setting the variable, this operation will lock the mutex.
Remarks
This constructor is useful for initializing the variable with a value. For example, if you have a variable called x that you want to initialize to 5, you can do so like so:
ThreadSafeVariable<int> x(5);
or like so:
ThreadSafeVariable<int> x = ThreadSafeVariable<int>(5);
Parameters
initialValue A unary const reference to a variable of type T_VARIABLE_TYPE
Since
v0.0.9
See also
mValue for the documentation on the variable that is wrapped by this class
Definition at line 126 of file ThreadSafeVariable.h.
References Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::set().
ThreadSafeVariable() [3/3]
template<typename T_VARIABLE_TYPE , typename T_MUTEX = std::mutex, typename T_LOCK_GUARD = std::lock_guard<T_MUTEX>>
Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::ThreadSafeVariable (ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD > & other) [inline]
The class's copy constructor that takes another ThreadSafeVariable as a parameter, and copies the variable wrapped by that class. Keep in mind that this operation is thread-safe because it locks the mutex.
Note
This is the preferred way to copy a ThreadSafeVariable.
Parameters
other A unary const reference to another ThreadSafeVariable WITH the same template parameters as this class. If it does not have the same template parameters, it will not compile.
Since
v0.0.9
Definition at line 143 of file ThreadSafeVariable.h.
References Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::get(), and Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::set().
Member Function Documentation
execute()
template<typename T_VARIABLE_TYPE , typename T_MUTEX = std::mutex, typename T_LOCK_GUARD = std::lock_guard<T_MUTEX>>
void Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::execute (std::function< void(ThreadSafeVariable< T_VARIABLE_TYPE > &)> function) [inline]
Executes a lambda function while locking the mutex.
Parameters
function
Definition at line 266 of file ThreadSafeVariable.h.
References Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::lock(), and Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::mMutex.
get()
template<typename T_VARIABLE_TYPE , typename T_MUTEX = std::mutex, typename T_LOCK_GUARD = std::lock_guard<T_MUTEX>>
T_VARIABLE_TYPE Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::get () [inline]
This function returns the variable that is wrapped by this class (mValue). There is no need to lock the mutex in this function because it is not being modified, and it is being copied. Should you need a reference to the variable, you can use the getAsReference() function.
Returns
A copy of the variable that is wrapped by this class. It is declared under T_VARIABLE_TYPE (the class's template parameter).
Since
v0.0.9
See also
getAsReference() for the sister function.
mValue for the variable that is wrapped by this class.
Definition at line 163 of file ThreadSafeVariable.h.
References Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::mValue.
Referenced by Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::operator()(), Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::operator->(), and Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::ThreadSafeVariable().
getAsReference()
template<typename T_VARIABLE_TYPE , typename T_MUTEX = std::mutex, typename T_LOCK_GUARD = std::lock_guard<T_MUTEX>>
T_VARIABLE_TYPE & Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::getAsReference () [inline]
Similar to get(), but returns a reference to the variable instead of simply copying it. Please refer to the remarks section below for info on why this function is not preferred.
Remarks
This function is not preferable to get() because there is a higher likelihood of a race condition or other thread safety issue.
Returns
A unary reference to the variable that is wrapped by this class. See the brief description for more info.
Since
v0.0.9
See also
get() for the sister function.
mValue for the variable that is wrapped by this class.
Definition at line 184 of file ThreadSafeVariable.h.
References Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::mValue.
isLocked()
template<typename T_VARIABLE_TYPE , typename T_MUTEX = std::mutex, typename T_LOCK_GUARD = std::lock_guard<T_MUTEX>>
bool Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::isLocked () [inline]
Check to see if the mutex is locked by calling std::mutex::try_lock(). If it is locked, it returns true, otherwise it returns false. The mValue returned is the opposite of what std::mutex::try_lock() returns. See the documentation (more specifically the note below) for why the opposite is returned. Additionally, See the remark below the note for info on how this function can be useful for you.
Note
Instead of directly returning the mValue of try_lock(), the opposite of it is returned instead because C++20 documentation states that it will return true if the mutex was able to be locked.
Remarks
This is quite useful for checking if the variable is currently in use somewhere. Let's say you have a function that you want to execute, but you don't want to execute it if the variable is already in use (so you dont waste time). You can use this function to check if the variable is in use, therefore saving time.
Returns
The result of an attempt to lock the mutex, true if it was locked, false otherwise.
Since
v0.0.9
Definition at line 257 of file ThreadSafeVariable.h.
References Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::mMutex.
lock()
template<typename T_VARIABLE_TYPE , typename T_MUTEX = std::mutex, typename T_LOCK_GUARD = std::lock_guard<T_MUTEX>>
T_LOCK_GUARD & Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::lock () [inline]
Locks the mutex variable and returns a reference to T_LOCK_GUARD.
Note
This returns a reference to T_LOCK_GUARD because it would automatically unlock the mutex when it goes out of scope if it wasn't returned as a reference.
Returns
A reference to T_LOCK_GUARD so that it doesn't automatically unlock the mutex. See the note above for the reasoning behind this.
Definition at line 226 of file ThreadSafeVariable.h.
References Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::lock(), and Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::mMutex.
Referenced by Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::execute(), Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::lock(), Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::operator=(), and Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::set().
operator()()
template<typename T_VARIABLE_TYPE , typename T_MUTEX = std::mutex, typename T_LOCK_GUARD = std::lock_guard<T_MUTEX>>
T_VARIABLE_TYPE Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::operator() () [inline]
Equivalent to the get() function.
Returns
Definition at line 291 of file ThreadSafeVariable.h.
References Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::get().
operator->()
template<typename T_VARIABLE_TYPE , typename T_MUTEX = std::mutex, typename T_LOCK_GUARD = std::lock_guard<T_MUTEX>>
T_VARIABLE_TYPE Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::operator-> () [inline]
This is equivalent to get() and operator()(). It also works in the same way that the -> operator in a shared_ptr works.
Returns
A copy of the wrapped variable
Since
v0.0.9
Definition at line 303 of file ThreadSafeVariable.h.
References Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::get().
operator=()
template<typename T_VARIABLE_TYPE , typename T_MUTEX = std::mutex, typename T_LOCK_GUARD = std::lock_guard<T_MUTEX>>
ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD > & Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::operator= (const ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD > & other) [inline]
This is the copy assignment operator, it only copies the mValue of the variable, not the mutex. Keep in mind that this LOCKS.
Parameters
other
Returns
Definition at line 279 of file ThreadSafeVariable.h.
References Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::lock(), Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::mMutex, and Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::mValue.
set()
template<typename T_VARIABLE_TYPE , typename T_MUTEX = std::mutex, typename T_LOCK_GUARD = std::lock_guard<T_MUTEX>>
void Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::set (const T_VARIABLE_TYPE & newValue) [inline]
This is one of the most important functions in this class because it allows you to set the mValue of the variable without having to deal with race conditions or locks. When this is called, it will automatically lock the mutex with whatever T_LOCK_GUARD is specified as within the template parameters. Then it will lock and then set the variable (mValue) to newValue.
Remarks
As an example for the use of this function, let's say you have a variable called x that you want to set to 5. You can do this by calling set(5) within this class or you can do this by calling x.set(5). Even if multiple threads are attempting to set the mValue, there will be NO race conditions. and the mValue will be uniform across all threads.
Parameters
newValue The new mValue to set the variable to. This is a const reference, so make sure to account for that. This variable will be copied into the variable that is wrapped by this class.
Since
v0.0.9
Definition at line 209 of file ThreadSafeVariable.h.
References Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::lock(), Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::mMutex, and Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::mValue.
Referenced by Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::ThreadSafeVariable(), and Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::ThreadSafeVariable().
Member Data Documentation
mMutex
template<typename T_VARIABLE_TYPE , typename T_MUTEX = std::mutex, typename T_LOCK_GUARD = std::lock_guard<T_MUTEX>>
T_MUTEX Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::mMutex [private]
Definition at line 49 of file ThreadSafeVariable.h.
Referenced by Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::execute(), Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::isLocked(), Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::lock(), Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::operator=(), and Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::set().
mValue
template<typename T_VARIABLE_TYPE , typename T_MUTEX = std::mutex, typename T_LOCK_GUARD = std::lock_guard<T_MUTEX>>
T_VARIABLE_TYPE Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::mValue [private]
This is the variable that is wrapped by this class.
Since
v0.0.9
Definition at line 48 of file ThreadSafeVariable.h.
Referenced by Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::get(), Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::getAsReference(), Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::operator=(), Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::set(), and Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::ThreadSafeVariable().
The documentation for this class was generated from the following file:
C:/Dev/Techstorm-v5/src/engine/core/threading/ThreadSafeVariable.h