Atlas::FileSystemRegistry Class Reference
The file system registry.
#include <FileSystemRegistry.h>
Classes
class AccessViolationException
class FileOutOfSandboxException
This is thrown when a piece of code tries to register, load, unload, or search for a file that is out of the sandbox. This class inherits from ForbiddenFileException because this is a type of forbidden access violation.
class ForbiddenFileException
This exception is thrown when a piece of code tries to search for a file that is not allowed to be searched for. This class inherits from AccessViolationException.
class ForbiddenFileSearchException
This is thrown when a piece of code tries to search for a file that does not exist, on a blacklist, or is otherwise forbidden. This class inherits from ForbiddenFileException because this is a type of forbidden access violation.
class ImpatientUsageException
What is meant by "impatient" is that a piece of code has used this class when sIsReady is false. Essentially, this is thrown when some code is being impatient and not waiting for the registry to be ready. This class inherits from AccessViolationException.
class MissingFileException
An exception that is thrown when a file is not found where it should be. This can mean that the key being used to search for a file is incorrect, or that the file is not registered. If this exception is thrown, it is recommended that you ensure that you have the correct key(s) being used to search for the file and that the file exists within the sandbox.
class MissingFileLoadFunctionException
An exception that is thrown when there is no registered load function for the file extension of the file that is being loaded.
Public Member Functions
FileSystemRegistry ()
Initializes a new instance of the FileSystemRegistry class.
void init (const char *rootPath)
This function is used to initialize the file system registry. It will scan the provided root path for files and add them to the registry. The recursive searching method used is LoadDirectoryFilesEx from Raylib.
void registerFile (std::string const &path)
Registers a file into the file registry using the provided path by creating a new FileMeta object, generating a unique index for the file, and adding it to the registry's lookup table. If the file's extension is in the load on register extensions set (mLoadOnRegisterExtensionsSet), it will be loaded immediately.
std::shared_ptr< FileMeta > GetFileMeta (std::string const &key)
Gets the file meta stored in the file registry under the specified key.
void loadFile (std::shared_ptr< RegisteredFile > file)
Turns a registered file into a loaded file. Typically, this is called internally within the registerFile function, but is also called when a file is used for the first time.
std::shared_ptr< RegisteredFile > getFile (std::string const &key, bool loadIfNotLoaded=true)
Looks up a file in the file registry. Unless loadIfNotLoaded is set to false, this function WILL load the file if it is not already loaded.
bool isFileRegistered (std::string const &key)
Checks within the registry if a file has been registered by looking up the key in the lookup table.
void addLoadFunction (std::string const &extension, FileLoadFuncType loadFunc)
Adds a load function for a specific extension. This is how you may inform Atlas on how to load a specific file type. This function is also a "call-and-forget" function; Atlas handles the loading of the file for you and there is not much you need to do afterwards.
void addLoadOnRegisterExtension (std::string const &extension)
This marks a certain extension as one that should be loaded when a file with the specified extension is registered using the concept of immediate loading (refer to the main page for more information). This must be done before a file(s) get registered. The way this works is by adding the extension to the mLoadOnRegisterExtensionsSet set.
std::string getFilePath (std::string const &key)
Private Member Functions
bool isReady () const
A getter function that tells you if the registry is ready or not; this just returns sIsReady.
uint16_t getFileIndex (std::string const &key) const
Searches the lookup table to find the index of a file.
Static Private Member Functions
static uint16_t GetNextFileIndex ()
Gets the next file index.
Private Attributes
std::unordered_map< std::string, FileLoadFuncType > mLoadingFunctions
Holds the functions that will be called when a file is loaded. When a file is loaded, the respective extension's load function will be called. The string key is the file extension, and the function is the load function. As is documented in the File Loading, each extension has to have it's own load function or else Atlas does not know how to load that specific filetype. This is where the whole concept of extension-based loading it comes into play.
std::unordered_map< uint16_t, std::shared_ptr< RegisteredFile > > mRegisteredFiles
An unordered map that maps a file index to a registered file (stored as a shared_ptr).
std::unordered_map< uint16_t, std::shared_ptr< FileMeta > > mFileMetaRegistry
An unordered map that maps a file index to a file meta shared_ptr (see FileMeta). This is the lookup table for the file meta. The uint16_t index is the output from the search in mLookupTable.
std::unordered_map< std::string, uint16_t > mLookupTable
An unordered map that maps a file path to a file index. This essentially serves as a reverse lookup table that maps a key to an index. The key can be either the file path, the file name, the file extension, or really anything that can be used to identify a file. However, Atlas only uses file path, the file name, and the file extension to identify a file. This is the first step in the process of looking up a file. The uint16_t index corresponds to the index in the mFileMetaRegistry unordered map.
std::unordered_set< std::string > mLoadOnRegisterExtensionsSet
Tells the registry which extensions should be loaded on register. If it exists in the set, it will be loaded.
Static Private Attributes
static volatile bool sIsReady = false
static uint16_t sFileIndex = 0
This static uint16_t variable represents the next available file index.
Friends
class BProject
Additional Inherited Members
Static Public Member Functions inherited from Atlas::Singleton< FileSystemRegistry >
static FileSystemRegistry & Instance ()
Retrieves the current singleton instance as a reference. If you need to create a class that has a single static instance, use this class.
Detailed Description
The file system registry.
Remarks
The file system registry is a relatively complex class because it:
Keeps track of files.
Handles loading of files
Handles unloading of files
Handles registration of files
And just about everything else that a registry does
As an example of how to add a new file extension, see the File Loading document.
Since
v0.0.4
Todo
Todo Clean this up, it is a complete mess.
Add unit tests
See also
Singleton
Definition at line 64 of file FileSystemRegistry.h.
Constructor & Destructor Documentation
FileSystemRegistry()
Atlas::FileSystemRegistry::FileSystemRegistry () [inline]
Initializes a new instance of the FileSystemRegistry class.
Since
v0.0.4
Definition at line 275 of file FileSystemRegistry.h.
Member Function Documentation
addLoadFunction()
void Atlas::FileSystemRegistry::addLoadFunction (std::string const & extension, FileLoadFuncType loadFunc)
Adds a load function for a specific extension. This is how you may inform Atlas on how to load a specific file type. This function is also a "call-and-forget" function; Atlas handles the loading of the file for you and there is not much you need to do afterwards.
Parameters
extension This defines what file type the load function is for. Keep in mind that this is case-sensitive and is WITHOUT the leading "." in the extension.
loadFunc A lambda function that takes a shared_ptr to the file meta as a parameter and returns a shared_ptr to the file data.
Since
v0.0.4
See also
FileLoadFuncType
Definition at line 204 of file FileSystemRegistry.cpp.
addLoadOnRegisterExtension()
void Atlas::FileSystemRegistry::addLoadOnRegisterExtension (std::string const & extension)
This marks a certain extension as one that should be loaded when a file with the specified extension is registered using the concept of immediate loading (refer to the main page for more information). This must be done before a file(s) get registered. The way this works is by adding the extension to the mLoadOnRegisterExtensionsSet set.
Note
It is recommended that you do this in your project's preInit function.
Parameters
extension The extension that should be flagged for loading in the mLoadOnRegisterExtensionsSet.
Since
v0.0.4
Definition at line 208 of file FileSystemRegistry.cpp.
getFile()
std::shared_ptr< Atlas::RegisteredFile > Atlas::FileSystemRegistry::getFile (std::string const & key, bool loadIfNotLoaded = true)
Looks up a file in the file registry. Unless loadIfNotLoaded is set to false, this function WILL load the file if it is not already loaded.
Parameters
key The key that was used to register the file and is stored in the lookup table as.
loadIfNotLoaded If set to true the file will be loaded if it is not already loaded. Please note that this is set to true by default.
Returns
A shared_ptr to the file that was found in the file registry.
Since
v0.0.4
Definition at line 176 of file FileSystemRegistry.cpp.
References Atlas::Log(), and Atlas::WARNING.
Referenced by Atlas::Window::init().
getFileIndex()
uint16_t Atlas::FileSystemRegistry::getFileIndex (std::string const & key) const [private]
Searches the lookup table to find the index of a file.
Parameters
key One of the keys that was used to register the file.
Returns
A uint16_t that corresponds to the index of the file in the registry.
Since
v0.0.9
Definition at line 32 of file FileSystemRegistry.cpp.
GetFileMeta()
std::shared_ptr< Atlas::FileMeta > Atlas::FileSystemRegistry::GetFileMeta (std::string const & key)
Gets the file meta stored in the file registry under the specified key.
Parameters
key The filename, file path, file extension, or anything else that was used to identify a file upon registration.
Returns
A shared_ptr to the file meta stored within the file registry.
Since
v0.0.4
See also
FileMeta for what file meta is
mFileMetaRegistry for where the file meta is stored at.
Definition at line 92 of file FileSystemRegistry.cpp.
References Atlas::Log(), and Atlas::WARNING.
getFilePath()
std::string Atlas::FileSystemRegistry::getFilePath (std::string const & key)
Definition at line 212 of file FileSystemRegistry.cpp.
GetNextFileIndex()
uint16_t Atlas::FileSystemRegistry::GetNextFileIndex () [inline], [static], [private]
Gets the next file index.
Returns
The next file index
Since
v0.0.4
See also
sFileIndex
Definition at line 24 of file FileSystemRegistry.cpp.
References sFileIndex.
init()
void Atlas::FileSystemRegistry::init (const char * rootPath)
This function is used to initialize the file system registry. It will scan the provided root path for files and add them to the registry. The recursive searching method used is LoadDirectoryFilesEx from Raylib.
Parameters
rootPath The path to the directory that should be scanned. For example, the "game" directory.
Since
v0.0.4
Todo
Todo Encapsulate this function
Definition at line 42 of file FileSystemRegistry.cpp.
References Atlas::Log(), and Atlas::WARNING.
Referenced by Atlas::BProject::preInit().
isFileRegistered()
bool Atlas::FileSystemRegistry::isFileRegistered (std::string const & key)
Checks within the registry if a file has been registered by looking up the key in the lookup table.
Parameters
key The key that was used to register the file and is stored in the lookup table as.
Returns
true if the file has been registered, false if not.
Definition at line 199 of file FileSystemRegistry.cpp.
isReady()
bool Atlas::FileSystemRegistry::isReady () const [private]
A getter function that tells you if the registry is ready or not; this just returns sIsReady.
Returns
The copied value of sIsReady
Since
v0.0.9
See also
sIsReady for what sIsReady is
Definition at line 28 of file FileSystemRegistry.cpp.
loadFile()
void Atlas::FileSystemRegistry::loadFile (std::shared_ptr< RegisteredFile > file)
Turns a registered file into a loaded file. Typically, this is called internally within the registerFile function, but is also called when a file is used for the first time.
Parameters
file A shared_ptr to the [registered] file that should be loaded.
Exceptions
ImpatientUsageException If this is called before the registry is ready
Since
v0.0.4
Definition at line 119 of file FileSystemRegistry.cpp.
References Atlas::ERROR, Atlas::Log(), Atlas::TRACE, and Atlas::WARNING.
registerFile()
void Atlas::FileSystemRegistry::registerFile (std::string const & path)
Registers a file into the file registry using the provided path by creating a new FileMeta object, generating a unique index for the file, and adding it to the registry's lookup table. If the file's extension is in the load on register extensions set (mLoadOnRegisterExtensionsSet), it will be loaded immediately.
Remarks
This function is mostly used internally within the init function during the file registration process, but has been made public because it can still be used to register files that were not registered during the initialization process.
Parameters
path The path to the file that should be registered. This is the exact path to the file, not the file name.
Since
v0.0.4
Definition at line 63 of file FileSystemRegistry.cpp.
References Atlas::FileMeta::extension, Atlas::FileMeta::filename, Atlas::FileMeta::format(), Atlas::Log(), Atlas::FileMeta::path, Atlas::FileMeta::sandboxPath, and Atlas::TRACE.
Friends And Related Symbol Documentation
BProject
friend class BProject [friend]
Definition at line 66 of file FileSystemRegistry.h.
Member Data Documentation
mFileMetaRegistry
std::unordered_map<uint16_t, std::shared_ptr<FileMeta> > Atlas::FileSystemRegistry::mFileMetaRegistry [private]
An unordered map that maps a file index to a file meta shared_ptr (see FileMeta). This is the lookup table for the file meta. The uint16_t index is the output from the search in mLookupTable.
Since
v0.0.4
See also
mLookupTable for how the lookup table works.
FileMeta for what a file meta is.
Definition at line 109 of file FileSystemRegistry.h.
mLoadingFunctions
std::unordered_map<std::string, FileLoadFuncType> Atlas::FileSystemRegistry::mLoadingFunctions [private]
Holds the functions that will be called when a file is loaded. When a file is loaded, the respective extension's load function will be called. The string key is the file extension, and the function is the load function. As is documented in the File Loading, each extension has to have it's own load function or else Atlas does not know how to load that specific filetype. This is where the whole concept of extension-based loading it comes into play.
Since
v0.0.4
See also
File Loading
Definition at line 91 of file FileSystemRegistry.h.
mLoadOnRegisterExtensionsSet
std::unordered_set<std::string> Atlas::FileSystemRegistry::mLoadOnRegisterExtensionsSet [private]
Tells the registry which extensions should be loaded on register. If it exists in the set, it will be loaded.
Note
This is set PRIOR to the discovery of files because this defines what extensions should be immediately loaded on registration. This is a set because this is only used to determine if a file should be loaded on register. The code knows if the file should be loaded on register by checking if the extension is contained in the set.
Since
v0.0.4
Definition at line 133 of file FileSystemRegistry.h.
mLookupTable
std::unordered_map<std::string, uint16_t> Atlas::FileSystemRegistry::mLookupTable [private]
An unordered map that maps a file path to a file index. This essentially serves as a reverse lookup table that maps a key to an index. The key can be either the file path, the file name, the file extension, or really anything that can be used to identify a file. However, Atlas only uses file path, the file name, and the file extension to identify a file. This is the first step in the process of looking up a file. The uint16_t index corresponds to the index in the mFileMetaRegistry unordered map.
Since
v0.0.4
Definition at line 120 of file FileSystemRegistry.h.
mRegisteredFiles
std::unordered_map<uint16_t, std::shared_ptr<RegisteredFile> > Atlas::FileSystemRegistry::mRegisteredFiles [private]
An unordered map that maps a file index to a registered file (stored as a shared_ptr).
Since
v0.0.4
Definition at line 98 of file FileSystemRegistry.h.
sFileIndex
uint16_t Atlas::FileSystemRegistry::sFileIndex = 0 [inline], [static], [private]
This static uint16_t variable represents the next available file index.
Remarks
This is typically only used during the discovery and registration of files. It is also used to quickly assign a unique index to each file meta.
Since
v0.0.4
Definition at line 78 of file FileSystemRegistry.h.
Referenced by GetNextFileIndex().
sIsReady
volatile bool Atlas::FileSystemRegistry::sIsReady = false [inline], [static], [private]
Definition at line 68 of file FileSystemRegistry.h.
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/fs/FileSystemRegistry.h
C:/Dev/Techstorm-v5/src/engine/fs/FileSystemRegistry.cpp