CScriptHandle Class Reference
#include <scripthandle.h>
Public Member Functions
CScriptHandle ()
CScriptHandle (const CScriptHandle &other)
CScriptHandle (void *ref, asITypeInfo *type)
~CScriptHandle ()
CScriptHandle & operator= (const CScriptHandle &other)
void Set (void *ref, asITypeInfo *type)
bool operator== (const CScriptHandle &o) const
bool operator!= (const CScriptHandle &o) const
bool Equals (void *ref, int typeId) const
void Cast (void **outRef, int typeId)
asITypeInfo * GetType () const
int GetTypeId () const
void * GetRef ()
void EnumReferences (asIScriptEngine *engine)
void ReleaseReferences (asIScriptEngine *engine)
CScriptHandle ()
CScriptHandle (const CScriptHandle &other)
CScriptHandle (void *ref, asITypeInfo *type)
~CScriptHandle ()
CScriptHandle & operator= (const CScriptHandle &other)
void Set (void *ref, asITypeInfo *type)
bool operator== (const CScriptHandle &o) const
bool operator!= (const CScriptHandle &o) const
bool Equals (void *ref, int typeId) const
void Cast (void **outRef, int typeId)
asITypeInfo * GetType () const
int GetTypeId () const
void * GetRef ()
void EnumReferences (asIScriptEngine *engine)
void ReleaseReferences (asIScriptEngine *engine)
Protected Member Functions
void ReleaseHandle ()
void AddRefHandle ()
CScriptHandle (void *ref, int typeId)
CScriptHandle & Assign (void *ref, int typeId)
void ReleaseHandle ()
void AddRefHandle ()
CScriptHandle (void *ref, int typeId)
CScriptHandle & Assign (void *ref, int typeId)
Protected Attributes
void * m_ref
asITypeInfo * m_type
Friends
void Construct (CScriptHandle *self, void *ref, int typeId)
void RegisterScriptHandle_Native (asIScriptEngine *engine)
void CScriptHandle_AssignVar_Generic (asIScriptGeneric *gen)
void Construct (CScriptHandle *self, void *ref, int typeId)
void RegisterScriptHandle_Native (asIScriptEngine *engine)
void CScriptHandle_AssignVar_Generic (asIScriptGeneric *gen)
Detailed Description
Definition at line 12 of file scripthandle.h.
Constructor & Destructor Documentation
CScriptHandle() [1/8]
CScriptHandle::CScriptHandle ()
Definition at line 14 of file scripthandle.cpp.
References m_ref, and m_type.
CScriptHandle() [2/8]
CScriptHandle::CScriptHandle (const CScriptHandle & other)
Definition at line 20 of file scripthandle.cpp.
References AddRefHandle(), m_ref, and m_type.
CScriptHandle() [3/8]
CScriptHandle::CScriptHandle (void * ref, asITypeInfo * type)
Definition at line 28 of file scripthandle.cpp.
References AddRefHandle(), m_ref, and m_type.
~CScriptHandle() [1/2]
CScriptHandle::~CScriptHandle ()
Definition at line 46 of file scripthandle.cpp.
References ReleaseHandle().
Referenced by CScriptHandle_Destruct_Generic(), and Destruct().
CScriptHandle() [4/8]
CScriptHandle::CScriptHandle (void * ref, int typeId) [protected]
Definition at line 38 of file scripthandle.cpp.
References Assign(), m_ref, and m_type.
CScriptHandle() [5/8]
CScriptHandle::CScriptHandle ()
CScriptHandle() [6/8]
CScriptHandle::CScriptHandle (const CScriptHandle & other)
CScriptHandle() [7/8]
CScriptHandle::CScriptHandle (void * ref, asITypeInfo * type)
~CScriptHandle() [2/2]
CScriptHandle::~CScriptHandle ()
CScriptHandle() [8/8]
CScriptHandle::CScriptHandle (void * ref, int typeId) [protected]
Member Function Documentation
AddRefHandle() [1/2]
void CScriptHandle::AddRefHandle () [protected]
Definition at line 65 of file scripthandle.cpp.
References m_ref, and m_type.
Referenced by CScriptHandle(), CScriptHandle(), and Set().
AddRefHandle() [2/2]
void CScriptHandle::AddRefHandle () [protected]
Assign() [1/2]
CScriptHandle & CScriptHandle::Assign (void * ref, int typeId) [protected]
Definition at line 116 of file scripthandle.cpp.
References m_ref, m_type, and Set().
Referenced by CScriptHandle(), and CScriptHandle_AssignVar_Generic().
Assign() [2/2]
CScriptHandle & CScriptHandle::Assign (void * ref, int typeId) [protected]
Cast() [1/2]
void CScriptHandle::Cast (void ** outRef, int typeId)
Definition at line 191 of file scripthandle.cpp.
References m_ref, and m_type.
Referenced by CScriptHandle_Cast_Generic().
Cast() [2/2]
void CScriptHandle::Cast (void ** outRef, int typeId)
EnumReferences() [1/2]
void CScriptHandle::EnumReferences (asIScriptEngine * engine)
Definition at line 214 of file scripthandle.cpp.
References m_ref, and m_type.
Referenced by CScriptHandle_EnumReferences_Generic().
EnumReferences() [2/2]
void CScriptHandle::EnumReferences (asIScriptEngine * engine)
Equals() [1/2]
bool CScriptHandle::Equals (void * ref, int typeId) const
Definition at line 168 of file scripthandle.cpp.
References m_ref.
Referenced by CScriptHandle_EqualsVar_Generic().
Equals() [2/2]
bool CScriptHandle::Equals (void * ref, int typeId) const
GetRef() [1/2]
void * CScriptHandle::GetRef ()
Definition at line 97 of file scripthandle.cpp.
References m_ref.
GetRef() [2/2]
void * CScriptHandle::GetRef ()
GetType() [1/2]
asITypeInfo * CScriptHandle::GetType () const
Definition at line 102 of file scripthandle.cpp.
References m_type.
GetType() [2/2]
asITypeInfo * CScriptHandle::GetType () const
GetTypeId() [1/2]
int CScriptHandle::GetTypeId () const
Definition at line 107 of file scripthandle.cpp.
References m_type.
GetTypeId() [2/2]
int CScriptHandle::GetTypeId () const
operator!=() [1/2]
bool CScriptHandle::operator!= (const CScriptHandle & o) const
Definition at line 163 of file scripthandle.cpp.
operator!=() [2/2]
bool CScriptHandle::operator!= (const CScriptHandle & o) const
operator=() [1/2]
CScriptHandle & CScriptHandle::operator= (const CScriptHandle & other)
Definition at line 78 of file scripthandle.cpp.
References m_ref, m_type, and Set().
operator=() [2/2]
CScriptHandle & CScriptHandle::operator= (const CScriptHandle & other)
operator==() [1/2]
bool CScriptHandle::operator== (const CScriptHandle & o) const
Definition at line 151 of file scripthandle.cpp.
References m_ref, and m_type.
operator==() [2/2]
bool CScriptHandle::operator== (const CScriptHandle & o) const
ReleaseHandle() [1/2]
void CScriptHandle::ReleaseHandle () [protected]
Definition at line 51 of file scripthandle.cpp.
References m_ref, and m_type.
Referenced by Set(), and ~CScriptHandle().
ReleaseHandle() [2/2]
void CScriptHandle::ReleaseHandle () [protected]
ReleaseReferences() [1/2]
void CScriptHandle::ReleaseReferences (asIScriptEngine * engine)
Definition at line 225 of file scripthandle.cpp.
References Set().
Referenced by CScriptHandle_ReleaseReferences_Generic().
ReleaseReferences() [2/2]
void CScriptHandle::ReleaseReferences (asIScriptEngine * engine)
Set() [1/2]
void CScriptHandle::Set (void * ref, asITypeInfo * type)
Definition at line 85 of file scripthandle.cpp.
References AddRefHandle(), m_ref, m_type, and ReleaseHandle().
Referenced by Assign(), operator=(), and ReleaseReferences().
Set() [2/2]
void CScriptHandle::Set (void * ref, asITypeInfo * type)
Friends And Related Symbol Documentation
Construct [1/2]
void Construct (CScriptHandle * self, void * ref, int typeId) [friend]
Definition at line 11 of file scripthandle.cpp.
Construct [2/2]
void Construct (CScriptHandle * self, void * ref, int typeId) [friend]
Definition at line 11 of file scripthandle.cpp.
CScriptHandle_AssignVar_Generic [1/2]
void CScriptHandle_AssignVar_Generic (asIScriptGeneric * gen) [friend]
Definition at line 297 of file scripthandle.cpp.
CScriptHandle_AssignVar_Generic [2/2]
void CScriptHandle_AssignVar_Generic (asIScriptGeneric * gen) [friend]
Definition at line 297 of file scripthandle.cpp.
RegisterScriptHandle_Native [1/2]
void RegisterScriptHandle_Native (asIScriptEngine * engine) [friend]
Definition at line 231 of file scripthandle.cpp.
RegisterScriptHandle_Native [2/2]
void RegisterScriptHandle_Native (asIScriptEngine * engine) [friend]
Definition at line 231 of file scripthandle.cpp.
Member Data Documentation
m_ref
void * CScriptHandle::m_ref [protected]
Definition at line 61 of file scripthandle.h.
Referenced by AddRefHandle(), Assign(), Cast(), CScriptHandle(), CScriptHandle(), CScriptHandle(), CScriptHandle(), EnumReferences(), Equals(), GetRef(), operator=(), operator==(), ReleaseHandle(), and Set().
m_type
asITypeInfo * CScriptHandle::m_type [protected]
Definition at line 62 of file scripthandle.h.
Referenced by AddRefHandle(), Assign(), Cast(), CScriptHandle(), CScriptHandle(), CScriptHandle(), CScriptHandle(), EnumReferences(), GetType(), GetTypeId(), operator=(), operator==(), ReleaseHandle(), and Set().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/application/add_on/scripthandle/scripthandle.h
C:/Dev/Techstorm-v5/src/engine/modding/add_on/scripthandle/scripthandle.h
C:/Dev/Techstorm-v5/src/application/add_on/scripthandle/scripthandle.cpp
C:/Dev/Techstorm-v5/src/engine/modding/add_on/scripthandle/scripthandle.cpp