CSerializedValue Class Reference
#include <serializer.h>
Public Member Functions
CSerializedValue ()
CSerializedValue (CSerializedValue *parent, const std::string &name, const std::string &nameSpace, void *ref, int typeId)
~CSerializedValue ()
void Store (void *ref, int refTypeId)
void Restore (void *ref, int refTypeId)
void SetType (int typeId)
asITypeInfo * GetType ()
CSerializedValue * FindByName (const std::string &name, const std::string &nameSpace)
CSerializedValue * FindByPtr (void *ptr)
void * GetUserData ()
void SetUserData (void *data)
CSerializedValue ()
CSerializedValue (CSerializedValue *parent, const std::string &name, const std::string &nameSpace, void *ref, int typeId)
~CSerializedValue ()
void Store (void *ref, int refTypeId)
void Restore (void *ref, int refTypeId)
void SetType (int typeId)
asITypeInfo * GetType ()
CSerializedValue * FindByName (const std::string &name, const std::string &nameSpace)
CSerializedValue * FindByPtr (void *ptr)
void * GetUserData ()
void SetUserData (void *data)
Public Attributes
std::vector< CSerializedValue * > m_children
Protected Member Functions
void Init ()
void Uninit ()
void ReplaceHandles ()
void RestoreHandles ()
void GetAllPointersOfChildren (std::vector< void * > *ptrs)
void CancelDuplicates (CSerializedValue *from)
CSerializedValue * FindByPtrInHandles (void *ptr)
void * GetPointerToRestoredObject (void *ptr)
void ClearChildren ()
void Init ()
void Uninit ()
void ReplaceHandles ()
void RestoreHandles ()
void GetAllPointersOfChildren (std::vector< void * > *ptrs)
void CancelDuplicates (CSerializedValue *from)
CSerializedValue * FindByPtrInHandles (void *ptr)
void * GetPointerToRestoredObject (void *ptr)
void ClearChildren ()
Protected Attributes
CSerializer * m_serializer
void * m_userData
int m_typeId
std::string m_typeName
std::string m_typeDecl
std::string m_name
std::string m_nameSpace
bool m_isInit
void * m_originalPtr
void * m_handlePtr
void * m_restorePtr
std::vector< char > m_mem
Friends
class CSerializer
Detailed Description
Definition at line 39 of file serializer.h.
Constructor & Destructor Documentation
CSerializedValue() [1/4]
CSerializedValue::CSerializedValue ()
Definition at line 173 of file serializer.cpp.
References Init().
Referenced by ReplaceHandles(), and Store().
CSerializedValue() [2/4]
CSerializedValue::CSerializedValue (CSerializedValue * parent, const std::string & name, const std::string & nameSpace, void * ref, int typeId)
Definition at line 178 of file serializer.cpp.
References Init(), m_name, m_nameSpace, m_serializer, and Store().
~CSerializedValue() [1/2]
CSerializedValue::~CSerializedValue ()
Definition at line 228 of file serializer.cpp.
References Uninit().
CSerializedValue() [3/4]
CSerializedValue::CSerializedValue ()
CSerializedValue() [4/4]
CSerializedValue::CSerializedValue (CSerializedValue * parent, const std::string & name, const std::string & nameSpace, void * ref, int typeId)
~CSerializedValue() [2/2]
CSerializedValue::~CSerializedValue ()
Member Function Documentation
CancelDuplicates() [1/2]
void CSerializedValue::CancelDuplicates (CSerializedValue * from) [protected]
Definition at line 452 of file serializer.cpp.
References ClearChildren(), FindByPtrInHandles(), GetAllPointersOfChildren(), CSerializer::m_root, and m_serializer.
Referenced by ReplaceHandles().
CancelDuplicates() [2/2]
void CSerializedValue::CancelDuplicates (CSerializedValue * from) [protected]
ClearChildren() [1/2]
void CSerializedValue::ClearChildren () [protected]
Definition at line 214 of file serializer.cpp.
References m_children, CSerializer::m_engine, m_restorePtr, m_serializer, and m_typeId.
Referenced by CancelDuplicates(), and Uninit().
ClearChildren() [2/2]
void CSerializedValue::ClearChildren () [protected]
FindByName() [1/2]
CSerializedValue * CSerializedValue::FindByName (const std::string & name, const std::string & nameSpace)
Definition at line 233 of file serializer.cpp.
References m_children, m_name, and m_nameSpace.
Referenced by CSerializer::Restore(), and Restore().
FindByName() [2/2]
CSerializedValue * CSerializedValue::FindByName (const std::string & name, const std::string & nameSpace)
FindByPtr() [1/2]
CSerializedValue * CSerializedValue::FindByPtr (void * ptr)
Definition at line 251 of file serializer.cpp.
References FindByPtr(), m_children, and m_originalPtr.
Referenced by FindByPtr(), ReplaceHandles(), and RestoreHandles().
FindByPtr() [2/2]
CSerializedValue * CSerializedValue::FindByPtr (void * ptr)
FindByPtrInHandles() [1/2]
CSerializedValue * CSerializedValue::FindByPtrInHandles (void * ptr) [protected]
Definition at line 282 of file serializer.cpp.
References FindByPtrInHandles(), m_children, m_originalPtr, and m_typeId.
Referenced by CancelDuplicates(), and FindByPtrInHandles().
FindByPtrInHandles() [2/2]
CSerializedValue * CSerializedValue::FindByPtrInHandles (void * ptr) [protected]
GetAllPointersOfChildren() [1/2]
void CSerializedValue::GetAllPointersOfChildren (std::vector< void * > * ptrs) [protected]
Definition at line 243 of file serializer.cpp.
References GetAllPointersOfChildren(), m_children, and m_originalPtr.
Referenced by CancelDuplicates(), and GetAllPointersOfChildren().
GetAllPointersOfChildren() [2/2]
void CSerializedValue::GetAllPointersOfChildren (std::vector< void * > * ptrs) [protected]
GetPointerToRestoredObject() [1/2]
void * CSerializedValue::GetPointerToRestoredObject (void * ptr) [protected]
Definition at line 266 of file serializer.cpp.
References GetPointerToRestoredObject(), m_children, m_originalPtr, and m_restorePtr.
Referenced by CSerializer::GetPointerToRestoredObject(), and GetPointerToRestoredObject().
GetPointerToRestoredObject() [2/2]
void * CSerializedValue::GetPointerToRestoredObject (void * ptr) [protected]
GetType() [1/2]
asITypeInfo * CSerializedValue::GetType ()
Definition at line 552 of file serializer.cpp.
References CSerializer::m_engine, CSerializer::m_mod, m_serializer, m_typeDecl, and m_typeName.
Referenced by ReplaceHandles(), and Store().
GetType() [2/2]
asITypeInfo * CSerializedValue::GetType ()
GetUserData() [1/2]
void * CSerializedValue::GetUserData ()
Definition at line 568 of file serializer.cpp.
References m_userData.
GetUserData() [2/2]
void * CSerializedValue::GetUserData ()
Init() [1/2]
void CSerializedValue::Init () [protected]
Definition at line 188 of file serializer.cpp.
References m_handlePtr, m_isInit, m_originalPtr, m_restorePtr, m_serializer, m_typeId, and m_userData.
Referenced by CSerializedValue(), and CSerializedValue().
Init() [2/2]
void CSerializedValue::Init () [protected]
ReplaceHandles() [1/2]
void CSerializedValue::ReplaceHandles () [protected]
Definition at line 472 of file serializer.cpp.
References CancelDuplicates(), CSerializedValue(), FindByPtr(), GetType(), m_children, m_handlePtr, m_name, m_nameSpace, CSerializer::m_root, m_serializer, and ReplaceHandles().
Referenced by ReplaceHandles(), and CSerializer::Store().
ReplaceHandles() [2/2]
void CSerializedValue::ReplaceHandles () [protected]
Restore() [1/2]
void CSerializedValue::Restore (void * ref, int refTypeId)
Definition at line 358 of file serializer.cpp.
References FindByName(), m_children, CSerializer::m_engine, m_handlePtr, m_isInit, m_mem, m_restorePtr, m_serializer, m_typeId, m_typeName, CSerializer::m_userTypes, Restore(), and SetType().
Referenced by CSerializer::Restore(), and Restore().
Restore() [2/2]
void CSerializedValue::Restore (void * ref, int refTypeId)
RestoreHandles() [1/2]
void CSerializedValue::RestoreHandles () [protected]
Definition at line 499 of file serializer.cpp.
References FindByPtr(), m_children, CSerializer::m_engine, m_handlePtr, m_restorePtr, CSerializer::m_root, m_serializer, m_typeId, and RestoreHandles().
Referenced by CSerializer::Restore(), and RestoreHandles().
RestoreHandles() [2/2]
void CSerializedValue::RestoreHandles () [protected]
SetType() [1/2]
void CSerializedValue::SetType (int typeId)
Definition at line 539 of file serializer.cpp.
References CSerializer::m_engine, m_serializer, m_typeDecl, m_typeId, and m_typeName.
Referenced by Restore(), and Store().
SetType() [2/2]
void CSerializedValue::SetType (int typeId)
SetUserData() [1/2]
void CSerializedValue::SetUserData (void * data)
Definition at line 563 of file serializer.cpp.
References m_userData.
SetUserData() [2/2]
void CSerializedValue::SetUserData (void * data)
Store() [1/2]
void CSerializedValue::Store (void * ref, int refTypeId)
Definition at line 304 of file serializer.cpp.
References CSerializedValue(), GetType(), m_children, CSerializer::m_engine, m_handlePtr, m_isInit, m_mem, m_originalPtr, m_serializer, m_typeId, m_typeName, CSerializer::m_userTypes, and SetType().
Referenced by CSerializedValue().
Store() [2/2]
void CSerializedValue::Store (void * ref, int refTypeId)
Uninit() [1/2]
void CSerializedValue::Uninit () [protected]
Definition at line 199 of file serializer.cpp.
References ClearChildren(), m_isInit, m_serializer, m_typeName, m_userData, and CSerializer::m_userTypes.
Referenced by CSerializer::Clear(), and ~CSerializedValue().
Uninit() [2/2]
void CSerializedValue::Uninit () [protected]
Friends And Related Symbol Documentation
CSerializer
CSerializer [friend]
Definition at line 74 of file serializer.h.
Member Data Documentation
m_children
std::vector< CSerializedValue * > CSerializedValue::m_children
Definition at line 71 of file serializer.h.
Referenced by CSerializer::Clear(), ClearChildren(), FindByName(), FindByPtr(), FindByPtrInHandles(), GetAllPointersOfChildren(), GetPointerToRestoredObject(), ReplaceHandles(), CSerializer::Restore(), Restore(), RestoreHandles(), CSerializer::Store(), and Store().
m_handlePtr
void * CSerializedValue::m_handlePtr [protected]
Definition at line 134 of file serializer.h.
Referenced by Init(), ReplaceHandles(), Restore(), RestoreHandles(), and Store().
m_isInit
bool CSerializedValue::m_isInit [protected]
Definition at line 124 of file serializer.h.
Referenced by Init(), Restore(), Store(), and Uninit().
m_mem
std::vector< char > CSerializedValue::m_mem [protected]
Definition at line 142 of file serializer.h.
Referenced by Restore(), and Store().
m_name
std::string CSerializedValue::m_name [protected]
Definition at line 120 of file serializer.h.
Referenced by CSerializedValue(), FindByName(), and ReplaceHandles().
m_nameSpace
std::string CSerializedValue::m_nameSpace [protected]
Definition at line 121 of file serializer.h.
Referenced by CSerializedValue(), FindByName(), and ReplaceHandles().
m_originalPtr
void * CSerializedValue::m_originalPtr [protected]
Definition at line 129 of file serializer.h.
Referenced by FindByPtr(), FindByPtrInHandles(), GetAllPointersOfChildren(), GetPointerToRestoredObject(), Init(), and Store().
m_restorePtr
void * CSerializedValue::m_restorePtr [protected]
Definition at line 139 of file serializer.h.
Referenced by ClearChildren(), GetPointerToRestoredObject(), Init(), Restore(), and RestoreHandles().
m_serializer
CSerializer * CSerializedValue::m_serializer [protected]
Definition at line 106 of file serializer.h.
Referenced by CancelDuplicates(), ClearChildren(), CSerializedValue(), GetType(), Init(), ReplaceHandles(), Restore(), RestoreHandles(), SetType(), CSerializer::Store(), Store(), and Uninit().
m_typeDecl
std::string CSerializedValue::m_typeDecl [protected]
Definition at line 117 of file serializer.h.
Referenced by GetType(), and SetType().
m_typeId
int CSerializedValue::m_typeId [protected]
Definition at line 112 of file serializer.h.
Referenced by ClearChildren(), FindByPtrInHandles(), Init(), Restore(), RestoreHandles(), SetType(), and Store().
m_typeName
std::string CSerializedValue::m_typeName [protected]
Definition at line 116 of file serializer.h.
Referenced by GetType(), Restore(), SetType(), Store(), and Uninit().
m_userData
void * CSerializedValue::m_userData [protected]
Definition at line 109 of file serializer.h.
Referenced by GetUserData(), Init(), SetUserData(), and Uninit().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/application/add_on/serializer/serializer.h
C:/Dev/Techstorm-v5/src/engine/modding/add_on/serializer/serializer.h
C:/Dev/Techstorm-v5/src/application/add_on/serializer/serializer.cpp
C:/Dev/Techstorm-v5/src/engine/modding/add_on/serializer/serializer.cpp