Atlas::ATimer Class Reference
#include <Timer.h>
Public Member Functions
ATimer (uint64_t startTime)
ATimer ()=default
virtual ~ATimer ()
virtual void start (uint64_t length)=0
virtual void start ()
virtual void stop ()=0
virtual void reset ()
Protected Attributes
uint64_t mStartTime = 0
bool mbClockRunning = false
bool mbClockPaused = false
bool mbClockFinished = false
Detailed Description
Definition at line 23 of file Timer.h.
Constructor & Destructor Documentation
ATimer() [1/2]
Atlas::ATimer::ATimer (uint64_t startTime) [inline], [explicit]
Definition at line 33 of file Timer.h.
ATimer() [2/2]
Atlas::ATimer::ATimer () [default]
~ATimer()
Atlas::ATimer::~ATimer () [virtual]
Definition at line 12 of file Timer.cpp.
References reset().
Member Function Documentation
reset()
void Atlas::ATimer::reset () [virtual]
Definition at line 20 of file Timer.cpp.
Referenced by ~ATimer().
start() [1/2]
void Atlas::ATimer::start () [virtual]
Reimplemented in Atlas::AsyncTimer.
Definition at line 16 of file Timer.cpp.
Referenced by Atlas::AsyncTimer::start().
start() [2/2]
virtual void Atlas::ATimer::start (uint64_t length) [pure virtual]
Implemented in Atlas::AsyncTimer.
stop()
virtual void Atlas::ATimer::stop () [pure virtual]
Implemented in Atlas::AsyncTimer.
Member Data Documentation
mbClockFinished
bool Atlas::ATimer::mbClockFinished = false [protected]
Definition at line 29 of file Timer.h.
mbClockPaused
bool Atlas::ATimer::mbClockPaused = false [protected]
Definition at line 28 of file Timer.h.
mbClockRunning
bool Atlas::ATimer::mbClockRunning = false [protected]
Definition at line 27 of file Timer.h.
mStartTime
uint64_t Atlas::ATimer::mStartTime = 0 [protected]
Definition at line 25 of file Timer.h.
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/core/Timer.h
C:/Dev/Techstorm-v5/src/engine/core/Timer.cpp