Atlas::Renderer Class Reference
Serves as the renderer for the game.
#include <Renderer.h>
Public Member Functions
Renderer ()
Initializes a new instance of the Renderer class.
void init ()
Initializes this instance.
void render (GameCamera &cam)
Renders the render texture to the screen using the specified camera.
void texture (GameCamera &cam)
Textures the scene to the render texture using the specified camera.
void update ()
void drawFBO ()
Draws the FBO/RenderTexture2D.
void addStandaloneDrawCall (std::function< void()> drawCall)
void addGameObject (IGameObject *gameObject)
Adds the game object.
void removeGameObject (IGameObject *gameObject)
Removes a game object.
void addGameObjectGate (IGameObjectGate *gameObjectGate)
Adds a game object gate.
void removeGameObjectGate (IGameObjectGate *gameObjectGate)
Removes a game object gate.
void cleanup ()
Cleanups this instance.
Public Attributes
GameCamera mCamera
Private Member Functions
void render3D (GameCamera &cam)
Renders the 3d scene.
Private Attributes
GameObjectRegistry mGameObjects
RenderTexture2D mScreenBuffer
Color mBackgroundColor = BLACK
Color mFBOTint = WHITE
Detailed Description
Serves as the renderer for the game.
Definition at line 22 of file Renderer.h.
Constructor & Destructor Documentation
Renderer()
Atlas::Renderer::Renderer ()
Initializes a new instance of the Renderer class.
Definition at line 29 of file Renderer.cpp.
References mCamera, Atlas::GameCamera::setFovy(), Atlas::GameCamera::setPosition(), Atlas::GameCamera::setProjection(), Atlas::GameCamera::setTarget(), and Atlas::GameCamera::setUp().
Member Function Documentation
addGameObject()
void Atlas::Renderer::addGameObject (IGameObject * gameObject)
Adds the game object.
Parameters
gameObject The game object pointer to add.
Definition at line 97 of file Renderer.cpp.
addGameObjectGate()
void Atlas::Renderer::addGameObjectGate (IGameObjectGate * gameObjectGate)
Adds a game object gate.
Parameters
gameObjectGate The game object gate pointer to add.
See also
IGameObjectGate
Definition at line 107 of file Renderer.cpp.
addStandaloneDrawCall()
void Atlas::Renderer::addStandaloneDrawCall (std::function< void()> drawCall)
Definition at line 92 of file Renderer.cpp.
cleanup()
void Atlas::Renderer::cleanup ()
Cleanups this instance.
Definition at line 111 of file Renderer.cpp.
drawFBO()
void Atlas::Renderer::drawFBO ()
Draws the FBO/RenderTexture2D.
Definition at line 86 of file Renderer.cpp.
init()
void Atlas::Renderer::init ()
Initializes this instance.
Definition at line 40 of file Renderer.cpp.
removeGameObject()
void Atlas::Renderer::removeGameObject (IGameObject * gameObject)
Removes a game object.
Parameters
gameObject The game object pointer to remove.
Definition at line 102 of file Renderer.cpp.
removeGameObjectGate()
void Atlas::Renderer::removeGameObjectGate (IGameObjectGate * gameObjectGate)
Removes a game object gate.
Parameters
gameObjectGate The game object gate pointer to remove.
See also
IGameObjectGate
Definition at line 109 of file Renderer.cpp.
render()
void Atlas::Renderer::render (GameCamera & cam)
Renders the render texture to the screen using the specified camera.
Parameters
cam The cam.
Definition at line 51 of file Renderer.cpp.
render3D()
void Atlas::Renderer::render3D (GameCamera & cam) [private]
Renders the 3d scene.
Parameters
cam The active camera.
Definition at line 120 of file Renderer.cpp.
texture()
void Atlas::Renderer::texture (GameCamera & cam)
Textures the scene to the render texture using the specified camera.
Parameters
cam The cam.
Definition at line 60 of file Renderer.cpp.
References Atlas::GameCamera::getCameraData().
update()
void Atlas::Renderer::update ()
Definition at line 81 of file Renderer.cpp.
Member Data Documentation
mBackgroundColor
Color Atlas::Renderer::mBackgroundColor = BLACK [private]
Definition at line 91 of file Renderer.h.
mCamera
GameCamera Atlas::Renderer::mCamera
Definition at line 87 of file Renderer.h.
Referenced by Renderer().
mFBOTint
Color Atlas::Renderer::mFBOTint = WHITE [private]
Definition at line 92 of file Renderer.h.
mGameObjects
GameObjectRegistry Atlas::Renderer::mGameObjects [private]
Definition at line 89 of file Renderer.h.
mScreenBuffer
RenderTexture2D Atlas::Renderer::mScreenBuffer [private]
Definition at line 90 of file Renderer.h.
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/renderer/Renderer.h
C:/Dev/Techstorm-v5/src/engine/renderer/Renderer.cpp