Atlas::PipelineBuilder Class Reference
#include <PipelineBuilder.h>
Public Member Functions
PipelineBuilder ()
void clear ()
VkPipeline buildPipeline (VkDevice device)
void setShaders (VkShaderModule vertexShader, VkShaderModule fragmentShader)
void setInputTopography (VkPrimitiveTopology topology)
void setPolygonMode (VkPolygonMode mode)
void setCullMode (VkCullModeFlags cullMode, VkFrontFace frontFace)
void setMultisamplingNone ()
void disableBlending ()
void setColorAttachmentFormat (VkFormat format)
void setDepthFormat (VkFormat format)
void disableDepthTest ()
Public Attributes
std::vector< VkPipelineShaderStageCreateInfo > shaderStages
PipelineBuilderSettings settings
Detailed Description
Definition at line 30 of file PipelineBuilder.h.
Constructor & Destructor Documentation
PipelineBuilder()
Atlas::PipelineBuilder::PipelineBuilder () [inline]
Definition at line 36 of file PipelineBuilder.h.
References clear().
Member Function Documentation
buildPipeline()
VkPipeline Atlas::PipelineBuilder::buildPipeline (VkDevice device)
Definition at line 33 of file PipelineBuilder.cpp.
Referenced by Atlas::VulkanRenderingBackend::initMeshPipeline(), and Atlas::VulkanRenderingBackend::initTrianglePipeline().
clear()
void Atlas::PipelineBuilder::clear ()
Definition at line 12 of file PipelineBuilder.cpp.
References Atlas::PipelineBuilderSettings::colorBlendAttachment, Atlas::PipelineBuilderSettings::depthStencil, Atlas::PipelineBuilderSettings::inputAssembly, Atlas::PipelineBuilderSettings::multisampling, Atlas::PipelineBuilderSettings::pipelineLayout, Atlas::PipelineBuilderSettings::rasterizer, Atlas::PipelineBuilderSettings::renderInfo, settings, and shaderStages.
Referenced by PipelineBuilder().
disableBlending()
void Atlas::PipelineBuilder::disableBlending () [inline]
Definition at line 82 of file PipelineBuilder.h.
References Atlas::PipelineBuilderSettings::colorBlendAttachment, and settings.
Referenced by Atlas::VulkanRenderingBackend::initMeshPipeline(), and Atlas::VulkanRenderingBackend::initTrianglePipeline().
disableDepthTest()
void Atlas::PipelineBuilder::disableDepthTest () [inline]
Definition at line 104 of file PipelineBuilder.h.
References Atlas::PipelineBuilderSettings::depthStencil, and settings.
Referenced by Atlas::VulkanRenderingBackend::initMeshPipeline(), and Atlas::VulkanRenderingBackend::initTrianglePipeline().
setColorAttachmentFormat()
void Atlas::PipelineBuilder::setColorAttachmentFormat (VkFormat format) [inline]
Definition at line 90 of file PipelineBuilder.h.
References Atlas::PipelineBuilderSettings::colorAttachmentformat, Atlas::PipelineBuilderSettings::renderInfo, and settings.
Referenced by Atlas::VulkanRenderingBackend::initMeshPipeline(), and Atlas::VulkanRenderingBackend::initTrianglePipeline().
setCullMode()
void Atlas::PipelineBuilder::setCullMode (VkCullModeFlags cullMode, VkFrontFace frontFace) [inline]
Definition at line 64 of file PipelineBuilder.h.
References Atlas::PipelineBuilderSettings::rasterizer, and settings.
Referenced by Atlas::VulkanRenderingBackend::initMeshPipeline(), and Atlas::VulkanRenderingBackend::initTrianglePipeline().
setDepthFormat()
void Atlas::PipelineBuilder::setDepthFormat (VkFormat format) [inline]
Definition at line 99 of file PipelineBuilder.h.
References Atlas::PipelineBuilderSettings::renderInfo, and settings.
Referenced by Atlas::VulkanRenderingBackend::initMeshPipeline(), and Atlas::VulkanRenderingBackend::initTrianglePipeline().
setInputTopography()
void Atlas::PipelineBuilder::setInputTopography (VkPrimitiveTopology topology) [inline]
Definition at line 52 of file PipelineBuilder.h.
References Atlas::PipelineBuilderSettings::inputAssembly, and settings.
Referenced by Atlas::VulkanRenderingBackend::initMeshPipeline(), and Atlas::VulkanRenderingBackend::initTrianglePipeline().
setMultisamplingNone()
void Atlas::PipelineBuilder::setMultisamplingNone () [inline]
Definition at line 70 of file PipelineBuilder.h.
References Atlas::PipelineBuilderSettings::multisampling, and settings.
Referenced by Atlas::VulkanRenderingBackend::initMeshPipeline(), and Atlas::VulkanRenderingBackend::initTrianglePipeline().
setPolygonMode()
void Atlas::PipelineBuilder::setPolygonMode (VkPolygonMode mode) [inline]
Definition at line 59 of file PipelineBuilder.h.
References Atlas::PipelineBuilderSettings::rasterizer, and settings.
Referenced by Atlas::VulkanRenderingBackend::initMeshPipeline(), and Atlas::VulkanRenderingBackend::initTrianglePipeline().
setShaders()
void Atlas::PipelineBuilder::setShaders (VkShaderModule vertexShader, VkShaderModule fragmentShader) [inline]
Definition at line 42 of file PipelineBuilder.h.
References Atlas::CreatePipelineShaderStageCreateInfo(), and shaderStages.
Referenced by Atlas::VulkanRenderingBackend::initMeshPipeline(), and Atlas::VulkanRenderingBackend::initTrianglePipeline().
Member Data Documentation
settings
PipelineBuilderSettings Atlas::PipelineBuilder::settings
Definition at line 34 of file PipelineBuilder.h.
Referenced by clear(), disableBlending(), disableDepthTest(), Atlas::VulkanRenderingBackend::initMeshPipeline(), Atlas::VulkanRenderingBackend::initTrianglePipeline(), setColorAttachmentFormat(), setCullMode(), setDepthFormat(), setInputTopography(), setMultisamplingNone(), and setPolygonMode().
shaderStages
std::vector<VkPipelineShaderStageCreateInfo> Atlas::PipelineBuilder::shaderStages
Definition at line 32 of file PipelineBuilder.h.
Referenced by clear(), and setShaders().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/graphics/PipelineBuilder.h
C:/Dev/Techstorm-v5/src/engine/graphics/PipelineBuilder.cpp