Atlas::BroadPhaseLayers Namespace Reference
Functions
static constexpr JPH::BroadPhaseLayer NON_MOVING (0)
static constexpr JPH::BroadPhaseLayer MOVING (1)
static constexpr JPH::uint NUM_LAYERS (2)
Function Documentation
MOVING()
static constexpr JPH::BroadPhaseLayer Atlas::BroadPhaseLayers::MOVING (1) [static], [constexpr]
Referenced by Atlas::BPLayerInterfaceImpl::BPLayerInterfaceImpl(), and Atlas::ObjectVsBroadPhaseLayerFilterImpl::ShouldCollide().
NON_MOVING()
static constexpr JPH::BroadPhaseLayer Atlas::BroadPhaseLayers::NON_MOVING (0) [static], [constexpr]
Referenced by Atlas::BPLayerInterfaceImpl::BPLayerInterfaceImpl().
NUM_LAYERS()
static constexpr JPH::uint Atlas::BroadPhaseLayers::NUM_LAYERS (2) [static], [constexpr]
Referenced by Atlas::BPLayerInterfaceImpl::GetNumBroadPhaseLayers().