C:/Dev/Techstorm-v5/src/bindings/imgui_impl_wgpu.h File Reference
#include "imgui.h"
#include <webgpu/webgpu.h>
Classes
struct ImGui_ImplWGPU_InitInfo
struct ImGui_ImplWGPU_RenderState
Functions
IMGUI_IMPL_API bool ImGui_ImplWGPU_Init (ImGui_ImplWGPU_InitInfo *init_info)
IMGUI_IMPL_API void ImGui_ImplWGPU_Shutdown ()
IMGUI_IMPL_API void ImGui_ImplWGPU_NewFrame ()
IMGUI_IMPL_API void ImGui_ImplWGPU_RenderDrawData (ImDrawData *draw_data, WGPURenderPassEncoder pass_encoder)
IMGUI_IMPL_API bool ImGui_ImplWGPU_CreateDeviceObjects ()
IMGUI_IMPL_API void ImGui_ImplWGPU_InvalidateDeviceObjects ()
Function Documentation
ImGui_ImplWGPU_CreateDeviceObjects()
IMGUI_IMPL_API bool ImGui_ImplWGPU_CreateDeviceObjects ()
Definition at line 613 of file imgui_impl_wgpu.cpp.
References __shader_frag_wgsl, __shader_vert_wgsl, RenderResources::CommonBindGroup, ImGui_ImplWGPU_Data::depthStencilFormat, RenderResources::FontTextureView, RenderResources::ImageBindGroup, RenderResources::ImageBindGroupLayout, RenderResources::ImageBindGroups, ImGui_ImplWGPU_CreateFontsTexture(), ImGui_ImplWGPU_CreateImageBindGroup(), ImGui_ImplWGPU_CreateShaderModule(), ImGui_ImplWGPU_CreateUniformBuffer(), ImGui_ImplWGPU_GetBackendData(), ImGui_ImplWGPU_InvalidateDeviceObjects(), ImHashData(), ImGui_ImplWGPU_Data::initInfo, MEMALIGN, ImGui_ImplWGPU_InitInfo::PipelineMultisampleState, ImGui_ImplWGPU_Data::pipelineState, ImGui_ImplWGPU_Data::renderResources, ImGui_ImplWGPU_Data::renderTargetFormat, SafeRelease(), RenderResources::Sampler, RenderResources::Uniforms, and ImGui_ImplWGPU_Data::wgpuDevice.
Referenced by ImGui_ImplWGPU_NewFrame().
ImGui_ImplWGPU_Init()
IMGUI_IMPL_API bool ImGui_ImplWGPU_Init (ImGui_ImplWGPU_InitInfo * init_info)
Definition at line 776 of file imgui_impl_wgpu.cpp.
References RenderResources::CommonBindGroup, ImGui_ImplWGPU_Data::defaultQueue, ImGui_ImplWGPU_Data::depthStencilFormat, ImGui_ImplWGPU_InitInfo::DepthStencilFormat, ImGui_ImplWGPU_InitInfo::Device, RenderResources::FontTexture, RenderResources::FontTextureView, ImGui_ImplWGPU_Data::frameIndex, RenderResources::ImageBindGroup, RenderResources::ImageBindGroupLayout, RenderResources::ImageBindGroups, FrameResources::IndexBuffer, FrameResources::IndexBufferHost, FrameResources::IndexBufferSize, ImGui_ImplWGPU_Data::initInfo, ImGui_ImplWGPU_Data::numFramesInFlight, ImGui_ImplWGPU_InitInfo::NumFramesInFlight, ImGui_ImplWGPU_Data::pFrameResources, ImGui_ImplWGPU_Data::renderResources, ImGui_ImplWGPU_Data::renderTargetFormat, ImGui_ImplWGPU_InitInfo::RenderTargetFormat, RenderResources::Sampler, RenderResources::Uniforms, FrameResources::VertexBuffer, FrameResources::VertexBufferHost, FrameResources::VertexBufferSize, and ImGui_ImplWGPU_Data::wgpuDevice.
ImGui_ImplWGPU_InvalidateDeviceObjects()
IMGUI_IMPL_API void ImGui_ImplWGPU_InvalidateDeviceObjects ()
Definition at line 760 of file imgui_impl_wgpu.cpp.
References ImGui_ImplWGPU_GetBackendData(), ImGui_ImplWGPU_Data::numFramesInFlight, ImGui_ImplWGPU_Data::pFrameResources, ImGui_ImplWGPU_Data::pipelineState, ImGui_ImplWGPU_Data::renderResources, SafeRelease(), and ImGui_ImplWGPU_Data::wgpuDevice.
Referenced by ImGui_ImplWGPU_CreateDeviceObjects(), and ImGui_ImplWGPU_Shutdown().
ImGui_ImplWGPU_NewFrame()
IMGUI_IMPL_API void ImGui_ImplWGPU_NewFrame ()
Definition at line 849 of file imgui_impl_wgpu.cpp.
References ImGui_ImplWGPU_CreateDeviceObjects(), ImGui_ImplWGPU_GetBackendData(), and ImGui_ImplWGPU_Data::pipelineState.
ImGui_ImplWGPU_RenderDrawData()
IMGUI_IMPL_API void ImGui_ImplWGPU_RenderDrawData (ImDrawData * draw_data, WGPURenderPassEncoder pass_encoder)
Definition at line 367 of file imgui_impl_wgpu.cpp.
References ImGui_ImplWGPU_Data::defaultQueue, ImGui_ImplWGPU_RenderState::Device, ImGui_ImplWGPU_Data::frameIndex, RenderResources::ImageBindGroupLayout, RenderResources::ImageBindGroups, ImGui_ImplWGPU_CreateImageBindGroup(), ImGui_ImplWGPU_GetBackendData(), ImGui_ImplWGPU_SetupRenderState(), ImHashData(), FrameResources::IndexBuffer, FrameResources::IndexBufferHost, FrameResources::IndexBufferSize, MEMALIGN, ImGui_ImplWGPU_Data::numFramesInFlight, ImGui_ImplWGPU_Data::pFrameResources, ImGui_ImplWGPU_RenderState::RenderPassEncoder, ImGui_ImplWGPU_Data::renderResources, SafeRelease(), FrameResources::VertexBuffer, FrameResources::VertexBufferHost, FrameResources::VertexBufferSize, and ImGui_ImplWGPU_Data::wgpuDevice.
ImGui_ImplWGPU_Shutdown()
IMGUI_IMPL_API void ImGui_ImplWGPU_Shutdown ()
Definition at line 829 of file imgui_impl_wgpu.cpp.
References ImGui_ImplWGPU_Data::defaultQueue, ImGui_ImplWGPU_Data::frameIndex, ImGui_ImplWGPU_GetBackendData(), ImGui_ImplWGPU_InvalidateDeviceObjects(), ImGui_ImplWGPU_Data::numFramesInFlight, ImGui_ImplWGPU_Data::pFrameResources, and ImGui_ImplWGPU_Data::wgpuDevice.