CDateTime Class Reference
#include <datetime.h>
Public Member Functions
CDateTime ()
CDateTime (const CDateTime &other)
CDateTime (asUINT year, asUINT month, asUINT day, asUINT hour, asUINT minute, asUINT second)
CDateTime & operator= (const CDateTime &other)
asUINT getYear () const
asUINT getMonth () const
asUINT getDay () const
asUINT getHour () const
asUINT getMinute () const
asUINT getSecond () const
bool setDate (asUINT year, asUINT month, asUINT day)
bool setTime (asUINT hour, asUINT minute, asUINT second)
asINT64 operator- (const CDateTime &other) const
CDateTime operator+ (asINT64 seconds) const
CDateTime & operator+= (asINT64 seconds)
CDateTime operator- (asINT64 seconds) const
CDateTime & operator-= (asINT64 seconds)
bool operator== (const CDateTime &other) const
bool operator< (const CDateTime &other) const
Protected Attributes
std::chrono::system_clock::time_point tp
Friends
CDateTime operator+ (asINT64 seconds, const CDateTime &other)
CDateTime operator- (asINT64 seconds, const CDateTime &other)
Detailed Description
Definition at line 17 of file datetime.h.
Constructor & Destructor Documentation
CDateTime() [1/3]
CDateTime::CDateTime ()
Definition at line 50 of file datetime.cpp.
CDateTime() [2/3]
CDateTime::CDateTime (const CDateTime & other)
Definition at line 54 of file datetime.cpp.
CDateTime() [3/3]
CDateTime::CDateTime (asUINT year, asUINT month, asUINT day, asUINT hour, asUINT minute, asUINT second)
Definition at line 146 of file datetime.cpp.
References setDate(), setTime(), and tp.
Member Function Documentation
getDay()
asUINT CDateTime::getDay () const
Definition at line 76 of file datetime.cpp.
References time_point_to_tm(), and tp.
getHour()
asUINT CDateTime::getHour () const
Definition at line 82 of file datetime.cpp.
References time_point_to_tm(), and tp.
getMinute()
asUINT CDateTime::getMinute () const
Definition at line 88 of file datetime.cpp.
References time_point_to_tm(), and tp.
getMonth()
asUINT CDateTime::getMonth () const
Definition at line 70 of file datetime.cpp.
References time_point_to_tm(), and tp.
getSecond()
asUINT CDateTime::getSecond () const
Definition at line 94 of file datetime.cpp.
References time_point_to_tm(), and tp.
getYear()
asUINT CDateTime::getYear () const
Definition at line 64 of file datetime.cpp.
References time_point_to_tm(), and tp.
operator+()
CDateTime CDateTime::operator+ (asINT64 seconds) const
Definition at line 158 of file datetime.cpp.
References tp.
operator+=()
CDateTime & CDateTime::operator+= (asINT64 seconds)
Definition at line 165 of file datetime.cpp.
References tp.
operator-() [1/2]
CDateTime CDateTime::operator- (asINT64 seconds) const
Definition at line 176 of file datetime.cpp.
operator-() [2/2]
asINT64 CDateTime::operator- (const CDateTime & other) const
Definition at line 153 of file datetime.cpp.
References tp.
operator-=()
CDateTime & CDateTime::operator-= (asINT64 seconds)
Definition at line 181 of file datetime.cpp.
operator<()
bool CDateTime::operator< (const CDateTime & other) const
Definition at line 196 of file datetime.cpp.
References tp.
operator=()
CDateTime & CDateTime::operator= (const CDateTime & other)
Definition at line 58 of file datetime.cpp.
References tp.
operator==()
bool CDateTime::operator== (const CDateTime & other) const
Definition at line 191 of file datetime.cpp.
References tp.
setDate()
bool CDateTime::setDate (asUINT year, asUINT month, asUINT day)
Definition at line 100 of file datetime.cpp.
References time_point_to_tm(), tm_to_time_point(), and tp.
Referenced by CDateTime().
setTime()
bool CDateTime::setTime (asUINT hour, asUINT minute, asUINT second)
Definition at line 123 of file datetime.cpp.
References time_point_to_tm(), tm_to_time_point(), and tp.
Referenced by CDateTime().
Friends And Related Symbol Documentation
operator+
CDateTime operator+ (asINT64 seconds, const CDateTime & other) [friend]
Definition at line 171 of file datetime.cpp.
operator-
CDateTime operator- (asINT64 seconds, const CDateTime & other) [friend]
Definition at line 186 of file datetime.cpp.
Member Data Documentation
tp
std::chrono::system_clock::time_point CDateTime::tp [protected]
Definition at line 54 of file datetime.h.
Referenced by CDateTime(), getDay(), getHour(), getMinute(), getMonth(), getSecond(), getYear(), operator+(), operator+=(), operator-(), operator<(), operator=(), operator==(), setDate(), and setTime().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/application/add_on/datetime/datetime.h
C:/Dev/Techstorm-v5/src/application/add_on/datetime/datetime.cpp