C:/Dev/Techstorm-v5/src/application/add_on/scriptgrid/scriptgrid.cpp File Reference
#include <new>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <stdio.h>
#include "scriptgrid.h"
Classes
struct SGridBuffer
Functions
static void RegisterScriptGrid_Native (asIScriptEngine *engine)
static bool ScriptGridTemplateCallback (asITypeInfo *ti, bool &dontGarbageCollect)
void RegisterScriptGrid (asIScriptEngine *engine)
Variables
static BEGIN_AS_NAMESPACE asALLOCFUNC_t userAlloc = asAllocMem
static asFREEFUNC_t userFree = asFreeMem
Function Documentation
RegisterScriptGrid()
void RegisterScriptGrid (asIScriptEngine * engine)
Definition at line 215 of file scriptgrid.cpp.
References RegisterScriptGrid_Native().
RegisterScriptGrid_Native()
static void RegisterScriptGrid_Native (asIScriptEngine * engine) [static]
Definition at line 221 of file scriptgrid.cpp.
References CScriptGrid::Create(), and ScriptGridTemplateCallback().
Referenced by RegisterScriptGrid().
ScriptGridTemplateCallback()
static bool ScriptGridTemplateCallback (asITypeInfo * ti, bool & dontGarbageCollect) [static]
Definition at line 101 of file scriptgrid.cpp.
Referenced by RegisterScriptGrid_Native().
Variable Documentation
userAlloc
BEGIN_AS_NAMESPACE asALLOCFUNC_t userAlloc = asAllocMem [static]
Definition at line 15 of file scriptgrid.cpp.
userFree
asFREEFUNC_t userFree = asFreeMem [static]
Definition at line 16 of file scriptgrid.cpp.