Atlas::DeletionQueue Class Reference
#include <DeletionQueue.h>
Public Member Functions
DeletionQueue ()=default
~DeletionQueue ()
void push (DeletionQueueDeletor &&function)
void flush ()
size_t getSize () const
std::deque< DeletionQueueDeletor > & getDeletorsDeque ()
Private Attributes
std::deque< DeletionQueueDeletor > mDeletorsDeque
Detailed Description
Definition at line 18 of file DeletionQueue.h.
Constructor & Destructor Documentation
DeletionQueue()
Atlas::DeletionQueue::DeletionQueue () [default]
~DeletionQueue()
Atlas::DeletionQueue::~DeletionQueue () [inline]
Definition at line 28 of file DeletionQueue.h.
References flush().
Member Function Documentation
flush()
void Atlas::DeletionQueue::flush () [inline]
Definition at line 36 of file DeletionQueue.h.
References mDeletorsDeque.
Referenced by Atlas::VulkanRenderingBackend::resetFences(), and ~DeletionQueue().
getDeletorsDeque()
std::deque< DeletionQueueDeletor > & Atlas::DeletionQueue::getDeletorsDeque () [inline]
Definition at line 52 of file DeletionQueue.h.
References mDeletorsDeque.
getSize()
size_t Atlas::DeletionQueue::getSize () const [inline]
Definition at line 48 of file DeletionQueue.h.
References mDeletorsDeque.
push()
void Atlas::DeletionQueue::push (DeletionQueueDeletor && function) [inline]
Definition at line 32 of file DeletionQueue.h.
References mDeletorsDeque.
Referenced by Atlas::Pipeline::init().
Member Data Documentation
mDeletorsDeque
std::deque<DeletionQueueDeletor> Atlas::DeletionQueue::mDeletorsDeque [private]
Definition at line 22 of file DeletionQueue.h.
Referenced by flush(), getDeletorsDeque(), getSize(), and push().
The documentation for this class was generated from the following file:
C:/Dev/Techstorm-v5/src/engine/graphics/DeletionQueue.h