C:/Dev/Techstorm-v5/src/application/add_on/scriptfile/scriptfilesystem.cpp File Reference
#include "scriptfilesystem.h"
#include "../autowrapper/aswrappedcall.h"
#include <string.h>
#include <unistd.h>
#include <dirent.h>
#include <sys/stat.h>
#include <assert.h>
Functions
BEGIN_AS_NAMESPACE CScriptFileSystem * ScriptFileSystem_Factory ()
void RegisterScriptFileSystem_Native (asIScriptEngine *engine)
void RegisterScriptFileSystem_Generic (asIScriptEngine *engine)
void RegisterScriptFileSystem (asIScriptEngine *engine)
Function Documentation
RegisterScriptFileSystem()
void RegisterScriptFileSystem (asIScriptEngine * engine)
Definition at line 89 of file scriptfilesystem.cpp.
References RegisterScriptFileSystem_Generic(), and RegisterScriptFileSystem_Native().
RegisterScriptFileSystem_Generic()
void RegisterScriptFileSystem_Generic (asIScriptEngine * engine)
Definition at line 60 of file scriptfilesystem.cpp.
References ScriptFileSystem_Factory(), WRAP_FN, and WRAP_MFN.
Referenced by RegisterScriptFileSystem().
RegisterScriptFileSystem_Native()
void RegisterScriptFileSystem_Native (asIScriptEngine * engine)
Definition at line 31 of file scriptfilesystem.cpp.
References ScriptFileSystem_Factory().
Referenced by RegisterScriptFileSystem().
ScriptFileSystem_Factory()
BEGIN_AS_NAMESPACE CScriptFileSystem * ScriptFileSystem_Factory ()
Definition at line 26 of file scriptfilesystem.cpp.
Referenced by RegisterScriptFileSystem_Generic(), and RegisterScriptFileSystem_Native().