C:/Dev/Techstorm-v5/src/application/add_on/weakref/weakref.cpp File Reference
#include "weakref.h"
#include <new>
#include <assert.h>
#include <string.h>
Functions
void RegisterScriptWeakRef_Native (asIScriptEngine *engine)
void CScriptWeakRef_Get_Generic (asIScriptGeneric *gen)
void CScriptWeakRef_Assign_Generic (asIScriptGeneric *gen)
void CScriptWeakRef_Assign2_Generic (asIScriptGeneric *gen)
void CScriptWeakRef_Equals_Generic (asIScriptGeneric *gen)
void CScriptWeakRef_Equals2_Generic (asIScriptGeneric *gen)
void RegisterScriptWeakRef_Generic (asIScriptEngine *engine)
void RegisterScriptWeakRef (asIScriptEngine *engine)
Function Documentation
CScriptWeakRef_Assign2_Generic()
void CScriptWeakRef_Assign2_Generic (asIScriptGeneric * gen)
Definition at line 297 of file weakref.cpp.
References CScriptWeakRef::Set().
Referenced by RegisterScriptWeakRef_Generic().
CScriptWeakRef_Assign_Generic()
void CScriptWeakRef_Assign_Generic (asIScriptGeneric * gen)
Definition at line 289 of file weakref.cpp.
CScriptWeakRef_Equals2_Generic()
void CScriptWeakRef_Equals2_Generic (asIScriptGeneric * gen)
Definition at line 312 of file weakref.cpp.
References CScriptWeakRef::Equals().
Referenced by RegisterScriptWeakRef_Generic().
CScriptWeakRef_Equals_Generic()
void CScriptWeakRef_Equals_Generic (asIScriptGeneric * gen)
Definition at line 305 of file weakref.cpp.
Referenced by RegisterScriptWeakRef_Generic().
CScriptWeakRef_Get_Generic()
void CScriptWeakRef_Get_Generic (asIScriptGeneric * gen)
Definition at line 283 of file weakref.cpp.
References CScriptWeakRef::Get().
RegisterScriptWeakRef()
void RegisterScriptWeakRef (asIScriptEngine * engine)
Definition at line 368 of file weakref.cpp.
References RegisterScriptWeakRef_Generic(), and RegisterScriptWeakRef_Native().
RegisterScriptWeakRef_Generic()
void RegisterScriptWeakRef_Generic (asIScriptEngine * engine)
Definition at line 327 of file weakref.cpp.
References CScriptWeakRef_Assign2_Generic(), CScriptWeakRef_Assign_Generic(), CScriptWeakRef_Equals2_Generic(), CScriptWeakRef_Equals_Generic(), and CScriptWeakRef_Get_Generic().
RegisterScriptWeakRef_Native()
void RegisterScriptWeakRef_Native (asIScriptEngine * engine)
Definition at line 221 of file weakref.cpp.