CScriptGrid Class Reference
#include <scriptgrid.h>
Public Member Functions
void AddRef () const
void Release () const
asITypeInfo * GetGridObjectType () const
int GetGridTypeId () const
int GetElementTypeId () const
asUINT GetWidth () const
asUINT GetHeight () const
void Resize (asUINT width, asUINT height)
void * At (asUINT x, asUINT y)
const void * At (asUINT x, asUINT y) const
void SetValue (asUINT x, asUINT y, void *value)
int GetRefCount ()
void SetFlag ()
bool GetFlag ()
void EnumReferences (asIScriptEngine *engine)
void ReleaseAllHandles (asIScriptEngine *engine)
void AddRef () const
void Release () const
asITypeInfo * GetGridObjectType () const
int GetGridTypeId () const
int GetElementTypeId () const
asUINT GetWidth () const
asUINT GetHeight () const
void Resize (asUINT width, asUINT height)
void * At (asUINT x, asUINT y)
const void * At (asUINT x, asUINT y) const
void SetValue (asUINT x, asUINT y, void *value)
int GetRefCount ()
void SetFlag ()
bool GetFlag ()
void EnumReferences (asIScriptEngine *engine)
void ReleaseAllHandles (asIScriptEngine *engine)
Static Public Member Functions
static void SetMemoryFunctions (asALLOCFUNC_t allocFunc, asFREEFUNC_t freeFunc)
static CScriptGrid * Create (asITypeInfo *ot)
static CScriptGrid * Create (asITypeInfo *ot, asUINT width, asUINT height)
static CScriptGrid * Create (asITypeInfo *ot, asUINT width, asUINT height, void *defaultValue)
static CScriptGrid * Create (asITypeInfo *ot, void *listBuffer)
static void SetMemoryFunctions (asALLOCFUNC_t allocFunc, asFREEFUNC_t freeFunc)
static CScriptGrid * Create (asITypeInfo *ot)
static CScriptGrid * Create (asITypeInfo *ot, asUINT width, asUINT height)
static CScriptGrid * Create (asITypeInfo *ot, asUINT width, asUINT height, void *defaultValue)
static CScriptGrid * Create (asITypeInfo *ot, void *listBuffer)
Protected Member Functions
CScriptGrid (asITypeInfo *ot, void *initBuf)
CScriptGrid (asUINT w, asUINT h, asITypeInfo *ot)
CScriptGrid (asUINT w, asUINT h, void *defVal, asITypeInfo *ot)
virtual ~CScriptGrid ()
bool CheckMaxSize (asUINT x, asUINT y)
void CreateBuffer (SGridBuffer **buf, asUINT w, asUINT h)
void DeleteBuffer (SGridBuffer *buf)
void Construct (SGridBuffer *buf)
void Destruct (SGridBuffer *buf)
void SetValue (SGridBuffer *buf, asUINT x, asUINT y, void *value)
void * At (SGridBuffer *buf, asUINT x, asUINT y)
CScriptGrid (asITypeInfo *ot, void *initBuf)
CScriptGrid (asUINT w, asUINT h, asITypeInfo *ot)
CScriptGrid (asUINT w, asUINT h, void *defVal, asITypeInfo *ot)
virtual ~CScriptGrid ()
bool CheckMaxSize (asUINT x, asUINT y)
void CreateBuffer (SGridBuffer **buf, asUINT w, asUINT h)
void DeleteBuffer (SGridBuffer *buf)
void Construct (SGridBuffer *buf)
void Destruct (SGridBuffer *buf)
void SetValue (SGridBuffer *buf, asUINT x, asUINT y, void *value)
void * At (SGridBuffer *buf, asUINT x, asUINT y)
Protected Attributes
int refCount
bool gcFlag
asITypeInfo * objType
SGridBuffer * buffer
int elementSize
int subTypeId
Detailed Description
Definition at line 13 of file scriptgrid.h.
Constructor & Destructor Documentation
CScriptGrid() [1/6]
CScriptGrid::CScriptGrid (asITypeInfo * ot, void * initBuf) [protected]
Definition at line 260 of file scriptgrid.cpp.
References At(), CheckMaxSize(), CreateBuffer(), elementSize, gcFlag, objType, refCount, and subTypeId.
CScriptGrid() [2/6]
CScriptGrid::CScriptGrid (asUINT w, asUINT h, asITypeInfo * ot) [protected]
Definition at line 412 of file scriptgrid.cpp.
References CheckMaxSize(), CreateBuffer(), elementSize, gcFlag, objType, refCount, and subTypeId.
CScriptGrid() [3/6]
CScriptGrid::CScriptGrid (asUINT w, asUINT h, void * defVal, asITypeInfo * ot) [protected]
Definition at line 469 of file scriptgrid.cpp.
References CheckMaxSize(), CreateBuffer(), elementSize, gcFlag, GetHeight(), GetWidth(), objType, refCount, SetValue(), and subTypeId.
~CScriptGrid() [1/2]
CScriptGrid::~CScriptGrid () [protected], [virtual]
Definition at line 543 of file scriptgrid.cpp.
References DeleteBuffer(), and objType.
Referenced by Release().
CScriptGrid() [4/6]
CScriptGrid::CScriptGrid (asITypeInfo * ot, void * initBuf) [protected]
CScriptGrid() [5/6]
CScriptGrid::CScriptGrid (asUINT w, asUINT h, asITypeInfo * ot) [protected]
CScriptGrid() [6/6]
CScriptGrid::CScriptGrid (asUINT w, asUINT h, void * defVal, asITypeInfo * ot) [protected]
~CScriptGrid() [2/2]
virtual CScriptGrid::~CScriptGrid () [protected], [virtual]
Member Function Documentation
AddRef() [1/2]
void CScriptGrid::AddRef () const
Definition at line 769 of file scriptgrid.cpp.
References gcFlag, and refCount.
AddRef() [2/2]
void CScriptGrid::AddRef () const
At() [1/6]
void * CScriptGrid::At (asUINT x, asUINT y)
Definition at line 609 of file scriptgrid.cpp.
References At().
Referenced by At(), At(), CScriptGrid(), Resize(), and SetValue().
At() [2/6]
void * CScriptGrid::At (asUINT x, asUINT y)
At() [3/6]
const void * CScriptGrid::At (asUINT x, asUINT y) const
Definition at line 632 of file scriptgrid.cpp.
References At().
At() [4/6]
const void * CScriptGrid::At (asUINT x, asUINT y) const
At() [5/6]
void * CScriptGrid::At (SGridBuffer * buf, asUINT x, asUINT y) [protected]
Definition at line 615 of file scriptgrid.cpp.
References SGridBuffer::data, elementSize, SGridBuffer::height, subTypeId, and SGridBuffer::width.
At() [6/6]
void * CScriptGrid::At (SGridBuffer * buf, asUINT x, asUINT y) [protected]
CheckMaxSize() [1/2]
bool CScriptGrid::CheckMaxSize (asUINT x, asUINT y) [protected]
Definition at line 570 of file scriptgrid.cpp.
References elementSize.
Referenced by CScriptGrid(), CScriptGrid(), CScriptGrid(), and Resize().
CheckMaxSize() [2/2]
bool CScriptGrid::CheckMaxSize (asUINT x, asUINT y) [protected]
Construct() [1/2]
void CScriptGrid::Construct (SGridBuffer * buf) [protected]
Definition at line 672 of file scriptgrid.cpp.
References SGridBuffer::data, SGridBuffer::height, objType, subTypeId, and SGridBuffer::width.
Referenced by CreateBuffer().
Construct() [2/2]
void CScriptGrid::Construct (SGridBuffer * buf) [protected]
Create() [1/8]
CScriptGrid * CScriptGrid::Create (asITypeInfo * ot) [static]
Definition at line 34 of file scriptgrid.cpp.
References Create().
Referenced by Create().
Create() [2/8]
static CScriptGrid * CScriptGrid::Create (asITypeInfo * ot) [static]
Create() [3/8]
CScriptGrid * CScriptGrid::Create (asITypeInfo * ot, asUINT width, asUINT height) [static]
Definition at line 39 of file scriptgrid.cpp.
Create() [4/8]
static CScriptGrid * CScriptGrid::Create (asITypeInfo * ot, asUINT width, asUINT height) [static]
Create() [5/8]
CScriptGrid * CScriptGrid::Create (asITypeInfo * ot, asUINT width, asUINT height, void * defaultValue) [static]
Definition at line 77 of file scriptgrid.cpp.
Create() [6/8]
static CScriptGrid * CScriptGrid::Create (asITypeInfo * ot, asUINT width, asUINT height, void * defaultValue) [static]
Create() [7/8]
CScriptGrid * CScriptGrid::Create (asITypeInfo * ot, void * listBuffer) [static]
Definition at line 58 of file scriptgrid.cpp.
Create() [8/8]
static CScriptGrid * CScriptGrid::Create (asITypeInfo * ot, void * listBuffer) [static]
CreateBuffer() [1/2]
void CScriptGrid::CreateBuffer (SGridBuffer ** buf, asUINT w, asUINT h) [protected]
Definition at line 639 of file scriptgrid.cpp.
References Construct(), elementSize, and SGridBuffer::width.
Referenced by CScriptGrid(), CScriptGrid(), CScriptGrid(), and Resize().
CreateBuffer() [2/2]
void CScriptGrid::CreateBuffer (SGridBuffer ** buf, asUINT w, asUINT h) [protected]
DeleteBuffer() [1/2]
void CScriptGrid::DeleteBuffer (SGridBuffer * buf) [protected]
Definition at line 661 of file scriptgrid.cpp.
References Destruct().
Referenced by ReleaseAllHandles(), Resize(), and ~CScriptGrid().
DeleteBuffer() [2/2]
void CScriptGrid::DeleteBuffer (SGridBuffer * buf) [protected]
Destruct() [1/2]
void CScriptGrid::Destruct (SGridBuffer * buf) [protected]
Definition at line 708 of file scriptgrid.cpp.
References SGridBuffer::data, SGridBuffer::height, objType, subTypeId, and SGridBuffer::width.
Referenced by DeleteBuffer().
Destruct() [2/2]
void CScriptGrid::Destruct (SGridBuffer * buf) [protected]
EnumReferences() [1/2]
void CScriptGrid::EnumReferences (asIScriptEngine * engine)
Definition at line 728 of file scriptgrid.cpp.
References subTypeId.
EnumReferences() [2/2]
void CScriptGrid::EnumReferences (asIScriptEngine * engine)
GetElementTypeId() [1/2]
int CScriptGrid::GetElementTypeId () const
Definition at line 604 of file scriptgrid.cpp.
References subTypeId.
GetElementTypeId() [2/2]
int CScriptGrid::GetElementTypeId () const
GetFlag() [1/2]
bool CScriptGrid::GetFlag ()
Definition at line 802 of file scriptgrid.cpp.
References gcFlag.
GetFlag() [2/2]
bool CScriptGrid::GetFlag ()
GetGridObjectType() [1/2]
asITypeInfo * CScriptGrid::GetGridObjectType () const
Definition at line 594 of file scriptgrid.cpp.
References objType.
GetGridObjectType() [2/2]
asITypeInfo * CScriptGrid::GetGridObjectType () const
GetGridTypeId() [1/2]
int CScriptGrid::GetGridTypeId () const
Definition at line 599 of file scriptgrid.cpp.
References objType.
GetGridTypeId() [2/2]
int CScriptGrid::GetGridTypeId () const
GetHeight() [1/2]
asUINT CScriptGrid::GetHeight () const
Definition at line 561 of file scriptgrid.cpp.
Referenced by CScriptGrid().
GetHeight() [2/2]
asUINT CScriptGrid::GetHeight () const
GetRefCount() [1/2]
int CScriptGrid::GetRefCount ()
Definition at line 790 of file scriptgrid.cpp.
References refCount.
GetRefCount() [2/2]
int CScriptGrid::GetRefCount ()
GetWidth() [1/2]
asUINT CScriptGrid::GetWidth () const
Definition at line 553 of file scriptgrid.cpp.
Referenced by CScriptGrid().
GetWidth() [2/2]
asUINT CScriptGrid::GetWidth () const
Release() [1/2]
void CScriptGrid::Release () const
Definition at line 776 of file scriptgrid.cpp.
References gcFlag, refCount, and ~CScriptGrid().
Release() [2/2]
void CScriptGrid::Release () const
ReleaseAllHandles() [1/2]
void CScriptGrid::ReleaseAllHandles (asIScriptEngine * engine)
Definition at line 761 of file scriptgrid.cpp.
References DeleteBuffer().
ReleaseAllHandles() [2/2]
void CScriptGrid::ReleaseAllHandles (asIScriptEngine * engine)
Resize() [1/2]
void CScriptGrid::Resize (asUINT width, asUINT height)
Definition at line 441 of file scriptgrid.cpp.
References At(), CheckMaxSize(), CreateBuffer(), DeleteBuffer(), and SetValue().
Resize() [2/2]
void CScriptGrid::Resize (asUINT width, asUINT height)
SetFlag() [1/2]
void CScriptGrid::SetFlag ()
Definition at line 796 of file scriptgrid.cpp.
References gcFlag.
SetFlag() [2/2]
void CScriptGrid::SetFlag ()
SetMemoryFunctions() [1/2]
void CScriptGrid::SetMemoryFunctions (asALLOCFUNC_t allocFunc, asFREEFUNC_t freeFunc) [static]
Definition at line 19 of file scriptgrid.cpp.
SetMemoryFunctions() [2/2]
static void CScriptGrid::SetMemoryFunctions (asALLOCFUNC_t allocFunc, asFREEFUNC_t freeFunc) [static]
SetValue() [1/4]
void CScriptGrid::SetValue (asUINT x, asUINT y, void * value)
Definition at line 503 of file scriptgrid.cpp.
References SetValue().
Referenced by CScriptGrid(), Resize(), and SetValue().
SetValue() [2/4]
void CScriptGrid::SetValue (asUINT x, asUINT y, void * value)
SetValue() [3/4]
void CScriptGrid::SetValue (SGridBuffer * buf, asUINT x, asUINT y, void * value) [protected]
Definition at line 508 of file scriptgrid.cpp.
References At(), objType, and subTypeId.
SetValue() [4/4]
void CScriptGrid::SetValue (SGridBuffer * buf, asUINT x, asUINT y, void * value) [protected]
Member Data Documentation
buffer
SGridBuffer * CScriptGrid::buffer [protected]
Definition at line 59 of file scriptgrid.h.
elementSize
int CScriptGrid::elementSize [protected]
Definition at line 60 of file scriptgrid.h.
Referenced by At(), CheckMaxSize(), CreateBuffer(), CScriptGrid(), CScriptGrid(), and CScriptGrid().
gcFlag
bool CScriptGrid::gcFlag [mutable], [protected]
Definition at line 57 of file scriptgrid.h.
Referenced by AddRef(), CScriptGrid(), CScriptGrid(), CScriptGrid(), GetFlag(), Release(), and SetFlag().
objType
asITypeInfo * CScriptGrid::objType [protected]
Definition at line 58 of file scriptgrid.h.
Referenced by Construct(), CScriptGrid(), CScriptGrid(), CScriptGrid(), Destruct(), GetGridObjectType(), GetGridTypeId(), SetValue(), and ~CScriptGrid().
refCount
int CScriptGrid::refCount [mutable], [protected]
Definition at line 56 of file scriptgrid.h.
Referenced by AddRef(), CScriptGrid(), CScriptGrid(), CScriptGrid(), GetRefCount(), and Release().
subTypeId
int CScriptGrid::subTypeId [protected]
Definition at line 61 of file scriptgrid.h.
Referenced by At(), Construct(), CScriptGrid(), CScriptGrid(), CScriptGrid(), Destruct(), EnumReferences(), GetElementTypeId(), and SetValue().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/application/add_on/scriptgrid/scriptgrid.h
C:/Dev/Techstorm-v5/src/engine/modding/add_on/scriptgrid/scriptgrid.h
C:/Dev/Techstorm-v5/src/application/add_on/scriptgrid/scriptgrid.cpp
C:/Dev/Techstorm-v5/src/engine/modding/add_on/scriptgrid/scriptgrid.cpp