Atlas::AsyncTimer Class Reference
#include <Timer.h>
Public Member Functions
void start (uint64_t length) override
void start () override
void stop () override
Public Member Functions inherited from Atlas::ATimer
ATimer (uint64_t startTime)
ATimer ()=default
virtual ~ATimer ()
virtual void reset ()
Static Private Member Functions
static void Wait (AsyncTimer *timer)
Private Attributes
uint64_t mDuration = 0
std::future< void > mTimerFuture
Additional Inherited Members
Protected Attributes inherited from Atlas::ATimer
uint64_t mStartTime = 0
bool mbClockRunning = false
bool mbClockPaused = false
bool mbClockFinished = false
Detailed Description
Definition at line 49 of file Timer.h.
Member Function Documentation
start() [1/2]
void Atlas::AsyncTimer::start () [override], [virtual]
Reimplemented from Atlas::ATimer.
Definition at line 39 of file Timer.cpp.
start() [2/2]
void Atlas::AsyncTimer::start (uint64_t length) [override], [virtual]
Implements Atlas::ATimer.
Definition at line 32 of file Timer.cpp.
References Atlas::ATimer::start(), and Wait().
stop()
void Atlas::AsyncTimer::stop () [override], [virtual]
Implements Atlas::ATimer.
Definition at line 44 of file Timer.cpp.
Wait()
static void Atlas::AsyncTimer::Wait (AsyncTimer * timer) [inline], [static], [private]
Definition at line 55 of file Timer.h.
References mDuration, and mTimerFuture.
Referenced by start().
Member Data Documentation
mDuration
uint64_t Atlas::AsyncTimer::mDuration = 0 [private]
Definition at line 51 of file Timer.h.
Referenced by Wait().
mTimerFuture
std::future<void> Atlas::AsyncTimer::mTimerFuture [private]
Definition at line 53 of file Timer.h.
Referenced by Wait().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/core/Timer.h
C:/Dev/Techstorm-v5/src/engine/core/Timer.cpp