CScriptAny Class Reference
#include <scriptany.h>
Classes
struct valueStruct
Public Member Functions
CScriptAny (asIScriptEngine *engine)
CScriptAny (void *ref, int refTypeId, asIScriptEngine *engine)
int AddRef () const
int Release () const
CScriptAny & operator= (const CScriptAny &)
int CopyFrom (const CScriptAny *other)
void Store (void *ref, int refTypeId)
void Store (asINT64 &value)
void Store (double &value)
bool Retrieve (void *ref, int refTypeId) const
bool Retrieve (asINT64 &value) const
bool Retrieve (double &value) const
int GetTypeId () const
int GetRefCount ()
void SetFlag ()
bool GetFlag ()
void EnumReferences (asIScriptEngine *engine)
void ReleaseAllHandles (asIScriptEngine *engine)
CScriptAny (asIScriptEngine *engine)
CScriptAny (void *ref, int refTypeId, asIScriptEngine *engine)
int AddRef () const
int Release () const
CScriptAny & operator= (const CScriptAny &)
int CopyFrom (const CScriptAny *other)
void Store (void *ref, int refTypeId)
void Store (asINT64 &value)
void Store (double &value)
bool Retrieve (void *ref, int refTypeId) const
bool Retrieve (asINT64 &value) const
bool Retrieve (double &value) const
int GetTypeId () const
int GetRefCount ()
void SetFlag ()
bool GetFlag ()
void EnumReferences (asIScriptEngine *engine)
void ReleaseAllHandles (asIScriptEngine *engine)
Protected Member Functions
virtual ~CScriptAny ()
void FreeObject ()
virtual ~CScriptAny ()
void FreeObject ()
Protected Attributes
int refCount
bool gcFlag
asIScriptEngine * engine
valueStruct value
Detailed Description
Definition at line 12 of file scriptany.h.
Constructor & Destructor Documentation
CScriptAny() [1/4]
CScriptAny::CScriptAny (asIScriptEngine * engine)
Definition at line 243 of file scriptany.cpp.
References engine, gcFlag, and refCount.
CScriptAny() [2/4]
CScriptAny::CScriptAny (void * ref, int refTypeId, asIScriptEngine * engine)
Definition at line 256 of file scriptany.cpp.
References engine, gcFlag, refCount, and Store().
~CScriptAny() [1/2]
CScriptAny::~CScriptAny () [protected], [virtual]
Definition at line 271 of file scriptany.cpp.
References FreeObject().
CScriptAny() [3/4]
CScriptAny::CScriptAny (asIScriptEngine * engine)
CScriptAny() [4/4]
CScriptAny::CScriptAny (void * ref, int refTypeId, asIScriptEngine * engine)
~CScriptAny() [2/2]
virtual CScriptAny::~CScriptAny () [protected], [virtual]
Member Function Documentation
AddRef() [1/2]
int CScriptAny::AddRef () const
Definition at line 453 of file scriptany.cpp.
References gcFlag, and refCount.
Referenced by operator=(), and ScriptAny_AddRef_Generic().
AddRef() [2/2]
int CScriptAny::AddRef () const
CopyFrom() [1/2]
int CScriptAny::CopyFrom (const CScriptAny * other)
Definition at line 234 of file scriptany.cpp.
CopyFrom() [2/2]
int CScriptAny::CopyFrom (const CScriptAny * other)
EnumReferences() [1/2]
void CScriptAny::EnumReferences (asIScriptEngine * engine)
Definition at line 424 of file scriptany.cpp.
References engine.
Referenced by ScriptAny_EnumReferences_Generic().
EnumReferences() [2/2]
void CScriptAny::EnumReferences (asIScriptEngine * engine)
FreeObject() [1/2]
void CScriptAny::FreeObject () [protected]
Definition at line 403 of file scriptany.cpp.
References engine.
Referenced by operator=(), ReleaseAllHandles(), Store(), and ~CScriptAny().
FreeObject() [2/2]
void CScriptAny::FreeObject () [protected]
GetFlag() [1/2]
bool CScriptAny::GetFlag ()
Definition at line 484 of file scriptany.cpp.
References gcFlag.
Referenced by ScriptAny_GetFlag_Generic().
GetFlag() [2/2]
bool CScriptAny::GetFlag ()
GetRefCount() [1/2]
int CScriptAny::GetRefCount ()
Definition at line 474 of file scriptany.cpp.
References refCount.
Referenced by ScriptAny_GetRefCount_Generic().
GetRefCount() [2/2]
int CScriptAny::GetRefCount ()
GetTypeId() [1/2]
int CScriptAny::GetTypeId () const
Definition at line 398 of file scriptany.cpp.
GetTypeId() [2/2]
int CScriptAny::GetTypeId () const
operator=() [1/2]
CScriptAny & CScriptAny::operator= (const CScriptAny & other)
Definition at line 201 of file scriptany.cpp.
References AddRef(), engine, FreeObject(), CScriptAny::valueStruct::typeId, value, CScriptAny::valueStruct::valueInt, and CScriptAny::valueStruct::valueObj.
operator=() [2/2]
CScriptAny & CScriptAny::operator= (const CScriptAny &)
Release() [1/2]
int CScriptAny::Release () const
Definition at line 460 of file scriptany.cpp.
References gcFlag, and refCount.
Referenced by ScriptAny_Release_Generic().
Release() [2/2]
int CScriptAny::Release () const
ReleaseAllHandles() [1/2]
void CScriptAny::ReleaseAllHandles (asIScriptEngine * engine)
Definition at line 448 of file scriptany.cpp.
References FreeObject().
Referenced by ScriptAny_ReleaseAllHandles_Generic().
ReleaseAllHandles() [2/2]
void CScriptAny::ReleaseAllHandles (asIScriptEngine * engine)
Retrieve() [1/6]
bool CScriptAny::Retrieve (asINT64 & value) const
Definition at line 388 of file scriptany.cpp.
References Retrieve().
Retrieve() [2/6]
bool CScriptAny::Retrieve (asINT64 & value) const
Retrieve() [3/6]
bool CScriptAny::Retrieve (double & value) const
Definition at line 393 of file scriptany.cpp.
References Retrieve().
Retrieve() [4/6]
bool CScriptAny::Retrieve (double & value) const
Retrieve() [5/6]
bool CScriptAny::Retrieve (void * ref, int refTypeId) const
Definition at line 326 of file scriptany.cpp.
References engine.
Referenced by Retrieve(), Retrieve(), ScriptAny_Retrieve_Generic(), ScriptAny_RetrieveFlt_Generic(), and ScriptAny_RetrieveInt_Generic().
Retrieve() [6/6]
bool CScriptAny::Retrieve (void * ref, int refTypeId) const
SetFlag() [1/2]
void CScriptAny::SetFlag ()
Definition at line 479 of file scriptany.cpp.
References gcFlag.
Referenced by ScriptAny_SetFlag_Generic().
SetFlag() [2/2]
void CScriptAny::SetFlag ()
Store() [1/6]
void CScriptAny::Store (asINT64 & value)
Definition at line 320 of file scriptany.cpp.
References Store().
Store() [2/6]
void CScriptAny::Store (asINT64 & value)
Store() [3/6]
void CScriptAny::Store (double & value)
Definition at line 315 of file scriptany.cpp.
References Store().
Store() [4/6]
void CScriptAny::Store (double & value)
Store() [5/6]
void CScriptAny::Store (void * ref, int refTypeId)
Definition at line 276 of file scriptany.cpp.
References engine, and FreeObject().
Referenced by CScriptAny(), ScriptAny_Store_Generic(), ScriptAny_StoreFlt_Generic(), ScriptAny_StoreInt_Generic(), Store(), and Store().
Store() [6/6]
void CScriptAny::Store (void * ref, int refTypeId)
Member Data Documentation
engine
asIScriptEngine * CScriptAny::engine [protected]
Definition at line 53 of file scriptany.h.
Referenced by CScriptAny(), CScriptAny(), EnumReferences(), FreeObject(), operator=(), Retrieve(), and Store().
gcFlag
bool CScriptAny::gcFlag [mutable], [protected]
Definition at line 52 of file scriptany.h.
Referenced by AddRef(), CScriptAny(), CScriptAny(), GetFlag(), Release(), and SetFlag().
refCount
int CScriptAny::refCount [mutable], [protected]
Definition at line 51 of file scriptany.h.
Referenced by AddRef(), CScriptAny(), CScriptAny(), GetRefCount(), and Release().
value
valueStruct CScriptAny::value [protected]
Definition at line 67 of file scriptany.h.
Referenced by operator=().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/application/add_on/scriptany/scriptany.h
C:/Dev/Techstorm-v5/src/engine/modding/add_on/scriptany/scriptany.h
C:/Dev/Techstorm-v5/src/application/add_on/scriptany/scriptany.cpp
C:/Dev/Techstorm-v5/src/engine/modding/add_on/scriptany/scriptany.cpp