C:/Dev/Techstorm-v5/src/application/add_on/datetime/datetime.h File Reference
#include <angelscript.h>
Classes
class CDateTime
Functions
void RegisterScriptDateTime (asIScriptEngine *engine)
Function Documentation
RegisterScriptDateTime()
void RegisterScriptDateTime (asIScriptEngine * engine)
Definition at line 235 of file datetime.cpp.
References Construct(), ConstructCopy(), ConstructSet(), ConstructSet_Generic(), opCmp(), WRAP_MFN, WRAP_MFN_PR, WRAP_OBJ_FIRST, WRAP_OBJ_LAST, and WRAP_OBJ_LAST_PR.