C:/Dev/Techstorm-v5/src/application/add_on/scripthelper/scripthelper.cpp File Reference
#include <string.h>
#include "scripthelper.h"
#include <assert.h>
#include <stdio.h>
#include <fstream>
#include <set>
#include <stdlib.h>
#include "../autowrapper/aswrappedcall.h"
Functions
BEGIN_AS_NAMESPACE int CompareRelation (asIScriptEngine *engine, void *lobj, void *robj, int typeId, int &result)
int CompareEquality (asIScriptEngine *engine, void *lobj, void *robj, int typeId, bool &result)
int ExecuteString (asIScriptEngine *engine, const char *code, asIScriptModule *mod, asIScriptContext *ctx)
int ExecuteString (asIScriptEngine *engine, const char *code, void *ref, int refTypeId, asIScriptModule *mod, asIScriptContext *ctx)
int WriteConfigToFile (asIScriptEngine *engine, const char *filename)
int WriteConfigToStream (asIScriptEngine *engine, ostream &strm)
int ConfigEngineFromStream (asIScriptEngine *engine, istream &strm, const char *configFile, asIStringFactory *stringFactory)
string GetExceptionInfo (asIScriptContext *ctx, bool showStack)
void ScriptThrow (const string &msg)
string ScriptGetExceptionInfo ()
void RegisterExceptionRoutines (asIScriptEngine *engine)
Function Documentation
CompareEquality()
int CompareEquality (asIScriptEngine * engine, void * lobj, void * robj, int typeId, bool & result)
Definition at line 71 of file scripthelper.cpp.
References CompareRelation().
CompareRelation()
BEGIN_AS_NAMESPACE int CompareRelation (asIScriptEngine * engine, void * lobj, void * robj, int typeId, int & result)
Definition at line 14 of file scripthelper.cpp.
Referenced by CompareEquality().
ConfigEngineFromStream()
int ConfigEngineFromStream (asIScriptEngine * engine, istream & strm, const char * configFile, asIStringFactory * stringFactory)
Definition at line 562 of file scripthelper.cpp.
References stringFactory.
ExecuteString() [1/2]
int ExecuteString (asIScriptEngine * engine, const char * code, asIScriptModule * mod, asIScriptContext * ctx)
Definition at line 136 of file scripthelper.cpp.
References ExecuteString().
Referenced by ExecuteString().
ExecuteString() [2/2]
int ExecuteString (asIScriptEngine * engine, const char * code, void * ref, int refTypeId, asIScriptModule * mod, asIScriptContext * ctx)
Definition at line 141 of file scripthelper.cpp.
GetExceptionInfo()
string GetExceptionInfo (asIScriptContext * ctx, bool showStack)
Definition at line 915 of file scripthelper.cpp.
RegisterExceptionRoutines()
void RegisterExceptionRoutines (asIScriptEngine * engine)
Definition at line 977 of file scripthelper.cpp.
References ScriptGetExceptionInfo(), ScriptThrow(), and WRAP_FN.
ScriptGetExceptionInfo()
string ScriptGetExceptionInfo ()
Definition at line 964 of file scripthelper.cpp.
Referenced by RegisterExceptionRoutines().
ScriptThrow()
void ScriptThrow (const string & msg)
Definition at line 957 of file scripthelper.cpp.
Referenced by RegisterExceptionRoutines().
WriteConfigToFile()
int WriteConfigToFile (asIScriptEngine * engine, const char * filename)
Definition at line 212 of file scripthelper.cpp.
References WriteConfigToStream().
WriteConfigToStream()
int WriteConfigToStream (asIScriptEngine * engine, ostream & strm)
Definition at line 220 of file scripthelper.cpp.
Referenced by WriteConfigToFile().