Atlas::BPLayerInterfaceImpl Class Reference
#include <Layers.h>
Public Member Functions
BPLayerInterfaceImpl ()
Initializes a new instance of the BPLayerInterfaceImpl class.
virtual JPH::uint GetNumBroadPhaseLayers () const override
Gets the number of broad phase layers. This is a virtual function, so feel free to override it and suit it to your needs.
virtual JPH::BroadPhaseLayer GetBroadPhaseLayer (JPH::ObjectLayer inLayer) const override
Gets the broad phase layer.
Private Attributes
JPH::BroadPhaseLayer mObjectToBroadPhase [Layers::NUM_LAYERS]
Detailed Description
Definition at line 42 of file Layers.h.
Constructor & Destructor Documentation
BPLayerInterfaceImpl()
BPLayerInterfaceImpl::BPLayerInterfaceImpl ()
Initializes a new instance of the BPLayerInterfaceImpl class.
Definition at line 18 of file Layers.cpp.
References Atlas::Layers::MOVING, Atlas::BroadPhaseLayers::MOVING(), Atlas::Layers::NON_MOVING, and Atlas::BroadPhaseLayers::NON_MOVING().
Member Function Documentation
GetBroadPhaseLayer()
JPH::BroadPhaseLayer BPLayerInterfaceImpl::GetBroadPhaseLayer (JPH::ObjectLayer inLayer) const [override], [virtual]
Gets the broad phase layer.
Parameters
inLayer The in layer.
Returns
Definition at line 30 of file Layers.cpp.
References Atlas::Layers::NUM_LAYERS.
GetNumBroadPhaseLayers()
JPH::uint BPLayerInterfaceImpl::GetNumBroadPhaseLayers () const [override], [virtual]
Gets the number of broad phase layers. This is a virtual function, so feel free to override it and suit it to your needs.
Returns
A JPH::uint that denotes the number of broad phase layers.
Definition at line 25 of file Layers.cpp.
References Atlas::BroadPhaseLayers::NUM_LAYERS().
Member Data Documentation
mObjectToBroadPhase
JPH::BroadPhaseLayer Atlas::BPLayerInterfaceImpl::mObjectToBroadPhase[Layers::NUM_LAYERS] [private]
Definition at line 68 of file Layers.h.
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/physics/Layers.h
C:/Dev/Techstorm-v5/src/engine/physics/Layers.cpp