Atlas::InputRegistry Class Reference
The input registry is used to register InputActions (InputAction) and their callbacks by using a Laissez-faire system.
#include <Input.h>
Public Member Functions
int registerActionCallback (InputAction *action, std::function< void(InputAction *)> const &callback)
Registers a pointer of InputAction to the callback given.
int registerSelfDeterminingActionCallback (InputAction *category, SelfDeterminingInputAction *action, std::function< bool(SelfDeterminingInputAction *)> const &checker, std::function< void(SelfDeterminingInputAction *)> const &callback)
int registerSelfDeterminingActionCallback (InputAction *category, SelfDeterminingInputAction *action)
void unregisterAction (InputAction *action)
Unregisters ALL callbacks for a given InputAction.
void unregisterCallback (InputAction *action, int id)
Unregisters a specific callback for a given InputAction.
void checkAll ()
Checks all registered InputActions for callbacks.
std::unordered_map< InputAction *, std::unordered_map< int, std::function< void(InputAction *)> > > & getActions ()
Private Member Functions
bool checkPressedAction (InputAction *action)
bool checkReleasedAction (InputAction *action)
bool checkDownAction (InputAction *action)
bool checkUpAction (InputAction *action)
bool checkRepeatAction (InputAction *action)
Private Attributes
const float cLeftStickDeadzoneX = 0.1f
The left stick x-axis deadzone.
const float cLeftStickDeadzoneY = 0.1f
The left stick y-axis deadzone.
const float cRightStickDeadzoneX = 0.1f
The right stick x-axis deadzone.
const float cRightStickDeadzoneY = 0.1f
The right stick y-axis deadzone.
const float cLeftTriggerDeadzone = -0.9f
The left trigger deadzone.
const float cRightTriggerDeadzone = -0.9f
The right trigger deadzone.
std::unordered_map< InputAction *, std::unordered_map< int, std::function< void(InputAction *)> > > mActions
std::unordered_map< InputAction *, std::unordered_map< int, SelfDeterminingInputAction * > > mSelfDeterminingActions
Additional Inherited Members
Static Public Member Functions inherited from Atlas::Singleton< InputRegistry >
static InputRegistry & Instance ()
Retrieves the current singleton instance as a reference. If you need to create a class that has a single static instance, use this class.
Detailed Description
The input registry is used to register InputActions (InputAction) and their callbacks by using a Laissez-faire system.
Note
Remember that this is a singleton, so you may use this statically.
See also
Singleton<InputRegistry>
Definition at line 94 of file Input.h.
Member Function Documentation
checkAll()
void Atlas::InputRegistry::checkAll ()
Checks all registered InputActions for callbacks.
Note
Without this, the callbacks won't be called and the input system is as useful as gloves are to an armless person.
Definition at line 230 of file Input.cpp.
References Atlas::SelfDeterminingInputAction::callback(), Atlas::SelfDeterminingInputAction::check(), Atlas::INPUT_TRIGGER_DOWN, Atlas::INPUT_TRIGGER_PRESSED, Atlas::INPUT_TRIGGER_RELEASED, Atlas::INPUT_TRIGGER_REPEAT, and Atlas::INPUT_TRIGGER_UP.
checkDownAction()
bool Atlas::InputRegistry::checkDownAction (InputAction * action) [private]
Definition at line 75 of file Input.cpp.
References Atlas::InputAction::controllerID, Atlas::INPUT_CONTROLLER, Atlas::INPUT_KEYBOARD, Atlas::INPUT_MOUSE, Atlas::InputAction::key, and Atlas::InputAction::type.
checkPressedAction()
bool Atlas::InputRegistry::checkPressedAction (InputAction * action) [private]
Definition at line 5 of file Input.cpp.
References Atlas::InputAction::controllerID, Atlas::INPUT_CONTROLLER, Atlas::INPUT_KEYBOARD, Atlas::INPUT_MOUSE, Atlas::InputAction::key, and Atlas::InputAction::type.
checkReleasedAction()
bool Atlas::InputRegistry::checkReleasedAction (InputAction * action) [private]
Definition at line 40 of file Input.cpp.
References Atlas::InputAction::controllerID, Atlas::INPUT_CONTROLLER, Atlas::INPUT_KEYBOARD, Atlas::INPUT_MOUSE, Atlas::InputAction::key, and Atlas::InputAction::type.
checkRepeatAction()
bool Atlas::InputRegistry::checkRepeatAction (InputAction * action) [private]
Definition at line 145 of file Input.cpp.
References Atlas::INPUT_CONTROLLER, Atlas::INPUT_KEYBOARD, Atlas::INPUT_MOUSE, Atlas::InputAction::key, and Atlas::InputAction::type.
checkUpAction()
bool Atlas::InputRegistry::checkUpAction (InputAction * action) [private]
Definition at line 110 of file Input.cpp.
References Atlas::InputAction::controllerID, Atlas::INPUT_CONTROLLER, Atlas::INPUT_KEYBOARD, Atlas::INPUT_MOUSE, Atlas::InputAction::key, and Atlas::InputAction::type.
getActions()
std::unordered_map< InputAction *, std::unordered_map< int, std::function< void(InputAction *)> > > & Atlas::InputRegistry::getActions () [inline]
Definition at line 199 of file Input.h.
References mActions.
registerActionCallback()
int Atlas::InputRegistry::registerActionCallback (InputAction * action, std::function< void(InputAction *)> const & callback)
Registers a pointer of InputAction to the callback given.
This works as a key-value pair, where the key is the action and the value is the callback and is the reason why the return value is important.
Warning
Please do not lose it or you will not be able to unregister the callback or you may unregister the wrong one!
Parameters
action The InputAction to be used as a key.
callback The callback that will be used to handle the InputAction.
Returns
The ID of the callback.
Definition at line 172 of file Input.cpp.
Referenced by Atlas::GameCamera::init().
registerSelfDeterminingActionCallback() [1/2]
int Atlas::InputRegistry::registerSelfDeterminingActionCallback (InputAction * category, SelfDeterminingInputAction * action)
Definition at line 217 of file Input.cpp.
registerSelfDeterminingActionCallback() [2/2]
int Atlas::InputRegistry::registerSelfDeterminingActionCallback (InputAction * category, SelfDeterminingInputAction * action, std::function< bool(SelfDeterminingInputAction *)> const & checker, std::function< void(SelfDeterminingInputAction *)> const & callback)
Definition at line 184 of file Input.cpp.
unregisterAction()
void Atlas::InputRegistry::unregisterAction (InputAction * action)
Unregisters ALL callbacks for a given InputAction.
This is useful if a keybind is no longer needed and you want to remove all callbacks in that category from the input system. For example, this is useful when the player is joining a game. See InputAction for more information on what an InputAction is.
Parameters
action The input action to unregister.
Definition at line 222 of file Input.cpp.
unregisterCallback()
void Atlas::InputRegistry::unregisterCallback (InputAction * action, int id)
Unregisters a specific callback for a given InputAction.
Parameters
action The action that owns the callback.
id The callback's (the one being unregistered) identifier.
Definition at line 226 of file Input.cpp.
Member Data Documentation
cLeftStickDeadzoneX
const float Atlas::InputRegistry::cLeftStickDeadzoneX = 0.1f [private]
The left stick x-axis deadzone.
Definition at line 110 of file Input.h.
cLeftStickDeadzoneY
const float Atlas::InputRegistry::cLeftStickDeadzoneY = 0.1f [private]
The left stick y-axis deadzone.
Definition at line 115 of file Input.h.
cLeftTriggerDeadzone
const float Atlas::InputRegistry::cLeftTriggerDeadzone = -0.9f [private]
The left trigger deadzone.
Definition at line 130 of file Input.h.
cRightStickDeadzoneX
const float Atlas::InputRegistry::cRightStickDeadzoneX = 0.1f [private]
The right stick x-axis deadzone.
Definition at line 120 of file Input.h.
cRightStickDeadzoneY
const float Atlas::InputRegistry::cRightStickDeadzoneY = 0.1f [private]
The right stick y-axis deadzone.
Definition at line 125 of file Input.h.
cRightTriggerDeadzone
const float Atlas::InputRegistry::cRightTriggerDeadzone = -0.9f [private]
The right trigger deadzone.
Definition at line 135 of file Input.h.
mActions
std::unordered_map<InputAction*, std::unordered_map<int, std::function<void(InputAction*)> > > Atlas::InputRegistry::mActions [private]
Definition at line 139 of file Input.h.
Referenced by getActions().
mSelfDeterminingActions
std::unordered_map< InputAction*, std::unordered_map< int, SelfDeterminingInputAction* > > Atlas::InputRegistry::mSelfDeterminingActions [private]
Definition at line 147 of file Input.h.
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/input/Input.h
C:/Dev/Techstorm-v5/src/engine/input/Input.cpp