Atlas Namespace Reference
Namespaces
namespace Application
namespace Tests
Classes
class ADevice
class AGameWindow
An interface that allows the creation of custom window classes in an API-agnostic way. It contains some general pure virtual functions that are required to create a window. This interface is what Atlas stores a pointer as when creating a window.
struct AllocatedBuffer
struct AllocatedImage
class ALogger
Interface for logging that is responsible for handling any logging from the engine, game, or mods.
class APathSearcher
class ARenderer
A base class for all renderers. This class is responsible for frontend rendering of your game. The rendering backend is responsible for the actual rendering. When using this class, you should inherit from it and implement the init and update methods. If you want this class to be multi-threaded by Atlas, you should make sure that the init and update methods are thread-safe. Additionally, make sure you set canBeMultiThreaded to true if you want this to take effect. If you do not, Atlas will only run the init and update methods on the rendering thread instead of accounting for your renderer's need to be multi-threaded.
class AsyncTimer
class ATimer
class AtlasEngine
This is the core and heart of Atlas; it is responsible for just about everything that is required to run the engine. It contains multiple different modules that can be used to extend the engine. If you want to extend the engine, you can simply inherit the respective module and utilize the concepts of polymorphism to your advantage. Keep in mind that the modules are stored as a ThreadSafeVariable and can be used concurrently. That means the user can multi-thread these modules if they so choose. This is just a default implementation of the IAtlasEngine and you do not have to use this class. However, if you would like to use a different implementation, you can simply inherit from IAtlasEngine and override the virtual functions. But one thing must remain: the class must inherit from IAtlasEngine or be a child of IAtlasEngine.
class AtlasEngineInitializer
struct AtlasSettings
class BackgroundColor
class Color
struct ComputeEffect
struct ComputePushConstants
class Counter
struct CurrentDrawData
class DebugEvent
class DeletionQueue
class DescriptorAllocator
class DescriptorLayoutBuilder
class Device
struct DeviceCapabilitiesInfo
class DiscordIntegrationService
class EngineModule
struct EngineModulesInfo
class EventPoller
class Fence
struct FileData
class FileHandle
class FileManager
As the name suggests, this non-copyable class is responsible for managing the files that Atlas and the user has loaded. This class has 3 main responsibilities (excluding the janitor): Loading, Unloading and Registering. Additionally, this class can be configured to ignore certain patterns it comes across during the file discovery process through the use of regex patterns.
struct FileRecord
struct FileSystemAuditInfo
Some information about Atlas' io module that may be helpful for debugging.
class FileSystemMap
struct FoundPathResult
class Frame
struct FrameData
class GameThread
class GameThreader
struct GameThreadingStats
class GameThreadScheduler
Scheduler for running tasks on separate threads. It will take given tasks, and distribute them across threads.
class GameTimeManager
struct GameWindowSettings
struct GPUDrawPushConstants
struct GPUMeshBuffers
struct GUIDecorations
class HapticDevice
This class represents a physical device that can provide haptic feedback to the user. Due to the sheer amount of ways haptic feedback can be provided, this class acts as a wrapper for the SDL_Haptic object.
struct HapticDeviceInitInfo
class HapticEffect
struct HapticEffectUploadResult
class IAtlasEngine
class IFactory
A pure virtual factory interface for creating unique pointer objects.
class IGameThread
class IGameThreader
class IHapticEffect
class IMemoryAllocator
struct ImmediateSubmitInfo
class IStringifiedObject
An interface for classes that want to be printable.
class ISymbol
struct LogMessage
class MakeNonCopyable
class MemoryAllocator
struct MemoryBlock
**
class MemoryCounter
struct MemoryFunctionsAggregator
class MonoRumbleHapticEffect
struct MonoRumbleHapticEffectInfo
class ObjectOptions
class PacedThread
class Parser
class Path
struct PathSearchResult
class PhysicalDevice
struct PhysicalDeviceFeaturesAggregate
struct PhysicalDeviceSelectionConstraints
class Pipeline
class PipelineBuilder
struct PipelineBuilderSettings
struct Rectangle
class RecursivePathSearcher
class ReferenceHolder
class Renderable
struct RendererSettings
class RenderingBackend
class ScriptedObject
An abstract class that provides the virtual functions needed to expose symbols to any potential mods/scripts. This class is supposed to be statically-typed, meaning it is supposed to be overriden instead of passing functions to it.
class ScriptingSymbolExposer
class SDLGameWindow
class Semaphore
class Shader
class Singleton
class SpdlogLogger
A generic logger that uses the Spdlog library. According to the spdlog documentation, you may call the spdlog::log() function to log messages after the logger has been initialized because of how spdlog works. For more information, on how to use spdlog, please refer to their documentation. This class was designed to work in the same way as the multi-sink logger example provided in the spdlog documentation. Another important thing to note about this class is that, assuming you are not implementing a custom PFN_vkDebugUtilsMessengerCallbackEXT callback for Vulkan, this class should be initialized prior to the initialization and usage of Atlas' Vulkan API. Otherwise, you will get errors the second Vulkan starts sending messages to the callback.
class StringifiedObject
An "inherit-and-forget" class that implements the IPrettyObject interface for you. This class uses a data-driven approach to get the string representation of the object.
class TaskHandle
class Temporary
struct ThreadLaunchInfo
class ThreadSafeVariable
This class wraps a variable (specified by T_VARIABLE_TYPE) and makes it thread-safe.
struct Version
struct Vertex
class VulkanInstanceWrapper
Acts as a wrapper for VkInstance and it's debug messenger. Furthermore, this class handles it's own initialization and shutdown.
class VulkanRenderer
class VulkanRenderingBackend
A wrapper class for the usage of Vulkan as a rendering backend. This class handles the lifecycle of Vulkan and simplifies the usage of Vulkan to a simple API.
class VulkanSwapchain
struct WindowDescription
A struct that contains all the information that a window needs.
struct WindowHint
Concepts
concept Numerical
concept ThreadTypeConcept
concept Clock
Typedefs
using HighResolutionTimepoint = std::chrono::high_resolution_clock::time_point
using AllocFunc = void *(*)(size_t size)
using ReallocFunc = void *(*)(void *blockPtr, size_t oldSize, size_t newSize)
using FreeFunc = void(*)(void *blockPtr)
using AlignedAllocFunc = void *(*)(size_t size, size_t alignment)
using AlignedFreeFunc = void(*)(void *blockPtr)
using SpdlogLogLevel = spdlog::level::level_enum
using ColorBit = uint8_t
A single color value. Each color channel is a 8-bit value.
using VulkanDebugCallback = PFN_vkDebugUtilsMessengerCallbackEXT
using WindowSize = glm::vec< 2, uint32_t, glm::lowp >
A using alias for a GLM low-precision 2D vector that can be used to store the size of a window.
using WindowRectangle = Rectangle< int >
using SDLEvent = SDL_Event
A null, non-copyable implementation of a game window. It does not do anything as it only provides stubs. Furthermore, this class is also used as the base class for the GLFWGameWindow and SDLGameWindow classes.
using HapticDeviceID = int
The ID of a haptic device. SDL uses an int to identify a haptic device.
using HapticEffectInfo = SDL_HapticEffect
using FileStream = std::fstream
using PathLocation = std::filesystem::path
using steady_clock = std::chrono::steady_clock
using TimePoint = std::chrono::time_point< steady_clock >
Enumerations
enum class EResultCode : uint32_t { Failed = -1
, Okay
, NotImplemented
, InvalidArgument
 }
enum class EDeviceType { Unknown = 0
 }
enum class EGameThreadSchedulerStatus : uint8_t {
Unknown = 0
, Initializing
, Running
, Stopped
,
ShuttingDown
 }
The state of the scheduler.
enum class EDebugEventType : uint8_t {
Unknown = -1
, Trace
, Info
, Warning
,
Error
 }
A list of debug event types in an order of increasing severity.
enum class ELogLevel : int {
trace = ATLAS_LEVEL_TRACE
, debug = ATLAS_LEVEL_DEBUG
, info = ATLAS_LEVEL_INFO
, warn = ATLAS_LEVEL_WARN
,
error = ATLAS_LEVEL_ERROR
, critical = ATLAS_LEVEL_CRITICAL
, off = ATLAS_LEVEL_OFF
, nLevels
 }
enum class ESpdlogInitListIndex : int { ConsoleLogger = 0
, FileLogger = 1
, Logger = 2
, Max = Logger
 }
enum class ESpdlogSinkType : int { Console = 0
, File = 1
 }
enum class EVulkanRenderingOption : size_t {
Version_Major = 0
, Version_Minor
, Version_Patch
, Enable_Validation_Layers
,
Use_Dynamic_Rendering
, Use_Default_Instance_Builder
, Enable_Syncronization
, Enable_Buffer_Device_Address
,
Enable_Descriptor_Indexing
, Swapchain_Format
, Fence_Timeout
 }
enum class EHapticDeviceInitMethod : int { Id = 0
, Joystick = 1
, Mouse = 2
 }
enum class ELookupType { Extension
, Filename
, FullPath
 }
enum class EPathType : int8_t { Unknown = -1
, File
, Directory
 }
Functions
template<typename T >
T AlignUp (T value, uint64_t alignment)
template<Numerical T_NUMERICAL_TYPE>
T_NUMERICAL_TYPE Normalize (T_NUMERICAL_TYPE value, T_NUMERICAL_TYPE min, T_NUMERICAL_TYPE max)
Normalizes a given value to be between a min and max value.
void RegisterMemoryFunctions (const MemoryFunctionsAggregator &memoryFunctionsAggregator)
void RegisterDefaultMemoryFunctions ()
void LogMessage (std::string const &message, ELogLevel logLevel)
void InfoLog (std::string const &message)
void ErrorLog (std::string const &message)
void WarnLog (std::string const &message)
void DebugLog (std::string const &message)
void TraceLog (std::string const &message)
void CriticalLog (std::string const &message)
VulkanRenderingBackend & getLoadedRenderingBacked ()
void setLoadedRenderingBackend (VulkanRenderingBackend *backend)
void resetLoadedRenderingBackend ()
VkCommandPoolCreateInfo CreateCommandPoolCreateInfo (uint32_t queueFamilyIndex, VkCommandPoolCreateFlags flags=0)
VkCommandBufferAllocateInfo CreateCommandBufferAllocateInfo (VkCommandPool pool, uint32_t count=1)
VkFenceCreateInfo CreateFenceCreateInfo (VkFenceCreateFlags flags=0)
VkSemaphoreCreateInfo CreateSemaphoreCreateInfo (VkSemaphoreCreateFlags flags=0)
VkSemaphoreSubmitInfo SubmitSemaphoreInfo (VkPipelineStageFlags2 stageMask, VkSemaphore semaphore)
VkCommandBufferSubmitInfo SubmitCommandBufferInfo (VkCommandBuffer cmd)
VkSubmitInfo2 SubmitInfo (VkCommandBufferSubmitInfo *cmd, VkSemaphoreSubmitInfo *signalSemaphoreInfo, VkSemaphoreSubmitInfo *waitSemaphoreInfo)
VkCommandBufferBeginInfo CreateCommandBufferBeginInfo (VkCommandBufferUsageFlags flags)
void TransitionImage (VkCommandBuffer cmd, VkImage image, VkImageLayout currentLayout, VkImageLayout newLayout)
VkImageSubresourceRange CreateImageSubresourceRange (VkImageAspectFlags aspectMask)
VkImageCreateInfo CreateImageCreateInfo (VkFormat format, VkImageUsageFlags usageFlags, VkExtent3D extent)
VkImageViewCreateInfo CreateImageViewCreateInfo (VkFormat format, VkImage image, VkImageAspectFlags aspectFlags)
VkRenderingAttachmentInfo CreateAttachmentInfo (VkImageView view, VkClearValue *clear, VkImageLayout layout)
VkRenderingInfo CreateRenderingInfo (VkExtent2D renderExtent, VkRenderingAttachmentInfo *colorAttachment, VkRenderingAttachmentInfo *depthAttachment)
void CopyImageToImage (VkCommandBuffer cmd, VkImage source, VkImage destination, VkExtent2D srcSize, VkExtent2D dstSize)
bool LoadShaderModule (const char *filePath, VkDevice device, VkShaderModule *outShaderModule)
VkPipelineLayoutCreateInfo CreatePipelineLayoutCreateInfo ()
VkPipelineShaderStageCreateInfo CreatePipelineShaderStageCreateInfo (VkShaderStageFlagBits stage, VkShaderModule shaderModule, const char *entry="main")
ELogLevel TranslateVulkanLogLevel (VkDebugUtilsMessageSeverityFlagBitsEXT messageSeverity)
Translates a vulkan debug log level to one that Atlas can use. For the most part, the Vulkan debug log levels are the same as the Atlas ones, with VK_DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT, VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT, and VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT being the same as ELogLevel::info, ELogLevel::warn, and ELogLevel::err in that order. However, VK_DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT and VK_DEBUG_UTILS_MESSAGE_SEVERITY_FLAG_BITS_MAX_ENUM_EXT are translated to ELogLevel::trace and ELogLevel::critical, respectively. The default is ELogLevel::info.
VkBool32 DefaultVulkanDebugCallback (VkDebugUtilsMessageSeverityFlagBitsEXT messageSeverity, VkDebugUtilsMessageTypeFlagsEXT messageType, const VkDebugUtilsMessengerCallbackDataEXT *pCallbackData, void *pUserData)
The default Vulkan debug callback that Atlas uses if no custom debug callback is provided by the user in VulkanInstanceWrapper before it is initialized. According to the Khronos specification on the PFN_vkDebugUtilsMessengerCallbackEXT object, this function should always return a value of VK_FALSE, which is what this function does. See the Khronos specification for more information (this is in the see also section of the documentation). The message is logged via the usage of spdlog::log(). However, this means that some logger (more specifically a Spdlog logger) must have been initialized before this function is called or it will crash.
unsigned int GetWindowConfigFlag (std::string const &flagName)
bool DoesPathExist (PathLocation const &cPath)
std::filesystem::path GetAbsolutePath (PathLocation const &cPath)
Variables
AllocFunc Alloc = nullptr
ReallocFunc Realloc = nullptr
FreeFunc Free = nullptr
AlignedAllocFunc AllocAligned = nullptr
AlignedFreeFunc FreeAligned = nullptr
constexpr unsigned int FRAME_OVERLAP = 2
Typedef Documentation
AlignedAllocFunc
using Atlas::AlignedAllocFunc = typedef void*(*)(size_t size, size_t alignment)
Definition at line 74 of file MemoryAllocator.h.
AlignedFreeFunc
using Atlas::AlignedFreeFunc = typedef void(*)(void* blockPtr)
Definition at line 75 of file MemoryAllocator.h.
AllocFunc
using Atlas::AllocFunc = typedef void*(*)(size_t size)
Definition at line 70 of file MemoryAllocator.h.
ColorBit
using Atlas::ColorBit = typedef uint8_t
A single color value. Each color channel is a 8-bit value.
Since
v0.0.1
See also
Color
Definition at line 30 of file Color.h.
FileStream
using Atlas::FileStream = typedef std::fstream
Definition at line 27 of file FileHandle.h.
FreeFunc
using Atlas::FreeFunc = typedef void(*)(void* blockPtr)
Definition at line 72 of file MemoryAllocator.h.
HapticDeviceID
using Atlas::HapticDeviceID = typedef int
The ID of a haptic device. SDL uses an int to identify a haptic device.
Since
v0.0.1
Definition at line 30 of file HapticDevice.h.
HapticEffectInfo
using Atlas::HapticEffectInfo = typedef SDL_HapticEffect
Definition at line 20 of file HapticEffect.h.
HighResolutionTimepoint
using Atlas::HighResolutionTimepoint = typedef std::chrono::high_resolution_clock::time_point
Definition at line 163 of file Common.h.
PathLocation
using Atlas::PathLocation = typedef std::filesystem::path
Definition at line 15 of file IOCommon.h.
ReallocFunc
using Atlas::ReallocFunc = typedef void* (*)(void* blockPtr, size_t oldSize, size_t newSize)
Definition at line 71 of file MemoryAllocator.h.
SDLEvent
using Atlas::SDLEvent = typedef SDL_Event
A null, non-copyable implementation of a game window. It does not do anything as it only provides stubs. Furthermore, this class is also used as the base class for the GLFWGameWindow and SDLGameWindow classes.
Since
v0.0.1
Definition at line 275 of file Window.h.
SpdlogLogLevel
using Atlas::SpdlogLogLevel = typedef spdlog::level::level_enum
Definition at line 56 of file Logging.h.
steady_clock
using Atlas::steady_clock = typedef std::chrono::steady_clock
Definition at line 16 of file IOCommon.h.
TimePoint
using Atlas::TimePoint = typedef std::chrono::time_point<steady_clock>
Definition at line 17 of file IOCommon.h.
VulkanDebugCallback
using Atlas::VulkanDebugCallback = typedef PFN_vkDebugUtilsMessengerCallbackEXT
Definition at line 32 of file VulkanInstance.h.
WindowRectangle
using Atlas::WindowRectangle = typedef Rectangle<int>
Definition at line 54 of file Window.h.
WindowSize
using Atlas::WindowSize = typedef glm::vec<2, uint32_t, glm::lowp>
A using alias for a GLM low-precision 2D vector that can be used to store the size of a window.
Note
There is no need for any real amount of precision as this is just used for storing the size of the window, so having a higher precision is not necessary and could be a performance hit.
Since
v0.0.1
Definition at line 52 of file Window.h.
Enumeration Type Documentation
EDebugEventType
enum class Atlas::EDebugEventType : uint8_t [strong]
A list of debug event types in an order of increasing severity.
Since
v0.0.1
Enumerator
Unknown
Trace
Info
Warning
Error
Definition at line 33 of file Debugger.h.
EDeviceType
enum class Atlas::EDeviceType [strong]
Enumerator
Unknown
Definition at line 17 of file Device.h.
EGameThreadSchedulerStatus
enum class Atlas::EGameThreadSchedulerStatus : uint8_t [strong]
The state of the scheduler.
Remarks
This enum class is useful for doing diagnostics on the scheduler.
Since
v0.0.10
Enumerator
Unknown The state of the scheduler is unknown. Typically this means that the scheduler is not initialized or something is wrong.
Since
v0.0.10
Initializing The scheduler is in the process of initializing.
Since
v0.0.10
Running The scheduler is running. This does not mean that there is work to be done, just that the scheduler is running.
Since
v0.0.10
Stopped The scheduler is stopped. This implies that the scheduler was once initialized and running, but is now stopped.
Since
v0.0.10
ShuttingDown The scheduler is shutting down.
Since
v0.0.10
Definition at line 38 of file GameThreadScheduler.h.
EHapticDeviceInitMethod
enum class Atlas::EHapticDeviceInitMethod : int [strong]
Enumerator
Id
Joystick
Mouse
Definition at line 32 of file HapticDevice.h.
ELogLevel
enum class Atlas::ELogLevel : int [strong]
Enumerator
trace
debug
info
warn
error
critical
off
nLevels
Definition at line 59 of file Logging.h.
ELookupType
enum class Atlas::ELookupType [strong]
Enumerator
Extension
Filename
FullPath
Definition at line 20 of file FileSystemMap.h.
EPathType
enum class Atlas::EPathType : int8_t [strong]
Enumerator
Unknown
File
Directory
Definition at line 24 of file PathSearcher.h.
EResultCode
enum class Atlas::EResultCode : uint32_t [strong]
Enumerator
Failed
Okay
NotImplemented
InvalidArgument
Definition at line 165 of file Common.h.
ESpdlogInitListIndex
enum class Atlas::ESpdlogInitListIndex : int [strong]
Enumerator
ConsoleLogger
FileLogger
Logger
Max
Definition at line 71 of file Logging.h.
ESpdlogSinkType
enum class Atlas::ESpdlogSinkType : int [strong]
Enumerator
Console
File
Definition at line 78 of file Logging.h.
EVulkanRenderingOption
enum class Atlas::EVulkanRenderingOption : size_t [strong]
Enumerator
Version_Major
Version_Minor
Version_Patch
Enable_Validation_Layers
Use_Dynamic_Rendering
Use_Default_Instance_Builder
Enable_Syncronization
Enable_Buffer_Device_Address
Enable_Descriptor_Indexing
Swapchain_Format
Fence_Timeout
Definition at line 255 of file VKDevice.h.
Function Documentation
AlignUp()
template<typename T >
T Atlas::AlignUp (T value, uint64_t alignment) [inline]
Definition at line 328 of file Common.h.
CopyImageToImage()
void Atlas::CopyImageToImage (VkCommandBuffer cmd, VkImage source, VkImage destination, VkExtent2D srcSize, VkExtent2D dstSize)
Definition at line 213 of file GraphicsUtils.cpp.
Referenced by Atlas::VulkanRenderingBackend::draw().
CreateAttachmentInfo()
VkRenderingAttachmentInfo Atlas::CreateAttachmentInfo (VkImageView view, VkClearValue * clear, VkImageLayout layout)
Definition at line 180 of file GraphicsUtils.cpp.
Referenced by Atlas::VulkanRenderingBackend::drawGeometry(), and Atlas::VulkanRenderingBackend::drawIMGUI().
CreateCommandBufferAllocateInfo()
VkCommandBufferAllocateInfo Atlas::CreateCommandBufferAllocateInfo (VkCommandPool pool, uint32_t count = 1)
Definition at line 13 of file GraphicsUtils.cpp.
References info.
Referenced by Atlas::Frame::init(), and Atlas::VulkanRenderingBackend::initCommands().
CreateCommandBufferBeginInfo()
VkCommandBufferBeginInfo Atlas::CreateCommandBufferBeginInfo (VkCommandBufferUsageFlags flags)
Definition at line 87 of file GraphicsUtils.cpp.
References info.
Referenced by Atlas::VulkanRenderingBackend::beginDrawingMode(), and Atlas::VulkanRenderingBackend::ImmediateSubmit().
CreateCommandPoolCreateInfo()
VkCommandPoolCreateInfo Atlas::CreateCommandPoolCreateInfo (uint32_t queueFamilyIndex, VkCommandPoolCreateFlags flags = 0)
Definition at line 3 of file GraphicsUtils.cpp.
References info.
Referenced by Atlas::VulkanRenderingBackend::initCommands().
CreateFenceCreateInfo()
VkFenceCreateInfo Atlas::CreateFenceCreateInfo (VkFenceCreateFlags flags = 0)
Definition at line 25 of file GraphicsUtils.cpp.
References info.
Referenced by Atlas::VulkanRenderingBackend::initCommands().
CreateImageCreateInfo()
VkImageCreateInfo Atlas::CreateImageCreateInfo (VkFormat format, VkImageUsageFlags usageFlags, VkExtent3D extent)
Definition at line 137 of file GraphicsUtils.cpp.
References info.
Referenced by Atlas::VulkanRenderingBackend::initSwapchain().
CreateImageSubresourceRange()
VkImageSubresourceRange Atlas::CreateImageSubresourceRange (VkImageAspectFlags aspectMask)
Definition at line 125 of file GraphicsUtils.cpp.
Referenced by TransitionImage().
CreateImageViewCreateInfo()
VkImageViewCreateInfo Atlas::CreateImageViewCreateInfo (VkFormat format, VkImage image, VkImageAspectFlags aspectFlags)
Definition at line 161 of file GraphicsUtils.cpp.
References info.
Referenced by Atlas::VulkanRenderingBackend::initSwapchain().
CreatePipelineLayoutCreateInfo()
VkPipelineLayoutCreateInfo Atlas::CreatePipelineLayoutCreateInfo ()
Definition at line 292 of file GraphicsUtils.cpp.
References info.
Referenced by Atlas::VulkanRenderingBackend::initMeshPipeline(), and Atlas::VulkanRenderingBackend::initTrianglePipeline().
CreatePipelineShaderStageCreateInfo()
VkPipelineShaderStageCreateInfo Atlas::CreatePipelineShaderStageCreateInfo (VkShaderStageFlagBits stage, VkShaderModule shaderModule, const char * entry = "main")
Definition at line 307 of file GraphicsUtils.cpp.
References info.
Referenced by Atlas::PipelineBuilder::setShaders().
CreateRenderingInfo()
VkRenderingInfo Atlas::CreateRenderingInfo (VkExtent2D renderExtent, VkRenderingAttachmentInfo * colorAttachment, VkRenderingAttachmentInfo * depthAttachment)
Definition at line 197 of file GraphicsUtils.cpp.
Referenced by Atlas::VulkanRenderingBackend::drawGeometry(), and Atlas::VulkanRenderingBackend::drawIMGUI().
CreateSemaphoreCreateInfo()
VkSemaphoreCreateInfo Atlas::CreateSemaphoreCreateInfo (VkSemaphoreCreateFlags flags = 0)
Definition at line 36 of file GraphicsUtils.cpp.
References info.
Referenced by Atlas::VulkanRenderingBackend::initCommands().
CriticalLog()
void Atlas::CriticalLog (std::string const & message)
Definition at line 285 of file Logging.cpp.
References critical.
DebugLog()
void Atlas::DebugLog (std::string const & message)
Definition at line 275 of file Logging.cpp.
References debug.
DefaultVulkanDebugCallback()
VkBool32 Atlas::DefaultVulkanDebugCallback (VkDebugUtilsMessageSeverityFlagBitsEXT messageSeverity, VkDebugUtilsMessageTypeFlagsEXT messageType, const VkDebugUtilsMessengerCallbackDataEXT * pCallbackData, void * pUserData)
The default Vulkan debug callback that Atlas uses if no custom debug callback is provided by the user in VulkanInstanceWrapper before it is initialized. According to the Khronos specification on the PFN_vkDebugUtilsMessengerCallbackEXT object, this function should always return a value of VK_FALSE, which is what this function does. See the Khronos specification for more information (this is in the see also section of the documentation). The message is logged via the usage of spdlog::log(). However, this means that some logger (more specifically a Spdlog logger) must have been initialized before this function is called or it will crash.
Remarks
While most of these parameters are not used, they are included for consistency with the specifications that are listed in the Khronos specifications at the link in the see also section.
Precondition
A Spdlog logger must have been initialized before this function is called. This should be handled by the SpdlogLogger class.
Parameters
messageSeverity The Vulkan debug log level reported by the vulkan debug callback. This is translated to an Atlas log level using the TranslateVulkanLogLevel function.
messageType The type of message reported by the vulkan debug callback.
pCallbackData A pointer to the vulkan debug callback data. Within this parameter, the message is located, which is what is passed to be logged via spdlog::log().
pUserData A pointer to user data that was provided when the vulkan debug callback was set.
Returns
Always returns VK_FALSE.
See also
https://registry.khronos.org/vulkan/specs/latest/man/html/PFN_vkDebugUtilsMessengerCallbackEXT.html
Todo
Todo Instead of logging via spdlog::log(), perhaps consider writing another function that will log using an already initialized Atlas logger. As of right now, this is assuming that the user is using the SpdlogLogger class, which is the default. However, the user should be able to use another logger and still have this function work.
Since
v0.0.1
Definition at line 160 of file VulkanInstance.cpp.
References TranslateVulkanLogLevel().
Referenced by Atlas::VulkanInstanceWrapper::init().
DoesPathExist()
bool Atlas::DoesPathExist (PathLocation const & cPath)
Definition at line 14 of file IOCommon.cpp.
Referenced by Atlas::FileManager::registerDirectory().
ErrorLog()
void Atlas::ErrorLog (std::string const & message)
Definition at line 265 of file Logging.cpp.
References error.
Referenced by Atlas::VulkanRenderingBackend::init(), Atlas::VulkanRenderingBackend::initMeshPipeline(), Atlas::VulkanRenderingBackend::initTrianglePipeline(), and Atlas::HapticDevice::open().
GetAbsolutePath()
std::filesystem::path Atlas::GetAbsolutePath (PathLocation const & cPath)
Definition at line 19 of file IOCommon.cpp.
Referenced by Atlas::FileManager::openFile(), Atlas::FileManager::registerFile(), and Atlas::FileManager::unloadFile().
getLoadedRenderingBacked()
Atlas::VulkanRenderingBackend & Atlas::getLoadedRenderingBacked ()
Definition at line 1227 of file VKDevice.cpp.
References gLoadedVulkanBackend.
GetWindowConfigFlag()
unsigned int Atlas::GetWindowConfigFlag (std::string const & flagName)
InfoLog()
void Atlas::InfoLog (std::string const & message)
Definition at line 260 of file Logging.cpp.
References info.
Referenced by Atlas::FileManager::FileJanitor::evictUnused(), Atlas::VulkanRenderingBackend::init(), Atlas::FileManager::FileJanitor::janitorLoop(), main(), Atlas::FileManager::registerDirectory(), Atlas::FileManager::registerFile(), and Atlas::FileManager::FileJanitor::startJanitor().
LoadShaderModule()
bool Atlas::LoadShaderModule (const char * filePath, VkDevice device, VkShaderModule * outShaderModule)
Definition at line 247 of file GraphicsUtils.cpp.
Referenced by Atlas::VulkanRenderingBackend::initBackgroundPipelines(), Atlas::VulkanRenderingBackend::initMeshPipeline(), Atlas::VulkanRenderingBackend::initTrianglePipeline(), and Atlas::Shader::load().
LogMessage()
void Atlas::LogMessage (std::string const & message, ELogLevel logLevel)
Definition at line 255 of file Logging.cpp.
Normalize()
template<Numerical T_NUMERICAL_TYPE>
T_NUMERICAL_TYPE Atlas::Normalize (T_NUMERICAL_TYPE value, T_NUMERICAL_TYPE min, T_NUMERICAL_TYPE max)
Normalizes a given value to be between a min and max value.
Parameters
value The value to normalize
min The minimum value that can be returned
max The maximum value that can be returned
Template Parameters
T_NUMERICAL_TYPE The numerical type to use. This can be any numerical type
Returns
A normalized value of the given value
Since
v0.0.1
Definition at line 35 of file Math.h.
RegisterDefaultMemoryFunctions()
void Atlas::RegisterDefaultMemoryFunctions ()
Definition at line 48 of file MemoryAllocator.cpp.
RegisterMemoryFunctions()
void Atlas::RegisterMemoryFunctions (const MemoryFunctionsAggregator & memoryFunctionsAggregator)
Definition at line 35 of file MemoryAllocator.cpp.
References Alloc, Atlas::MemoryFunctionsAggregator::alloc, AllocAligned, Atlas::MemoryFunctionsAggregator::allocAligned, Free, Atlas::MemoryFunctionsAggregator::free, FreeAligned, Atlas::MemoryFunctionsAggregator::freeAligned, Realloc, and Atlas::MemoryFunctionsAggregator::realloc.
resetLoadedRenderingBackend()
void Atlas::resetLoadedRenderingBackend ()
Definition at line 1243 of file VKDevice.cpp.
References setLoadedRenderingBackend().
setLoadedRenderingBackend()
void Atlas::setLoadedRenderingBackend (VulkanRenderingBackend * backend)
Definition at line 1232 of file VKDevice.cpp.
References gLoadedVulkanBackend, and Atlas::VulkanRenderingBackend::shutdown().
Referenced by resetLoadedRenderingBackend().
SubmitCommandBufferInfo()
VkCommandBufferSubmitInfo Atlas::SubmitCommandBufferInfo (VkCommandBuffer cmd)
Definition at line 58 of file GraphicsUtils.cpp.
References info.
Referenced by Atlas::VulkanRenderingBackend::endDrawingMode(), and Atlas::VulkanRenderingBackend::ImmediateSubmit().
SubmitInfo()
VkSubmitInfo2 Atlas::SubmitInfo (VkCommandBufferSubmitInfo * cmd, VkSemaphoreSubmitInfo * signalSemaphoreInfo, VkSemaphoreSubmitInfo * waitSemaphoreInfo)
Definition at line 69 of file GraphicsUtils.cpp.
References info.
Referenced by Atlas::VulkanRenderingBackend::endDrawingMode(), and Atlas::VulkanRenderingBackend::ImmediateSubmit().
SubmitSemaphoreInfo()
VkSemaphoreSubmitInfo Atlas::SubmitSemaphoreInfo (VkPipelineStageFlags2 stageMask, VkSemaphore semaphore)
Definition at line 45 of file GraphicsUtils.cpp.
Referenced by Atlas::VulkanRenderingBackend::endDrawingMode().
TraceLog()
void Atlas::TraceLog (std::string const & message)
Definition at line 280 of file Logging.cpp.
References trace.
Referenced by Atlas::HapticDevice::close(), Atlas::VulkanRenderingBackend::initMeshPipeline(), Atlas::VulkanRenderingBackend::initTrianglePipeline(), and Atlas::HapticDevice::open().
TransitionImage()
void Atlas::TransitionImage (VkCommandBuffer cmd, VkImage image, VkImageLayout currentLayout, VkImageLayout newLayout)
Definition at line 98 of file GraphicsUtils.cpp.
References CreateImageSubresourceRange().
Referenced by Atlas::VulkanRenderingBackend::draw().
TranslateVulkanLogLevel()
Atlas::ELogLevel Atlas::TranslateVulkanLogLevel (VkDebugUtilsMessageSeverityFlagBitsEXT messageSeverity)
Translates a vulkan debug log level to one that Atlas can use. For the most part, the Vulkan debug log levels are the same as the Atlas ones, with VK_DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT, VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT, and VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT being the same as ELogLevel::info, ELogLevel::warn, and ELogLevel::err in that order. However, VK_DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT and VK_DEBUG_UTILS_MESSAGE_SEVERITY_FLAG_BITS_MAX_ENUM_EXT are translated to ELogLevel::trace and ELogLevel::critical, respectively. The default is ELogLevel::info.
Parameters
messageSeverity The Vulkan debug log level to translate.
Returns
The translated log level. See the description for more information.
Since
v0.0.1
Definition at line 130 of file VulkanInstance.cpp.
References critical, error, info, trace, and warn.
Referenced by DefaultVulkanDebugCallback().
WarnLog()
void Atlas::WarnLog (std::string const & message)
Definition at line 270 of file Logging.cpp.
References warn.
Referenced by Atlas::HapticDevice::open(), and Atlas::MonoRumbleHapticEffect::upload().
Variable Documentation
Alloc
AllocFunc Atlas::Alloc = nullptr
Definition at line 26 of file MemoryAllocator.cpp.
Referenced by RegisterMemoryFunctions().
AllocAligned
AlignedAllocFunc Atlas::AllocAligned = nullptr
Definition at line 30 of file MemoryAllocator.cpp.
Referenced by RegisterMemoryFunctions().
FRAME_OVERLAP
constexpr unsigned int Atlas::FRAME_OVERLAP = 2 [constexpr]
Definition at line 30 of file Frame.h.
Referenced by Atlas::VulkanRenderingBackend::getCurrentFrame(), Atlas::VulkanRenderingBackend::initCommands(), and Atlas::VulkanRenderingBackend::shutdown().
Free
FreeFunc Atlas::Free = nullptr
Definition at line 28 of file MemoryAllocator.cpp.
Referenced by RegisterMemoryFunctions().
FreeAligned
AlignedFreeFunc Atlas::FreeAligned = nullptr
Definition at line 31 of file MemoryAllocator.cpp.
Referenced by RegisterMemoryFunctions().
Realloc
ReallocFunc Atlas::Realloc = nullptr
Definition at line 27 of file MemoryAllocator.cpp.
Referenced by RegisterMemoryFunctions().