Atlas::FileManager::FileJanitor Class Reference
Automatically evicts unused files in a background thread and cleans up the mRecords map in the FileManager. Furthermore, this class also handles the janitor thread, which is where the janitor loop runs. This class is handled by the FileManager class. It is not recommended to use this class directly, and let the FileManager handle it. However, if you do infact need to use this class directly, please refer to the details section in the documentation below.
#include <IOManager.h>
Public Member Functions
ATLAS_DISALLOW_COPY (FileJanitor)
FileJanitor (FileManager &fileManagerRef, const Options &options)
Initializes a new instance of the FileJanitor class.
FileJanitor ()=delete
~FileJanitor ()
Stops the janitor thread and waits for it to stop.
void startJanitor ()
Starts the janitor thread if it is not already running.
void janitorLoop ()
Runs the janitor loop, which checks for inactive files and evicts them if they have been inactive for too long.
void evictUnused ()
Checks for inactive files and evicts them if they have been inactive for too long, assuming nothing is currently using the file.
Private Attributes
FileManager & mFileManagerRef
A reference to the FileManager class.
Options mOptions
The configuration options for the janitor. This should be the same as the one passed to the FileManager.
std::atomic< bool > mJanitorStopFlag
An atomic flag that indicates whether or not the janitor should stop.
std::condition_variable_any mJanitorCV
A condition variable that is used to notify the janitor thread that it should check for unused files.
std::mutex mJanitorCVMutex
Syncronizes access to mJanitorCV.
std::jthread mJanitorThread
The thread that the janitor will run on.
Detailed Description
Automatically evicts unused files in a background thread and cleans up the mRecords map in the FileManager. Furthermore, this class also handles the janitor thread, which is where the janitor loop runs. This class is handled by the FileManager class. It is not recommended to use this class directly, and let the FileManager handle it. However, if you do infact need to use this class directly, please refer to the details section in the documentation below.
Since
v0.0.1
See also
FileManager
Definition at line 241 of file IOManager.h.
Constructor & Destructor Documentation
FileJanitor() [1/2]
Atlas::FileManager::FileJanitor::FileJanitor (FileManager & fileManagerRef, const Options & options)
Initializes a new instance of the FileJanitor class.
Parameters
fileManagerRef A reference to an instance of the FileManager class.
options The configuration options for the janitor. This is the same as the one passed to the FileManager in it's constructor.
Since
v0.0.1
Definition at line 38 of file IOManager.cpp.
References Atlas::FileManager::Options::bStartJanitor, mOptions, and startJanitor().
FileJanitor() [2/2]
Atlas::FileManager::FileJanitor::FileJanitor () [delete]
~FileJanitor()
Atlas::FileManager::FileJanitor::~FileJanitor ()
Stops the janitor thread and waits for it to stop.
Since
v0.0.1
Definition at line 46 of file IOManager.cpp.
Member Function Documentation
ATLAS_DISALLOW_COPY()
Atlas::FileManager::FileJanitor::ATLAS_DISALLOW_COPY (FileJanitor)
evictUnused()
void Atlas::FileManager::FileJanitor::evictUnused ()
Checks for inactive files and evicts them if they have been inactive for too long, assuming nothing is currently using the file.
Since
v0.0.1
Definition at line 89 of file IOManager.cpp.
References Atlas::FileManager::Options::fileTTL, Atlas::InfoLog(), and Atlas::FileManager::mOptions.
janitorLoop()
void Atlas::FileManager::FileJanitor::janitorLoop ()
Runs the janitor loop, which checks for inactive files and evicts them if they have been inactive for too long.
Note
Under normal circumstances, this runs on the janitor thread.
Since
v0.0.1
Definition at line 74 of file IOManager.cpp.
References Atlas::FileManager::Options::evictionCheckInterval, Atlas::InfoLog(), and Atlas::FileManager::mOptions.
startJanitor()
void Atlas::FileManager::FileJanitor::startJanitor ()
Starts the janitor thread if it is not already running.
Warning
This will assert if the janitor thread is already running.
Since
v0.0.1
Definition at line 60 of file IOManager.cpp.
References ATLAS_ASSERT, and Atlas::InfoLog().
Referenced by FileJanitor().
Member Data Documentation
mFileManagerRef
FileManager& Atlas::FileManager::FileJanitor::mFileManagerRef [private]
A reference to the FileManager class.
Since
v0.0.1
Definition at line 249 of file IOManager.h.
mJanitorCV
std::condition_variable_any Atlas::FileManager::FileJanitor::mJanitorCV [private]
A condition variable that is used to notify the janitor thread that it should check for unused files.
Since
v0.0.1
See also
mJanitorCVMutex
Definition at line 272 of file IOManager.h.
mJanitorCVMutex
std::mutex Atlas::FileManager::FileJanitor::mJanitorCVMutex [private]
Syncronizes access to mJanitorCV.
Since
v0.0.1
Definition at line 279 of file IOManager.h.
mJanitorStopFlag
std::atomic<bool> Atlas::FileManager::FileJanitor::mJanitorStopFlag [private]
An atomic flag that indicates whether or not the janitor should stop.
Since
v0.0.1
Definition at line 263 of file IOManager.h.
mJanitorThread
std::jthread Atlas::FileManager::FileJanitor::mJanitorThread [private]
The thread that the janitor will run on.
Since
v0.0.1
Definition at line 286 of file IOManager.h.
mOptions
Options Atlas::FileManager::FileJanitor::mOptions [private]
The configuration options for the janitor. This should be the same as the one passed to the FileManager.
Since
v0.0.1
Definition at line 256 of file IOManager.h.
Referenced by FileJanitor().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/io/IOManager.h
C:/Dev/Techstorm-v5/src/engine/io/IOManager.cpp