Atlas::HapticDevice Class Reference
This class represents a physical device that can provide haptic feedback to the user. Due to the sheer amount of ways haptic feedback can be provided, this class acts as a wrapper for the SDL_Haptic object.
#include <HapticDevice.h>
Public Member Functions
HapticDevice (HapticDeviceID hapticDeviceID)
A constructor that sets the haptic device ID to the one provided. This must be a valid haptic device ID or else this class will not behave as expected and errors will occur.
HapticDevice ()=default
A default constructor.
~HapticDevice ()
The default destructor that will close the haptic device if it is open.
void open ()
Opens the haptic device using the HappticDeviceID that was provided in the constructor. If the haptic device is already open, this function will essentially restart the haptic device by closing it and then opening it again. Keep in mind that this will cause all haptic effects to be lost. Since this class is built on SDL's haptic feedback API, this function will open the haptic device using SDL's API. Please do note that if the value of sCurrentHapticDevicesCount is equal to the value of sMaxHapticDevices, then this function WILL NOT open the haptic device unless the value of sMaxHapticDevices is set to -1.
void close ()
If the value of mbIsOpen is true, then this function will attempt to close the haptic device. otherwise, this function will do nothing. Additionally, when the haptic device is closed, it will decrement the value of sCurrentHapticDevicesCount.
void addHapticEffect (std::unique_ptr< IHapticEffect > hapticEffect)
bool isOpen () const
Checks if the haptic device is open.
bool canUseEffect (std::unique_ptr< IHapticEffect > hapticEffect) const
Checks if a specific haptic effect can be used on this haptic device.
std::shared_ptr< SDL_Haptic > getSDLHapticPtr () const
Returns the SDL haptic device pointer that is associated with this haptic device.
HapticDeviceID getHapticDeviceID () const
Gets this device's id.
operator std::string () const
Returns the name of the haptic device as a string. Functionally speaking, this calls the.
operator const char * () const
Returns the name of the haptic device as a string.
Static Public Member Functions
static uint8_t GetMaxHapticDevices ()
Returns the maximum number of haptic devices that can be open at once.
static void SetMaxHapticDevices (uint8_t maxHapticDevices)
Sets the maximum number of haptic devices that can be open at once.
static uint8_t GetHapticDevicesCount ()
Gets the current number of haptic devices that are open.
static bool HasReachedMaxHapticDevices ()
Whether or not the maximum number of haptic devices has been reached.
Private Member Functions
std::shared_ptr< SDL_Haptic > openHapticDeviceFromID (HapticDeviceID hapticDeviceID) const
std::shared_ptr< SDL_Haptic > openHapticDeviceFromJoystick (SDL_Joystick *joystick) const
std::shared_ptr< SDL_Haptic > openHapticDeviceFromMouse () const
Private Attributes
std::unordered_map< int, std::unique_ptr< IHapticEffect > > mHapticEffects
std::shared_ptr< SDL_Haptic > mSDLHapticPtr = nullptr
The SDL_Haptic object that this class wraps around. Since this is a shared pointer, it can be shared between multiple haptic devices if desired.
HapticDeviceID mHapticDeviceID = ATLAS_INVALID_HAPTIC_DEVICE_ID
The ID of a valid physical haptic device that this class will represent. The value of this should be set in the constructor.
bool mbIsOpen = false
Whether or not this haptic device has been opened.
Static Private Attributes
static uint8_t sMaxHapticDevices = -1
The maximum number of haptic devices that can be open at once. Set this to -1 to have no limit (default).
static uint8_t sCurrentHapticDevicesCount = 0
The current number of haptic devices that are open. Anytime a haptic device is opened, this number will increase by 1, and any time a haptic device is closed, this number will decrease by 1.
Detailed Description
This class represents a physical device that can provide haptic feedback to the user. Due to the sheer amount of ways haptic feedback can be provided, this class acts as a wrapper for the SDL_Haptic object.
Precondition
As is with the rest of Atlas' haptic API, SDL must be initialized before this class can be used and the flag SDL_INIT_HAPTIC must be set.
Since
v0.0.1
Definition at line 61 of file HapticDevice.h.
Constructor & Destructor Documentation
HapticDevice() [1/2]
Atlas::HapticDevice::HapticDevice (HapticDeviceID hapticDeviceID) [explicit]
A constructor that sets the haptic device ID to the one provided. This must be a valid haptic device ID or else this class will not behave as expected and errors will occur.
Parameters
hapticDeviceID The ID of the physical haptic device that this class will represent.
Since
v0.0.1
Definition at line 57 of file HapticDevice.cpp.
HapticDevice() [2/2]
Atlas::HapticDevice::HapticDevice () [default]
A default constructor.
Since
v0.0.1
~HapticDevice()
Atlas::HapticDevice::~HapticDevice ()
The default destructor that will close the haptic device if it is open.
Since
v0.0.1
Definition at line 62 of file HapticDevice.cpp.
Member Function Documentation
addHapticEffect()
void Atlas::HapticDevice::addHapticEffect (std::unique_ptr< IHapticEffect > hapticEffect)
Definition at line 166 of file HapticDevice.cpp.
canUseEffect()
bool Atlas::HapticDevice::canUseEffect (std::unique_ptr< IHapticEffect > hapticEffect) const
Checks if a specific haptic effect can be used on this haptic device.
Note
Currently, this function does nothing.
Parameters
hapticEffect A unique pointer to a haptic effect object instance.
Returns
true if the haptic effect can be used on this haptic device, otherwise false
Since
v0.0.1
See also
IHapticEffect
Definition at line 191 of file HapticDevice.cpp.
close()
void Atlas::HapticDevice::close ()
If the value of mbIsOpen is true, then this function will attempt to close the haptic device. otherwise, this function will do nothing. Additionally, when the haptic device is closed, it will decrement the value of sCurrentHapticDevicesCount.
Since
v
Definition at line 149 of file HapticDevice.cpp.
References Atlas::TraceLog().
getHapticDeviceID()
Atlas::HapticDeviceID Atlas::HapticDevice::getHapticDeviceID () const
Gets this device's id.
Returns
The device's id as HapticDeviceID
Since
v
Definition at line 200 of file HapticDevice.cpp.
GetHapticDevicesCount()
uint8_t Atlas::HapticDevice::GetHapticDevicesCount () [inline], [static]
Gets the current number of haptic devices that are open.
Returns
uint8_t The value of sCurrentHapticDevicesCount
Since
v
Definition at line 76 of file HapticDevice.cpp.
GetMaxHapticDevices()
uint8_t Atlas::HapticDevice::GetMaxHapticDevices () [inline], [static]
Returns the maximum number of haptic devices that can be open at once.
Returns
sMaxHapticDevices
Since
v0.0.1
Definition at line 67 of file HapticDevice.cpp.
getSDLHapticPtr()
std::shared_ptr< SDL_Haptic > Atlas::HapticDevice::getSDLHapticPtr () const
Returns the SDL haptic device pointer that is associated with this haptic device.
Returns
A shared pointer to the SDL haptic device variable in this class.
Since
v0.0.1
Definition at line 196 of file HapticDevice.cpp.
HasReachedMaxHapticDevices()
bool Atlas::HapticDevice::HasReachedMaxHapticDevices () [inline], [static]
Whether or not the maximum number of haptic devices has been reached.
Returns
true if the maximum number of haptic devices has been reached, false otherwise.
Since
v0.0.1
Definition at line 81 of file HapticDevice.cpp.
isOpen()
bool Atlas::HapticDevice::isOpen () const
Checks if the haptic device is open.
Returns
true if the haptic device is open, otherwise false
Since
v0.0.1
Definition at line 187 of file HapticDevice.cpp.
open()
void Atlas::HapticDevice::open ()
Opens the haptic device using the HappticDeviceID that was provided in the constructor. If the haptic device is already open, this function will essentially restart the haptic device by closing it and then opening it again. Keep in mind that this will cause all haptic effects to be lost. Since this class is built on SDL's haptic feedback API, this function will open the haptic device using SDL's API. Please do note that if the value of sCurrentHapticDevicesCount is equal to the value of sMaxHapticDevices, then this function WILL NOT open the haptic device unless the value of sMaxHapticDevices is set to -1.
Since
v0.0.1
Definition at line 86 of file HapticDevice.cpp.
References Atlas::ErrorLog(), Atlas::TraceLog(), and Atlas::WarnLog().
openHapticDeviceFromID()
std::shared_ptr< SDL_Haptic > Atlas::HapticDevice::openHapticDeviceFromID (HapticDeviceID hapticDeviceID) const [private]
Definition at line 42 of file HapticDevice.cpp.
openHapticDeviceFromJoystick()
std::shared_ptr< SDL_Haptic > Atlas::HapticDevice::openHapticDeviceFromJoystick (SDL_Joystick * joystick) const [private]
Definition at line 47 of file HapticDevice.cpp.
openHapticDeviceFromMouse()
std::shared_ptr< SDL_Haptic > Atlas::HapticDevice::openHapticDeviceFromMouse () const [private]
Definition at line 52 of file HapticDevice.cpp.
operator const char *()
Atlas::HapticDevice::operator const char * () const
Returns the name of the haptic device as a string.
Returns
const char* The name of the physical device.
Since
v0.0.1
Definition at line 209 of file HapticDevice.cpp.
operator std::string()
Atlas::HapticDevice::operator std::string () const
Returns the name of the haptic device as a string. Functionally speaking, this calls the.
operator const char* () const
 and cast it to a string.
Returns
std::string The name of the physical device.
Since
v0.0.1
Definition at line 204 of file HapticDevice.cpp.
SetMaxHapticDevices()
void Atlas::HapticDevice::SetMaxHapticDevices (uint8_t maxHapticDevices) [inline], [static]
Sets the maximum number of haptic devices that can be open at once.
Note
If the value of sMaxHapticDevices is set to -1, then there will be no limit.
Parameters
maxHapticDevices An 8-bit integer value that sMaxHapticDevices will be set to.
Since
v0.0.1
Definition at line 72 of file HapticDevice.cpp.
Member Data Documentation
mbIsOpen
bool Atlas::HapticDevice::mbIsOpen = false [private]
Whether or not this haptic device has been opened.
Since
v0.0.1
Definition at line 104 of file HapticDevice.h.
mHapticDeviceID
HapticDeviceID Atlas::HapticDevice::mHapticDeviceID = ATLAS_INVALID_HAPTIC_DEVICE_ID [private]
The ID of a valid physical haptic device that this class will represent. The value of this should be set in the constructor.
Since
v0.0.1
Definition at line 97 of file HapticDevice.h.
mHapticEffects
std::unordered_map<int, std::unique_ptr<IHapticEffect> > Atlas::HapticDevice::mHapticEffects [private]
Definition at line 78 of file HapticDevice.h.
mSDLHapticPtr
std::shared_ptr<SDL_Haptic> Atlas::HapticDevice::mSDLHapticPtr = nullptr [private]
The SDL_Haptic object that this class wraps around. Since this is a shared pointer, it can be shared between multiple haptic devices if desired.
Note
This will be null if the haptic device is not open. Additionally, this must be set to a valid SDL_Haptic value or else this class will not work.
Since
v0.0.1
Definition at line 89 of file HapticDevice.h.
sCurrentHapticDevicesCount
uint8_t Atlas::HapticDevice::sCurrentHapticDevicesCount = 0 [inline], [static], [private]
The current number of haptic devices that are open. Anytime a haptic device is opened, this number will increase by 1, and any time a haptic device is closed, this number will decrease by 1.
Since
v0.0.1
Definition at line 76 of file HapticDevice.h.
sMaxHapticDevices
uint8_t Atlas::HapticDevice::sMaxHapticDevices = -1 [inline], [static], [private]
The maximum number of haptic devices that can be open at once. Set this to -1 to have no limit (default).
Since
v0.0.1
Definition at line 68 of file HapticDevice.h.
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/haptics/HapticDevice.h
C:/Dev/Techstorm-v5/src/engine/haptics/HapticDevice.cpp