Atlas::ConfigFileRegistry Class Reference
#include <Config.h>
Public Member Functions
ConfigFileRegistry ()
Initializes a new instance of the ConfigFileRegistry class.
~ConfigFileRegistry ()
Finalizes an instance of the ConfigFileRegistry class.
void init ()
Initializes this instance.
void readConfigFiles ()
Reads the configuration files.
void readConfigFile (const std::string &name)
Reads the configuration file.
void writeConfigFiles ()
Writes the configuration files.
void registerConfigFiles (const std::string &searchPath)
Registers the configuration files.
void registerConfigFile (const std::string &name, const std::string &path)
Registers the configuration file.
void unregisterConfigFiles ()
Unregisters the configuration files.
void unregisterConfigFile (const std::string &name)
Unregisters the configuration file.
libconfig::Setting & configLookup (const std::string &fileName, const std::string &lookupTarget)
Configurations the lookup.
JSONFile * getJsonFile (std::string const &fileName)
Static Private Member Functions
static std::any LoadConfigFile (std::shared_ptr< Atlas::FileMeta > fileMeta)
Loads the configuration file.
static std::any LoadJSONFile (std::shared_ptr< Atlas::FileMeta > fileMeta)
Loads a json file.
static std::any LoadXMLFile (std::shared_ptr< Atlas::FileMeta > fileMeta)
Loads the XML file.
Additional Inherited Members
Static Public Member Functions inherited from Atlas::Singleton< ConfigFileRegistry >
static ConfigFileRegistry & Instance ()
Retrieves the current singleton instance as a reference. If you need to create a class that has a single static instance, use this class.
Detailed Description
See also
Singleton<ConfigFileRegistry>
Definition at line 21 of file Config.h.
Constructor & Destructor Documentation
ConfigFileRegistry()
Atlas::ConfigFileRegistry::ConfigFileRegistry ()
Initializes a new instance of the ConfigFileRegistry class.
Definition at line 12 of file Config.cpp.
~ConfigFileRegistry()
Atlas::ConfigFileRegistry::~ConfigFileRegistry ()
Finalizes an instance of the ConfigFileRegistry class.
Definition at line 16 of file Config.cpp.
Member Function Documentation
configLookup()
libconfig::Setting & Atlas::ConfigFileRegistry::configLookup (const std::string & fileName, const std::string & lookupTarget)
Configurations the lookup.
Parameters
fileName Name of the file.
lookupTarget The lookup target.
Returns
Definition at line 67 of file Config.cpp.
References Atlas::GetFile(), Atlas::Log(), and Atlas::TRACE.
Referenced by Atlas::LookupConfig().
getJsonFile()
JSONFile * Atlas::ConfigFileRegistry::getJsonFile (std::string const & fileName) [inline]
Definition at line 88 of file Config.h.
References Atlas::GetFile().
init()
void Atlas::ConfigFileRegistry::init ()
Initializes this instance.
Definition at line 20 of file Config.cpp.
References Atlas::AddFileRegistryLoadFunction(), Atlas::Log(), and Atlas::TRACE.
Referenced by Atlas::InitializeConfigRegistry().
LoadConfigFile()
std::any Atlas::ConfigFileRegistry::LoadConfigFile (std::shared_ptr< Atlas::FileMeta > fileMeta) [inline], [static], [private]
Loads the configuration file.
Parameters
fileMeta The file meta.
Returns
Definition at line 78 of file Config.cpp.
References Atlas::Log(), and Atlas::TRACE.
LoadJSONFile()
std::any Atlas::ConfigFileRegistry::LoadJSONFile (std::shared_ptr< Atlas::FileMeta > fileMeta) [inline], [static], [private]
Loads a json file.
Parameters
fileMeta The file meta.
Returns
Definition at line 86 of file Config.cpp.
References Atlas::Log(), and Atlas::TRACE.
LoadXMLFile()
std::any Atlas::ConfigFileRegistry::LoadXMLFile (std::shared_ptr< Atlas::FileMeta > fileMeta) [inline], [static], [private]
Loads the XML file.
Parameters
fileMeta The file meta.
Returns
Definition at line 94 of file Config.cpp.
References Atlas::Log(), and Atlas::TRACE.
readConfigFile()
void Atlas::ConfigFileRegistry::readConfigFile (const std::string & name)
Reads the configuration file.
Parameters
name The name.
Definition at line 41 of file Config.cpp.
References Atlas::GetFile().
readConfigFiles()
void Atlas::ConfigFileRegistry::readConfigFiles ()
Reads the configuration files.
Definition at line 37 of file Config.cpp.
registerConfigFile()
void Atlas::ConfigFileRegistry::registerConfigFile (const std::string & name, const std::string & path)
Registers the configuration file.
Parameters
name The name.
path The path.
Definition at line 54 of file Config.cpp.
registerConfigFiles()
void Atlas::ConfigFileRegistry::registerConfigFiles (const std::string & searchPath)
Registers the configuration files.
Parameters
searchPath The search path.
Definition at line 50 of file Config.cpp.
unregisterConfigFile()
void Atlas::ConfigFileRegistry::unregisterConfigFile (const std::string & name)
Unregisters the configuration file.
Parameters
name The name.
Definition at line 63 of file Config.cpp.
unregisterConfigFiles()
void Atlas::ConfigFileRegistry::unregisterConfigFiles ()
Unregisters the configuration files.
Definition at line 59 of file Config.cpp.
writeConfigFiles()
void Atlas::ConfigFileRegistry::writeConfigFiles ()
Writes the configuration files.
Note
Unimplemented
Definition at line 46 of file Config.cpp.
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/conf/Config.h
C:/Dev/Techstorm-v5/src/engine/conf/Config.cpp