C:/Dev/Techstorm-v5/src/application/add_on/scriptarray/scriptarray.cpp File Reference
#include <new>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <stdio.h>
#include <string>
#include <algorithm>
#include "scriptarray.h"
Classes
struct SArrayBuffer
struct SArrayCache
Macros
#define UNUSED_VAR(x) (void)(x)
#define COMPARE(T) *((const T*)a) < *((const T*)b)
#define COMPARE(T) *((const T*)a) == *((const T*)b)
Functions
static void RegisterScriptArray_Native (asIScriptEngine *engine)
static void RegisterScriptArray_Generic (asIScriptEngine *engine)
static void CleanupTypeInfoArrayCache (asITypeInfo *type)
static bool ScriptArrayTemplateCallback (asITypeInfo *ti, bool &dontGarbageCollect)
void RegisterScriptArray (asIScriptEngine *engine, bool defaultArray)
static void ScriptArrayFactory_Generic (asIScriptGeneric *gen)
static void ScriptArrayFactory2_Generic (asIScriptGeneric *gen)
static void ScriptArrayListFactory_Generic (asIScriptGeneric *gen)
static void ScriptArrayFactoryDefVal_Generic (asIScriptGeneric *gen)
static void ScriptArrayTemplateCallback_Generic (asIScriptGeneric *gen)
static void ScriptArrayAssignment_Generic (asIScriptGeneric *gen)
static void ScriptArrayEquals_Generic (asIScriptGeneric *gen)
static void ScriptArrayFind_Generic (asIScriptGeneric *gen)
static void ScriptArrayFind2_Generic (asIScriptGeneric *gen)
static void ScriptArrayFindByRef_Generic (asIScriptGeneric *gen)
static void ScriptArrayFindByRef2_Generic (asIScriptGeneric *gen)
static void ScriptArrayAt_Generic (asIScriptGeneric *gen)
static void ScriptArrayInsertAt_Generic (asIScriptGeneric *gen)
static void ScriptArrayInsertAtArray_Generic (asIScriptGeneric *gen)
static void ScriptArrayRemoveAt_Generic (asIScriptGeneric *gen)
static void ScriptArrayRemoveRange_Generic (asIScriptGeneric *gen)
static void ScriptArrayInsertLast_Generic (asIScriptGeneric *gen)
static void ScriptArrayRemoveLast_Generic (asIScriptGeneric *gen)
static void ScriptArrayLength_Generic (asIScriptGeneric *gen)
static void ScriptArrayResize_Generic (asIScriptGeneric *gen)
static void ScriptArrayReserve_Generic (asIScriptGeneric *gen)
static void ScriptArraySortAsc_Generic (asIScriptGeneric *gen)
static void ScriptArrayReverse_Generic (asIScriptGeneric *gen)
static void ScriptArrayIsEmpty_Generic (asIScriptGeneric *gen)
static void ScriptArraySortAsc2_Generic (asIScriptGeneric *gen)
static void ScriptArraySortDesc_Generic (asIScriptGeneric *gen)
static void ScriptArraySortDesc2_Generic (asIScriptGeneric *gen)
static void ScriptArraySortCallback_Generic (asIScriptGeneric *gen)
static void ScriptArrayAddRef_Generic (asIScriptGeneric *gen)
static void ScriptArrayRelease_Generic (asIScriptGeneric *gen)
static void ScriptArrayGetRefCount_Generic (asIScriptGeneric *gen)
static void ScriptArraySetFlag_Generic (asIScriptGeneric *gen)
static void ScriptArrayGetFlag_Generic (asIScriptGeneric *gen)
static void ScriptArrayEnumReferences_Generic (asIScriptGeneric *gen)
static void ScriptArrayReleaseAllHandles_Generic (asIScriptGeneric *gen)
Variables
static asALLOCFUNC_t userAlloc = asAllocMem
static asFREEFUNC_t userFree = asFreeMem
const asPWORD ARRAY_CACHE = 1000
Macro Definition Documentation
COMPARE [1/2]
#define COMPARE(T) *((const T*)a) < *((const T*)b)
COMPARE [2/2]
#define COMPARE(T) *((const T*)a) == *((const T*)b)
UNUSED_VAR
#define UNUSED_VAR(x) (void)(x)
Definition at line 17 of file scriptarray.cpp.
Function Documentation
CleanupTypeInfoArrayCache()
static void CleanupTypeInfoArrayCache (asITypeInfo * type) [static]
Definition at line 54 of file scriptarray.cpp.
References ARRAY_CACHE, and userFree.
Referenced by RegisterScriptArray_Generic(), and RegisterScriptArray_Native().
RegisterScriptArray()
void RegisterScriptArray (asIScriptEngine * engine, bool defaultArray)
Definition at line 248 of file scriptarray.cpp.
References RegisterScriptArray_Generic(), RegisterScriptArray_Native(), and UNUSED_VAR.
RegisterScriptArray_Generic()
static void RegisterScriptArray_Generic (asIScriptEngine * engine) [static]
Definition at line 2206 of file scriptarray.cpp.
References ARRAY_CACHE, CleanupTypeInfoArrayCache(), ScriptArrayAddRef_Generic(), ScriptArrayAssignment_Generic(), ScriptArrayAt_Generic(), ScriptArrayEnumReferences_Generic(), ScriptArrayEquals_Generic(), ScriptArrayFactory2_Generic(), ScriptArrayFactory_Generic(), ScriptArrayFactoryDefVal_Generic(), ScriptArrayFind2_Generic(), ScriptArrayFind_Generic(), ScriptArrayFindByRef2_Generic(), ScriptArrayFindByRef_Generic(), ScriptArrayGetFlag_Generic(), ScriptArrayGetRefCount_Generic(), ScriptArrayInsertAt_Generic(), ScriptArrayInsertAtArray_Generic(), ScriptArrayInsertLast_Generic(), ScriptArrayIsEmpty_Generic(), ScriptArrayLength_Generic(), ScriptArrayListFactory_Generic(), ScriptArrayRelease_Generic(), ScriptArrayReleaseAllHandles_Generic(), ScriptArrayRemoveAt_Generic(), ScriptArrayRemoveLast_Generic(), ScriptArrayRemoveRange_Generic(), ScriptArrayReserve_Generic(), ScriptArrayResize_Generic(), ScriptArrayReverse_Generic(), ScriptArraySetFlag_Generic(), ScriptArraySortAsc2_Generic(), ScriptArraySortAsc_Generic(), ScriptArraySortCallback_Generic(), ScriptArraySortDesc2_Generic(), ScriptArraySortDesc_Generic(), ScriptArrayTemplateCallback_Generic(), and UNUSED_VAR.
Referenced by RegisterScriptArray().
RegisterScriptArray_Native()
static void RegisterScriptArray_Native (asIScriptEngine * engine) [static]
Definition at line 262 of file scriptarray.cpp.
References ARRAY_CACHE, CleanupTypeInfoArrayCache(), CScriptArray::Create(), ScriptArrayTemplateCallback(), and UNUSED_VAR.
Referenced by RegisterScriptArray().
ScriptArrayAddRef_Generic()
static void ScriptArrayAddRef_Generic (asIScriptGeneric * gen) [static]
Definition at line 2162 of file scriptarray.cpp.
References CScriptArray::AddRef().
Referenced by RegisterScriptArray_Generic().
ScriptArrayAssignment_Generic()
static void ScriptArrayAssignment_Generic (asIScriptGeneric * gen) [static]
Definition at line 1994 of file scriptarray.cpp.
Referenced by RegisterScriptArray_Generic().
ScriptArrayAt_Generic()
static void ScriptArrayAt_Generic (asIScriptGeneric * gen) [static]
Definition at line 2039 of file scriptarray.cpp.
References CScriptArray::At().
Referenced by RegisterScriptArray_Generic().
ScriptArrayEnumReferences_Generic()
static void ScriptArrayEnumReferences_Generic (asIScriptGeneric * gen) [static]
Definition at line 2192 of file scriptarray.cpp.
References CScriptArray::EnumReferences().
Referenced by RegisterScriptArray_Generic().
ScriptArrayEquals_Generic()
static void ScriptArrayEquals_Generic (asIScriptGeneric * gen) [static]
Definition at line 2002 of file scriptarray.cpp.
Referenced by RegisterScriptArray_Generic().
ScriptArrayFactory2_Generic()
static void ScriptArrayFactory2_Generic (asIScriptGeneric * gen) [static]
Definition at line 1962 of file scriptarray.cpp.
References CScriptArray::Create().
Referenced by RegisterScriptArray_Generic().
ScriptArrayFactory_Generic()
static void ScriptArrayFactory_Generic (asIScriptGeneric * gen) [static]
Definition at line 1955 of file scriptarray.cpp.
References CScriptArray::Create().
Referenced by RegisterScriptArray_Generic().
ScriptArrayFactoryDefVal_Generic()
static void ScriptArrayFactoryDefVal_Generic (asIScriptGeneric * gen) [static]
Definition at line 1978 of file scriptarray.cpp.
References CScriptArray::Create().
Referenced by RegisterScriptArray_Generic().
ScriptArrayFind2_Generic()
static void ScriptArrayFind2_Generic (asIScriptGeneric * gen) [static]
Definition at line 2016 of file scriptarray.cpp.
References CScriptArray::Find().
Referenced by RegisterScriptArray_Generic().
ScriptArrayFind_Generic()
static void ScriptArrayFind_Generic (asIScriptGeneric * gen) [static]
Definition at line 2009 of file scriptarray.cpp.
References CScriptArray::Find().
Referenced by RegisterScriptArray_Generic().
ScriptArrayFindByRef2_Generic()
static void ScriptArrayFindByRef2_Generic (asIScriptGeneric * gen) [static]
Definition at line 2031 of file scriptarray.cpp.
References CScriptArray::FindByRef().
Referenced by RegisterScriptArray_Generic().
ScriptArrayFindByRef_Generic()
static void ScriptArrayFindByRef_Generic (asIScriptGeneric * gen) [static]
Definition at line 2024 of file scriptarray.cpp.
References CScriptArray::FindByRef().
Referenced by RegisterScriptArray_Generic().
ScriptArrayGetFlag_Generic()
static void ScriptArrayGetFlag_Generic (asIScriptGeneric * gen) [static]
Definition at line 2186 of file scriptarray.cpp.
References CScriptArray::GetFlag().
Referenced by RegisterScriptArray_Generic().
ScriptArrayGetRefCount_Generic()
static void ScriptArrayGetRefCount_Generic (asIScriptGeneric * gen) [static]
Definition at line 2174 of file scriptarray.cpp.
References CScriptArray::GetRefCount().
Referenced by RegisterScriptArray_Generic().
ScriptArrayInsertAt_Generic()
static void ScriptArrayInsertAt_Generic (asIScriptGeneric * gen) [static]
Definition at line 2047 of file scriptarray.cpp.
References CScriptArray::InsertAt().
Referenced by RegisterScriptArray_Generic().
ScriptArrayInsertAtArray_Generic()
static void ScriptArrayInsertAtArray_Generic (asIScriptGeneric * gen) [static]
Definition at line 2055 of file scriptarray.cpp.
References CScriptArray::InsertAt().
Referenced by RegisterScriptArray_Generic().
ScriptArrayInsertLast_Generic()
static void ScriptArrayInsertLast_Generic (asIScriptGeneric * gen) [static]
Definition at line 2078 of file scriptarray.cpp.
References CScriptArray::InsertLast().
Referenced by RegisterScriptArray_Generic().
ScriptArrayIsEmpty_Generic()
static void ScriptArrayIsEmpty_Generic (asIScriptGeneric * gen) [static]
Definition at line 2125 of file scriptarray.cpp.
References CScriptArray::IsEmpty().
Referenced by RegisterScriptArray_Generic().
ScriptArrayLength_Generic()
static void ScriptArrayLength_Generic (asIScriptGeneric * gen) [static]
Definition at line 2091 of file scriptarray.cpp.
References CScriptArray::GetSize().
Referenced by RegisterScriptArray_Generic().
ScriptArrayListFactory_Generic()
static void ScriptArrayListFactory_Generic (asIScriptGeneric * gen) [static]
Definition at line 1970 of file scriptarray.cpp.
References CScriptArray::Create().
Referenced by RegisterScriptArray_Generic().
ScriptArrayRelease_Generic()
static void ScriptArrayRelease_Generic (asIScriptGeneric * gen) [static]
Definition at line 2168 of file scriptarray.cpp.
References CScriptArray::Release().
Referenced by RegisterScriptArray_Generic().
ScriptArrayReleaseAllHandles_Generic()
static void ScriptArrayReleaseAllHandles_Generic (asIScriptGeneric * gen) [static]
Definition at line 2199 of file scriptarray.cpp.
References CScriptArray::ReleaseAllHandles().
Referenced by RegisterScriptArray_Generic().
ScriptArrayRemoveAt_Generic()
static void ScriptArrayRemoveAt_Generic (asIScriptGeneric * gen) [static]
Definition at line 2063 of file scriptarray.cpp.
References CScriptArray::RemoveAt().
Referenced by RegisterScriptArray_Generic().
ScriptArrayRemoveLast_Generic()
static void ScriptArrayRemoveLast_Generic (asIScriptGeneric * gen) [static]
Definition at line 2085 of file scriptarray.cpp.
References CScriptArray::RemoveLast().
Referenced by RegisterScriptArray_Generic().
ScriptArrayRemoveRange_Generic()
static void ScriptArrayRemoveRange_Generic (asIScriptGeneric * gen) [static]
Definition at line 2070 of file scriptarray.cpp.
References CScriptArray::RemoveRange().
Referenced by RegisterScriptArray_Generic().
ScriptArrayReserve_Generic()
static void ScriptArrayReserve_Generic (asIScriptGeneric * gen) [static]
Definition at line 2106 of file scriptarray.cpp.
References CScriptArray::Reserve().
Referenced by RegisterScriptArray_Generic().
ScriptArrayResize_Generic()
static void ScriptArrayResize_Generic (asIScriptGeneric * gen) [static]
Definition at line 2098 of file scriptarray.cpp.
References CScriptArray::Resize().
Referenced by RegisterScriptArray_Generic().
ScriptArrayReverse_Generic()
static void ScriptArrayReverse_Generic (asIScriptGeneric * gen) [static]
Definition at line 2119 of file scriptarray.cpp.
References CScriptArray::Reverse().
Referenced by RegisterScriptArray_Generic().
ScriptArraySetFlag_Generic()
static void ScriptArraySetFlag_Generic (asIScriptGeneric * gen) [static]
Definition at line 2180 of file scriptarray.cpp.
References CScriptArray::SetFlag().
Referenced by RegisterScriptArray_Generic().
ScriptArraySortAsc2_Generic()
static void ScriptArraySortAsc2_Generic (asIScriptGeneric * gen) [static]
Definition at line 2131 of file scriptarray.cpp.
References CScriptArray::SortAsc().
Referenced by RegisterScriptArray_Generic().
ScriptArraySortAsc_Generic()
static void ScriptArraySortAsc_Generic (asIScriptGeneric * gen) [static]
Definition at line 2113 of file scriptarray.cpp.
References CScriptArray::SortAsc().
Referenced by RegisterScriptArray_Generic().
ScriptArraySortCallback_Generic()
static void ScriptArraySortCallback_Generic (asIScriptGeneric * gen) [static]
Definition at line 2153 of file scriptarray.cpp.
References CScriptArray::Sort().
Referenced by RegisterScriptArray_Generic().
ScriptArraySortDesc2_Generic()
static void ScriptArraySortDesc2_Generic (asIScriptGeneric * gen) [static]
Definition at line 2145 of file scriptarray.cpp.
References CScriptArray::SortDesc().
Referenced by RegisterScriptArray_Generic().
ScriptArraySortDesc_Generic()
static void ScriptArraySortDesc_Generic (asIScriptGeneric * gen) [static]
Definition at line 2139 of file scriptarray.cpp.
References CScriptArray::SortDesc().
Referenced by RegisterScriptArray_Generic().
ScriptArrayTemplateCallback()
static bool ScriptArrayTemplateCallback (asITypeInfo * ti, bool & dontGarbageCollect) [static]
Definition at line 131 of file scriptarray.cpp.
Referenced by RegisterScriptArray_Native(), and ScriptArrayTemplateCallback_Generic().
ScriptArrayTemplateCallback_Generic()
static void ScriptArrayTemplateCallback_Generic (asIScriptGeneric * gen) [static]
Definition at line 1987 of file scriptarray.cpp.
References ScriptArrayTemplateCallback().
Referenced by RegisterScriptArray_Generic().
Variable Documentation
ARRAY_CACHE
const asPWORD ARRAY_CACHE = 1000
Definition at line 52 of file scriptarray.cpp.
Referenced by CleanupTypeInfoArrayCache(), CScriptArray::Find(), CScriptArray::operator==(), CScriptArray::Precache(), RegisterScriptArray_Generic(), RegisterScriptArray_Native(), and CScriptArray::Sort().
userAlloc
asALLOCFUNC_t userAlloc = asAllocMem [static]
Definition at line 21 of file scriptarray.cpp.
Referenced by CScriptArray::Create(), CScriptArray::Create(), CScriptGrid::Create(), CScriptGrid::Create(), CScriptArray::Create(), CScriptGrid::Create(), CScriptArray::CreateBuffer(), CScriptGrid::CreateBuffer(), CScriptArray::Precache(), CScriptArray::Reserve(), CScriptArray::Resize(), CScriptArray::SetMemoryFunctions(), and CScriptGrid::SetMemoryFunctions().
userFree
asFREEFUNC_t userFree = asFreeMem [static]
Definition at line 22 of file scriptarray.cpp.
Referenced by CleanupTypeInfoArrayCache(), CScriptArray::DeleteBuffer(), CScriptGrid::DeleteBuffer(), CScriptArray::Release(), CScriptGrid::Release(), CScriptArray::Reserve(), CScriptArray::Resize(), CScriptArray::SetMemoryFunctions(), and CScriptGrid::SetMemoryFunctions().