C:/Dev/Techstorm-v5/src/engine/modding/add_on/scriptany/scriptany.h File Reference
#include <angelscript.h>
Classes
class CScriptAny
struct CScriptAny::valueStruct
Functions
void RegisterScriptAny (asIScriptEngine *engine)
void RegisterScriptAny_Native (asIScriptEngine *engine)
void RegisterScriptAny_Generic (asIScriptEngine *engine)
Function Documentation
RegisterScriptAny()
void RegisterScriptAny (asIScriptEngine * engine)
Definition at line 134 of file scriptany.cpp.
References RegisterScriptAny_Generic(), and RegisterScriptAny_Native().
RegisterScriptAny_Generic()
void RegisterScriptAny_Generic (asIScriptEngine * engine)
Definition at line 171 of file scriptany.cpp.
References ScriptAny_AddRef_Generic(), ScriptAny_EnumReferences_Generic(), ScriptAny_GetFlag_Generic(), ScriptAny_GetRefCount_Generic(), ScriptAny_Release_Generic(), ScriptAny_ReleaseAllHandles_Generic(), ScriptAny_Retrieve_Generic(), ScriptAny_RetrieveFlt_Generic(), ScriptAny_RetrieveInt_Generic(), ScriptAny_SetFlag_Generic(), ScriptAny_Store_Generic(), ScriptAny_StoreFlt_Generic(), ScriptAny_StoreInt_Generic(), ScriptAnyAssignment_Generic(), ScriptAnyFactory2_Generic(), and ScriptAnyFactory_Generic().
Referenced by RegisterScriptAny().
RegisterScriptAny_Native()
void RegisterScriptAny_Native (asIScriptEngine * engine)
Definition at line 142 of file scriptany.cpp.
References ScriptAnyAssignment(), ScriptAnyFactory2_Generic(), and ScriptAnyFactory_Generic().
Referenced by RegisterScriptAny().