C:/Dev/Techstorm-v5/src/engine/modding/add_on/scriptfile/scriptfile.h File Reference
#include <angelscript.h>
#include <string>
#include <stdio.h>
Classes
class CScriptFile
Macros
#define AS_WRITE_OPS 1
Functions
void RegisterScriptFile (asIScriptEngine *engine)
void RegisterScriptFile_Native (asIScriptEngine *engine)
void RegisterScriptFile_Generic (asIScriptEngine *engine)
Macro Definition Documentation
AS_WRITE_OPS
#define AS_WRITE_OPS 1
Definition at line 20 of file scriptfile.h.
Function Documentation
RegisterScriptFile()
void RegisterScriptFile (asIScriptEngine * engine)
Definition at line 235 of file scriptfile.cpp.
References RegisterScriptFile_Generic(), and RegisterScriptFile_Native().
RegisterScriptFile_Generic()
void RegisterScriptFile_Generic (asIScriptEngine * engine)
Definition at line 202 of file scriptfile.cpp.
References ScriptFile_AddRef_Generic(), ScriptFile_Close_Generic(), ScriptFile_Factory_Generic(), ScriptFile_GetPos_Generic(), ScriptFile_GetSize_Generic(), ScriptFile_IsEOF_Generic(), ScriptFile_MovePos_Generic(), ScriptFile_Open_Generic(), ScriptFile_ReadDouble_Generic(), ScriptFile_ReadFloat_Generic(), ScriptFile_ReadInt_Generic(), ScriptFile_ReadLine_Generic(), ScriptFile_ReadString_Generic(), ScriptFile_ReadUInt_Generic(), ScriptFile_Release_Generic(), ScriptFile_SetPos_Generic(), ScriptFile_WriteDouble_Generic(), ScriptFile_WriteFloat_Generic(), ScriptFile_WriteInt_Generic(), ScriptFile_WriteString_Generic(), and ScriptFile_WriteUInt_Generic().
Referenced by RegisterScriptFile().
RegisterScriptFile_Native()
void RegisterScriptFile_Native (asIScriptEngine * engine)
Definition at line 169 of file scriptfile.cpp.
References ScriptFile_Factory().
Referenced by RegisterScriptFile().