C:/Dev/Techstorm-v5/src/application/add_on/contextmgr/contextmgr.cpp File Reference
#include <assert.h>
#include <string>
#include "contextmgr.h"
Classes
struct SContextInfo
Functions
static void ScriptSleep (asUINT milliSeconds)
static void ScriptYield ()
void ScriptCreateCoRoutine (asIScriptFunction *func, CScriptDictionary *arg)
Variables
BEGIN_AS_NAMESPACE const asPWORD CONTEXT_MGR = 1002
Function Documentation
ScriptCreateCoRoutine()
void ScriptCreateCoRoutine (asIScriptFunction * func, CScriptDictionary * arg)
Definition at line 72 of file contextmgr.cpp.
References CContextMgr::AddContextForCoRoutine(), and CONTEXT_MGR.
Referenced by CContextMgr::RegisterCoRoutineSupport().
ScriptSleep()
static void ScriptSleep (asUINT milliSeconds) [static]
Definition at line 32 of file contextmgr.cpp.
References CONTEXT_MGR, and CContextMgr::SetSleeping().
Referenced by CContextMgr::RegisterThreadSupport().
ScriptYield()
static void ScriptYield () [static]
Definition at line 52 of file contextmgr.cpp.
References CONTEXT_MGR, and CContextMgr::NextCoRoutine().
Referenced by CContextMgr::RegisterCoRoutineSupport().
Variable Documentation
CONTEXT_MGR
BEGIN_AS_NAMESPACE const asPWORD CONTEXT_MGR = 1002
Definition at line 22 of file contextmgr.cpp.
Referenced by CContextMgr::AddContext(), CContextMgr::AddContextForCoRoutine(), ScriptCreateCoRoutine(), ScriptSleep(), and ScriptYield().