BPLayerInterfaceImpl Class Reference
#include <PhysicsPrototype.h>
Public Member Functions
BPLayerInterfaceImpl ()
virtual JPH::uint GetNumBroadPhaseLayers () const override
virtual JPH::BroadPhaseLayer GetBroadPhaseLayer (JPH::ObjectLayer inLayer) const override
Private Attributes
JPH::BroadPhaseLayer mObjectToBroadPhase [Layers::NUM_LAYERS]
Detailed Description
Definition at line 145 of file PhysicsPrototype.h.
Constructor & Destructor Documentation
BPLayerInterfaceImpl()
BPLayerInterfaceImpl::BPLayerInterfaceImpl () [inline]
Definition at line 148 of file PhysicsPrototype.h.
References mObjectToBroadPhase, Layers::MOVING, BroadPhaseLayers::MOVING(), Layers::NON_MOVING, and BroadPhaseLayers::NON_MOVING().
Member Function Documentation
GetBroadPhaseLayer()
virtual JPH::BroadPhaseLayer BPLayerInterfaceImpl::GetBroadPhaseLayer (JPH::ObjectLayer inLayer) const [inline], [override], [virtual]
Definition at line 160 of file PhysicsPrototype.h.
References mObjectToBroadPhase, and Layers::NUM_LAYERS.
GetNumBroadPhaseLayers()
virtual JPH::uint BPLayerInterfaceImpl::GetNumBroadPhaseLayers () const [inline], [override], [virtual]
Definition at line 155 of file PhysicsPrototype.h.
References BroadPhaseLayers::NUM_LAYERS().
Member Data Documentation
mObjectToBroadPhase
JPH::BroadPhaseLayer BPLayerInterfaceImpl::mObjectToBroadPhase[Layers::NUM_LAYERS] [private]
Definition at line 180 of file PhysicsPrototype.h.
Referenced by BPLayerInterfaceImpl(), and GetBroadPhaseLayer().
The documentation for this class was generated from the following file:
C:/Dev/Techstorm-v5/src/application/prototyping/PhysicsPrototype.h