Atlas::MonoRumbleHapticEffect Class Reference
#include <HapticEffect.h>
Public Member Functions
MonoRumbleHapticEffect ()=default
void play (std::shared_ptr< HapticDevice > hapticDevice) override
void stop (std::shared_ptr< HapticDevice > hapticDevice) override
void pause (std::shared_ptr< HapticDevice > hapticDevice) override
void resume (std::shared_ptr< HapticDevice > hapticDevice) override
HapticEffectUploadResult upload (std::shared_ptr< HapticDevice > hapticDevice) override
void destroy (std::shared_ptr< HapticDevice > hapticDevice) override
Public Member Functions inherited from Atlas::IHapticEffect
virtual ~IHapticEffect ()=default
Private Attributes
MonoRumbleHapticEffectInfo mRumbleHapticEffectInfo
bool mbIsUploaded = false
Detailed Description
Definition at line 53 of file HapticEffect.h.
Constructor & Destructor Documentation
MonoRumbleHapticEffect()
Atlas::MonoRumbleHapticEffect::MonoRumbleHapticEffect () [default]
Member Function Documentation
destroy()
void Atlas::MonoRumbleHapticEffect::destroy (std::shared_ptr< HapticDevice > hapticDevice) [override], [virtual]
Implements Atlas::IHapticEffect.
Definition at line 65 of file HapticEffect.cpp.
Referenced by main().
pause()
void Atlas::MonoRumbleHapticEffect::pause (std::shared_ptr< HapticDevice > hapticDevice) [override], [virtual]
Implements Atlas::IHapticEffect.
Definition at line 25 of file HapticEffect.cpp.
play()
void Atlas::MonoRumbleHapticEffect::play (std::shared_ptr< HapticDevice > hapticDevice) [override], [virtual]
Implements Atlas::IHapticEffect.
Definition at line 15 of file HapticEffect.cpp.
References Atlas::MonoRumbleHapticEffectInfo::lengthMS, mRumbleHapticEffectInfo, and Atlas::MonoRumbleHapticEffectInfo::strength.
Referenced by main().
resume()
void Atlas::MonoRumbleHapticEffect::resume (std::shared_ptr< HapticDevice > hapticDevice) [override], [virtual]
Implements Atlas::IHapticEffect.
Definition at line 30 of file HapticEffect.cpp.
stop()
void Atlas::MonoRumbleHapticEffect::stop (std::shared_ptr< HapticDevice > hapticDevice) [override], [virtual]
Implements Atlas::IHapticEffect.
Definition at line 20 of file HapticEffect.cpp.
upload()
Atlas::HapticEffectUploadResult Atlas::MonoRumbleHapticEffect::upload (std::shared_ptr< HapticDevice > hapticDevice) [override], [virtual]
Implements Atlas::IHapticEffect.
Definition at line 35 of file HapticEffect.cpp.
References Atlas::WarnLog().
Referenced by main().
Member Data Documentation
mbIsUploaded
bool Atlas::MonoRumbleHapticEffect::mbIsUploaded = false [private]
Definition at line 58 of file HapticEffect.h.
mRumbleHapticEffectInfo
MonoRumbleHapticEffectInfo Atlas::MonoRumbleHapticEffect::mRumbleHapticEffectInfo [private]
Definition at line 56 of file HapticEffect.h.
Referenced by play().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/haptics/HapticEffect.h
C:/Dev/Techstorm-v5/src/engine/haptics/HapticEffect.cpp