Atlas::Validatable Class Reference
#include <Common.h>
Public Member Functions
ATLAS_EXPLICIT Validatable (bool bIsValid)
Validatable ()=default
virtual ~Validatable ()=default
virtual bool isValid () const
virtual ATLAS_IMPLICIT operator bool () const
Protected Member Functions
bool & getInternalValidityValue ()
virtual void setValidity (bool bIsValid)
virtual void setValid ()
virtual void setInvalid ()
Private Attributes
bool mbIsValid { false }
Detailed Description
Definition at line 258 of file Common.h.
Constructor & Destructor Documentation
Validatable() [1/2]
ATLAS_EXPLICIT Atlas::Validatable::Validatable (bool bIsValid) [inline]
Definition at line 281 of file Common.h.
Validatable() [2/2]
Atlas::Validatable::Validatable () [default]
~Validatable()
virtual Atlas::Validatable::~Validatable () [virtual], [default]
Member Function Documentation
getInternalValidityValue()
bool & Atlas::Validatable::getInternalValidityValue () [inline], [protected]
Definition at line 264 of file Common.h.
References mbIsValid.
isValid()
virtual bool Atlas::Validatable::isValid () const [inline], [virtual]
Reimplemented in Atlas::PhysicalDevice, Atlas::InitializableAndValidatable, Atlas::HandleWrapperBase< T_WRAPS >, Atlas::AVulkanHandleWrapper< T_WRAPS >, Atlas::AVulkanHandleWrapper< VkDevice >, Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >, and Atlas::AVulkanCompositeHandleWrapper< VkPhysicalDevice, vkb::PhysicalDevice, vkb::PhysicalDeviceSelector >.
Definition at line 287 of file Common.h.
References mbIsValid.
Referenced by Atlas::InitializableAndValidatable::isValid(), and operator bool().
operator bool()
virtual ATLAS_IMPLICIT Atlas::Validatable::operator bool () const [inline], [virtual]
Definition at line 291 of file Common.h.
References isValid().
setInvalid()
virtual void Atlas::Validatable::setInvalid () [inline], [protected], [virtual]
Definition at line 276 of file Common.h.
References setValidity().
Referenced by Atlas::SurfaceBase< T_SURFACE_HANDLE >::destroySurface(), and Atlas::HandleWrapperBase< T_WRAPS >::setHandle().
setValid()
virtual void Atlas::Validatable::setValid () [inline], [protected], [virtual]
Definition at line 272 of file Common.h.
References setValidity().
Referenced by Atlas::HandleWrapperBase< T_WRAPS >::setHandle().
setValidity()
virtual void Atlas::Validatable::setValidity (bool bIsValid) [inline], [protected], [virtual]
Definition at line 268 of file Common.h.
References mbIsValid.
Referenced by setInvalid(), and setValid().
Member Data Documentation
mbIsValid
bool Atlas::Validatable::mbIsValid { false } [private]
Definition at line 261 of file Common.h.
Referenced by getInternalValidityValue(), isValid(), and setValidity().
The documentation for this class was generated from the following file:
C:/Dev/Techstorm-v5/src/engine/core/Common.h