Atlas::Application::FrameManager Class Reference
#include <ApplicationUtils.h>
Public Member Functions
int RunUpdateThread (PROJECT_TYPENAME *userProject)
int RunWorkerThread (PROJECT_TYPENAME *userProject)
void launchThreads (PROJECT_TYPENAME &gameSettings)
void killThreads ()
Public Attributes
float sFrameTime = 0.0f
volatile bool sIsWaitingForOthers = false
volatile bool sExit = false
std::unordered_map< std::string, std::shared_ptr< bool > > sThreads
volatile bool isWorkerWaiting = false
volatile bool isUpdateWaiting = false
std::shared_ptr< PROJECT_TYPENAME > userProject
std::jthread updateThread
std::jthread workThread
Additional Inherited Members
Static Public Member Functions inherited from Atlas::Singleton< FrameManager >
static FrameManager & Instance ()
Retrieves the current singleton instance as a reference. If you need to create a class that has a single static instance, use this class.
Detailed Description
Definition at line 152 of file ApplicationUtils.h.
Member Function Documentation
killThreads()
void Atlas::Application::FrameManager::killThreads () [inline]
Definition at line 250 of file ApplicationUtils.h.
References sExit.
launchThreads()
void Atlas::Application::FrameManager::launchThreads (PROJECT_TYPENAME & gameSettings) [inline]
Definition at line 215 of file ApplicationUtils.h.
References isUpdateWaiting, isWorkerWaiting, Atlas::Log(), RunUpdateThread(), RunWorkerThread(), sExit, sIsWaitingForOthers, Atlas::TRACE, updateThread, and workThread.
RunUpdateThread()
int Atlas::Application::FrameManager::RunUpdateThread (PROJECT_TYPENAME * userProject) [inline]
Definition at line 167 of file ApplicationUtils.h.
References ATLAS_THREAD_YIELD, isUpdateWaiting, Atlas::Log(), sExit, sIsWaitingForOthers, and userProject.
Referenced by launchThreads().
RunWorkerThread()
int Atlas::Application::FrameManager::RunWorkerThread (PROJECT_TYPENAME * userProject) [inline]
Definition at line 198 of file ApplicationUtils.h.
References ATLAS_THREAD_YIELD, isWorkerWaiting, Atlas::Log(), sExit, and sIsWaitingForOthers.
Referenced by launchThreads().
Member Data Documentation
isUpdateWaiting
volatile bool Atlas::Application::FrameManager::isUpdateWaiting = false
Definition at line 161 of file ApplicationUtils.h.
Referenced by launchThreads(), and RunUpdateThread().
isWorkerWaiting
volatile bool Atlas::Application::FrameManager::isWorkerWaiting = false
Definition at line 160 of file ApplicationUtils.h.
Referenced by launchThreads(), and RunWorkerThread().
sExit
volatile bool Atlas::Application::FrameManager::sExit = false
Definition at line 157 of file ApplicationUtils.h.
Referenced by killThreads(), launchThreads(), RunUpdateThread(), and RunWorkerThread().
sFrameTime
float Atlas::Application::FrameManager::sFrameTime = 0.0f
Definition at line 155 of file ApplicationUtils.h.
sIsWaitingForOthers
volatile bool Atlas::Application::FrameManager::sIsWaitingForOthers = false
Definition at line 156 of file ApplicationUtils.h.
Referenced by launchThreads(), RunUpdateThread(), and RunWorkerThread().
sThreads
std::unordered_map<std::string, std::shared_ptr<bool> > Atlas::Application::FrameManager::sThreads
Definition at line 158 of file ApplicationUtils.h.
updateThread
std::jthread Atlas::Application::FrameManager::updateThread
Definition at line 164 of file ApplicationUtils.h.
Referenced by launchThreads().
userProject
std::shared_ptr<PROJECT_TYPENAME> Atlas::Application::FrameManager::userProject
Definition at line 163 of file ApplicationUtils.h.
Referenced by RunUpdateThread().
workThread
std::jthread Atlas::Application::FrameManager::workThread
Definition at line 165 of file ApplicationUtils.h.
Referenced by launchThreads().
The documentation for this class was generated from the following file:
C:/Dev/Techstorm-v5/src/application/ApplicationUtils.h