C:/Dev/Techstorm-v5/src/engine/modding/add_on/autowrapper/generator/generateheader.cpp File Reference
#include <stdio.h>
#include <string>
Functions
void PrintTemplate (const char *base, const char *typeNameList, const char *retType, const char *objType, const char *isConst, const char *newExpr, const char *objExpr, const char *argList1, const char *argList2, const char *wrapName)
void PrintConstructor (const char *comma, const char *typeNameList, const char *typeList, const char *argList)
int main ()
Variables
const int max_args = 4
Function Documentation
main()
int main ()
Definition at line 27 of file generateheader.cpp.
References max_args, PrintConstructor(), and PrintTemplate().
PrintConstructor()
void PrintConstructor (const char * comma, const char * typeNameList, const char * typeList, const char * argList)
Definition at line 178 of file generateheader.cpp.
Referenced by main().
PrintTemplate()
void PrintTemplate (const char * base, const char * typeNameList, const char * retType, const char * objType, const char * isConst, const char * newExpr, const char * objExpr, const char * argList1, const char * argList2, const char * wrapName)
Definition at line 167 of file generateheader.cpp.
Referenced by main().
Variable Documentation
max_args
const int max_args = 4
Definition at line 20 of file generateheader.cpp.
Referenced by main().