C:/Dev/Techstorm-v5/src/engine/modding/add_on/scriptdictionary/scriptdictionary.cpp File Reference
#include <assert.h>
#include <string.h>
#include "scriptdictionary.h"
#include "../scriptarray/scriptarray.h"
Classes
struct SDictionaryCache
Functions
void ScriptDictionaryFactory_Generic (asIScriptGeneric *gen)
void ScriptDictionaryListFactory_Generic (asIScriptGeneric *gen)
void ScriptDictionaryAddRef_Generic (asIScriptGeneric *gen)
void ScriptDictionaryRelease_Generic (asIScriptGeneric *gen)
void ScriptDictionaryAssign_Generic (asIScriptGeneric *gen)
void ScriptDictionarySet_Generic (asIScriptGeneric *gen)
void ScriptDictionarySetInt_Generic (asIScriptGeneric *gen)
void ScriptDictionarySetFlt_Generic (asIScriptGeneric *gen)
void ScriptDictionaryGet_Generic (asIScriptGeneric *gen)
void ScriptDictionaryGetInt_Generic (asIScriptGeneric *gen)
void ScriptDictionaryGetFlt_Generic (asIScriptGeneric *gen)
void ScriptDictionaryExists_Generic (asIScriptGeneric *gen)
void ScriptDictionaryIsEmpty_Generic (asIScriptGeneric *gen)
void ScriptDictionaryGetSize_Generic (asIScriptGeneric *gen)
void ScriptDictionaryDelete_Generic (asIScriptGeneric *gen)
void ScriptDictionaryDeleteAll_Generic (asIScriptGeneric *gen)
static void ScriptDictionaryGetRefCount_Generic (asIScriptGeneric *gen)
static void ScriptDictionarySetGCFlag_Generic (asIScriptGeneric *gen)
static void ScriptDictionaryGetGCFlag_Generic (asIScriptGeneric *gen)
static void ScriptDictionaryEnumReferences_Generic (asIScriptGeneric *gen)
static void ScriptDictionaryReleaseAllReferences_Generic (asIScriptGeneric *gen)
static void CScriptDictionaryGetKeys_Generic (asIScriptGeneric *gen)
static void CScriptDictionary_opIndex_Generic (asIScriptGeneric *gen)
static void CScriptDictionary_opIndex_const_Generic (asIScriptGeneric *gen)
static void CScriptDictValue_Construct (void *mem)
static void CScriptDictValue_Destruct (CScriptDictValue *obj)
static CScriptDictValue & CScriptDictValue_opAssign (void *ref, int typeId, CScriptDictValue *obj)
static CScriptDictValue & CScriptDictValue_opAssign (const CScriptDictValue &other, CScriptDictValue *obj)
static CScriptDictValue & CScriptDictValue_opAssign (double val, CScriptDictValue *obj)
static CScriptDictValue & CScriptDictValue_opAssign (asINT64 val, CScriptDictValue *obj)
static void CScriptDictValue_opCast (void *ref, int typeId, CScriptDictValue *obj)
static asINT64 CScriptDictValue_opConvInt (CScriptDictValue *obj)
static double CScriptDictValue_opConvDouble (CScriptDictValue *obj)
static void CScriptDictValue_opConvDouble_Generic (asIScriptGeneric *gen)
static void CScriptDictValue_opConvInt_Generic (asIScriptGeneric *gen)
static void CScriptDictValue_opCast_Generic (asIScriptGeneric *gen)
static void CScriptDictValue_opAssign_int64_Generic (asIScriptGeneric *gen)
static void CScriptDictValue_opAssign_double_Generic (asIScriptGeneric *gen)
static void CScriptDictValue_opAssign_Generic (asIScriptGeneric *gen)
static void CScriptDictValue_opCopyAssign_Generic (asIScriptGeneric *gen)
static void CScriptDictValue_Construct_Generic (asIScriptGeneric *gen)
static void CScriptDictValue_Destruct_Generic (asIScriptGeneric *gen)
static void CScriptDictValue_EnumReferences_Generic (asIScriptGeneric *gen)
static void CScriptDictValue_FreeValue_Generic (asIScriptGeneric *gen)
void RegisterScriptDictionary (asIScriptEngine *engine)
void RegisterScriptDictionary_Native (asIScriptEngine *engine)
void RegisterScriptDictionary_Generic (asIScriptEngine *engine)
Variables
const asPWORD DICTIONARY_CACHE = 1003
Function Documentation
CScriptDictionary_opIndex_const_Generic()
static void CScriptDictionary_opIndex_const_Generic (asIScriptGeneric * gen) [static]
Definition at line 603 of file scriptdictionary.cpp.
Referenced by RegisterScriptDictionary_Generic().
CScriptDictionary_opIndex_Generic()
static void CScriptDictionary_opIndex_Generic (asIScriptGeneric * gen) [static]
Definition at line 596 of file scriptdictionary.cpp.
Referenced by RegisterScriptDictionary_Generic().
CScriptDictionaryGetKeys_Generic()
static void CScriptDictionaryGetKeys_Generic (asIScriptGeneric * gen) [static]
Definition at line 590 of file scriptdictionary.cpp.
References CScriptDictionary::GetKeys().
Referenced by RegisterScriptDictionary_Generic().
CScriptDictValue_Construct()
static void CScriptDictValue_Construct (void * mem) [static]
Definition at line 912 of file scriptdictionary.cpp.
Referenced by CScriptDictValue_Construct_Generic(), and RegisterScriptDictionary_Native().
CScriptDictValue_Construct_Generic()
static void CScriptDictValue_Construct_Generic (asIScriptGeneric * gen) [static]
Definition at line 1034 of file scriptdictionary.cpp.
References CScriptDictValue_Construct().
Referenced by RegisterScriptDictionary_Generic().
CScriptDictValue_Destruct()
static void CScriptDictValue_Destruct (CScriptDictValue * obj) [static]
Definition at line 917 of file scriptdictionary.cpp.
References CScriptDictValue::FreeValue(), and CScriptDictValue::~CScriptDictValue().
Referenced by CScriptDictValue_Destruct_Generic(), and RegisterScriptDictionary_Native().
CScriptDictValue_Destruct_Generic()
static void CScriptDictValue_Destruct_Generic (asIScriptGeneric * gen) [static]
Definition at line 1040 of file scriptdictionary.cpp.
References CScriptDictValue_Destruct().
Referenced by RegisterScriptDictionary_Generic().
CScriptDictValue_EnumReferences_Generic()
static void CScriptDictValue_EnumReferences_Generic (asIScriptGeneric * gen) [static]
Definition at line 1046 of file scriptdictionary.cpp.
References CScriptDictValue::EnumReferences().
Referenced by RegisterScriptDictionary_Generic().
CScriptDictValue_FreeValue_Generic()
static void CScriptDictValue_FreeValue_Generic (asIScriptGeneric * gen) [static]
Definition at line 1052 of file scriptdictionary.cpp.
References CScriptDictValue::FreeValue().
Referenced by RegisterScriptDictionary_Generic().
CScriptDictValue_opAssign() [1/4]
static CScriptDictValue & CScriptDictValue_opAssign (asINT64 val, CScriptDictValue * obj) [static]
Definition at line 956 of file scriptdictionary.cpp.
References CScriptDictValue_opAssign().
CScriptDictValue_opAssign() [2/4]
static CScriptDictValue & CScriptDictValue_opAssign (const CScriptDictValue & other, CScriptDictValue * obj) [static]
Definition at line 939 of file scriptdictionary.cpp.
References CScriptDictValue::Set().
CScriptDictValue_opAssign() [3/4]
static CScriptDictValue & CScriptDictValue_opAssign (double val, CScriptDictValue * obj) [static]
Definition at line 951 of file scriptdictionary.cpp.
References CScriptDictValue_opAssign().
CScriptDictValue_opAssign() [4/4]
static CScriptDictValue & CScriptDictValue_opAssign (void * ref, int typeId, CScriptDictValue * obj) [static]
Definition at line 928 of file scriptdictionary.cpp.
References CScriptDictValue::Set().
Referenced by CScriptDictValue_opAssign(), CScriptDictValue_opAssign(), CScriptDictValue_opAssign_double_Generic(), CScriptDictValue_opAssign_Generic(), CScriptDictValue_opAssign_int64_Generic(), CScriptDictValue_opCopyAssign_Generic(), and RegisterScriptDictionary_Native().
CScriptDictValue_opAssign_double_Generic()
static void CScriptDictValue_opAssign_double_Generic (asIScriptGeneric * gen) [static]
Definition at line 1016 of file scriptdictionary.cpp.
References CScriptDictValue_opAssign().
Referenced by RegisterScriptDictionary_Generic().
CScriptDictValue_opAssign_Generic()
static void CScriptDictValue_opAssign_Generic (asIScriptGeneric * gen) [static]
Definition at line 1022 of file scriptdictionary.cpp.
References CScriptDictValue_opAssign().
Referenced by RegisterScriptDictionary_Generic().
CScriptDictValue_opAssign_int64_Generic()
static void CScriptDictValue_opAssign_int64_Generic (asIScriptGeneric * gen) [static]
Definition at line 1010 of file scriptdictionary.cpp.
References CScriptDictValue_opAssign().
Referenced by RegisterScriptDictionary_Generic().
CScriptDictValue_opCast()
static void CScriptDictValue_opCast (void * ref, int typeId, CScriptDictValue * obj) [static]
Definition at line 961 of file scriptdictionary.cpp.
References CScriptDictValue::Get().
Referenced by CScriptDictValue_opConvDouble(), CScriptDictValue_opConvInt(), and RegisterScriptDictionary_Native().
CScriptDictValue_opCast_Generic()
static void CScriptDictValue_opCast_Generic (asIScriptGeneric * gen) [static]
Definition at line 1004 of file scriptdictionary.cpp.
References CScriptDictValue::Get().
Referenced by RegisterScriptDictionary_Generic().
CScriptDictValue_opConvDouble()
static double CScriptDictValue_opConvDouble (CScriptDictValue * obj) [static]
Definition at line 978 of file scriptdictionary.cpp.
References CScriptDictValue_opCast().
Referenced by RegisterScriptDictionary_Native().
CScriptDictValue_opConvDouble_Generic()
static void CScriptDictValue_opConvDouble_Generic (asIScriptGeneric * gen) [static]
Definition at line 988 of file scriptdictionary.cpp.
References CScriptDictValue::Get().
Referenced by RegisterScriptDictionary_Generic().
CScriptDictValue_opConvInt()
static asINT64 CScriptDictValue_opConvInt (CScriptDictValue * obj) [static]
Definition at line 971 of file scriptdictionary.cpp.
References CScriptDictValue_opCast().
Referenced by RegisterScriptDictionary_Native().
CScriptDictValue_opConvInt_Generic()
static void CScriptDictValue_opConvInt_Generic (asIScriptGeneric * gen) [static]
Definition at line 996 of file scriptdictionary.cpp.
References CScriptDictValue::Get().
Referenced by RegisterScriptDictionary_Generic().
CScriptDictValue_opCopyAssign_Generic()
static void CScriptDictValue_opCopyAssign_Generic (asIScriptGeneric * gen) [static]
Definition at line 1028 of file scriptdictionary.cpp.
References CScriptDictValue_opAssign().
Referenced by RegisterScriptDictionary_Generic().
RegisterScriptDictionary()
void RegisterScriptDictionary (asIScriptEngine * engine)
Definition at line 1061 of file scriptdictionary.cpp.
References RegisterScriptDictionary_Generic(), and RegisterScriptDictionary_Native().
RegisterScriptDictionary_Generic()
void RegisterScriptDictionary_Generic (asIScriptEngine * engine)
Definition at line 1148 of file scriptdictionary.cpp.
References SDictionaryCache::Cleanup(), CScriptDictionary_opIndex_const_Generic(), CScriptDictionary_opIndex_Generic(), CScriptDictionaryGetKeys_Generic(), CScriptDictValue_Construct_Generic(), CScriptDictValue_Destruct_Generic(), CScriptDictValue_EnumReferences_Generic(), CScriptDictValue_FreeValue_Generic(), CScriptDictValue_opAssign_double_Generic(), CScriptDictValue_opAssign_Generic(), CScriptDictValue_opAssign_int64_Generic(), CScriptDictValue_opCast_Generic(), CScriptDictValue_opConvDouble_Generic(), CScriptDictValue_opConvInt_Generic(), CScriptDictValue_opCopyAssign_Generic(), DICTIONARY_CACHE, ScriptDictionaryAddRef_Generic(), ScriptDictionaryAssign_Generic(), ScriptDictionaryDelete_Generic(), ScriptDictionaryDeleteAll_Generic(), ScriptDictionaryEnumReferences_Generic(), ScriptDictionaryExists_Generic(), ScriptDictionaryFactory_Generic(), ScriptDictionaryGet_Generic(), ScriptDictionaryGetFlt_Generic(), ScriptDictionaryGetGCFlag_Generic(), ScriptDictionaryGetInt_Generic(), ScriptDictionaryGetRefCount_Generic(), ScriptDictionaryGetSize_Generic(), ScriptDictionaryIsEmpty_Generic(), ScriptDictionaryListFactory_Generic(), ScriptDictionaryRelease_Generic(), ScriptDictionaryReleaseAllReferences_Generic(), ScriptDictionarySet_Generic(), ScriptDictionarySetFlt_Generic(), ScriptDictionarySetGCFlag_Generic(), ScriptDictionarySetInt_Generic(), and SDictionaryCache::Setup().
Referenced by RegisterScriptDictionary().
RegisterScriptDictionary_Native()
void RegisterScriptDictionary_Native (asIScriptEngine * engine)
Definition at line 1069 of file scriptdictionary.cpp.
References CScriptDictValue_Construct(), CScriptDictValue_Destruct(), CScriptDictValue_opAssign(), CScriptDictValue_opCast(), CScriptDictValue_opConvDouble(), CScriptDictValue_opConvInt(), ScriptDictionaryFactory_Generic(), ScriptDictionaryListFactory_Generic(), and SDictionaryCache::Setup().
Referenced by RegisterScriptDictionary().
ScriptDictionaryAddRef_Generic()
void ScriptDictionaryAddRef_Generic (asIScriptGeneric * gen)
Definition at line 453 of file scriptdictionary.cpp.
References CScriptDictionary::AddRef().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionaryAssign_Generic()
void ScriptDictionaryAssign_Generic (asIScriptGeneric * gen)
Definition at line 465 of file scriptdictionary.cpp.
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionaryDelete_Generic()
void ScriptDictionaryDelete_Generic (asIScriptGeneric * gen)
Definition at line 545 of file scriptdictionary.cpp.
References CScriptDictionary::Delete().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionaryDeleteAll_Generic()
void ScriptDictionaryDeleteAll_Generic (asIScriptGeneric * gen)
Definition at line 552 of file scriptdictionary.cpp.
References CScriptDictionary::DeleteAll().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionaryEnumReferences_Generic()
static void ScriptDictionaryEnumReferences_Generic (asIScriptGeneric * gen) [static]
Definition at line 576 of file scriptdictionary.cpp.
References CScriptDictionary::EnumReferences().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionaryExists_Generic()
void ScriptDictionaryExists_Generic (asIScriptGeneric * gen)
Definition at line 523 of file scriptdictionary.cpp.
References CScriptDictionary::Exists().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionaryFactory_Generic()
void ScriptDictionaryFactory_Generic (asIScriptGeneric * gen)
Definition at line 442 of file scriptdictionary.cpp.
References CScriptDictionary::Create().
Referenced by RegisterScriptDictionary_Generic(), and RegisterScriptDictionary_Native().
ScriptDictionaryGet_Generic()
void ScriptDictionaryGet_Generic (asIScriptGeneric * gen)
Definition at line 498 of file scriptdictionary.cpp.
References CScriptDictionary::Get().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionaryGetFlt_Generic()
void ScriptDictionaryGetFlt_Generic (asIScriptGeneric * gen)
Definition at line 515 of file scriptdictionary.cpp.
References CScriptDictionary::Get().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionaryGetGCFlag_Generic()
static void ScriptDictionaryGetGCFlag_Generic (asIScriptGeneric * gen) [static]
Definition at line 570 of file scriptdictionary.cpp.
References CScriptDictionary::GetGCFlag().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionaryGetInt_Generic()
void ScriptDictionaryGetInt_Generic (asIScriptGeneric * gen)
Definition at line 507 of file scriptdictionary.cpp.
References CScriptDictionary::Get().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionaryGetRefCount_Generic()
static void ScriptDictionaryGetRefCount_Generic (asIScriptGeneric * gen) [static]
Definition at line 558 of file scriptdictionary.cpp.
References CScriptDictionary::GetRefCount().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionaryGetSize_Generic()
void ScriptDictionaryGetSize_Generic (asIScriptGeneric * gen)
Definition at line 538 of file scriptdictionary.cpp.
References CScriptDictionary::GetSize().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionaryIsEmpty_Generic()
void ScriptDictionaryIsEmpty_Generic (asIScriptGeneric * gen)
Definition at line 531 of file scriptdictionary.cpp.
References CScriptDictionary::IsEmpty().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionaryListFactory_Generic()
void ScriptDictionaryListFactory_Generic (asIScriptGeneric * gen)
Definition at line 447 of file scriptdictionary.cpp.
References CScriptDictionary::Create().
Referenced by RegisterScriptDictionary_Generic(), and RegisterScriptDictionary_Native().
ScriptDictionaryRelease_Generic()
void ScriptDictionaryRelease_Generic (asIScriptGeneric * gen)
Definition at line 459 of file scriptdictionary.cpp.
References CScriptDictionary::Release().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionaryReleaseAllReferences_Generic()
static void ScriptDictionaryReleaseAllReferences_Generic (asIScriptGeneric * gen) [static]
Definition at line 583 of file scriptdictionary.cpp.
References CScriptDictionary::ReleaseAllReferences().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionarySet_Generic()
void ScriptDictionarySet_Generic (asIScriptGeneric * gen)
Definition at line 473 of file scriptdictionary.cpp.
References CScriptDictionary::Set().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionarySetFlt_Generic()
void ScriptDictionarySetFlt_Generic (asIScriptGeneric * gen)
Definition at line 490 of file scriptdictionary.cpp.
References CScriptDictionary::Set().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionarySetGCFlag_Generic()
static void ScriptDictionarySetGCFlag_Generic (asIScriptGeneric * gen) [static]
Definition at line 564 of file scriptdictionary.cpp.
References CScriptDictionary::SetGCFlag().
Referenced by RegisterScriptDictionary_Generic().
ScriptDictionarySetInt_Generic()
void ScriptDictionarySetInt_Generic (asIScriptGeneric * gen)
Definition at line 482 of file scriptdictionary.cpp.
References CScriptDictionary::Set().
Referenced by RegisterScriptDictionary_Generic().
Variable Documentation
DICTIONARY_CACHE
const asPWORD DICTIONARY_CACHE = 1003
Definition at line 16 of file scriptdictionary.cpp.
Referenced by SDictionaryCache::Cleanup(), RegisterScriptDictionary_Generic(), and SDictionaryCache::Setup().