C:/Dev/Techstorm-v5/src/application/add_on/scripthandle/scripthandle.cpp File Reference
#include "scripthandle.h"
#include <new>
#include <assert.h>
#include <string.h>
Functions
static BEGIN_AS_NAMESPACE void Construct (CScriptHandle *self)
static void Construct (CScriptHandle *self, const CScriptHandle &o)
void Construct (CScriptHandle *self, void *ref, int typeId)
static void Destruct (CScriptHandle *self)
void RegisterScriptHandle_Native (asIScriptEngine *engine)
void CScriptHandle_Construct_Generic (asIScriptGeneric *gen)
void CScriptHandle_ConstructCopy_Generic (asIScriptGeneric *gen)
void CScriptHandle_ConstructVar_Generic (asIScriptGeneric *gen)
void CScriptHandle_Destruct_Generic (asIScriptGeneric *gen)
void CScriptHandle_Cast_Generic (asIScriptGeneric *gen)
void CScriptHandle_Assign_Generic (asIScriptGeneric *gen)
void CScriptHandle_AssignVar_Generic (asIScriptGeneric *gen)
void CScriptHandle_Equals_Generic (asIScriptGeneric *gen)
void CScriptHandle_EqualsVar_Generic (asIScriptGeneric *gen)
void CScriptHandle_EnumReferences_Generic (asIScriptGeneric *gen)
void CScriptHandle_ReleaseReferences_Generic (asIScriptGeneric *gen)
void RegisterScriptHandle_Generic (asIScriptEngine *engine)
void RegisterScriptHandle (asIScriptEngine *engine)
Function Documentation
Construct() [1/3]
static BEGIN_AS_NAMESPACE void Construct (CScriptHandle * self) [static]
Definition at line 8 of file scripthandle.cpp.
Referenced by CScriptHandle_ConstructVar_Generic(), and RegisterScriptHandle_Native().
Construct() [2/3]
static void Construct (CScriptHandle * self, const CScriptHandle & o) [static]
Definition at line 9 of file scripthandle.cpp.
Construct() [3/3]
void Construct (CScriptHandle * self, void * ref, int typeId)
Definition at line 11 of file scripthandle.cpp.
CScriptHandle_Assign_Generic()
void CScriptHandle_Assign_Generic (asIScriptGeneric * gen)
Definition at line 289 of file scripthandle.cpp.
Referenced by RegisterScriptHandle_Generic().
CScriptHandle_AssignVar_Generic()
void CScriptHandle_AssignVar_Generic (asIScriptGeneric * gen)
Definition at line 297 of file scripthandle.cpp.
Referenced by RegisterScriptHandle_Generic().
CScriptHandle_Cast_Generic()
void CScriptHandle_Cast_Generic (asIScriptGeneric * gen)
Definition at line 281 of file scripthandle.cpp.
References CScriptHandle::Cast().
Referenced by RegisterScriptHandle_Generic().
CScriptHandle_Construct_Generic()
void CScriptHandle_Construct_Generic (asIScriptGeneric * gen)
Definition at line 254 of file scripthandle.cpp.
Referenced by RegisterScriptHandle_Generic().
CScriptHandle_ConstructCopy_Generic()
void CScriptHandle_ConstructCopy_Generic (asIScriptGeneric * gen)
Definition at line 260 of file scripthandle.cpp.
Referenced by RegisterScriptHandle_Generic().
CScriptHandle_ConstructVar_Generic()
void CScriptHandle_ConstructVar_Generic (asIScriptGeneric * gen)
Definition at line 267 of file scripthandle.cpp.
References Construct().
Referenced by RegisterScriptHandle_Generic().
CScriptHandle_Destruct_Generic()
void CScriptHandle_Destruct_Generic (asIScriptGeneric * gen)
Definition at line 275 of file scripthandle.cpp.
References CScriptHandle::~CScriptHandle().
Referenced by RegisterScriptHandle_Generic().
CScriptHandle_EnumReferences_Generic()
void CScriptHandle_EnumReferences_Generic (asIScriptGeneric * gen)
Definition at line 321 of file scripthandle.cpp.
References CScriptHandle::EnumReferences().
Referenced by RegisterScriptHandle_Generic().
CScriptHandle_Equals_Generic()
void CScriptHandle_Equals_Generic (asIScriptGeneric * gen)
Definition at line 306 of file scripthandle.cpp.
Referenced by RegisterScriptHandle_Generic().
CScriptHandle_EqualsVar_Generic()
void CScriptHandle_EqualsVar_Generic (asIScriptGeneric * gen)
Definition at line 313 of file scripthandle.cpp.
References CScriptHandle::Equals().
Referenced by RegisterScriptHandle_Generic().
CScriptHandle_ReleaseReferences_Generic()
void CScriptHandle_ReleaseReferences_Generic (asIScriptGeneric * gen)
Definition at line 327 of file scripthandle.cpp.
References CScriptHandle::ReleaseReferences().
Referenced by RegisterScriptHandle_Generic().
Destruct()
static void Destruct (CScriptHandle * self) [static]
Definition at line 12 of file scripthandle.cpp.
References CScriptHandle::~CScriptHandle().
Referenced by RegisterScriptHandle_Native().
RegisterScriptHandle()
void RegisterScriptHandle (asIScriptEngine * engine)
Definition at line 351 of file scripthandle.cpp.
References RegisterScriptHandle_Generic(), and RegisterScriptHandle_Native().
RegisterScriptHandle_Generic()
void RegisterScriptHandle_Generic (asIScriptEngine * engine)
Definition at line 333 of file scripthandle.cpp.
References CScriptHandle_Assign_Generic(), CScriptHandle_AssignVar_Generic(), CScriptHandle_Cast_Generic(), CScriptHandle_Construct_Generic(), CScriptHandle_ConstructCopy_Generic(), CScriptHandle_ConstructVar_Generic(), CScriptHandle_Destruct_Generic(), CScriptHandle_EnumReferences_Generic(), CScriptHandle_Equals_Generic(), CScriptHandle_EqualsVar_Generic(), and CScriptHandle_ReleaseReferences_Generic().
Referenced by RegisterScriptHandle().
RegisterScriptHandle_Native()
void RegisterScriptHandle_Native (asIScriptEngine * engine)
Definition at line 231 of file scripthandle.cpp.
Referenced by RegisterScriptHandle().