C:/Dev/Techstorm-v5/src/bindings/imgui_impl_dx11.cpp File Reference
#include "imgui.h"
#include "imgui_impl_dx11.h"
#include <stdio.h>
#include <d3d11.h>
#include <d3dcompiler.h>
Classes
struct ImGui_ImplDX11_Data
struct VERTEX_CONSTANT_BUFFER_DX11
Functions
void ImGui_ImplDX11_RenderDrawData (ImDrawData *draw_data)
bool ImGui_ImplDX11_CreateDeviceObjects ()
void ImGui_ImplDX11_InvalidateDeviceObjects ()
bool ImGui_ImplDX11_Init (ID3D11Device *device, ID3D11DeviceContext *device_context)
void ImGui_ImplDX11_Shutdown ()
void ImGui_ImplDX11_NewFrame ()
Function Documentation
ImGui_ImplDX11_CreateDeviceObjects()
bool ImGui_ImplDX11_CreateDeviceObjects ()
Definition at line 385 of file imgui_impl_dx11.cpp.
References ImGui_ImplDX11_InvalidateDeviceObjects(), ImGui_ImplDX11_Data::pBlendState, ImGui_ImplDX11_Data::pd3dDevice, ImGui_ImplDX11_Data::pDepthStencilState, ImGui_ImplDX11_Data::pFontSampler, ImGui_ImplDX11_Data::pInputLayout, ImGui_ImplDX11_Data::pPixelShader, ImGui_ImplDX11_Data::pRasterizerState, ImGui_ImplDX11_Data::pVertexConstantBuffer, and ImGui_ImplDX11_Data::pVertexShader.
Referenced by ImGui_ImplDX11_NewFrame().
ImGui_ImplDX11_Init()
bool ImGui_ImplDX11_Init (ID3D11Device * device, ID3D11DeviceContext * device_context)
Definition at line 558 of file imgui_impl_dx11.cpp.
References ImGui_ImplDX11_Data::pd3dDevice, ImGui_ImplDX11_Data::pd3dDeviceContext, and ImGui_ImplDX11_Data::pFactory.
ImGui_ImplDX11_InvalidateDeviceObjects()
void ImGui_ImplDX11_InvalidateDeviceObjects ()
Definition at line 539 of file imgui_impl_dx11.cpp.
References ImGui_ImplDX11_Data::pBlendState, ImGui_ImplDX11_Data::pd3dDevice, ImGui_ImplDX11_Data::pDepthStencilState, ImGui_ImplDX11_Data::pFontSampler, ImGui_ImplDX11_Data::pFontTextureView, ImGui_ImplDX11_Data::pIB, ImGui_ImplDX11_Data::pInputLayout, ImGui_ImplDX11_Data::pPixelShader, ImGui_ImplDX11_Data::pRasterizerState, ImGui_ImplDX11_Data::pVB, ImGui_ImplDX11_Data::pVertexConstantBuffer, and ImGui_ImplDX11_Data::pVertexShader.
Referenced by ImGui_ImplDX11_CreateDeviceObjects(), and ImGui_ImplDX11_Shutdown().
ImGui_ImplDX11_NewFrame()
void ImGui_ImplDX11_NewFrame ()
Definition at line 607 of file imgui_impl_dx11.cpp.
References ImGui_ImplDX11_CreateDeviceObjects(), and ImGui_ImplDX11_Data::pFontSampler.
ImGui_ImplDX11_RenderDrawData()
void ImGui_ImplDX11_RenderDrawData (ImDrawData * draw_data)
Definition at line 125 of file imgui_impl_dx11.cpp.
References ImGui_ImplDX11_RenderState::Device, ImGui_ImplDX11_RenderState::DeviceContext, ImGui_ImplDX11_Data::IndexBufferSize, VERTEX_CONSTANT_BUFFER_DX11::mvp, ImGui_ImplDX11_Data::pd3dDevice, ImGui_ImplDX11_Data::pd3dDeviceContext, ImGui_ImplDX11_Data::pFontSampler, ImGui_ImplDX11_Data::pIB, ImGui_ImplDX11_Data::pVB, ImGui_ImplDX11_Data::pVertexConstantBuffer, ImGui_ImplDX11_RenderState::SamplerDefault, and ImGui_ImplDX11_Data::VertexBufferSize.
ImGui_ImplDX11_Shutdown()
void ImGui_ImplDX11_Shutdown ()
Definition at line 591 of file imgui_impl_dx11.cpp.
References ImGui_ImplDX11_InvalidateDeviceObjects(), ImGui_ImplDX11_Data::pd3dDevice, ImGui_ImplDX11_Data::pd3dDeviceContext, and ImGui_ImplDX11_Data::pFactory.