C:/Dev/Techstorm-v5/src/bindings/imgui_impl_metal.mm File Reference
#include "imgui.h"
#include "imgui_impl_metal.h"
import <time.h>
import <Metal/Metal.h>
Classes
class MetalBuffer
class FramebufferDescriptor
class MetalContext
struct ImGui_ImplMetal_Data
Functions
static ImGui_ImplMetal_Data * ImGui_ImplMetal_GetBackendData ()
static void ImGui_ImplMetal_DestroyBackendData ()
static CFTimeInterval GetMachAbsoluteTimeInSeconds ()
bool ImGui_ImplMetal_Init (id< MTLDevice > device)
void ImGui_ImplMetal_Shutdown ()
void ImGui_ImplMetal_NewFrame (MTLRenderPassDescriptor *renderPassDescriptor)
static void ImGui_ImplMetal_SetupRenderState (ImDrawData *drawData, id< MTLCommandBuffer > commandBuffer, id< MTLRenderCommandEncoder > commandEncoder, id< MTLRenderPipelineState > renderPipelineState, MetalBuffer *vertexBuffer, size_t vertexBufferOffset)
void ImGui_ImplMetal_RenderDrawData (ImDrawData *drawData, id< MTLCommandBuffer > commandBuffer, id< MTLRenderCommandEncoder > commandEncoder)
bool ImGui_ImplMetal_CreateFontsTexture (id< MTLDevice > device)
void ImGui_ImplMetal_DestroyFontsTexture ()
bool ImGui_ImplMetal_CreateDeviceObjects (id< MTLDevice > device)
void ImGui_ImplMetal_DestroyDeviceObjects ()
Function Documentation
GetMachAbsoluteTimeInSeconds()
static CFTimeInterval GetMachAbsoluteTimeInSeconds () [inline], [static]
Definition at line 85 of file imgui_impl_metal.mm.
ImGui_ImplMetal_CreateDeviceObjects()
bool ImGui_ImplMetal_CreateDeviceObjects (id< MTLDevice > device)
Definition at line 363 of file imgui_impl_metal.mm.
References MetalContext::depthStencilState, ImGui_ImplMetal_CreateFontsTexture(), ImGui_ImplMetal_GetBackendData(), and ImGui_ImplMetal_Data::SharedMetalContext.
Referenced by ImGui_ImplMetal_NewFrame().
ImGui_ImplMetal_CreateFontsTexture()
bool ImGui_ImplMetal_CreateFontsTexture (id< MTLDevice > device)
Definition at line 325 of file imgui_impl_metal.mm.
References MetalContext::fontTexture, ImGui_ImplMetal_GetBackendData(), and ImGui_ImplMetal_Data::SharedMetalContext.
Referenced by ImGui_ImplMetal_CreateDeviceObjects().
ImGui_ImplMetal_DestroyBackendData()
static void ImGui_ImplMetal_DestroyBackendData () [static]
Definition at line 83 of file imgui_impl_metal.mm.
References ImGui_ImplMetal_GetBackendData().
Referenced by ImGui_ImplMetal_Shutdown().
ImGui_ImplMetal_DestroyDeviceObjects()
void ImGui_ImplMetal_DestroyDeviceObjects ()
Definition at line 375 of file imgui_impl_metal.mm.
References ImGui_ImplMetal_DestroyFontsTexture(), and ImGui_ImplMetal_GetBackendData().
Referenced by ImGui_ImplMetal_Shutdown().
ImGui_ImplMetal_DestroyFontsTexture()
void ImGui_ImplMetal_DestroyFontsTexture ()
Definition at line 355 of file imgui_impl_metal.mm.
References MetalContext::fontTexture, ImGui_ImplMetal_GetBackendData(), and ImGui_ImplMetal_Data::SharedMetalContext.
Referenced by ImGui_ImplMetal_DestroyDeviceObjects().
ImGui_ImplMetal_GetBackendData()
static ImGui_ImplMetal_Data * ImGui_ImplMetal_GetBackendData () [static]
Definition at line 82 of file imgui_impl_metal.mm.
Referenced by ImGui_ImplMetal_CreateDeviceObjects(), ImGui_ImplMetal_CreateFontsTexture(), ImGui_ImplMetal_DestroyBackendData(), ImGui_ImplMetal_DestroyDeviceObjects(), ImGui_ImplMetal_DestroyFontsTexture(), ImGui_ImplMetal_NewFrame(), ImGui_ImplMetal_RenderDrawData(), ImGui_ImplMetal_SetupRenderState(), and ImGui_ImplMetal_Shutdown().
ImGui_ImplMetal_Init()
bool ImGui_ImplMetal_Init (id< MTLDevice > device)
Definition at line 125 of file imgui_impl_metal.mm.
References MetalContext::device, and ImGui_ImplMetal_Data::SharedMetalContext.
ImGui_ImplMetal_NewFrame()
void ImGui_ImplMetal_NewFrame (MTLRenderPassDescriptor * renderPassDescriptor)
Definition at line 155 of file imgui_impl_metal.mm.
References MetalContext::depthStencilState, MetalContext::device, MetalContext::framebufferDescriptor, ImGui_ImplMetal_CreateDeviceObjects(), ImGui_ImplMetal_GetBackendData(), and ImGui_ImplMetal_Data::SharedMetalContext.
ImGui_ImplMetal_RenderDrawData()
void ImGui_ImplMetal_RenderDrawData (ImDrawData * drawData, id< MTLCommandBuffer > commandBuffer, id< MTLRenderCommandEncoder > commandEncoder)
Definition at line 210 of file imgui_impl_metal.mm.
References MetalBuffer::buffer, MetalContext::dequeueReusableBufferOfLength:device:, MetalContext::framebufferDescriptor, ImGui_ImplMetal_GetBackendData(), ImGui_ImplMetal_SetupRenderState(), MetalContext::renderPipelineStateCache, MetalContext::renderPipelineStateForFramebufferDescriptor:device:, and ImGui_ImplMetal_Data::SharedMetalContext.
ImGui_ImplMetal_SetupRenderState()
static void ImGui_ImplMetal_SetupRenderState (ImDrawData * drawData, id< MTLCommandBuffer > commandBuffer, id< MTLRenderCommandEncoder > commandEncoder, id< MTLRenderPipelineState > renderPipelineState, MetalBuffer * vertexBuffer, size_t vertexBufferOffset) [static]
Definition at line 165 of file imgui_impl_metal.mm.
References ImGui_ImplMetal_GetBackendData().
Referenced by ImGui_ImplMetal_RenderDrawData().
ImGui_ImplMetal_Shutdown()
void ImGui_ImplMetal_Shutdown ()
Definition at line 142 of file imgui_impl_metal.mm.
References ImGui_ImplMetal_DestroyBackendData(), ImGui_ImplMetal_DestroyDeviceObjects(), and ImGui_ImplMetal_GetBackendData().