Atlas::AGlobalRenderingBackend< T_CHILD > Class Template Reference
#include <RenderingBackend.h>
Public Member Functions
virtual void init (AGameWindow *windowHandle) override
void setThisAsGlobalInstance ()
virtual void shutdown () override
RenderingBackend ()=default
Public Member Functions inherited from Atlas::RenderingBackend
RenderingBackend ()=default
virtual ~RenderingBackend ()
virtual void beginDrawing ()
virtual void draw ()
virtual void endDrawing ()
virtual void setAPIVersion (uint32_t major, uint32_t minor, uint32_t patch)
virtual void setAPIVersion (Version version)
virtual Version getAPIVersion () const
bool areDebuggingToolsEnabled () const
bool isErrorCheckingEnabled () const
template<typename T_CAST_TO >
T_CAST_TO * castAs ()
Static Public Member Functions
static std::shared_ptr< T_CHILD > GetGlobalInstance ()
static bool HasGlobalInstance ()
static void ClearGlobalInstance ()
Static Protected Member Functions
static void SetGlobalInstance (const std::shared_ptr< T_CHILD > &instance)
Static Protected Attributes
static std::shared_ptr< T_CHILD > sActiveInstanceTSSV {}
static std::shared_mutex sActiveInstanceMutex {}
Additional Inherited Members
Public Types inherited from Atlas::RenderingBackend
using APIVersion = Version
Protected Attributes inherited from Atlas::RenderingBackend
std::shared_ptr< State > mState
std::shared_mutex mStateMutex
Version mAPIVersion
bool mbIsInitialized = false
bool mbUseDebuggingTools = false
bool mbEnableErrorChecking = false
Detailed Description
template<typename T_CHILD>
class Atlas::AGlobalRenderingBackend< T_CHILD >
Definition at line 191 of file RenderingBackend.h.
Member Function Documentation
ClearGlobalInstance()
template<typename T_CHILD >
static void Atlas::AGlobalRenderingBackend< T_CHILD >::ClearGlobalInstance () [inline], [static]
Definition at line 213 of file RenderingBackend.h.
References Atlas::AGlobalRenderingBackend< T_CHILD >::sActiveInstanceTSSV.
Referenced by Atlas::AGlobalRenderingBackend< T_CHILD >::shutdown().
GetGlobalInstance()
template<typename T_CHILD >
static std::shared_ptr< T_CHILD > Atlas::AGlobalRenderingBackend< T_CHILD >::GetGlobalInstance () [inline], [static]
Definition at line 205 of file RenderingBackend.h.
References Atlas::AGlobalRenderingBackend< T_CHILD >::sActiveInstanceTSSV.
HasGlobalInstance()
template<typename T_CHILD >
static bool Atlas::AGlobalRenderingBackend< T_CHILD >::HasGlobalInstance () [inline], [static]
Definition at line 209 of file RenderingBackend.h.
References Atlas::AGlobalRenderingBackend< T_CHILD >::sActiveInstanceTSSV.
Referenced by Atlas::AGlobalRenderingBackend< T_CHILD >::init().
init()
template<typename T_CHILD >
virtual void Atlas::AGlobalRenderingBackend< T_CHILD >::init (AGameWindow * windowHandle) [inline], [override], [virtual]
Implements Atlas::RenderingBackend.
Definition at line 221 of file RenderingBackend.h.
References Atlas::ErrorLog(), Atlas::AGlobalRenderingBackend< T_CHILD >::HasGlobalInstance(), Atlas::RenderingBackend::init(), and Atlas::AGlobalRenderingBackend< T_CHILD >::setThisAsGlobalInstance().
RenderingBackend()
template<typename T_CHILD >
Atlas::RenderingBackend::RenderingBackend () [default]
SetGlobalInstance()
template<typename T_CHILD >
static void Atlas::AGlobalRenderingBackend< T_CHILD >::SetGlobalInstance (const std::shared_ptr< T_CHILD > & instance) [inline], [static], [protected]
Definition at line 196 of file RenderingBackend.h.
References Atlas::AGlobalRenderingBackend< T_CHILD >::sActiveInstanceTSSV.
Referenced by Atlas::AGlobalRenderingBackend< T_CHILD >::setThisAsGlobalInstance().
setThisAsGlobalInstance()
template<typename T_CHILD >
void Atlas::AGlobalRenderingBackend< T_CHILD >::setThisAsGlobalInstance () [inline]
Definition at line 233 of file RenderingBackend.h.
References Atlas::AGlobalRenderingBackend< T_CHILD >::SetGlobalInstance().
Referenced by Atlas::AGlobalRenderingBackend< T_CHILD >::init().
shutdown()
template<typename T_CHILD >
virtual void Atlas::AGlobalRenderingBackend< T_CHILD >::shutdown () [inline], [override], [virtual]
Reimplemented from Atlas::RenderingBackend.
Definition at line 237 of file RenderingBackend.h.
References Atlas::AGlobalRenderingBackend< T_CHILD >::ClearGlobalInstance(), and Atlas::RenderingBackend::shutdown().
Member Data Documentation
sActiveInstanceMutex
template<typename T_CHILD >
std::shared_mutex Atlas::AGlobalRenderingBackend< T_CHILD >::sActiveInstanceMutex {} [inline], [static], [protected]
Definition at line 194 of file RenderingBackend.h.
sActiveInstanceTSSV
template<typename T_CHILD >
std::shared_ptr<T_CHILD> Atlas::AGlobalRenderingBackend< T_CHILD >::sActiveInstanceTSSV {} [inline], [static], [protected]
Definition at line 193 of file RenderingBackend.h.
Referenced by Atlas::AGlobalRenderingBackend< T_CHILD >::ClearGlobalInstance(), Atlas::AGlobalRenderingBackend< T_CHILD >::GetGlobalInstance(), Atlas::AGlobalRenderingBackend< T_CHILD >::HasGlobalInstance(), and Atlas::AGlobalRenderingBackend< T_CHILD >::SetGlobalInstance().
The documentation for this class was generated from the following file:
C:/Dev/Techstorm-v5/src/engine/graphics/backend/RenderingBackend.h