Atlas::Application::AtlasApp Class Reference
#include <AtlasApp.h>
Public Member Functions
AtlasApp ()
Private Member Functions
void prepareProject ()
void initConfig ()
void initWindow (WindowDecorations &decorations)
void initScripting ()
void handleFrame (PROJECT_TYPENAME &project)
Private Attributes
PROJECT_TYPENAME mProject = PROJECT_TYPENAME()
ScriptingAPI * mScriptingAPI = nullptr
Detailed Description
Definition at line 6 of file AtlasApp.h.
Constructor & Destructor Documentation
AtlasApp()
Atlas::Application::AtlasApp::AtlasApp () [inline]
Definition at line 8 of file AtlasApp.h.
Member Function Documentation
handleFrame()
void Atlas::Application::AtlasApp::handleFrame (PROJECT_TYPENAME & project) [inline], [private]
Definition at line 49 of file AtlasApp.h.
References ATLAS_THREAD_YIELD.
initConfig()
void Atlas::Application::AtlasApp::initConfig () [inline], [private]
Definition at line 22 of file AtlasApp.h.
initScripting()
void Atlas::Application::AtlasApp::initScripting () [inline], [private]
Definition at line 43 of file AtlasApp.h.
References mProject, and mScriptingAPI.
initWindow()
void Atlas::Application::AtlasApp::initWindow (WindowDecorations & decorations) [inline], [private]
Definition at line 26 of file AtlasApp.h.
References ATLAS_ASSET_DIR, Atlas::WindowDecorations::height, Atlas::WindowDecorations::icon, Atlas::Log(), Atlas::LookupConfig(), Atlas::WindowDecorations::title, and Atlas::WindowDecorations::width.
prepareProject()
void Atlas::Application::AtlasApp::prepareProject () [inline], [private]
Definition at line 15 of file AtlasApp.h.
References Atlas::Log(), and mProject.
Member Data Documentation
mProject
PROJECT_TYPENAME Atlas::Application::AtlasApp::mProject = PROJECT_TYPENAME() [private]
Definition at line 12 of file AtlasApp.h.
Referenced by initScripting(), and prepareProject().
mScriptingAPI
ScriptingAPI* Atlas::Application::AtlasApp::mScriptingAPI = nullptr [private]
Definition at line 13 of file AtlasApp.h.
Referenced by initScripting().
The documentation for this class was generated from the following file:
C:/Dev/Techstorm-v5/src/application/AtlasApp.h