C:/Dev/Techstorm-v5/src/engine/modding/add_on/scriptstdstring/scriptstdstring_utils.cpp File Reference
#include <assert.h>
#include "scriptstdstring.h"
#include "../scriptarray/scriptarray.h"
#include <stdio.h>
#include <string.h>
Functions
static BEGIN_AS_NAMESPACE CScriptArray * StringSplit (const string &delim, const string &str)
static void StringSplit_Generic (asIScriptGeneric *gen)
static string StringJoin (const CScriptArray &array, const string &delim)
static void StringJoin_Generic (asIScriptGeneric *gen)
void RegisterStdStringUtils (asIScriptEngine *engine)
Function Documentation
RegisterStdStringUtils()
void RegisterStdStringUtils (asIScriptEngine * engine)
Definition at line 114 of file scriptstdstring_utils.cpp.
References StringJoin(), StringJoin_Generic(), StringSplit(), and StringSplit_Generic().
StringJoin()
static string StringJoin (const CScriptArray & array, const string & delim) [static]
Definition at line 82 of file scriptstdstring_utils.cpp.
References CScriptArray::At(), and CScriptArray::GetSize().
Referenced by RegisterStdStringUtils(), and StringJoin_Generic().
StringJoin_Generic()
static void StringJoin_Generic (asIScriptGeneric * gen) [static]
Definition at line 102 of file scriptstdstring_utils.cpp.
References StringJoin().
Referenced by RegisterStdStringUtils().
StringSplit()
static BEGIN_AS_NAMESPACE CScriptArray * StringSplit (const string & delim, const string & str) [static]
Definition at line 23 of file scriptstdstring_utils.cpp.
References CScriptArray::At(), CScriptArray::Create(), CScriptArray::GetSize(), and CScriptArray::Resize().
Referenced by RegisterStdStringUtils(), and StringSplit_Generic().
StringSplit_Generic()
static void StringSplit_Generic (asIScriptGeneric * gen) [static]
Definition at line 57 of file scriptstdstring_utils.cpp.
References StringSplit().
Referenced by RegisterStdStringUtils().