Atlas::MemoryCounter Class Reference
#include <MemoryCounter.h>
Public Member Functions
MemoryCounter (const size_t cMaxMemoryUsageInBytes)
size_t getMaxMemoryUsage () const
size_t getCurrentMemoryUsage () const
bool isMemoryUsageExceeded () const
bool isMemoryUsageWithinBounds () const
bool willMemoryUsageExceed (const size_t cIncrement) const
void setCurrentMemoryUsage (const size_t cCurrentMemoryUsageInBytes)
void incrementCurrentMemoryUsage (const size_t cIncrement)
void decrementCurrentMemoryUsage (const size_t cDecrement)
void reset ()
MemoryCounter & operator= (const MemoryCounter &other)
MemoryCounter & operator++ ()
MemoryCounter operator++ (int)
MemoryCounter & operator-- ()
MemoryCounter operator-- (int)
size_t operator+= (const size_t cIncrement)
Private Attributes
const size_t mMemoryCap
size_t mCurrentMemoryUsageInBytes
Detailed Description
Definition at line 4 of file MemoryCounter.h.
Constructor & Destructor Documentation
MemoryCounter()
Atlas::MemoryCounter::MemoryCounter (const size_t cMaxMemoryUsageInBytes) [explicit]
Definition at line 3 of file MemoryCounter.cpp.
Member Function Documentation
decrementCurrentMemoryUsage()
void Atlas::MemoryCounter::decrementCurrentMemoryUsage (const size_t cDecrement)
Definition at line 40 of file MemoryCounter.cpp.
Referenced by operator--(), and operator--().
getCurrentMemoryUsage()
size_t Atlas::MemoryCounter::getCurrentMemoryUsage () const
Definition at line 11 of file MemoryCounter.cpp.
getMaxMemoryUsage()
size_t Atlas::MemoryCounter::getMaxMemoryUsage () const
Definition at line 7 of file MemoryCounter.cpp.
incrementCurrentMemoryUsage()
void Atlas::MemoryCounter::incrementCurrentMemoryUsage (const size_t cIncrement)
Definition at line 32 of file MemoryCounter.cpp.
Referenced by operator++(), operator++(), and operator+=().
isMemoryUsageExceeded()
bool Atlas::MemoryCounter::isMemoryUsageExceeded () const
Definition at line 15 of file MemoryCounter.cpp.
isMemoryUsageWithinBounds()
bool Atlas::MemoryCounter::isMemoryUsageWithinBounds () const
Definition at line 19 of file MemoryCounter.cpp.
operator++() [1/2]
MemoryCounter & Atlas::MemoryCounter::operator++ () [inline]
Definition at line 39 of file MemoryCounter.h.
References incrementCurrentMemoryUsage().
operator++() [2/2]
MemoryCounter Atlas::MemoryCounter::operator++ (int) [inline]
Definition at line 44 of file MemoryCounter.h.
References incrementCurrentMemoryUsage().
operator+=()
size_t Atlas::MemoryCounter::operator+= (const size_t cIncrement) [inline]
Definition at line 62 of file MemoryCounter.h.
References incrementCurrentMemoryUsage(), and mCurrentMemoryUsageInBytes.
operator--() [1/2]
MemoryCounter & Atlas::MemoryCounter::operator-- () [inline]
Definition at line 51 of file MemoryCounter.h.
References decrementCurrentMemoryUsage().
operator--() [2/2]
MemoryCounter Atlas::MemoryCounter::operator-- (int) [inline]
Definition at line 56 of file MemoryCounter.h.
References decrementCurrentMemoryUsage().
operator=()
MemoryCounter & Atlas::MemoryCounter::operator= (const MemoryCounter & other) [inline]
Definition at line 33 of file MemoryCounter.h.
References mCurrentMemoryUsageInBytes.
reset()
void Atlas::MemoryCounter::reset ()
Definition at line 44 of file MemoryCounter.cpp.
setCurrentMemoryUsage()
void Atlas::MemoryCounter::setCurrentMemoryUsage (const size_t cCurrentMemoryUsageInBytes)
Definition at line 28 of file MemoryCounter.cpp.
willMemoryUsageExceed()
bool Atlas::MemoryCounter::willMemoryUsageExceed (const size_t cIncrement) const
Definition at line 24 of file MemoryCounter.cpp.
Member Data Documentation
mCurrentMemoryUsageInBytes
size_t Atlas::MemoryCounter::mCurrentMemoryUsageInBytes [private]
Definition at line 8 of file MemoryCounter.h.
Referenced by operator+=(), and operator=().
mMemoryCap
const size_t Atlas::MemoryCounter::mMemoryCap [private]
Definition at line 6 of file MemoryCounter.h.
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/core/MemoryCounter.h
C:/Dev/Techstorm-v5/src/engine/core/MemoryCounter.cpp