Atlas::FileManager Class Reference
As the name suggests, this non-copyable class is responsible for managing the files that Atlas and the user has loaded. This class has 3 main responsibilities (excluding the janitor): Loading, Unloading and Registering. Additionally, this class can be configured to ignore certain patterns it comes across during the file discovery process through the use of regex patterns.
#include <IOManager.h>
Classes
class FileJanitor
Automatically evicts unused files in a background thread and cleans up the mRecords map in the FileManager. Furthermore, this class also handles the janitor thread, which is where the janitor loop runs. This class is handled by the FileManager class. It is not recommended to use this class directly, and let the FileManager handle it. However, if you do infact need to use this class directly, please refer to the details section in the documentation below.
struct Options
Configuration options for the FileManager and its FileJanitor.
Public Member Functions
ATLAS_DISALLOW_COPY (FileManager)
FileManager (const Options &options=Options())
Initializes a new instance of the FileManager class with the specified configuration.
~FileManager ()
Destroys the current instance of the FileManager class.
void registerDirectory (const std::filesystem::path &dir)
Register a directory (recursively); applies ignore regexes.
void registerFile (const std::filesystem::path &p)
Register a file; applies ignore regexes. The file must exist.
void addIgnorePattern (const std::string &pattern)
Add an ignore pattern to the ignore list using ECMAScript regex. Files matching this pattern will not be loaded.
void removeIgnorePatterns ()
Remove all ignore patterns.
FileHandle openFile (const std::filesystem::path &p)
Open a file.
bool unloadFile (const std::filesystem::path &p)
An explicit unload function that unloads a file (forces if not in use).
size_t getRegisteredCount () const
Get the number of registered files. This can be used for debugging purposes.
void preloadAll ()
Preloads all registered files. This is an optional function, and it is extremely expensive.
void unloadAll ()
Unloads all files.
std::vector< std::filesystem::path > findRegistered (const std::regex &re) const
Finds all registered files that match the specified regex pattern.
Private Member Functions
bool isIgnored (const std::filesystem::path &p) const
Checks if a path should be ignored based on the ignore patterns.
Private Attributes
FileJanitor mJanitor
The janitor for this class.
std::shared_mutex mMapMutex
A shared mutex that is used to guard access to the mRecords map.
std::unordered_map< std::filesystem::path, std::shared_ptr< FileRecord > > mRecords
A map of registered files. This is guarded by mMapMutex.
Options mOptions
This class' configuration options.
std::mutex mIgnoreMutex
A mutex that is used to guard access to the mIgnorePatterns vector.
std::vector< std::regex > mIgnorePatterns
A vector of regex ignore patterns. This is guarded by mIgnoreMutex.
Friends
class FileJanitor
Detailed Description
As the name suggests, this non-copyable class is responsible for managing the files that Atlas and the user has loaded. This class has 3 main responsibilities (excluding the janitor): Loading, Unloading and Registering. Additionally, this class can be configured to ignore certain patterns it comes across during the file discovery process through the use of regex patterns.
Since
v0.0.1
Definition at line 158 of file IOManager.h.
Constructor & Destructor Documentation
FileManager()
Atlas::FileManager::FileManager (const Options & options = Options()) [explicit]
Initializes a new instance of the FileManager class with the specified configuration.
Parameters
options The configuration options for the file manager.
Since
v0.0.1
Definition at line 137 of file IOManager.cpp.
~FileManager()
Atlas::FileManager::~FileManager ()
Destroys the current instance of the FileManager class.
Since
v0.0.1
Definition at line 142 of file IOManager.cpp.
Member Function Documentation
addIgnorePattern()
void Atlas::FileManager::addIgnorePattern (const std::string & pattern)
Add an ignore pattern to the ignore list using ECMAScript regex. Files matching this pattern will not be loaded.
Parameters
pattern A ECMAScript regex pattern.
Since
v0.0.1
Definition at line 199 of file IOManager.cpp.
ATLAS_DISALLOW_COPY()
Atlas::FileManager::ATLAS_DISALLOW_COPY (FileManager)
findRegistered()
std::vector< std::filesystem::path > Atlas::FileManager::findRegistered (const std::regex & re) const
Finds all registered files that match the specified regex pattern.
Parameters
re An ECMAScript regex pattern to use for searching.
Returns
std::vector<std::filesystem::path> A vector of paths that match the pattern.
Since
v0.0.1
Definition at line 343 of file IOManager.cpp.
getRegisteredCount()
size_t Atlas::FileManager::getRegisteredCount () const
Get the number of registered files. This can be used for debugging purposes.
Returns
size_t The number of registered files.
Since
v0.0.1
Definition at line 307 of file IOManager.cpp.
Referenced by main().
isIgnored()
bool Atlas::FileManager::isIgnored (const std::filesystem::path & p) const [private]
Checks if a path should be ignored based on the ignore patterns.
Parameters
p
Returns
Since
v
Definition at line 355 of file IOManager.cpp.
openFile()
Atlas::FileHandle Atlas::FileManager::openFile (const std::filesystem::path & p)
Open a file.
Parameters
p The path to the file that should be opened.
Warning
Do not discard the return value! It keeps the file loaded while alive.
Returns
shared_ptr<FileData> This return value keeps the file loaded while alive.
Since
v0.0.1
Definition at line 209 of file IOManager.cpp.
References Atlas::GetAbsolutePath().
Referenced by main().
preloadAll()
void Atlas::FileManager::preloadAll ()
Preloads all registered files. This is an optional function, and it is extremely expensive.
Note
As an edge case, this could be used to measure loading times.
Since
v0.0.1
Definition at line 312 of file IOManager.cpp.
registerDirectory()
void Atlas::FileManager::registerDirectory (const std::filesystem::path & dir)
Register a directory (recursively); applies ignore regexes.
Parameters
dir The directory to register.
Since
v0.0.1
Definition at line 149 of file IOManager.cpp.
References ATLAS_ASSERT, Atlas::DoesPathExist(), and Atlas::InfoLog().
Referenced by main().
registerFile()
void Atlas::FileManager::registerFile (const std::filesystem::path & p)
Register a file; applies ignore regexes. The file must exist.
Parameters
p The file to register.
Since
v0.0.1
Definition at line 184 of file IOManager.cpp.
References Atlas::GetAbsolutePath(), and Atlas::InfoLog().
removeIgnorePatterns()
void Atlas::FileManager::removeIgnorePatterns ()
Remove all ignore patterns.
Since
v0.0.1
Definition at line 204 of file IOManager.cpp.
unloadAll()
void Atlas::FileManager::unloadAll ()
Unloads all files.
Since
v0.0.1
Definition at line 328 of file IOManager.cpp.
unloadFile()
bool Atlas::FileManager::unloadFile (const std::filesystem::path & p)
An explicit unload function that unloads a file (forces if not in use).
Parameters
p The path to the file that should be unloaded.
Returns
bool Whether the file was unloaded or not.
Since
v0.0.1
Definition at line 275 of file IOManager.cpp.
References Atlas::GetAbsolutePath().
Referenced by main().
Friends And Related Symbol Documentation
FileJanitor
friend class FileJanitor [friend]
Definition at line 339 of file IOManager.h.
Member Data Documentation
mIgnoreMutex
std::mutex Atlas::FileManager::mIgnoreMutex [mutable], [private]
A mutex that is used to guard access to the mIgnorePatterns vector.
Since
v0.0.1
See also
mIgnorePatterns
Definition at line 382 of file IOManager.h.
mIgnorePatterns
std::vector<std::regex> Atlas::FileManager::mIgnorePatterns [private]
A vector of regex ignore patterns. This is guarded by mIgnoreMutex.
Since
v0.0.1
See also
mIgnoreMutex
Definition at line 391 of file IOManager.h.
mJanitor
FileJanitor Atlas::FileManager::mJanitor [private]
The janitor for this class.
Since
v0.0.1
Definition at line 346 of file IOManager.h.
mMapMutex
std::shared_mutex Atlas::FileManager::mMapMutex [mutable], [private]
A shared mutex that is used to guard access to the mRecords map.
Since
v0.0.1
See also
mRecords
Definition at line 355 of file IOManager.h.
mOptions
Options Atlas::FileManager::mOptions [private]
This class' configuration options.
Since
v0.0.1
Definition at line 369 of file IOManager.h.
Referenced by Atlas::FileManager::FileJanitor::evictUnused(), and Atlas::FileManager::FileJanitor::janitorLoop().
mRecords
std::unordered_map<std::filesystem::path, std::shared_ptr<FileRecord> > Atlas::FileManager::mRecords [private]
A map of registered files. This is guarded by mMapMutex.
Since
v0.0.1
Definition at line 362 of file IOManager.h.
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/io/IOManager.h
C:/Dev/Techstorm-v5/src/engine/io/IOManager.cpp