Complex Struct Reference
#include <scriptmathcomplex.h>
Public Member Functions
Complex ()
Complex (const Complex &other)
Complex (float r, float i=0)
Complex & operator= (const Complex &other)
Complex & operator+= (const Complex &other)
Complex & operator-= (const Complex &other)
Complex & operator*= (const Complex &other)
Complex & operator/= (const Complex &other)
float length () const
float squaredLength () const
Complex get_ri () const
void set_ri (const Complex &in)
Complex get_ir () const
void set_ir (const Complex &in)
bool operator== (const Complex &other) const
bool operator!= (const Complex &other) const
Complex operator+ (const Complex &other) const
Complex operator- (const Complex &other) const
Complex operator* (const Complex &other) const
Complex operator/ (const Complex &other) const
Complex ()
Complex (const Complex &other)
Complex (float r, float i=0)
Complex & operator= (const Complex &other)
Complex & operator+= (const Complex &other)
Complex & operator-= (const Complex &other)
Complex & operator*= (const Complex &other)
Complex & operator/= (const Complex &other)
float length () const
float squaredLength () const
Complex get_ri () const
void set_ri (const Complex &in)
Complex get_ir () const
void set_ir (const Complex &in)
bool operator== (const Complex &other) const
bool operator!= (const Complex &other) const
Complex operator+ (const Complex &other) const
Complex operator- (const Complex &other) const
Complex operator* (const Complex &other) const
Complex operator/ (const Complex &other) const
Public Attributes
float r
float i
Detailed Description
Definition at line 17 of file scriptmathcomplex.h.
Constructor & Destructor Documentation
Complex() [1/6]
BEGIN_AS_NAMESPACE Complex::Complex ()
Definition at line 15 of file scriptmathcomplex.cpp.
References i, and r.
Referenced by get_ir(), operator*(), operator+(), operator-(), and operator/().
Complex() [2/6]
Complex::Complex (const Complex & other)
Definition at line 21 of file scriptmathcomplex.cpp.
References i, and r.
Complex() [3/6]
Complex::Complex (float r, float i = 0)
Definition at line 27 of file scriptmathcomplex.cpp.
References i, and r.
Complex() [4/6]
Complex::Complex ()
Complex() [5/6]
Complex::Complex (const Complex & other)
Complex() [6/6]
Complex::Complex (float r, float i = 0)
Member Function Documentation
get_ir() [1/2]
Complex Complex::get_ir () const
Definition at line 117 of file scriptmathcomplex.cpp.
References Complex(), i, and r.
get_ir() [2/2]
Complex Complex::get_ir () const
get_ri() [1/2]
Complex Complex::get_ri () const
Definition at line 113 of file scriptmathcomplex.cpp.
get_ri() [2/2]
Complex Complex::get_ri () const
length() [1/2]
float Complex::length () const
Definition at line 81 of file scriptmathcomplex.cpp.
References squaredLength().
length() [2/2]
float Complex::length () const
operator!=() [1/2]
bool Complex::operator!= (const Complex & other) const
Definition at line 38 of file scriptmathcomplex.cpp.
operator!=() [2/2]
bool Complex::operator!= (const Complex & other) const
operator*() [1/2]
Complex Complex::operator* (const Complex & other) const
Definition at line 96 of file scriptmathcomplex.cpp.
References Complex(), i, and r.
operator*() [2/2]
Complex Complex::operator* (const Complex & other) const
operator*=() [1/2]
Complex & Complex::operator*= (const Complex & other)
Definition at line 64 of file scriptmathcomplex.cpp.
operator*=() [2/2]
Complex & Complex::operator*= (const Complex & other)
operator+() [1/2]
Complex Complex::operator+ (const Complex & other) const
Definition at line 86 of file scriptmathcomplex.cpp.
References Complex(), i, and r.
operator+() [2/2]
Complex Complex::operator+ (const Complex & other) const
operator+=() [1/2]
Complex & Complex::operator+= (const Complex & other)
Definition at line 50 of file scriptmathcomplex.cpp.
References i, and r.
operator+=() [2/2]
Complex & Complex::operator+= (const Complex & other)
operator-() [1/2]
Complex Complex::operator- (const Complex & other) const
Definition at line 91 of file scriptmathcomplex.cpp.
References Complex(), i, and r.
operator-() [2/2]
Complex Complex::operator- (const Complex & other) const
operator-=() [1/2]
Complex & Complex::operator-= (const Complex & other)
Definition at line 57 of file scriptmathcomplex.cpp.
References i, and r.
operator-=() [2/2]
Complex & Complex::operator-= (const Complex & other)
operator/() [1/2]
Complex Complex::operator/ (const Complex & other) const
Definition at line 101 of file scriptmathcomplex.cpp.
References Complex(), i, r, and squaredLength().
operator/() [2/2]
Complex Complex::operator/ (const Complex & other) const
operator/=() [1/2]
Complex & Complex::operator/= (const Complex & other)
Definition at line 70 of file scriptmathcomplex.cpp.
operator/=() [2/2]
Complex & Complex::operator/= (const Complex & other)
operator=() [1/2]
Complex & Complex::operator= (const Complex & other)
Definition at line 43 of file scriptmathcomplex.cpp.
References i, and r.
operator=() [2/2]
Complex & Complex::operator= (const Complex & other)
operator==() [1/2]
bool Complex::operator== (const Complex & other) const
Definition at line 33 of file scriptmathcomplex.cpp.
References i, and r.
operator==() [2/2]
bool Complex::operator== (const Complex & other) const
set_ir() [1/2]
void Complex::set_ir (const Complex & in)
Definition at line 125 of file scriptmathcomplex.cpp.
References i, and r.
set_ir() [2/2]
void Complex::set_ir (const Complex & in)
set_ri() [1/2]
void Complex::set_ri (const Complex & in)
Definition at line 121 of file scriptmathcomplex.cpp.
set_ri() [2/2]
void Complex::set_ri (const Complex & in)
squaredLength() [1/2]
float Complex::squaredLength () const
Definition at line 76 of file scriptmathcomplex.cpp.
References i, and r.
Referenced by length(), and operator/().
squaredLength() [2/2]
float Complex::squaredLength () const
Member Data Documentation
i
float Complex::i
Definition at line 52 of file scriptmathcomplex.h.
Referenced by Complex(), Complex(), Complex(), get_ir(), operator*(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator=(), operator==(), set_ir(), and squaredLength().
r
float Complex::r
Definition at line 51 of file scriptmathcomplex.h.
Referenced by Complex(), Complex(), Complex(), get_ir(), operator*(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator=(), operator==(), set_ir(), and squaredLength().
The documentation for this struct was generated from the following files:
C:/Dev/Techstorm-v5/src/application/add_on/scriptmath/scriptmathcomplex.h
C:/Dev/Techstorm-v5/src/engine/modding/add_on/scriptmath/scriptmathcomplex.h
C:/Dev/Techstorm-v5/src/application/add_on/scriptmath/scriptmathcomplex.cpp
C:/Dev/Techstorm-v5/src/engine/modding/add_on/scriptmath/scriptmathcomplex.cpp