C:/Dev/Techstorm-v5/src/application/main.cpp File Reference
#include "ApplicationUtils.h"
#include <raylib.h>
#include <Common.h>
#include <conf/Config.h>
#include <dbg/Logging.h>
#include <modding/ScriptingAPI.h>
#include <renderer/Renderer.h>
#include <renderer/window/WindowDecorations.h>
#include <project.h>
Functions
void InitWindow (WindowDecorations &decorations)
void InitScripting (ScriptingAPI &scriptingAPI, PROJECT_TYPENAME &project)
void HandleFrame (PROJECT_TYPENAME &project)
int main (int argc, char *argv[])
Function Documentation
HandleFrame()
void HandleFrame (PROJECT_TYPENAME & project)
Definition at line 38 of file main.cpp.
References ATLAS_THREAD_YIELD.
Referenced by main().
InitScripting()
void InitScripting (ScriptingAPI & scriptingAPI, PROJECT_TYPENAME & project)
Definition at line 33 of file main.cpp.
Referenced by main().
InitWindow()
void InitWindow (WindowDecorations & decorations)
Definition at line 13 of file main.cpp.
References ATLAS_ASSET_DIR, Atlas::WindowDecorations::height, Atlas::WindowDecorations::icon, InitWindow(), Atlas::Log(), Atlas::LookupConfig(), Atlas::WindowDecorations::title, and Atlas::WindowDecorations::width.
Referenced by ChunkTesting(), Atlas::Application::AtlasApp::initWindow(), InitWindow(), main(), PrototypePhysicsTerrain(), and PrototypeTerrain().
main()
int main (int argc, char * argv[])
Definition at line 48 of file main.cpp.
References Atlas::GetConfigFileRegistry(), HandleFrame(), Atlas::InitializeConfigRegistry(), InitScripting(), InitWindow(), Atlas::Singleton< FrameManager >::Instance(), Atlas::Application::FrameManager::killThreads(), Atlas::Application::FrameManager::launchThreads(), Atlas::Log(), PROJECT_TYPENAME, and Atlas::WindowDecorations::targetFPS.