C:/Dev/Techstorm-v5/src/bindings/imgui_impl_dx9.h File Reference
#include "imgui.h"
Functions
IMGUI_IMPL_API bool ImGui_ImplDX9_Init (IDirect3DDevice9 *device)
IMGUI_IMPL_API void ImGui_ImplDX9_Shutdown ()
IMGUI_IMPL_API void ImGui_ImplDX9_NewFrame ()
IMGUI_IMPL_API void ImGui_ImplDX9_RenderDrawData (ImDrawData *draw_data)
IMGUI_IMPL_API bool ImGui_ImplDX9_CreateDeviceObjects ()
IMGUI_IMPL_API void ImGui_ImplDX9_InvalidateDeviceObjects ()
Function Documentation
ImGui_ImplDX9_CreateDeviceObjects()
IMGUI_IMPL_API bool ImGui_ImplDX9_CreateDeviceObjects ()
Definition at line 389 of file imgui_impl_dx9.cpp.
References ImGui_ImplDX9_CreateFontsTexture(), ImGui_ImplDX9_GetBackendData(), and ImGui_ImplDX9_Data::pd3dDevice.
Referenced by ImGui_ImplDX9_NewFrame().
ImGui_ImplDX9_Init()
IMGUI_IMPL_API bool ImGui_ImplDX9_Init (IDirect3DDevice9 * device)
Definition at line 294 of file imgui_impl_dx9.cpp.
References ImGui_ImplDX9_Data::pd3dDevice.
ImGui_ImplDX9_InvalidateDeviceObjects()
IMGUI_IMPL_API void ImGui_ImplDX9_InvalidateDeviceObjects ()
Definition at line 399 of file imgui_impl_dx9.cpp.
References ImGui_ImplDX9_Data::FontTexture, ImGui_ImplDX9_GetBackendData(), ImGui_ImplDX9_Data::pd3dDevice, ImGui_ImplDX9_Data::pIB, and ImGui_ImplDX9_Data::pVB.
Referenced by ImGui_ImplDX9_Shutdown().
ImGui_ImplDX9_NewFrame()
IMGUI_IMPL_API void ImGui_ImplDX9_NewFrame ()
Definition at line 409 of file imgui_impl_dx9.cpp.
References ImGui_ImplDX9_Data::FontTexture, ImGui_ImplDX9_CreateDeviceObjects(), and ImGui_ImplDX9_GetBackendData().
ImGui_ImplDX9_RenderDrawData()
IMGUI_IMPL_API void ImGui_ImplDX9_RenderDrawData (ImDrawData * draw_data)
Definition at line 155 of file imgui_impl_dx9.cpp.
References CUSTOMVERTEX::col, D3DFVF_CUSTOMVERTEX, IMGUI_COL_TO_DX9_ARGB, ImGui_ImplDX9_GetBackendData(), ImGui_ImplDX9_SetupRenderState(), ImGui_ImplDX9_Data::IndexBufferSize, ImGui_ImplDX9_Data::pd3dDevice, ImGui_ImplDX9_Data::pIB, CUSTOMVERTEX::pos, ImGui_ImplDX9_Data::pVB, CUSTOMVERTEX::uv, and ImGui_ImplDX9_Data::VertexBufferSize.
ImGui_ImplDX9_Shutdown()
IMGUI_IMPL_API void ImGui_ImplDX9_Shutdown ()
Definition at line 312 of file imgui_impl_dx9.cpp.
References ImGui_ImplDX9_GetBackendData(), ImGui_ImplDX9_InvalidateDeviceObjects(), and ImGui_ImplDX9_Data::pd3dDevice.