C:/Dev/Techstorm-v5/src/engine/modding/add_on/scriptmath/scriptmath.h File Reference
#include <angelscript.h>
Functions
BEGIN_AS_NAMESPACE void RegisterScriptMath (asIScriptEngine *engine)
void RegisterScriptMath_Native (asIScriptEngine *engine)
void RegisterScriptMath_Generic (asIScriptEngine *engine)
Function Documentation
RegisterScriptMath()
BEGIN_AS_NAMESPACE void RegisterScriptMath (asIScriptEngine * engine)
Definition at line 361 of file scriptmath.cpp.
References RegisterScriptMath_Generic(), and RegisterScriptMath_Native().
RegisterScriptMath_Generic()
void RegisterScriptMath_Generic (asIScriptEngine * engine)
Definition at line 303 of file scriptmath.cpp.
References atan2f_generic().
Referenced by RegisterScriptMath().
RegisterScriptMath_Native()
void RegisterScriptMath_Native (asIScriptEngine * engine)
Definition at line 157 of file scriptmath.cpp.
References closeTo(), fpFromIEEE(), fpToIEEE(), and fractionf().
Referenced by RegisterScriptMath().