C:/Dev/Techstorm-v5/src/application/add_on/scriptany/scriptany.cpp File Reference
#include "scriptany.h"
#include <new>
#include <assert.h>
#include <string.h>
Functions
void RegisterScriptAny (asIScriptEngine *engine)
void RegisterScriptAny_Native (asIScriptEngine *engine)
void RegisterScriptAny_Generic (asIScriptEngine *engine)
Function Documentation
RegisterScriptAny()
void RegisterScriptAny (asIScriptEngine * engine)
Definition at line 134 of file scriptany.cpp.
References RegisterScriptAny_Generic(), and RegisterScriptAny_Native().
RegisterScriptAny_Generic()
void RegisterScriptAny_Generic (asIScriptEngine * engine)
Definition at line 171 of file scriptany.cpp.
Referenced by RegisterScriptAny().
RegisterScriptAny_Native()
void RegisterScriptAny_Native (asIScriptEngine * engine)
Definition at line 142 of file scriptany.cpp.
Referenced by RegisterScriptAny().