Atlas::GameCamera::CameraInputAction Class Reference
Like an InputAction, this class is used to handle input for the camera.
#include <GameCamera.h>
Public Member Functions
CameraInputAction (const std::string &name, int key, const EInputType &type, const EInputTrigger &trigger, GameCamera *camera)
Initializes a new instance of the CameraInputAction class.
void moveForward (float amount)
Move the camera forward.
void moveBackward (float amount)
Move the camera backward.
void moveLeft (float amount)
Move the camera left.
void moveRight (float amount)
Move the camera right.
void moveUp (float amount)
Move the camera up.
void moveDown (float amount)
Move the camera down.
Public Member Functions inherited from Atlas::InputAction
InputAction ()=default
InputAction (const std::string &name, int key, const EInputType &type, const EInputTrigger &trigger)
Public Attributes
GameCamera * camera = nullptr
A pointer to the camera that this input action is associated with.
Public Attributes inherited from Atlas::InputAction
std::string name
int key
std::optional< int > controllerID
EInputType type
EInputTrigger trigger
Detailed Description
Like an InputAction, this class is used to handle input for the camera.
Since
v0.0.8
Definition at line 246 of file GameCamera.h.
Constructor & Destructor Documentation
CameraInputAction()
Atlas::GameCamera::CameraInputAction::CameraInputAction (const std::string & name, int key, const EInputType & type, const EInputTrigger & trigger, GameCamera * camera)
Initializes a new instance of the CameraInputAction class.
Parameters
name The name of the input action.
key The key that is associated with the input action.
type The type of the input action.
trigger The trigger that is associated with the input action.
camera The camera that is associated with the input action.
Since
v0.0.8
Definition at line 228 of file GameCamera.cpp.
Member Function Documentation
moveBackward()
void Atlas::GameCamera::CameraInputAction::moveBackward (float amount)
Move the camera backward.
Parameters
amount The amount to move the camera backward.
Since
v0.0.8
Definition at line 238 of file GameCamera.cpp.
References Atlas::GameCamera::BACKWARD_DIRECTION, and camera.
Referenced by Atlas::GameCamera::init().
moveDown()
void Atlas::GameCamera::CameraInputAction::moveDown (float amount)
Move the camera down.
Parameters
amount The amount to move the camera down.
Since
v0.0.8
Definition at line 258 of file GameCamera.cpp.
References camera, and Atlas::GameCamera::DOWN_DIRECTION.
Referenced by Atlas::GameCamera::init().
moveForward()
void Atlas::GameCamera::CameraInputAction::moveForward (float amount)
Move the camera forward.
Parameters
amount The amount to move the camera forward.
Since
v0.0.8
Definition at line 233 of file GameCamera.cpp.
References camera, and Atlas::GameCamera::FORWARD_DIRECTION.
Referenced by Atlas::GameCamera::init().
moveLeft()
void Atlas::GameCamera::CameraInputAction::moveLeft (float amount)
Move the camera left.
Parameters
amount The amount to move the camera left.
Since
v0.0.8
Definition at line 243 of file GameCamera.cpp.
References camera, and Atlas::GameCamera::LEFT_DIRECTION.
Referenced by Atlas::GameCamera::init().
moveRight()
void Atlas::GameCamera::CameraInputAction::moveRight (float amount)
Move the camera right.
Parameters
amount The amount to move the camera right.
Since
v0.0.8
Definition at line 248 of file GameCamera.cpp.
References camera, and Atlas::GameCamera::RIGHT_DIRECTION.
Referenced by Atlas::GameCamera::init().
moveUp()
void Atlas::GameCamera::CameraInputAction::moveUp (float amount)
Move the camera up.
Parameters
amount The amount to move the camera up.
Since
v0.0.8
Definition at line 253 of file GameCamera.cpp.
References camera, and Atlas::GameCamera::UP_DIRECTION.
Referenced by Atlas::GameCamera::init().
Member Data Documentation
camera
GameCamera* Atlas::GameCamera::CameraInputAction::camera = nullptr
A pointer to the camera that this input action is associated with.
Definition at line 252 of file GameCamera.h.
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/renderer/GameCamera.h
C:/Dev/Techstorm-v5/src/engine/renderer/GameCamera.cpp