Atlas::RenderingBackend Class Reference
#include <RenderingBackend.h>
Classes
struct State
Public Types
using APIVersion = Version
Public Member Functions
RenderingBackend ()=default
virtual ~RenderingBackend ()
virtual void init (AGameWindow *gameWindow)=0
virtual void beginDrawing ()
virtual void draw ()
virtual void endDrawing ()
virtual void shutdown ()
virtual void setAPIVersion (uint32_t major, uint32_t minor, uint32_t patch)
virtual void setAPIVersion (Version version)
virtual Version getAPIVersion () const
bool areDebuggingToolsEnabled () const
bool isErrorCheckingEnabled () const
template<typename T_CAST_TO >
T_CAST_TO * castAs ()
Protected Attributes
std::shared_ptr< State > mState
std::shared_mutex mStateMutex
Version mAPIVersion
bool mbIsInitialized = false
bool mbUseDebuggingTools = false
bool mbEnableErrorChecking = false
Detailed Description
Definition at line 120 of file RenderingBackend.h.
Member Typedef Documentation
APIVersion
using Atlas::RenderingBackend::APIVersion = Version
Definition at line 122 of file RenderingBackend.h.
Constructor & Destructor Documentation
RenderingBackend()
Atlas::RenderingBackend::RenderingBackend () [default]
~RenderingBackend()
virtual Atlas::RenderingBackend::~RenderingBackend () [inline], [virtual]
Definition at line 146 of file RenderingBackend.h.
References shutdown().
Member Function Documentation
areDebuggingToolsEnabled()
bool Atlas::RenderingBackend::areDebuggingToolsEnabled () const
Definition at line 40 of file RenderingBackend.cpp.
beginDrawing()
virtual void Atlas::RenderingBackend::beginDrawing () [inline], [virtual]
Definition at line 159 of file RenderingBackend.h.
castAs()
template<typename T_CAST_TO >
T_CAST_TO * Atlas::RenderingBackend::castAs () [inline]
Definition at line 182 of file RenderingBackend.h.
Referenced by Atlas::ARenderer::castRenderingBackendAs().
draw()
virtual void Atlas::RenderingBackend::draw () [inline], [virtual]
Reimplemented in Atlas::VulkanRenderingBackend.
Definition at line 161 of file RenderingBackend.h.
endDrawing()
virtual void Atlas::RenderingBackend::endDrawing () [inline], [virtual]
Definition at line 163 of file RenderingBackend.h.
getAPIVersion()
Atlas::Version Atlas::RenderingBackend::getAPIVersion () const [virtual]
Definition at line 36 of file RenderingBackend.cpp.
init()
virtual void Atlas::RenderingBackend::init (AGameWindow * gameWindow) [pure virtual]
Implemented in Atlas::VulkanRenderingBackend, and Atlas::AGlobalRenderingBackend< T_CHILD >.
Referenced by Atlas::AGlobalRenderingBackend< T_CHILD >::init().
isErrorCheckingEnabled()
bool Atlas::RenderingBackend::isErrorCheckingEnabled () const
Definition at line 44 of file RenderingBackend.cpp.
setAPIVersion() [1/2]
void Atlas::RenderingBackend::setAPIVersion (uint32_t major, uint32_t minor, uint32_t patch) [virtual]
Definition at line 26 of file RenderingBackend.cpp.
References Atlas::Version::major, mAPIVersion, Atlas::Version::minor, and Atlas::Version::patch.
setAPIVersion() [2/2]
void Atlas::RenderingBackend::setAPIVersion (Version version) [virtual]
Definition at line 32 of file RenderingBackend.cpp.
References Atlas::Version::major, Atlas::Version::minor, and Atlas::Version::patch.
shutdown()
virtual void Atlas::RenderingBackend::shutdown () [inline], [virtual]
Reimplemented in Atlas::AGlobalRenderingBackend< T_CHILD >, and Atlas::VulkanRenderingBackend.
Definition at line 165 of file RenderingBackend.h.
References mbIsInitialized.
Referenced by Atlas::AGlobalRenderingBackend< T_CHILD >::shutdown(), and ~RenderingBackend().
Member Data Documentation
mAPIVersion
Version Atlas::RenderingBackend::mAPIVersion [protected]
Definition at line 137 of file RenderingBackend.h.
Referenced by setAPIVersion().
mbEnableErrorChecking
bool Atlas::RenderingBackend::mbEnableErrorChecking = false [protected]
Definition at line 141 of file RenderingBackend.h.
mbIsInitialized
bool Atlas::RenderingBackend::mbIsInitialized = false [protected]
Definition at line 139 of file RenderingBackend.h.
Referenced by shutdown().
mbUseDebuggingTools
bool Atlas::RenderingBackend::mbUseDebuggingTools = false [protected]
Definition at line 140 of file RenderingBackend.h.
mState
std::shared_ptr<State> Atlas::RenderingBackend::mState [protected]
Definition at line 134 of file RenderingBackend.h.
mStateMutex
std::shared_mutex Atlas::RenderingBackend::mStateMutex [protected]
Definition at line 135 of file RenderingBackend.h.
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/graphics/backend/RenderingBackend.h
C:/Dev/Techstorm-v5/src/engine/graphics/backend/RenderingBackend.cpp