Atlas::EffectManager Class Reference
#include <EffectManager.h>
Public Member Functions
int getCurrentEffectIndex ()
int getEffectCount ()
ComputeEffect & getCurrentEffect ()
Private Attributes
std::vector< ComputeEffect > mComputeEffects
int mCurrentEffectIndex { 0 }
Detailed Description
Definition at line 17 of file EffectManager.h.
Member Function Documentation
getCurrentEffect()
ComputeEffect & Atlas::EffectManager::getCurrentEffect () [inline]
Definition at line 32 of file EffectManager.h.
References mComputeEffects, and mCurrentEffectIndex.
Referenced by Atlas::IMGUIRenderable::setupElements().
getCurrentEffectIndex()
int Atlas::EffectManager::getCurrentEffectIndex () [inline]
Definition at line 24 of file EffectManager.h.
References mCurrentEffectIndex.
Referenced by Atlas::IMGUIRenderable::setupElements().
getEffectCount()
int Atlas::EffectManager::getEffectCount () [inline]
Definition at line 28 of file EffectManager.h.
References mComputeEffects.
Referenced by Atlas::IMGUIRenderable::setupElements().
Member Data Documentation
mComputeEffects
std::vector<ComputeEffect> Atlas::EffectManager::mComputeEffects [private]
Definition at line 19 of file EffectManager.h.
Referenced by getCurrentEffect(), and getEffectCount().
mCurrentEffectIndex
int Atlas::EffectManager::mCurrentEffectIndex { 0 } [private]
Definition at line 21 of file EffectManager.h.
Referenced by getCurrentEffect(), and getCurrentEffectIndex().
The documentation for this class was generated from the following file:
C:/Dev/Techstorm-v5/src/engine/graphics/drawing/EffectManager.h