Atlas::ThreadGroup Class Reference
#include <ThreadGroup.h>
Public Member Functions
ThreadGroup ()=default
virtual ~ThreadGroup ()
virtual void addThread (const std::string &name, std::function< void()> task)
virtual void stopAll ()
virtual void waitForAll ()
Protected Attributes
std::vector< GameThread > mThreads
bool mShouldStop = false
std::mutex mMutex
std::condition_variable mConditionalVariable
std::string mGroupName
Detailed Description
Definition at line 10 of file ThreadGroup.h.
Constructor & Destructor Documentation
ThreadGroup()
Atlas::ThreadGroup::ThreadGroup () [default]
~ThreadGroup()
Atlas::ThreadGroup::~ThreadGroup () [virtual]
Definition at line 9 of file ThreadGroup.cpp.
References stopAll().
Member Function Documentation
addThread()
void Atlas::ThreadGroup::addThread (const std::string & name, std::function< void()> task) [virtual]
Definition at line 13 of file ThreadGroup.cpp.
References Atlas::t().
stopAll()
void Atlas::ThreadGroup::stopAll () [virtual]
Definition at line 20 of file ThreadGroup.cpp.
References Atlas::t().
Referenced by ~ThreadGroup().
waitForAll()
void Atlas::ThreadGroup::waitForAll () [virtual]
Definition at line 38 of file ThreadGroup.cpp.
Member Data Documentation
mConditionalVariable
std::condition_variable Atlas::ThreadGroup::mConditionalVariable [protected]
Definition at line 15 of file ThreadGroup.h.
mGroupName
std::string Atlas::ThreadGroup::mGroupName [protected]
Definition at line 16 of file ThreadGroup.h.
mMutex
std::mutex Atlas::ThreadGroup::mMutex [protected]
Definition at line 14 of file ThreadGroup.h.
mShouldStop
bool Atlas::ThreadGroup::mShouldStop = false [protected]
Definition at line 13 of file ThreadGroup.h.
mThreads
std::vector<GameThread> Atlas::ThreadGroup::mThreads [protected]
Definition at line 12 of file ThreadGroup.h.
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/core/ThreadGroup.h
C:/Dev/Techstorm-v5/src/engine/core/ThreadGroup.cpp