Atlas::PhysicalDevice Class Reference
#include <PhysicalDevice.h>
Public Member Functions
PhysicalDevice (VulkanInstanceWrapper &cVulkanInstanceRef, PhysicalDeviceSelectionConstraints const &selectionConstraints)
PhysicalDevice ()=default
vkb::PhysicalDeviceSelector selectDevice (VulkanInstanceWrapper &cVulkanInstanceRef)
bool isValid () const final
PhysicalDeviceProperties getPhysicalDeviceProperties () const
std::string_view getName () const
void setName (std::string const &cNameRef)
std::string_view getName () const
Public Member Functions inherited from Atlas::AVulkanCompositeHandleWrapper< VkPhysicalDevice, vkb::PhysicalDevice, vkb::PhysicalDeviceSelector >
AVulkanCompositeHandleWrapper (T_WRAPS handle, vkb::PhysicalDevice vkbHandle)
AVulkanCompositeHandleWrapper (vkb::PhysicalDeviceSelector builder)
AVulkanCompositeHandleWrapper ()=default
virtual ~AVulkanCompositeHandleWrapper () override=default
vkb::PhysicalDevice & getVkbHandle ()
vkb::PhysicalDevice * getVkbHandlePtr ()
vkb::PhysicalDevice * safeGetVkbHandlePtr ()
explicit (false) operator const vkb::PhysicalDevice &() const
vkb::PhysicalDevice * operator-> ()
Public Member Functions inherited from Atlas::AVulkanHandleWrapper< T_WRAPS >
explicit (false) AVulkanHandleWrapper(T_WRAPS &handle)
AVulkanHandleWrapper ()=default
virtual ~AVulkanHandleWrapper () override=default
virtual bool hasValidHandle () const
T_WRAPS getHandle () const
explicit (false) operator const T_WRAPS &() const
explicit (false) operator T_WRAPS &()
explicit (false) operator bool() const
Public Member Functions inherited from Atlas::InitializableAndValidatable
InitializableAndValidatable (bool bIsInit, bool bIsValid)
InitializableAndValidatable ()=default
Public Member Functions inherited from Atlas::Initializable
ATLAS_EXPLICIT Initializable (bool bIsInit)
Initializable ()=default
virtual ~Initializable ()=default
virtual bool isInit () const
Public Member Functions inherited from Atlas::Validatable
ATLAS_EXPLICIT Validatable (bool bIsValid)
Validatable ()=default
virtual ~Validatable ()=default
virtual ATLAS_IMPLICIT operator bool () const
Protected Member Functions
void populateDeviceProperties ()
void evaluateValidity ()
void setDeviceName (std::string_view deviceName)
Protected Member Functions inherited from Atlas::AVulkanCompositeHandleWrapper< VkPhysicalDevice, vkb::PhysicalDevice, vkb::PhysicalDeviceSelector >
void setVkbHandle (vkb::PhysicalDevice vkbHandle)
bool hasValidVkbHandle () const
Protected Member Functions inherited from Atlas::AVulkanHandleWrapper< T_WRAPS >
void setHandle (T_WRAPS handle)
T_WRAPS & getHandleRef ()
Protected Member Functions inherited from Atlas::Initializable
bool & getInternalInitValue ()
virtual void setInitState (bool bNewInitState)
virtual void setInit ()
virtual void setNotInit ()
Protected Member Functions inherited from Atlas::Validatable
bool & getInternalValidityValue ()
virtual void setValidity (bool bIsValid)
virtual void setValid ()
virtual void setInvalid ()
Private Member Functions
bool init (VulkanInstanceWrapper &cVulkanInstanceRef)
Private Attributes
std::unique_ptr< vkb::PhysicalDeviceSelector > mVkbDeviceSelectorPtr { nullptr }
std::string mDeviceName
PhysicalDeviceProperties mDevicePropertiesAggregate {}
PhysicalDeviceSelectionConstraints mSelectionConstraints
Friends
class VulkanRenderingBackend
Detailed Description
Definition at line 92 of file PhysicalDevice.h.
Constructor & Destructor Documentation
PhysicalDevice() [1/2]
Atlas::PhysicalDevice::PhysicalDevice (VulkanInstanceWrapper & cVulkanInstanceRef, PhysicalDeviceSelectionConstraints const & selectionConstraints) [explicit]
Definition at line 94 of file PhysicalDevice.cpp.
References init().
PhysicalDevice() [2/2]
Atlas::PhysicalDevice::PhysicalDevice () [default]
Member Function Documentation
evaluateValidity()
void Atlas::PhysicalDevice::evaluateValidity () [protected]
Definition at line 65 of file PhysicalDevice.cpp.
getName() [1/2]
std::string_view Atlas::PhysicalDevice::getName () const
Definition at line 182 of file PhysicalDevice.cpp.
getName() [2/2]
std::string_view Atlas::PhysicalDevice::getName () const [inline]
Definition at line 15 of file PhysicalDevice.h.
References mDeviceName.
getPhysicalDeviceProperties()
Atlas::PhysicalDeviceProperties Atlas::PhysicalDevice::getPhysicalDeviceProperties () const
Definition at line 172 of file PhysicalDevice.cpp.
init()
bool Atlas::PhysicalDevice::init (VulkanInstanceWrapper & cVulkanInstanceRef) [private]
Definition at line 38 of file PhysicalDevice.cpp.
Referenced by PhysicalDevice().
isValid()
bool Atlas::PhysicalDevice::isValid () const [final], [virtual]
Reimplemented from Atlas::AVulkanCompositeHandleWrapper< VkPhysicalDevice, vkb::PhysicalDevice, vkb::PhysicalDeviceSelector >.
Definition at line 164 of file PhysicalDevice.cpp.
References Atlas::AVulkanHandleWrapper< T_WRAPS >::isValid().
populateDeviceProperties()
void Atlas::PhysicalDevice::populateDeviceProperties () [protected]
Definition at line 59 of file PhysicalDevice.cpp.
selectDevice()
vkb::PhysicalDeviceSelector Atlas::PhysicalDevice::selectDevice (VulkanInstanceWrapper & cVulkanInstanceRef)
Definition at line 112 of file PhysicalDevice.cpp.
References Atlas::VulkanInstanceWrapper::getVulkanBootstrapInstance(), and Atlas::ToVkbPreferredDeviceType().
setDeviceName()
void Atlas::PhysicalDevice::setDeviceName (std::string_view deviceName) [protected]
Definition at line 90 of file PhysicalDevice.cpp.
setName()
void Atlas::PhysicalDevice::setName (std::string const & cNameRef) [inline]
Definition at line 11 of file PhysicalDevice.h.
References mDeviceName.
Friends And Related Symbol Documentation
VulkanRenderingBackend
friend class VulkanRenderingBackend [friend]
Definition at line 105 of file PhysicalDevice.h.
Member Data Documentation
mDeviceName
std::string Atlas::PhysicalDevice::mDeviceName [private]
Definition at line 100 of file PhysicalDevice.h.
Referenced by getName(), and setName().
mDevicePropertiesAggregate
PhysicalDeviceProperties Atlas::PhysicalDevice::mDevicePropertiesAggregate {} [private]
Definition at line 101 of file PhysicalDevice.h.
mSelectionConstraints
PhysicalDeviceSelectionConstraints Atlas::PhysicalDevice::mSelectionConstraints [private]
Definition at line 103 of file PhysicalDevice.h.
mVkbDeviceSelectorPtr
std::unique_ptr<vkb::PhysicalDeviceSelector> Atlas::PhysicalDevice::mVkbDeviceSelectorPtr { nullptr } [private]
Definition at line 97 of file PhysicalDevice.h.
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/graphics/PhysicalDevice.h
C:/Dev/Techstorm-v5/src/engine/system/PhysicalDevice.h
C:/Dev/Techstorm-v5/src/engine/graphics/PhysicalDevice.cpp