Atlas::SpdlogLogger Class Reference
A generic logger that uses the Spdlog library. According to the spdlog documentation, you may call the spdlog::log() function to log messages after the logger has been initialized because of how spdlog works. For more information, on how to use spdlog, please refer to their documentation. This class was designed to work in the same way as the multi-sink logger example provided in the spdlog documentation. Another important thing to note about this class is that, assuming you are not implementing a custom PFN_vkDebugUtilsMessengerCallbackEXT callback for Vulkan, this class should be initialized prior to the initialization and usage of Atlas' Vulkan API. Otherwise, you will get errors the second Vulkan starts sending messages to the callback.
#include <Logging.h>
Classes
struct LoggerSinks
A struct that bundles together the console sink and the file sink as it is required for the spdlog logger during it's initialization.
Public Types
using ConsoleColorSink = spdlog::sinks::stdout_color_sink_mt
The standard spdlog console color sink.
using BasicFileSink = spdlog::sinks::basic_file_sink_mt
The standard spdlog basic file sink.
Public Member Functions
SpdlogLogger (std::string const &loggerName, std::string const &messageFormatPattern, std::string const &logFilePath, bool truncateMessages, std::initializer_list< ELogLevel > sinksLogLevels)
An explicit and verbose constructor for the SpdlogLogger class.
SpdlogLogger (std::string const &loggerName, std::string const &messageFormatPattern, std::string const &logFilePath, bool truncateMessages)
An explicit constructor for the SpdlogLogger class that will also set the value of mTruncateMessages.
SpdlogLogger (std::string const &loggerName, std::string const &messageFormatPattern, std::string const &logFilePath)
An explicit constructor for the SpdlogLogger class. This constructor will be suitable for most use cases.
SpdlogLogger ()=default
void init () override
Initializes the logger and the spdlog library. This function must be called before the logger can be used. Once this function is called, this logger will be able to log messages.
void setThisAsDefaultLogger ()
Pretty much the same as setThisAsDefaultLogger(), but sets this logger instance as the default logger.
void log (std::string const &message, ELogLevel logLevel) override
A more explicit logging function where the message and log level must be specified. This function will only log using this logger instance, not the default logger. This function is inherited from ALogger.
void info (std::string const &message)
Logs a message at the ELogLevel::info log level using this class' log() function.
void error (std::string const &message)
Logs a message at the ELogLevel::err log level using this class' log() function.
void warn (std::string const &message)
Logs a message at the ELogLevel::warn log level using this class' log() function.
void debug (std::string const &message)
Logs a message at the ELogLevel::debug log level using this class' log() function.
void trace (std::string const &message)
Logs a message at the ELogLevel::trace log level using this class' log() function.
void critical (std::string const &message)
Logs a message at the ELogLevel::critical log level using this class' log() function.
void close () override
Closes the logger. Currently, this function does nothing.
void setConsoleLogLevel (ELogLevel logLevel)
Sets the console sink's log level.
void setFileLogLevel (ELogLevel logLevel)
Sets the file sink's log level.
void setLoggerLevel (ELogLevel logLevel)
Sets the logger's log level.
bool shouldTruncateMessage () const
Returns whether or not the logger should truncate the message, derived from the mbTruncateMessages flag.
Public Member Functions inherited from Atlas::ALogger
ALogger ()=default
virtual ~ALogger ()=default
Static Public Member Functions
static void QueueMessage (std::string const &message, ELogLevel logLevel)
static void SetDefaultLogger (SpdlogLogger *logger)
Sets the logger that will be used as the default logger for spdlog::log() or the other namespace-scope logging functions for spdlog.
Static Public Member Functions inherited from Atlas::ALogger
static std::string GenerateLogFileName ()
static void Log (std::string const &message, ELogLevel logLevel)
Private Member Functions
void display (std::string const &message) override
void setLevel (ELogLevel logLevel) override
void initConsoleSink ()
Initializes the console sink in the LoggerSinks struct that will be used by the spdlog logger. This function will set the console sink's log level to mConsoleLogLevel and will set the sink's pattern to mMessageFormatPattern. This is called by the init() function.
void initFileSink ()
Initializes the file sink in the LoggerSinks struct that will be used by the spdlog logger. This function will set the file sink's log level to the value of mFileLogLevel.
void initInternalSpdlogLogger ()
Initializes the spdlog logger instance. Once this function is called (assuming that everything went okay up to this point), the spdlog logger instance can be used to log messages.
Static Private Member Functions
static ELogLevel ExtractLogLevel (std::initializer_list< ELogLevel > logLevels, int index)
Private Attributes
bool mbTruncateMessages = SHOULD_TRUNCATE_FILE_LOGS
A flag that indicates whether or not the log messages should be truncated if they are too long. This is used by the file sink when writing to the log file. If the message is too long, it will be truncated. By default, this flag is set to false.
bool mbIsFullyInitialized = false
A flag that indicates whether or not the logger is initialized and can be used without error.
bool mbUseFileSink = false
ELogLevel mConsoleLogLevel = DEFAULT_CONSOLE_SINK_LEVEL
The minimum log level for a message to be logged to the console. By default, this is set to warn. You can change this value by calling setConsoleLogLevel(). However, this is not recommended to be done after initializing the logger because you would have to shutdown the logger and reinitialize it for it to take effect.
ELogLevel mFileLogLevel = DEFAULT_FILE_SINK_LEVEL
The minimum log level for a message to be logged (written) to the log file. By default, this is set to trace. You can change this value by calling setFileLogLevel(). However, this is not recommended to be done after initializing the logger because you would have to shutdown the logger and reinitialize it for it to take effect.
ELogLevel mLoggerLevel = DEFAULT_LOGGER_LEVEL
The minimum log level for a message to be logged. By default, this is set to debug. You can change this value by calling setLevel(). However, this is not recommended to be done after initializing the logger because you would have to shutdown the logger and reinitialize it for it to take effect.
const std::string mLoggerName = "Atlas"
The name of the logger that will be passed to the spdlog logger library when it is initialized. There is not much need to change this value unless you are doing something special. By default, this is set to "Atlas".
const std::string mLogFilePath
The path to the log file that will be written to when a message is successfully passed to the file sink.
std::string mMessageFormatPattern
The pattern that will be used to format the messages that are passed to the logger. The value of this should be set PRIOR to calling init(). Furthermore, please use the pattern flags that Spdlog provides (see this variable's see also section in the documentation for a link to the Spdlog documentation that explains the pattern flags).
std::unique_ptr< LoggerSinks > mLoggingSinks = nullptr
A unique pointer to the LoggerSinks aggregator struct.
std::unique_ptr< spdlog::logger > mInternalSpdlogLoggerPtr = nullptr
A unique pointer to the spdlog logger instance. All logging is done through this instance, so this must be initialized before any logging can be done.
std::mutex mInternalSpdlogLoggerMutex
Static Private Attributes
static constexpr bool SHOULD_TRUNCATE_FILE_LOGS = false
static constexpr ELogLevel DEFAULT_CONSOLE_SINK_LEVEL = ELogLevel::info
static constexpr ELogLevel DEFAULT_FILE_SINK_LEVEL = ELogLevel::trace
static constexpr ELogLevel DEFAULT_LOGGER_LEVEL = ELogLevel::debug
Detailed Description
A generic logger that uses the Spdlog library. According to the spdlog documentation, you may call the spdlog::log() function to log messages after the logger has been initialized because of how spdlog works. For more information, on how to use spdlog, please refer to their documentation. This class was designed to work in the same way as the multi-sink logger example provided in the spdlog documentation. Another important thing to note about this class is that, assuming you are not implementing a custom PFN_vkDebugUtilsMessengerCallbackEXT callback for Vulkan, this class should be initialized prior to the initialization and usage of Atlas' Vulkan API. Otherwise, you will get errors the second Vulkan starts sending messages to the callback.
To initialize this class in a case where you immediately have the initialization variables, consider the following code:
SpdlogLogger logger = SpdlogLogger("Atlas", "[Some Logger] [%^%l%$] %v", "log.txt");
logger.init();
If you do not have the initialization variables but need to set them later, you may make logger a pointer to get around the lack of a default constructor. However, keep in mind that a default constructor may be implemented later on.
Note
While most of the variables that are required for initialization within this class, there are a couple that must absolutely be set because there is no default value for them. More specifically, the values of the following variables that do not have a default value must be set PRIOR to calling init():
mMessageFormatPattern
mLogFilePath Please refer to the documentation of those variables for more information about them.
Since
v0.0.1
See also
ALogger The interface that this class publicly implements.
 https://github.com/gabime/spdlog?tab=readme-ov-file#logger-with-multi-sinks---each-with-a-different-format-and-log-level for what this class' main functionality is based on.
Todo
Todo Consider adding a constructor that doesn't require the message format pattern and log file path to be passed. For the log file path (mLogFilePath), maybe a function should exist that automatically generates a file path for you? Or maybe a function should exist that automatically generates a log file name for you? And for the message format pattern, the one that is provided in the Spdlog documentation could be used as a default value.
Definition at line 201 of file Logging.h.
Member Typedef Documentation
BasicFileSink
using Atlas::SpdlogLogger::BasicFileSink = spdlog::sinks::basic_file_sink_mt
The standard spdlog basic file sink.
Note
This is just to make the code more readable
Since
v0.0.1
Definition at line 219 of file Logging.h.
ConsoleColorSink
using Atlas::SpdlogLogger::ConsoleColorSink = spdlog::sinks::stdout_color_sink_mt
The standard spdlog console color sink.
Note
This is just to make the code more readable
Since
v0.0.1
Definition at line 210 of file Logging.h.
Constructor & Destructor Documentation
SpdlogLogger() [1/4]
Atlas::SpdlogLogger::SpdlogLogger (std::string const & loggerName, std::string const & messageFormatPattern, std::string const & logFilePath, bool truncateMessages, std::initializer_list< ELogLevel > sinksLogLevels) [explicit]
An explicit and verbose constructor for the SpdlogLogger class.
Note
If the value of logFilePath is empty, the file sink will not be initialized. If logFilePath is not a valid path, an exception will be thrown when init() is called.
Parameters
loggerName What the logger will be called.
messageFormatPattern The pattern that will be used to format the messages that are passed to the logger.
logFilePath The path to the log file.
truncateMessages Whether or not to truncate the messages that are passed to the logger.
sinksLogLevels An initializer list of log levels that will be used to set the log level for each sink. Unless you are implementing more than the default sinks, this should have 3 entries in accordance with the ESpdlogInitListIndex enum class.
Since
v0.0.1
Definition at line 148 of file Logging.cpp.
SpdlogLogger() [2/4]
Atlas::SpdlogLogger::SpdlogLogger (std::string const & loggerName, std::string const & messageFormatPattern, std::string const & logFilePath, bool truncateMessages) [explicit]
An explicit constructor for the SpdlogLogger class that will also set the value of mTruncateMessages.
Note
If the value of logFilePath is empty, the file sink will not be initialized. If logFilePath is not a valid path, an exception will be thrown when init() is called.
Parameters
loggerName What the logger will be called.
messageFormatPattern The pattern that will be used to format the messages that are passed to the logger.
logFilePath The path to the log file.
truncateMessages Whether or not to truncate the messages that are passed to the logger.
Since
v0.0.1
Definition at line 156 of file Logging.cpp.
References DEFAULT_CONSOLE_SINK_LEVEL, DEFAULT_FILE_SINK_LEVEL, and DEFAULT_LOGGER_LEVEL.
SpdlogLogger() [3/4]
Atlas::SpdlogLogger::SpdlogLogger (std::string const & loggerName, std::string const & messageFormatPattern, std::string const & logFilePath) [explicit]
An explicit constructor for the SpdlogLogger class. This constructor will be suitable for most use cases.
Note
If the value of logFilePath is empty, the file sink will not be initialized. If logFilePath is not a valid path, an exception will be thrown when init() is called.
Parameters
loggerName What the logger will be called.
messageFormatPattern The pattern that will be used to format the messages that are passed to the logger.
logFilePath The path to the log file.
Since
v0.0.1
Definition at line 161 of file Logging.cpp.
SpdlogLogger() [4/4]
Atlas::SpdlogLogger::SpdlogLogger () [default]
Member Function Documentation
close()
void Atlas::SpdlogLogger::close () [override], [virtual]
Closes the logger. Currently, this function does nothing.
Since
v0.0.1
Implements Atlas::ALogger.
Definition at line 246 of file Logging.cpp.
critical()
void Atlas::SpdlogLogger::critical (std::string const & message)
Logs a message at the ELogLevel::critical log level using this class' log() function.
Parameters
message The message that will be logged.
Since
v0.0.1
Definition at line 241 of file Logging.cpp.
References Atlas::critical.
debug()
void Atlas::SpdlogLogger::debug (std::string const & message)
Logs a message at the ELogLevel::debug log level using this class' log() function.
Parameters
message The message that will be logged.
Since
v0.0.1
Definition at line 231 of file Logging.cpp.
References Atlas::debug.
display()
void Atlas::SpdlogLogger::display (std::string const & message) [override], [private], [virtual]
Reimplemented from Atlas::ALogger.
Definition at line 114 of file Logging.cpp.
error()
void Atlas::SpdlogLogger::error (std::string const & message)
Logs a message at the ELogLevel::err log level using this class' log() function.
Parameters
message The message that will be logged.
Since
v0.0.1
Definition at line 221 of file Logging.cpp.
References Atlas::error.
ExtractLogLevel()
Atlas::ELogLevel Atlas::SpdlogLogger::ExtractLogLevel (std::initializer_list< ELogLevel > logLevels, int index) [static], [private]
Definition at line 106 of file Logging.cpp.
References Atlas::trace.
info()
void Atlas::SpdlogLogger::info (std::string const & message)
Logs a message at the ELogLevel::info log level using this class' log() function.
Parameters
message The message that will be logged.
Since
v0.0.1
Definition at line 216 of file Logging.cpp.
References Atlas::info.
Referenced by main().
init()
void Atlas::SpdlogLogger::init () [override], [virtual]
Initializes the logger and the spdlog library. This function must be called before the logger can be used. Once this function is called, this logger will be able to log messages.
Precondition
The required user-defined initialization variables mLoggerName, mMessageFormatPattern, and mLogFilePath must be set before calling this function. If it is not, behavior is undefined and exceptions may be thrown depending on what is not set.
Since
v0.0.1
Implements Atlas::ALogger.
Definition at line 185 of file Logging.cpp.
Referenced by main().
initConsoleSink()
void Atlas::SpdlogLogger::initConsoleSink () [private]
Initializes the console sink in the LoggerSinks struct that will be used by the spdlog logger. This function will set the console sink's log level to mConsoleLogLevel and will set the sink's pattern to mMessageFormatPattern. This is called by the init() function.
Note
Just because this function has been called, does not mean that the console sink is ready to be used because spdlog requires the console sink to be initialized before the spdlog::logger instance can be initialized. In the case of this class, the spdlog::logger instance is stored as mInternalSpdlogLoggerPtr. In other words, the variable mInternalSpdlogLoggerPtr must be initialized before any logging can be done.
Since
v0.0.1
Todo
Todo Implement some checks to make sure that the console sink is not already initialized and that the pattern is not empty. Doing so should make the initialization of the console sink more robust and less error-prone.
Definition at line 122 of file Logging.cpp.
initFileSink()
void Atlas::SpdlogLogger::initFileSink () [private]
Initializes the file sink in the LoggerSinks struct that will be used by the spdlog logger. This function will set the file sink's log level to the value of mFileLogLevel.
Note
Just because this function has been called, does not mean that the file sink is ready to be used because spdlog requires the file sink to be initialized before the spdlog::logger instance can be initialized.
Since
v0.0.1
Definition at line 132 of file Logging.cpp.
initInternalSpdlogLogger()
void Atlas::SpdlogLogger::initInternalSpdlogLogger () [private]
Initializes the spdlog logger instance. Once this function is called (assuming that everything went okay up to this point), the spdlog logger instance can be used to log messages.
Precondition
The console sink and the file sink must be initialized PRIOR to calling this function.
Since
v0.0.1
Definition at line 140 of file Logging.cpp.
log()
void Atlas::SpdlogLogger::log (std::string const & message, ELogLevel logLevel) [override], [virtual]
A more explicit logging function where the message and log level must be specified. This function will only log using this logger instance, not the default logger. This function is inherited from ALogger.
Parameters
message A const reference to the message that will be logged.
logLevel The log level of the message that will be logged.
Since
v0.0.1
Reimplemented from Atlas::ALogger.
Definition at line 210 of file Logging.cpp.
Referenced by QueueMessage().
QueueMessage()
void Atlas::SpdlogLogger::QueueMessage (std::string const & message, ELogLevel logLevel) [static]
Definition at line 167 of file Logging.cpp.
References log().
setConsoleLogLevel()
void Atlas::SpdlogLogger::setConsoleLogLevel (ELogLevel logLevel) [inline]
Sets the console sink's log level.
Parameters
logLevel The minimum log level that the console sink will log.
Since
v0.0.1
Definition at line 582 of file Logging.h.
References mConsoleLogLevel.
SetDefaultLogger()
void Atlas::SpdlogLogger::SetDefaultLogger (SpdlogLogger * logger) [static]
Sets the logger that will be used as the default logger for spdlog::log() or the other namespace-scope logging functions for spdlog.
Parameters
logger
Since
v
Definition at line 178 of file Logging.cpp.
References ATLAS_ASSERT, and mInternalSpdlogLoggerPtr.
setFileLogLevel()
void Atlas::SpdlogLogger::setFileLogLevel (ELogLevel logLevel) [inline]
Sets the file sink's log level.
Parameters
logLevel The minimum log level that the file sink will log.
Since
v0.0.1
Definition at line 593 of file Logging.h.
References mFileLogLevel.
setLevel()
void Atlas::SpdlogLogger::setLevel (ELogLevel logLevel) [override], [private], [virtual]
Reimplemented from Atlas::ALogger.
Definition at line 118 of file Logging.cpp.
setLoggerLevel()
void Atlas::SpdlogLogger::setLoggerLevel (ELogLevel logLevel) [inline]
Sets the logger's log level.
Parameters
logLevel The minimum log level that the logger will log.
Since
v0.0.1
Definition at line 604 of file Logging.h.
References mLoggerLevel.
setThisAsDefaultLogger()
void Atlas::SpdlogLogger::setThisAsDefaultLogger ()
Pretty much the same as setThisAsDefaultLogger(), but sets this logger instance as the default logger.
Since
v0.0.1
See also
SetDefaultLogger
Definition at line 206 of file Logging.cpp.
Referenced by main().
shouldTruncateMessage()
bool Atlas::SpdlogLogger::shouldTruncateMessage () const
Returns whether or not the logger should truncate the message, derived from the mbTruncateMessages flag.
Returns
true if the logger should truncate the message, false otherwise.
Since
v0.0.1
Definition at line 251 of file Logging.cpp.
trace()
void Atlas::SpdlogLogger::trace (std::string const & message)
Logs a message at the ELogLevel::trace log level using this class' log() function.
Parameters
message The message that will be logged.
Since
v0.0.1
Definition at line 236 of file Logging.cpp.
References Atlas::trace.
warn()
void Atlas::SpdlogLogger::warn (std::string const & message)
Logs a message at the ELogLevel::warn log level using this class' log() function.
Parameters
message The message that will be logged.
Since
v0.0.1
Definition at line 226 of file Logging.cpp.
References Atlas::warn.
Member Data Documentation
DEFAULT_CONSOLE_SINK_LEVEL
constexpr ELogLevel Atlas::SpdlogLogger::DEFAULT_CONSOLE_SINK_LEVEL = ELogLevel::info [static], [constexpr], [private]
Definition at line 265 of file Logging.h.
Referenced by SpdlogLogger().
DEFAULT_FILE_SINK_LEVEL
constexpr ELogLevel Atlas::SpdlogLogger::DEFAULT_FILE_SINK_LEVEL = ELogLevel::trace [static], [constexpr], [private]
Definition at line 266 of file Logging.h.
Referenced by SpdlogLogger().
DEFAULT_LOGGER_LEVEL
constexpr ELogLevel Atlas::SpdlogLogger::DEFAULT_LOGGER_LEVEL = ELogLevel::debug [static], [constexpr], [private]
Definition at line 267 of file Logging.h.
Referenced by SpdlogLogger().
mbIsFullyInitialized
bool Atlas::SpdlogLogger::mbIsFullyInitialized = false [private]
A flag that indicates whether or not the logger is initialized and can be used without error.
Since
v0.0.1
Definition at line 287 of file Logging.h.
mbTruncateMessages
bool Atlas::SpdlogLogger::mbTruncateMessages = SHOULD_TRUNCATE_FILE_LOGS [private]
A flag that indicates whether or not the log messages should be truncated if they are too long. This is used by the file sink when writing to the log file. If the message is too long, it will be truncated. By default, this flag is set to false.
@important If you want messages to be truncated, this flag should be set to true BEFORE calling init(). On a public scope, this should be done by the SpdlogLogger constructor that accepts a truncateMessages parameter.
Since
v0.0.1
Definition at line 280 of file Logging.h.
mbUseFileSink
bool Atlas::SpdlogLogger::mbUseFileSink = false [private]
Definition at line 289 of file Logging.h.
mConsoleLogLevel
ELogLevel Atlas::SpdlogLogger::mConsoleLogLevel = DEFAULT_CONSOLE_SINK_LEVEL [private]
The minimum log level for a message to be logged to the console. By default, this is set to warn. You can change this value by calling setConsoleLogLevel(). However, this is not recommended to be done after initializing the logger because you would have to shutdown the logger and reinitialize it for it to take effect.
Since
v0.0.1
Definition at line 298 of file Logging.h.
Referenced by setConsoleLogLevel().
mFileLogLevel
ELogLevel Atlas::SpdlogLogger::mFileLogLevel = DEFAULT_FILE_SINK_LEVEL [private]
The minimum log level for a message to be logged (written) to the log file. By default, this is set to trace. You can change this value by calling setFileLogLevel(). However, this is not recommended to be done after initializing the logger because you would have to shutdown the logger and reinitialize it for it to take effect.
Since
v0.0.1
Definition at line 307 of file Logging.h.
Referenced by setFileLogLevel().
mInternalSpdlogLoggerMutex
std::mutex Atlas::SpdlogLogger::mInternalSpdlogLoggerMutex [private]
Definition at line 362 of file Logging.h.
mInternalSpdlogLoggerPtr
std::unique_ptr<spdlog::logger> Atlas::SpdlogLogger::mInternalSpdlogLoggerPtr = nullptr [private]
A unique pointer to the spdlog logger instance. All logging is done through this instance, so this must be initialized before any logging can be done.
Since
v0.0.1
Definition at line 360 of file Logging.h.
Referenced by SetDefaultLogger().
mLogFilePath
const std::string Atlas::SpdlogLogger::mLogFilePath [private]
The path to the log file that will be written to when a message is successfully passed to the file sink.
Since
v0.0.1
Todo
Todo Implement this with a std::filesystem::path variable.
Definition at line 333 of file Logging.h.
mLoggerLevel
ELogLevel Atlas::SpdlogLogger::mLoggerLevel = DEFAULT_LOGGER_LEVEL [private]
The minimum log level for a message to be logged. By default, this is set to debug. You can change this value by calling setLevel(). However, this is not recommended to be done after initializing the logger because you would have to shutdown the logger and reinitialize it for it to take effect.
Since
v0.0.1
Definition at line 316 of file Logging.h.
Referenced by setLoggerLevel().
mLoggerName
const std::string Atlas::SpdlogLogger::mLoggerName = "Atlas" [private]
The name of the logger that will be passed to the spdlog logger library when it is initialized. There is not much need to change this value unless you are doing something special. By default, this is set to "Atlas".
Since
v0.0.1
Definition at line 324 of file Logging.h.
mLoggingSinks
std::unique_ptr<LoggerSinks> Atlas::SpdlogLogger::mLoggingSinks = nullptr [private]
A unique pointer to the LoggerSinks aggregator struct.
Since
v0.0.1
Definition at line 352 of file Logging.h.
mMessageFormatPattern
std::string Atlas::SpdlogLogger::mMessageFormatPattern [private]
The pattern that will be used to format the messages that are passed to the logger. The value of this should be set PRIOR to calling init(). Furthermore, please use the pattern flags that Spdlog provides (see this variable's see also section in the documentation for a link to the Spdlog documentation that explains the pattern flags).
Since
v0.0.1
See also
 https://github.com/gabime/spdlog/wiki/Custom-formatting Spdlog documentation on custom formatting. Please use the same pattern flags that Spdlog provides to format the messages that are passed to the logger.
Definition at line 345 of file Logging.h.
SHOULD_TRUNCATE_FILE_LOGS
constexpr bool Atlas::SpdlogLogger::SHOULD_TRUNCATE_FILE_LOGS = false [static], [constexpr], [private]
Definition at line 263 of file Logging.h.
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/debugging/Logging.h
C:/Dev/Techstorm-v5/src/engine/debugging/Logging.cpp