CScriptDictionary Class Reference
#include <scriptdictionary.h>
Classes
class CIterator
Public Member Functions
void AddRef () const
void Release () const
CScriptDictionary & operator= (const CScriptDictionary &other)
void Set (const dictKey_t &key, void *value, int typeId)
void Set (const dictKey_t &key, const asINT64 &value)
void Set (const dictKey_t &key, const double &value)
bool Get (const dictKey_t &key, void *value, int typeId) const
bool Get (const dictKey_t &key, asINT64 &value) const
bool Get (const dictKey_t &key, double &value) const
CScriptDictValue * operator[] (const dictKey_t &key)
const CScriptDictValue * operator[] (const dictKey_t &key) const
int GetTypeId (const dictKey_t &key) const
bool Exists (const dictKey_t &key) const
bool IsEmpty () const
asUINT GetSize () const
bool Delete (const dictKey_t &key)
void DeleteAll ()
CScriptArray * GetKeys () const
CIterator begin () const
CIterator end () const
CIterator find (const dictKey_t &key) const
int GetRefCount ()
void SetGCFlag ()
bool GetGCFlag ()
void EnumReferences (asIScriptEngine *engine)
void ReleaseAllReferences (asIScriptEngine *engine)
void AddRef () const
void Release () const
CScriptDictionary & operator= (const CScriptDictionary &other)
void Set (const dictKey_t &key, void *value, int typeId)
void Set (const dictKey_t &key, const asINT64 &value)
void Set (const dictKey_t &key, const double &value)
bool Get (const dictKey_t &key, void *value, int typeId) const
bool Get (const dictKey_t &key, asINT64 &value) const
bool Get (const dictKey_t &key, double &value) const
CScriptDictValue * operator[] (const dictKey_t &key)
const CScriptDictValue * operator[] (const dictKey_t &key) const
int GetTypeId (const dictKey_t &key) const
bool Exists (const dictKey_t &key) const
bool IsEmpty () const
asUINT GetSize () const
bool Delete (const dictKey_t &key)
void DeleteAll ()
CScriptArray * GetKeys () const
CIterator begin () const
CIterator end () const
CIterator find (const dictKey_t &key) const
int GetRefCount ()
void SetGCFlag ()
bool GetGCFlag ()
void EnumReferences (asIScriptEngine *engine)
void ReleaseAllReferences (asIScriptEngine *engine)
Static Public Member Functions
static CScriptDictionary * Create (asIScriptEngine *engine)
static CScriptDictionary * Create (asBYTE *buffer)
static CScriptDictionary * Create (asIScriptEngine *engine)
static CScriptDictionary * Create (asBYTE *buffer)
Protected Member Functions
CScriptDictionary (asIScriptEngine *engine)
CScriptDictionary (asBYTE *buffer)
virtual ~CScriptDictionary ()
void Init (asIScriptEngine *engine)
CScriptDictionary (asIScriptEngine *engine)
CScriptDictionary (asBYTE *buffer)
virtual ~CScriptDictionary ()
void Init (asIScriptEngine *engine)
Protected Attributes
asIScriptEngine * engine
int refCount
bool gcFlag
dictMap_t dict
Detailed Description
Definition at line 109 of file scriptdictionary.h.
Constructor & Destructor Documentation
CScriptDictionary() [1/4]
CScriptDictionary::CScriptDictionary (asIScriptEngine * engine) [protected]
Definition at line 71 of file scriptdictionary.cpp.
References engine, and Init().
CScriptDictionary() [2/4]
CScriptDictionary::CScriptDictionary (asBYTE * buffer) [protected]
Definition at line 94 of file scriptdictionary.cpp.
References DICTIONARY_CACHE, engine, Init(), SDictionaryCache::keyType, and Set().
~CScriptDictionary() [1/2]
CScriptDictionary::~CScriptDictionary () [protected], [virtual]
Definition at line 194 of file scriptdictionary.cpp.
References DeleteAll().
Referenced by Release().
CScriptDictionary() [3/4]
CScriptDictionary::CScriptDictionary (asIScriptEngine * engine) [protected]
CScriptDictionary() [4/4]
CScriptDictionary::CScriptDictionary (asBYTE * buffer) [protected]
~CScriptDictionary() [2/2]
virtual CScriptDictionary::~CScriptDictionary () [protected], [virtual]
Member Function Documentation
AddRef() [1/2]
void CScriptDictionary::AddRef () const
Definition at line 200 of file scriptdictionary.cpp.
References gcFlag, and refCount.
Referenced by ScriptDictionaryAddRef_Generic().
AddRef() [2/2]
void CScriptDictionary::AddRef () const
begin() [1/2]
CScriptDictionary::CIterator CScriptDictionary::begin () const
Definition at line 1218 of file scriptdictionary.cpp.
References dict.
begin() [2/2]
CIterator CScriptDictionary::begin () const
Create() [1/4]
CScriptDictionary * CScriptDictionary::Create (asBYTE * buffer) [static]
Definition at line 63 of file scriptdictionary.cpp.
Create() [2/4]
static CScriptDictionary * CScriptDictionary::Create (asBYTE * buffer) [static]
Create() [3/4]
CScriptDictionary * CScriptDictionary::Create (asIScriptEngine * engine) [static]
Definition at line 55 of file scriptdictionary.cpp.
References engine.
Referenced by ScriptDictionaryFactory_Generic(), and ScriptDictionaryListFactory_Generic().
Create() [4/4]
static CScriptDictionary * CScriptDictionary::Create (asIScriptEngine * engine) [static]
Delete() [1/2]
bool CScriptDictionary::Delete (const dictKey_t & key)
Definition at line 397 of file scriptdictionary.cpp.
References dict, and engine.
Referenced by ScriptDictionaryDelete_Generic().
Delete() [2/2]
bool CScriptDictionary::Delete (const dictKey_t & key)
DeleteAll() [1/2]
void CScriptDictionary::DeleteAll ()
Definition at line 411 of file scriptdictionary.cpp.
References dict, and engine.
Referenced by operator=(), ReleaseAllReferences(), ScriptDictionaryDeleteAll_Generic(), and ~CScriptDictionary().
DeleteAll() [2/2]
void CScriptDictionary::DeleteAll ()
end() [1/2]
CScriptDictionary::CIterator CScriptDictionary::end () const
Definition at line 1223 of file scriptdictionary.cpp.
References dict.
end() [2/2]
CIterator CScriptDictionary::end () const
EnumReferences() [1/2]
void CScriptDictionary::EnumReferences (asIScriptEngine * engine)
Definition at line 233 of file scriptdictionary.cpp.
References dict, and engine.
Referenced by ScriptDictionaryEnumReferences_Generic().
EnumReferences() [2/2]
void CScriptDictionary::EnumReferences (asIScriptEngine * engine)
Exists() [1/2]
bool CScriptDictionary::Exists (const dictKey_t & key) const
Definition at line 374 of file scriptdictionary.cpp.
References dict.
Referenced by ScriptDictionaryExists_Generic().
Exists() [2/2]
bool CScriptDictionary::Exists (const dictKey_t & key) const
find() [1/2]
CScriptDictionary::CIterator CScriptDictionary::find (const dictKey_t & key) const
Definition at line 1228 of file scriptdictionary.cpp.
References dict.
find() [2/2]
CIterator CScriptDictionary::find (const dictKey_t & key) const
Get() [1/6]
bool CScriptDictionary::Get (const dictKey_t & key, asINT64 & value) const
Definition at line 364 of file scriptdictionary.cpp.
References Get().
Get() [2/6]
bool CScriptDictionary::Get (const dictKey_t & key, asINT64 & value) const
Get() [3/6]
bool CScriptDictionary::Get (const dictKey_t & key, double & value) const
Definition at line 369 of file scriptdictionary.cpp.
References Get().
Get() [4/6]
bool CScriptDictionary::Get (const dictKey_t & key, double & value) const
Get() [5/6]
bool CScriptDictionary::Get (const dictKey_t & key, void * value, int typeId) const
Definition at line 339 of file scriptdictionary.cpp.
References dict, and engine.
Referenced by Get(), Get(), ScriptDictionaryGet_Generic(), ScriptDictionaryGetFlt_Generic(), and ScriptDictionaryGetInt_Generic().
Get() [6/6]
bool CScriptDictionary::Get (const dictKey_t & key, void * value, int typeId) const
GetGCFlag() [1/2]
bool CScriptDictionary::GetGCFlag ()
Definition at line 228 of file scriptdictionary.cpp.
References gcFlag.
Referenced by ScriptDictionaryGetGCFlag_Generic().
GetGCFlag() [2/2]
bool CScriptDictionary::GetGCFlag ()
GetKeys() [1/2]
CScriptArray * CScriptDictionary::GetKeys () const
Definition at line 420 of file scriptdictionary.cpp.
References SDictionaryCache::arrayType, CScriptArray::At(), CScriptArray::Create(), dict, DICTIONARY_CACHE, and engine.
Referenced by CScriptDictionaryGetKeys_Generic().
GetKeys() [2/2]
CScriptArray * CScriptDictionary::GetKeys () const
GetRefCount() [1/2]
int CScriptDictionary::GetRefCount ()
Definition at line 218 of file scriptdictionary.cpp.
References refCount.
Referenced by ScriptDictionaryGetRefCount_Generic().
GetRefCount() [2/2]
int CScriptDictionary::GetRefCount ()
GetSize() [1/2]
asUINT CScriptDictionary::GetSize () const
Definition at line 392 of file scriptdictionary.cpp.
References dict.
Referenced by ScriptDictionaryGetSize_Generic().
GetSize() [2/2]
asUINT CScriptDictionary::GetSize () const
GetTypeId() [1/2]
int CScriptDictionary::GetTypeId (const dictKey_t & key) const
Definition at line 354 of file scriptdictionary.cpp.
References dict.
GetTypeId() [2/2]
int CScriptDictionary::GetTypeId (const dictKey_t & key) const
Init() [1/2]
void CScriptDictionary::Init (asIScriptEngine * engine) [protected]
Definition at line 76 of file scriptdictionary.cpp.
References DICTIONARY_CACHE, SDictionaryCache::dictType, engine, gcFlag, and refCount.
Referenced by CScriptDictionary(), and CScriptDictionary().
Init() [2/2]
void CScriptDictionary::Init (asIScriptEngine * engine) [protected]
IsEmpty() [1/2]
bool CScriptDictionary::IsEmpty () const
Definition at line 384 of file scriptdictionary.cpp.
References dict.
Referenced by ScriptDictionaryIsEmpty_Generic().
IsEmpty() [2/2]
bool CScriptDictionary::IsEmpty () const
operator=() [1/2]
CScriptDictionary & CScriptDictionary::operator= (const CScriptDictionary & other)
Definition at line 267 of file scriptdictionary.cpp.
References DeleteAll(), dict, and Set().
operator=() [2/2]
CScriptDictionary & CScriptDictionary::operator= (const CScriptDictionary & other)
operator[]() [1/4]
CScriptDictValue * CScriptDictionary::operator[] (const dictKey_t & key)
Definition at line 287 of file scriptdictionary.cpp.
References dict.
operator[]() [2/4]
CScriptDictValue * CScriptDictionary::operator[] (const dictKey_t & key)
operator[]() [3/4]
const CScriptDictValue * CScriptDictionary::operator[] (const dictKey_t & key) const
Definition at line 293 of file scriptdictionary.cpp.
References dict.
operator[]() [4/4]
const CScriptDictValue * CScriptDictionary::operator[] (const dictKey_t & key) const
Release() [1/2]
void CScriptDictionary::Release () const
Definition at line 207 of file scriptdictionary.cpp.
References gcFlag, refCount, and ~CScriptDictionary().
Referenced by ScriptDictionaryRelease_Generic().
Release() [2/2]
void CScriptDictionary::Release () const
ReleaseAllReferences() [1/2]
void CScriptDictionary::ReleaseAllReferences (asIScriptEngine * engine)
Definition at line 260 of file scriptdictionary.cpp.
References DeleteAll().
Referenced by ScriptDictionaryReleaseAllReferences_Generic().
ReleaseAllReferences() [2/2]
void CScriptDictionary::ReleaseAllReferences (asIScriptEngine * engine)
Set() [1/6]
void CScriptDictionary::Set (const dictKey_t & key, const asINT64 & value)
Definition at line 324 of file scriptdictionary.cpp.
References Set().
Set() [2/6]
void CScriptDictionary::Set (const dictKey_t & key, const asINT64 & value)
Set() [3/6]
void CScriptDictionary::Set (const dictKey_t & key, const double & value)
Definition at line 333 of file scriptdictionary.cpp.
References Set().
Set() [4/6]
void CScriptDictionary::Set (const dictKey_t & key, const double & value)
Set() [5/6]
void CScriptDictionary::Set (const dictKey_t & key, void * value, int typeId)
Definition at line 309 of file scriptdictionary.cpp.
References dict, and engine.
Referenced by CScriptDictionary(), operator=(), ScriptDictionarySet_Generic(), ScriptDictionarySetFlt_Generic(), ScriptDictionarySetInt_Generic(), Set(), and Set().
Set() [6/6]
void CScriptDictionary::Set (const dictKey_t & key, void * value, int typeId)
SetGCFlag() [1/2]
void CScriptDictionary::SetGCFlag ()
Definition at line 223 of file scriptdictionary.cpp.
References gcFlag.
Referenced by ScriptDictionarySetGCFlag_Generic().
SetGCFlag() [2/2]
void CScriptDictionary::SetGCFlag ()
Member Data Documentation
dict
dictMap_t CScriptDictionary::dict [protected]
Definition at line 223 of file scriptdictionary.h.
Referenced by begin(), Delete(), DeleteAll(), end(), EnumReferences(), Exists(), find(), Get(), GetKeys(), GetSize(), GetTypeId(), IsEmpty(), operator=(), operator[](), operator[](), and Set().
engine
asIScriptEngine * CScriptDictionary::engine [protected]
Definition at line 220 of file scriptdictionary.h.
Referenced by Create(), CScriptDictionary(), CScriptDictionary(), Delete(), DeleteAll(), EnumReferences(), Get(), GetKeys(), Init(), and Set().
gcFlag
bool CScriptDictionary::gcFlag [mutable], [protected]
Definition at line 222 of file scriptdictionary.h.
Referenced by AddRef(), GetGCFlag(), Init(), Release(), and SetGCFlag().
refCount
int CScriptDictionary::refCount [mutable], [protected]
Definition at line 221 of file scriptdictionary.h.
Referenced by AddRef(), GetRefCount(), Init(), and Release().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/application/add_on/scriptdictionary/scriptdictionary.h
C:/Dev/Techstorm-v5/src/engine/modding/add_on/scriptdictionary/scriptdictionary.h
C:/Dev/Techstorm-v5/src/application/add_on/scriptdictionary/scriptdictionary.cpp
C:/Dev/Techstorm-v5/src/engine/modding/add_on/scriptdictionary/scriptdictionary.cpp