C:/Dev/Techstorm-v5/src/application/add_on/scriptstdstring/scriptstdstring.cpp File Reference
#include "scriptstdstring.h"
#include <assert.h>
#include <sstream>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <locale.h>
#include <map>
Classes
class CStdStringFactory
class CStdStringFactoryCleaner
Macros
#define UNUSED_VAR(x) (void)(x)
Functions
CStdStringFactory * GetStdStringFactorySingleton ()
static void ConstructString (string *thisPointer)
static void CopyConstructString (const string &other, string *thisPointer)
static void DestructString (string *thisPointer)
static string & AddAssignStringToString (const string &str, string &dest)
static bool StringIsEmpty (const string &str)
static string & AssignUInt64ToString (asQWORD i, string &dest)
static string & AddAssignUInt64ToString (asQWORD i, string &dest)
static string AddStringUInt64 (const string &str, asQWORD i)
static string AddInt64String (asINT64 i, const string &str)
static string & AssignInt64ToString (asINT64 i, string &dest)
static string & AddAssignInt64ToString (asINT64 i, string &dest)
static string AddStringInt64 (const string &str, asINT64 i)
static string AddUInt64String (asQWORD i, const string &str)
static string & AssignDoubleToString (double f, string &dest)
static string & AddAssignDoubleToString (double f, string &dest)
static string & AssignFloatToString (float f, string &dest)
static string & AddAssignFloatToString (float f, string &dest)
static string & AssignBoolToString (bool b, string &dest)
static string & AddAssignBoolToString (bool b, string &dest)
static string AddStringDouble (const string &str, double f)
static string AddDoubleString (double f, const string &str)
static string AddStringFloat (const string &str, float f)
static string AddFloatString (float f, const string &str)
static string AddStringBool (const string &str, bool b)
static string AddBoolString (bool b, const string &str)
static char * StringCharAt (unsigned int i, string &str)
static int StringCmp (const string &a, const string &b)
static int StringFindFirst (const string &sub, asUINT start, const string &str)
static int StringFindFirstOf (const string &sub, asUINT start, const string &str)
static int StringFindLastOf (const string &sub, asUINT start, const string &str)
static int StringFindFirstNotOf (const string &sub, asUINT start, const string &str)
static int StringFindLastNotOf (const string &sub, asUINT start, const string &str)
static int StringFindLast (const string &sub, int start, const string &str)
static void StringInsert (unsigned int pos, const string &other, string &str)
static void StringErase (unsigned int pos, int count, string &str)
static asUINT StringLength (const string &str)
static void StringResize (asUINT l, string &str)
static string formatInt (asINT64 value, const string &options, asUINT width)
static string formatUInt (asQWORD value, const string &options, asUINT width)
static string formatFloat (double value, const string &options, asUINT width, asUINT precision)
static asINT64 parseInt (const string &val, asUINT base, asUINT *byteCount)
static asQWORD parseUInt (const string &val, asUINT base, asUINT *byteCount)
double parseFloat (const string &val, asUINT *byteCount)
static string StringSubString (asUINT start, int count, const string &str)
static bool StringEquals (const std::string &lhs, const std::string &rhs)
void RegisterStdString_Native (asIScriptEngine *engine)
static void ConstructStringGeneric (asIScriptGeneric *gen)
static void CopyConstructStringGeneric (asIScriptGeneric *gen)
static void DestructStringGeneric (asIScriptGeneric *gen)
static void AssignStringGeneric (asIScriptGeneric *gen)
static void AddAssignStringGeneric (asIScriptGeneric *gen)
static void StringEqualsGeneric (asIScriptGeneric *gen)
static void StringCmpGeneric (asIScriptGeneric *gen)
static void StringAddGeneric (asIScriptGeneric *gen)
static void StringLengthGeneric (asIScriptGeneric *gen)
static void StringIsEmptyGeneric (asIScriptGeneric *gen)
static void StringResizeGeneric (asIScriptGeneric *gen)
static void StringInsert_Generic (asIScriptGeneric *gen)
static void StringErase_Generic (asIScriptGeneric *gen)
static void StringFindFirst_Generic (asIScriptGeneric *gen)
static void StringFindLast_Generic (asIScriptGeneric *gen)
static void StringFindFirstOf_Generic (asIScriptGeneric *gen)
static void StringFindLastOf_Generic (asIScriptGeneric *gen)
static void StringFindFirstNotOf_Generic (asIScriptGeneric *gen)
static void StringFindLastNotOf_Generic (asIScriptGeneric *gen)
static void formatInt_Generic (asIScriptGeneric *gen)
static void formatUInt_Generic (asIScriptGeneric *gen)
static void formatFloat_Generic (asIScriptGeneric *gen)
static void parseInt_Generic (asIScriptGeneric *gen)
static void parseUInt_Generic (asIScriptGeneric *gen)
static void parseFloat_Generic (asIScriptGeneric *gen)
static void StringCharAtGeneric (asIScriptGeneric *gen)
static void AssignInt2StringGeneric (asIScriptGeneric *gen)
static void AssignUInt2StringGeneric (asIScriptGeneric *gen)
static void AssignDouble2StringGeneric (asIScriptGeneric *gen)
static void AssignFloat2StringGeneric (asIScriptGeneric *gen)
static void AssignBool2StringGeneric (asIScriptGeneric *gen)
static void AddAssignDouble2StringGeneric (asIScriptGeneric *gen)
static void AddAssignFloat2StringGeneric (asIScriptGeneric *gen)
static void AddAssignInt2StringGeneric (asIScriptGeneric *gen)
static void AddAssignUInt2StringGeneric (asIScriptGeneric *gen)
static void AddAssignBool2StringGeneric (asIScriptGeneric *gen)
static void AddString2DoubleGeneric (asIScriptGeneric *gen)
static void AddString2FloatGeneric (asIScriptGeneric *gen)
static void AddString2IntGeneric (asIScriptGeneric *gen)
static void AddString2UIntGeneric (asIScriptGeneric *gen)
static void AddString2BoolGeneric (asIScriptGeneric *gen)
static void AddDouble2StringGeneric (asIScriptGeneric *gen)
static void AddFloat2StringGeneric (asIScriptGeneric *gen)
static void AddInt2StringGeneric (asIScriptGeneric *gen)
static void AddUInt2StringGeneric (asIScriptGeneric *gen)
static void AddBool2StringGeneric (asIScriptGeneric *gen)
static void StringSubString_Generic (asIScriptGeneric *gen)
void RegisterStdString_Generic (asIScriptEngine *engine)
void RegisterStdString (asIScriptEngine *engine)
Variables
BEGIN_AS_NAMESPACE typedef map< string, int > map_t
static CStdStringFactory * stringFactory = 0
static CStdStringFactoryCleaner cleaner
Macro Definition Documentation
UNUSED_VAR
#define UNUSED_VAR(x) (void)(x)
Definition at line 15 of file scriptstdstring.cpp.
Function Documentation
AddAssignBool2StringGeneric()
static void AddAssignBool2StringGeneric (asIScriptGeneric * gen) [static]
Definition at line 1162 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
AddAssignBoolToString()
static string & AddAssignBoolToString (bool b, string & dest) [static]
Definition at line 289 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
AddAssignDouble2StringGeneric()
static void AddAssignDouble2StringGeneric (asIScriptGeneric * gen) [static]
Definition at line 1122 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
AddAssignDoubleToString()
static string & AddAssignDoubleToString (double f, string & dest) [static]
Definition at line 257 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
AddAssignFloat2StringGeneric()
static void AddAssignFloat2StringGeneric (asIScriptGeneric * gen) [static]
Definition at line 1132 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
AddAssignFloatToString()
static string & AddAssignFloatToString (float f, string & dest) [static]
Definition at line 273 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
AddAssignInt2StringGeneric()
static void AddAssignInt2StringGeneric (asIScriptGeneric * gen) [static]
Definition at line 1142 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
AddAssignInt64ToString()
static string & AddAssignInt64ToString (asINT64 i, string & dest) [static]
Definition at line 227 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
AddAssignStringGeneric()
static void AddAssignStringGeneric (asIScriptGeneric * gen) [static]
Definition at line 887 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
AddAssignStringToString()
static string & AddAssignStringToString (const string & str, string & dest) [static]
Definition at line 167 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
AddAssignUInt2StringGeneric()
static void AddAssignUInt2StringGeneric (asIScriptGeneric * gen) [static]
Definition at line 1152 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
AddAssignUInt64ToString()
static string & AddAssignUInt64ToString (asQWORD i, string & dest) [static]
Definition at line 197 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
AddBool2StringGeneric()
static void AddBool2StringGeneric (asIScriptGeneric * gen) [static]
Definition at line 1262 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
AddBoolString()
static string AddBoolString (bool b, const string & str) [static]
Definition at line 332 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
AddDouble2StringGeneric()
static void AddDouble2StringGeneric (asIScriptGeneric * gen) [static]
Definition at line 1222 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
AddDoubleString()
static string AddDoubleString (double f, const string & str) [static]
Definition at line 304 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
AddFloat2StringGeneric()
static void AddFloat2StringGeneric (asIScriptGeneric * gen) [static]
Definition at line 1232 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
AddFloatString()
static string AddFloatString (float f, const string & str) [static]
Definition at line 318 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
AddInt2StringGeneric()
static void AddInt2StringGeneric (asIScriptGeneric * gen) [static]
Definition at line 1242 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
AddInt64String()
static string AddInt64String (asINT64 i, const string & str) [static]
Definition at line 212 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
AddString2BoolGeneric()
static void AddString2BoolGeneric (asIScriptGeneric * gen) [static]
Definition at line 1212 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
AddString2DoubleGeneric()
static void AddString2DoubleGeneric (asIScriptGeneric * gen) [static]
Definition at line 1172 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
AddString2FloatGeneric()
static void AddString2FloatGeneric (asIScriptGeneric * gen) [static]
Definition at line 1182 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
AddString2IntGeneric()
static void AddString2IntGeneric (asIScriptGeneric * gen) [static]
Definition at line 1192 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
AddString2UIntGeneric()
static void AddString2UIntGeneric (asIScriptGeneric * gen) [static]
Definition at line 1202 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
AddStringBool()
static string AddStringBool (const string & str, bool b) [static]
Definition at line 325 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
AddStringDouble()
static string AddStringDouble (const string & str, double f) [static]
Definition at line 297 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
AddStringFloat()
static string AddStringFloat (const string & str, float f) [static]
Definition at line 311 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
AddStringInt64()
static string AddStringInt64 (const string & str, asINT64 i) [static]
Definition at line 235 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
AddStringUInt64()
static string AddStringUInt64 (const string & str, asQWORD i) [static]
Definition at line 205 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
AddUInt2StringGeneric()
static void AddUInt2StringGeneric (asIScriptGeneric * gen) [static]
Definition at line 1252 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
AddUInt64String()
static string AddUInt64String (asQWORD i, const string & str) [static]
Definition at line 242 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
AssignBool2StringGeneric()
static void AssignBool2StringGeneric (asIScriptGeneric * gen) [static]
Definition at line 1112 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
AssignBoolToString()
static string & AssignBoolToString (bool b, string & dest) [static]
Definition at line 281 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
AssignDouble2StringGeneric()
static void AssignDouble2StringGeneric (asIScriptGeneric * gen) [static]
Definition at line 1092 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
AssignDoubleToString()
static string & AssignDoubleToString (double f, string & dest) [static]
Definition at line 249 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
AssignFloat2StringGeneric()
static void AssignFloat2StringGeneric (asIScriptGeneric * gen) [static]
Definition at line 1102 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
AssignFloatToString()
static string & AssignFloatToString (float f, string & dest) [static]
Definition at line 265 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
AssignInt2StringGeneric()
static void AssignInt2StringGeneric (asIScriptGeneric * gen) [static]
Definition at line 1072 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
AssignInt64ToString()
static string & AssignInt64ToString (asINT64 i, string & dest) [static]
Definition at line 219 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
AssignStringGeneric()
static void AssignStringGeneric (asIScriptGeneric * gen) [static]
Definition at line 879 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
AssignUInt2StringGeneric()
static void AssignUInt2StringGeneric (asIScriptGeneric * gen) [static]
Definition at line 1082 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
AssignUInt64ToString()
static string & AssignUInt64ToString (asQWORD i, string & dest) [static]
Definition at line 189 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
ConstructString()
static void ConstructString (string * thisPointer) [static]
Definition at line 152 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
ConstructStringGeneric()
static void ConstructStringGeneric (asIScriptGeneric * gen) [static]
Definition at line 862 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
CopyConstructString()
static void CopyConstructString (const string & other, string * thisPointer) [static]
Definition at line 157 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
CopyConstructStringGeneric()
static void CopyConstructStringGeneric (asIScriptGeneric * gen) [static]
Definition at line 867 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
DestructString()
static void DestructString (string * thisPointer) [static]
Definition at line 162 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
DestructStringGeneric()
static void DestructStringGeneric (asIScriptGeneric * gen) [static]
Definition at line 873 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
formatFloat()
static string formatFloat (double value, const string & options, asUINT width, asUINT precision) [static]
Definition at line 559 of file scriptstdstring.cpp.
Referenced by formatFloat_Generic(), and RegisterStdString_Native().
formatFloat_Generic()
static void formatFloat_Generic (asIScriptGeneric * gen) [static]
Definition at line 1020 of file scriptstdstring.cpp.
References formatFloat().
Referenced by RegisterStdString_Generic().
formatInt()
static string formatInt (asINT64 value, const string & options, asUINT width) [static]
Definition at line 471 of file scriptstdstring.cpp.
Referenced by formatInt_Generic(), and RegisterStdString_Native().
formatInt_Generic()
static void formatInt_Generic (asIScriptGeneric * gen) [static]
Definition at line 1004 of file scriptstdstring.cpp.
References formatInt().
Referenced by RegisterStdString_Generic().
formatUInt()
static string formatUInt (asQWORD value, const string & options, asUINT width) [static]
Definition at line 515 of file scriptstdstring.cpp.
Referenced by formatUInt_Generic(), and RegisterStdString_Native().
formatUInt_Generic()
static void formatUInt_Generic (asIScriptGeneric * gen) [static]
Definition at line 1012 of file scriptstdstring.cpp.
References formatUInt().
Referenced by RegisterStdString_Generic().
GetStdStringFactorySingleton()
CStdStringFactory * GetStdStringFactorySingleton ()
Definition at line 110 of file scriptstdstring.cpp.
References stringFactory.
Referenced by RegisterStdString_Generic(), and RegisterStdString_Native().
parseFloat()
double parseFloat (const string & val, asUINT * byteCount)
Definition at line 696 of file scriptstdstring.cpp.
Referenced by parseFloat_Generic(), and RegisterStdString_Native().
parseFloat_Generic()
static void parseFloat_Generic (asIScriptGeneric * gen) [static]
Definition at line 1045 of file scriptstdstring.cpp.
References parseFloat().
Referenced by RegisterStdString_Generic().
parseInt()
static asINT64 parseInt (const string & val, asUINT base, asUINT * byteCount) [static]
Definition at line 595 of file scriptstdstring.cpp.
Referenced by parseInt_Generic(), and RegisterStdString_Native().
parseInt_Generic()
static void parseInt_Generic (asIScriptGeneric * gen) [static]
Definition at line 1029 of file scriptstdstring.cpp.
References parseInt().
Referenced by RegisterStdString_Generic().
parseUInt()
static asQWORD parseUInt (const string & val, asUINT base, asUINT * byteCount) [static]
Definition at line 652 of file scriptstdstring.cpp.
Referenced by parseUInt_Generic(), and RegisterStdString_Native().
parseUInt_Generic()
static void parseUInt_Generic (asIScriptGeneric * gen) [static]
Definition at line 1037 of file scriptstdstring.cpp.
References parseUInt().
Referenced by RegisterStdString_Generic().
RegisterStdString()
void RegisterStdString (asIScriptEngine * engine)
Definition at line 1367 of file scriptstdstring.cpp.
References RegisterStdString_Generic(), and RegisterStdString_Native().
Referenced by ConfigureEngine().
RegisterStdString_Generic()
void RegisterStdString_Generic (asIScriptEngine * engine)
Definition at line 1284 of file scriptstdstring.cpp.
References AddAssignBool2StringGeneric(), AddAssignDouble2StringGeneric(), AddAssignFloat2StringGeneric(), AddAssignInt2StringGeneric(), AddAssignStringGeneric(), AddAssignUInt2StringGeneric(), AddBool2StringGeneric(), AddDouble2StringGeneric(), AddFloat2StringGeneric(), AddInt2StringGeneric(), AddString2BoolGeneric(), AddString2DoubleGeneric(), AddString2FloatGeneric(), AddString2IntGeneric(), AddString2UIntGeneric(), AddUInt2StringGeneric(), AssignBool2StringGeneric(), AssignDouble2StringGeneric(), AssignFloat2StringGeneric(), AssignInt2StringGeneric(), AssignStringGeneric(), AssignUInt2StringGeneric(), ConstructStringGeneric(), CopyConstructStringGeneric(), DestructStringGeneric(), formatFloat_Generic(), formatInt_Generic(), formatUInt_Generic(), GetStdStringFactorySingleton(), parseFloat_Generic(), parseInt_Generic(), parseUInt_Generic(), StringAddGeneric(), StringCharAtGeneric(), StringCmpGeneric(), StringEqualsGeneric(), StringErase_Generic(), StringFindFirst_Generic(), StringFindFirstNotOf_Generic(), StringFindFirstOf_Generic(), StringFindLast_Generic(), StringFindLastNotOf_Generic(), StringFindLastOf_Generic(), StringInsert_Generic(), StringIsEmptyGeneric(), StringLengthGeneric(), StringResizeGeneric(), StringSubString_Generic(), and UNUSED_VAR.
Referenced by RegisterStdString().
RegisterStdString_Native()
void RegisterStdString_Native (asIScriptEngine * engine)
Definition at line 749 of file scriptstdstring.cpp.
References AddAssignBoolToString(), AddAssignDoubleToString(), AddAssignFloatToString(), AddAssignInt64ToString(), AddAssignStringToString(), AddAssignUInt64ToString(), AddBoolString(), AddDoubleString(), AddFloatString(), AddInt64String(), AddStringBool(), AddStringDouble(), AddStringFloat(), AddStringInt64(), AddStringUInt64(), AddUInt64String(), AssignBoolToString(), AssignDoubleToString(), AssignFloatToString(), AssignInt64ToString(), AssignUInt64ToString(), ConstructString(), CopyConstructString(), DestructString(), formatFloat(), formatInt(), formatUInt(), GetStdStringFactorySingleton(), parseFloat(), parseInt(), parseUInt(), StringCharAt(), StringCmp(), StringEquals(), StringErase(), StringFindFirst(), StringFindFirstNotOf(), StringFindFirstOf(), StringFindLast(), StringFindLastNotOf(), StringFindLastOf(), StringInsert(), StringIsEmpty(), StringLength(), StringResize(), StringSubString(), and UNUSED_VAR.
Referenced by RegisterStdString().
StringAddGeneric()
static void StringAddGeneric (asIScriptGeneric * gen) [static]
Definition at line 914 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
StringCharAt()
static char * StringCharAt (unsigned int i, string & str) [static]
Definition at line 340 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
StringCharAtGeneric()
static void StringCharAtGeneric (asIScriptGeneric * gen) [static]
Definition at line 1052 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
StringCmp()
static int StringCmp (const string & a, const string & b) [static]
Definition at line 357 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
StringCmpGeneric()
static void StringCmpGeneric (asIScriptGeneric * gen) [static]
Definition at line 902 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
StringEquals()
static bool StringEquals (const std::string & lhs, const std::string & rhs) [static]
Definition at line 744 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
StringEqualsGeneric()
static void StringEqualsGeneric (asIScriptGeneric * gen) [static]
Definition at line 895 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
StringErase()
static void StringErase (unsigned int pos, int count, string & str) [static]
Definition at line 445 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native(), and StringErase_Generic().
StringErase_Generic()
static void StringErase_Generic (asIScriptGeneric * gen) [static]
Definition at line 948 of file scriptstdstring.cpp.
References StringErase().
Referenced by RegisterStdString_Generic().
StringFindFirst()
static int StringFindFirst (const string & sub, asUINT start, const string & str) [static]
Definition at line 371 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native(), and StringFindFirst_Generic().
StringFindFirst_Generic()
static void StringFindFirst_Generic (asIScriptGeneric * gen) [static]
Definition at line 956 of file scriptstdstring.cpp.
References StringFindFirst().
Referenced by RegisterStdString_Generic().
StringFindFirstNotOf()
static int StringFindFirstNotOf (const string & sub, asUINT start, const string & str) [static]
Definition at line 406 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native(), and StringFindFirstNotOf_Generic().
StringFindFirstNotOf_Generic()
static void StringFindFirstNotOf_Generic (asIScriptGeneric * gen) [static]
Definition at line 988 of file scriptstdstring.cpp.
References StringFindFirstNotOf().
Referenced by RegisterStdString_Generic().
StringFindFirstOf()
static int StringFindFirstOf (const string & sub, asUINT start, const string & str) [static]
Definition at line 383 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native(), and StringFindFirstOf_Generic().
StringFindFirstOf_Generic()
static void StringFindFirstOf_Generic (asIScriptGeneric * gen) [static]
Definition at line 972 of file scriptstdstring.cpp.
References StringFindFirstOf().
Referenced by RegisterStdString_Generic().
StringFindLast()
static int StringFindLast (const string & sub, int start, const string & str) [static]
Definition at line 429 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native(), and StringFindLast_Generic().
StringFindLast_Generic()
static void StringFindLast_Generic (asIScriptGeneric * gen) [static]
Definition at line 964 of file scriptstdstring.cpp.
References StringFindLast().
Referenced by RegisterStdString_Generic().
StringFindLastNotOf()
static int StringFindLastNotOf (const string & sub, asUINT start, const string & str) [static]
Definition at line 417 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native(), and StringFindLastNotOf_Generic().
StringFindLastNotOf_Generic()
static void StringFindLastNotOf_Generic (asIScriptGeneric * gen) [static]
Definition at line 996 of file scriptstdstring.cpp.
References StringFindLastNotOf().
Referenced by RegisterStdString_Generic().
StringFindLastOf()
static int StringFindLastOf (const string & sub, asUINT start, const string & str) [static]
Definition at line 395 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native(), and StringFindLastOf_Generic().
StringFindLastOf_Generic()
static void StringFindLastOf_Generic (asIScriptGeneric * gen) [static]
Definition at line 980 of file scriptstdstring.cpp.
References StringFindLastOf().
Referenced by RegisterStdString_Generic().
StringInsert()
static void StringInsert (unsigned int pos, const string & other, string & str) [static]
Definition at line 437 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native(), and StringInsert_Generic().
StringInsert_Generic()
static void StringInsert_Generic (asIScriptGeneric * gen) [static]
Definition at line 940 of file scriptstdstring.cpp.
References StringInsert().
Referenced by RegisterStdString_Generic().
StringIsEmpty()
static bool StringIsEmpty (const string & str) [static]
Definition at line 179 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native(), and StringIsEmptyGeneric().
StringIsEmptyGeneric()
static void StringIsEmptyGeneric (asIScriptGeneric * gen) [static]
Definition at line 928 of file scriptstdstring.cpp.
References StringIsEmpty().
Referenced by RegisterStdString_Generic().
StringLength()
static asUINT StringLength (const string & str) [static]
Definition at line 454 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
StringLengthGeneric()
static void StringLengthGeneric (asIScriptGeneric * gen) [static]
Definition at line 922 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
StringResize()
static void StringResize (asUINT l, string & str) [static]
Definition at line 463 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
StringResizeGeneric()
static void StringResizeGeneric (asIScriptGeneric * gen) [static]
Definition at line 934 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic().
StringSubString()
static string StringSubString (asUINT start, int count, const string & str) [static]
Definition at line 728 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native(), and StringSubString_Generic().
StringSubString_Generic()
static void StringSubString_Generic (asIScriptGeneric * gen) [static]
Definition at line 1273 of file scriptstdstring.cpp.
References StringSubString().
Referenced by RegisterStdString_Generic().
Variable Documentation
cleaner
CStdStringFactoryCleaner cleaner [static]
Definition at line 149 of file scriptstdstring.cpp.
map_t
BEGIN_AS_NAMESPACE typedef map<string, int> map_t
Definition at line 27 of file scriptstdstring.cpp.
stringFactory
CStdStringFactory* stringFactory = 0 [static]
Definition at line 105 of file scriptstdstring.cpp.
Referenced by ConfigEngineFromStream(), GetStdStringFactorySingleton(), and CStdStringFactoryCleaner::~CStdStringFactoryCleaner().