Atlas::GameCamera Class Reference
Represents a camera wherein the world is rendered and viewed from.
#include <GameCamera.h>
Classes
class CameraInputAction
Like an InputAction, this class is used to handle input for the camera.
class DirectionalInput
Directional input.
Public Member Functions
GameCamera ()
Initializes a new instance of the GameCamera class.
virtual ~GameCamera ()
Finalizes an instance of the GameCamera class.
virtual void init ()
Initializes this instance.
virtual void update ()
Updates this instance in one of two ways, depending on the camera's settings.
virtual Camera3D getCameraData ()
Gets the underlying mCameraData struct.
virtual Vector3 getPosition () const
Returns the current position of this camera.
virtual Vector3 getTarget () const
Returns the current target of this camera.
virtual Vector3 getUp () const
Returns the current up vector of this camera.
virtual float getFovy () const
Gets the camera's fovy (Field of View Y). For more information, please see the section on it in the documentation.
virtual int getProjection () const
Gets the camera's projection.
virtual void setCameraData (Camera3D const &data)
Sets this camera's underlying Camera3D struct.
virtual void setPosition (Vector3 position)
Sets this camera's position.
virtual void setTarget (Vector3 target)
Sets the target.
virtual void setUp (Vector3 up)
Sets the camera's up vector. This function is virtual because it can be overridden by derived classes.
virtual void setFovy (float fovy)
Sets the fovy. This function is virtual because it can be overridden by derived classes.
virtual void setProjection (int projection)
Sets the projection. This function is virtual because it can be overridden by derived classes.
virtual void setAsMainCamera ()
Sets this instance as the main camera. This function is virtual because it can be overridden by derived classes.
virtual bool isMainCamera () const
Checks if this instance is the main camera. This function is virtual because it can be overridden by derived classes.
bool operator== (const GameCamera &other) const =default
Operator==s the specified other.
Static Public Member Functions
static GameCamera * GetMainCamera ()
This function is a static function and is used to get the main camera.
Public Attributes
Camera3D mCameraData = { 0 }
The raylib camera data struct. This is used to interface with raylib.
Protected Types
enum class EMovementDirection {
FORWARD_DIRECTION
, BACKWARD_DIRECTION
, LEFT_DIRECTION
, RIGHT_DIRECTION
,
UP_DIRECTION
, DOWN_DIRECTION
 }
Protected Attributes
std::array< float, 6 > mDirectionalInput = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f }
This is how the CameraInputAction class is used to handle input for the camera.
Private Attributes
uint16_t mCameraID = 0
This camera's unique identifier in the sCameras map.
bool mIsMainCamera = false
A flag that indicates if this camera is the main camera.
Static Private Attributes
static uint16_t sCameraCount = 0
A uint16_t that represents the number of cameras that have been created.
static std::unordered_map< uint16_t, GameCamera * > sCameras
This unordered map contains all of the cameras that have been created.
static GameCamera * sMainCamera = nullptr
This is a pointer to what ever camera is currently the main camera.
Friends
class Renderer
class CameraInputAction
Detailed Description
Represents a camera wherein the world is rendered and viewed from.
Todo
Todo Add 2D camera support.
Since
v0.0.8
Definition at line 23 of file GameCamera.h.
Member Enumeration Documentation
EMovementDirection
enum class Atlas::GameCamera::EMovementDirection [strong], [protected]
Remarks
This enum is used to represent the different directions that the camera can move. This is used in the mDirectionalInput array and is used to access mDirectionalInput[static_cast<size_t>(GameCamera::EMovementDirection::FORWARD_DIRECTION)] within the GameCamera class. It is also used within the CameraInputAction class.
Since
v0.0.8
Enumerator
FORWARD_DIRECTION Represents the forward direction.
Remarks
This is used to move the camera forward.
Since
v0.0.8
BACKWARD_DIRECTION Represents the backward direction.
Remarks
This is used to move the camera backward.
Since
v0.0.8
LEFT_DIRECTION Represents the left direction.
Remarks
This is used to move the camera left.
Since
v0.0.8
RIGHT_DIRECTION Represents the right direction.
Remarks
This is used to move the camera right.
Since
v0.0.8
UP_DIRECTION Represents the up direction.
Remarks
This is used to move the camera up.
Since
v0.0.8
DOWN_DIRECTION Represents the down direction.
Remarks
This is used to move the camera down.
Since
v0.0.8
Definition at line 197 of file GameCamera.h.
Constructor & Destructor Documentation
GameCamera()
Atlas::GameCamera::GameCamera ()
Initializes a new instance of the GameCamera class.
Note
This is the default constructor and does not do anything.
Since
v0.0.3
Definition at line 7 of file GameCamera.cpp.
~GameCamera()
Atlas::GameCamera::~GameCamera () [virtual]
Finalizes an instance of the GameCamera class.
Finalizes an instance of the GameCamera class. Please note that if this is the main camera, it will make the camera with ID 0 the main camera.
Note
Please note that if this is the main camera, it will make the camera with ID 0 the main camera.
Since
v0.0.3
Definition at line 12 of file GameCamera.cpp.
Member Function Documentation
getCameraData()
Camera3D Atlas::GameCamera::getCameraData () [virtual]
Gets the underlying mCameraData struct.
Gets the camera data.
Remarks
The mCameraData struct is used to store the camera's data.
Note
The mCameraData struct type is Raylib's Camera3D type.
Returns
A reference to the underlying mCameraData variable
Definition at line 139 of file GameCamera.cpp.
Referenced by Atlas::Renderer::texture().
getFovy()
float Atlas::GameCamera::getFovy () const [virtual]
Gets the camera's fovy (Field of View Y). For more information, please see the section on it in the documentation.
See also
how-cameras-work
Returns
The camera's fovy (Field of View Y)
Since
v0.0.3
Returns
The camera's fovy
how-cameras-work
Definition at line 166 of file GameCamera.cpp.
GetMainCamera()
Atlas::GameCamera * Atlas::GameCamera::GetMainCamera () [inline], [static]
This function is a static function and is used to get the main camera.
Returns
The main camera
Since
v0.0.3
Definition at line 174 of file GameCamera.cpp.
References sMainCamera.
getPosition()
Vector3 Atlas::GameCamera::getPosition () const [virtual]
Returns the current position of this camera.
Gets the position.
Returns
A Vector3 that represents the current position
Since
v0.0.3
Returns
Definition at line 146 of file GameCamera.cpp.
getProjection()
int Atlas::GameCamera::getProjection () const [virtual]
Gets the camera's projection.
See also
how-cameras-work
Returns
The camera's projection. This is a Raylib enum
Since
v0.0.3
Returns
Definition at line 172 of file GameCamera.cpp.
getTarget()
Vector3 Atlas::GameCamera::getTarget () const [virtual]
Returns the current target of this camera.
Gets the target.
Remarks
In other words, this returns the position that the camera is looking at
Returns
A Vector3 that represents the current target
Since
v0.0.3
Returns
Definition at line 153 of file GameCamera.cpp.
getUp()
Vector3 Atlas::GameCamera::getUp () const [virtual]
Returns the current up vector of this camera.
Gets up.
Returns
A Vector3 that represents the current up vector
Since
v0.0.3
Returns
Definition at line 159 of file GameCamera.cpp.
init()
void Atlas::GameCamera::init () [virtual]
Initializes this instance.
Since
v0.0.3
Definition at line 25 of file GameCamera.cpp.
References Atlas::GetAtlasEngine(), Atlas::INPUT_KEYBOARD, Atlas::INPUT_TRIGGER_DOWN, Atlas::GameCamera::CameraInputAction::moveBackward(), Atlas::GameCamera::CameraInputAction::moveDown(), Atlas::GameCamera::CameraInputAction::moveForward(), Atlas::GameCamera::CameraInputAction::moveLeft(), Atlas::GameCamera::CameraInputAction::moveRight(), Atlas::GameCamera::CameraInputAction::moveUp(), and Atlas::InputRegistry::registerActionCallback().
isMainCamera()
bool Atlas::GameCamera::isMainCamera () const [virtual]
Checks if this instance is the main camera. This function is virtual because it can be overridden by derived classes.
Checks if this instance is the main camera.
Returns
Definition at line 226 of file GameCamera.cpp.
operator==()
bool Atlas::GameCamera::operator== (const GameCamera & other) const [default]
Operator==s the specified other.
Parameters
other The other.
Returns
setAsMainCamera()
void Atlas::GameCamera::setAsMainCamera () [virtual]
Sets this instance as the main camera. This function is virtual because it can be overridden by derived classes.
Sets this instance as the main camera.
Definition at line 216 of file GameCamera.cpp.
setCameraData()
void Atlas::GameCamera::setCameraData (Camera3D const & data) [virtual]
Sets this camera's underlying Camera3D struct.
Sets the camera data.
Parameters
data A const reference to a Camera3D struct.
Note
The parameter is a const reference to a Camera3D struct, but the function just copies the struct to the mCameraData struct.
Since
v0.0.3
Parameters
data The data.
Definition at line 180 of file GameCamera.cpp.
setFovy()
void Atlas::GameCamera::setFovy (float fovy) [virtual]
Sets the fovy. This function is virtual because it can be overridden by derived classes.
Sets the fovy.
Parameters
fovy The fovy.
Definition at line 204 of file GameCamera.cpp.
Referenced by Atlas::Renderer::Renderer().
setPosition()
void Atlas::GameCamera::setPosition (Vector3 position) [virtual]
Sets this camera's position.
Sets the position.
Parameters
position The position that this camera should be at
Since
v0.0.3
Parameters
position The position.
Definition at line 186 of file GameCamera.cpp.
Referenced by Atlas::Renderer::Renderer().
setProjection()
void Atlas::GameCamera::setProjection (int projection) [virtual]
Sets the projection. This function is virtual because it can be overridden by derived classes.
Sets the projection.
Parameters
projection The projection.
Definition at line 210 of file GameCamera.cpp.
Referenced by Atlas::Renderer::Renderer().
setTarget()
void Atlas::GameCamera::setTarget (Vector3 target) [virtual]
Sets the target.
Parameters
target The target.
Definition at line 192 of file GameCamera.cpp.
Referenced by Atlas::Renderer::Renderer().
setUp()
void Atlas::GameCamera::setUp (Vector3 up) [virtual]
Sets the camera's up vector. This function is virtual because it can be overridden by derived classes.
Sets up.
Parameters
up Up.
Definition at line 198 of file GameCamera.cpp.
Referenced by Atlas::Renderer::Renderer().
update()
void Atlas::GameCamera::update () [virtual]
Updates this instance in one of two ways, depending on the camera's settings.
Remarks
For a more in-depth explanation of camera settings, see how-cameras-work and GameCamera in the documentation.
Since
v0.0.3
Definition at line 4 of file Camera.cpp.
Friends And Related Symbol Documentation
CameraInputAction
friend class CameraInputAction [friend]
Remarks
The CameraInputAction class (
See also
CameraInputAction) is being friended here because it requires access to this camera's mDirectionalInput.
Since
v0.0.8
Definition at line 187 of file GameCamera.h.
Renderer
friend class Renderer [friend]
Remarks
The Renderer class is being friended here because it requires access to this camera's updating and other functions.
Since
v0.0.3
Definition at line 179 of file GameCamera.h.
Member Data Documentation
mCameraData
Camera3D Atlas::GameCamera::mCameraData = { 0 }
The raylib camera data struct. This is used to interface with raylib.
Definition at line 455 of file GameCamera.h.
mCameraID
uint16_t Atlas::GameCamera::mCameraID = 0 [private]
This camera's unique identifier in the sCameras map.
Remarks
this is a uint16_t that is used as a key in the sCameras map.
Since
v0.0.3
Definition at line 165 of file GameCamera.h.
mDirectionalInput
std::array<float, 6> Atlas::GameCamera::mDirectionalInput = { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } [protected]
This is how the CameraInputAction class is used to handle input for the camera.
Remarks
The CameraInputAction class is used to handle input for the camera. Each CameraInputAction is assigned a direction. Then that direction is used to move the camera in that direction. The EMovementDirection enum is used to represent the directions, aka the index within this array. To see this in action, please see the how-cameras-work and GameCamera in the documentation.
Since
v0.0.8
Definition at line 315 of file GameCamera.h.
mIsMainCamera
bool Atlas::GameCamera::mIsMainCamera = false [private]
A flag that indicates if this camera is the main camera.
Remarks
This is set to true if this camera is the main camera. If this is the main camera, then it will set the sMainCamera. This can happen in
Since
v0.0.3
Definition at line 173 of file GameCamera.h.
sCameraCount
uint16_t Atlas::GameCamera::sCameraCount = 0 [inline], [static], [private]
A uint16_t that represents the number of cameras that have been created.
Remarks
This is static inline and is incremented every time a camera is created. This is also used to create the camera identifiers before they are put in sCameras.
Since
v0.0.3
Definition at line 142 of file GameCamera.h.
sCameras
std::unordered_map<uint16_t, GameCamera*> Atlas::GameCamera::sCameras [inline], [static], [private]
This unordered map contains all of the cameras that have been created.
Remarks
This is static inline and is used to store all of the cameras that have been created. The uint16_t represents the camera's identifier. The reason for why it is a uint16_t is because it is used as a key in the map and there does not need to be more than 65535 cameras.
Note
The GameCamera is stored as a pointer to the camera.
Since
v0.0.3
Definition at line 152 of file GameCamera.h.
sMainCamera
GameCamera* Atlas::GameCamera::sMainCamera = nullptr [inline], [static], [private]
This is a pointer to what ever camera is currently the main camera.
Since
v0.0.3
Definition at line 158 of file GameCamera.h.
Referenced by GetMainCamera().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/renderer/GameCamera.h
C:/Dev/Techstorm-v5/src/engine/renderer/Camera.cpp
C:/Dev/Techstorm-v5/src/engine/renderer/GameCamera.cpp