Atlas::Pipeline Class Reference
#include <VKDevice.h>
Public Member Functions
Pipeline ()=default
void createLayout (VkPipelineLayoutCreateInfo layoutInfo, VkDevice *device)
void createLayout (VkDevice *device, VkDescriptorSetLayout *descriptorSetLayout)
void init (VkDevice *device, DeletionQueue *deletionQueue, VkPipelineShaderStageCreateInfo stageInfo, VkComputePipelineCreateInfo pipelineInfo)
void destroyPipeline (VkDevice *device)
Protected Attributes
VkPipelineLayoutCreateInfo mComputeLayoutInfo
VkPushConstantRange mPushConstantRange
VkPipeline mPipeline = VK_NULL_HANDLE
VkPipelineLayout mPipelineLayout = VK_NULL_HANDLE
Shader mShader
Detailed Description
Definition at line 204 of file VKDevice.h.
Constructor & Destructor Documentation
Pipeline()
Atlas::Pipeline::Pipeline () [default]
Member Function Documentation
createLayout() [1/2]
void Atlas::Pipeline::createLayout (VkDevice * device, VkDescriptorSetLayout * descriptorSetLayout)
Definition at line 1255 of file VKDevice.cpp.
createLayout() [2/2]
void Atlas::Pipeline::createLayout (VkPipelineLayoutCreateInfo layoutInfo, VkDevice * device)
Definition at line 1250 of file VKDevice.cpp.
destroyPipeline()
void Atlas::Pipeline::destroyPipeline (VkDevice * device) [inline]
Definition at line 231 of file VKDevice.h.
References mPipeline, and mPipelineLayout.
Referenced by init().
init()
void Atlas::Pipeline::init (VkDevice * device, DeletionQueue * deletionQueue, VkPipelineShaderStageCreateInfo stageInfo, VkComputePipelineCreateInfo pipelineInfo) [inline]
Definition at line 221 of file VKDevice.h.
References destroyPipeline(), Atlas::Shader::getModule(), mPipeline, mShader, and Atlas::DeletionQueue::push().
Member Data Documentation
mComputeLayoutInfo
VkPipelineLayoutCreateInfo Atlas::Pipeline::mComputeLayoutInfo [protected]
Definition at line 206 of file VKDevice.h.
mPipeline
VkPipeline Atlas::Pipeline::mPipeline = VK_NULL_HANDLE [protected]
Definition at line 209 of file VKDevice.h.
Referenced by destroyPipeline(), and init().
mPipelineLayout
VkPipelineLayout Atlas::Pipeline::mPipelineLayout = VK_NULL_HANDLE [protected]
Definition at line 210 of file VKDevice.h.
Referenced by destroyPipeline().
mPushConstantRange
VkPushConstantRange Atlas::Pipeline::mPushConstantRange [protected]
Definition at line 207 of file VKDevice.h.
mShader
Shader Atlas::Pipeline::mShader [protected]
Definition at line 212 of file VKDevice.h.
Referenced by init().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/graphics/backend/VKDevice.h
C:/Dev/Techstorm-v5/src/engine/graphics/backend/VKDevice.cpp