SamplesProject Class Reference
#include <SamplesProject.h>
Public Member Functions
SamplesProject ()
void postInit () override
Does a post initialization of the project. This is empty because it is not neccesary to override.
void addSampleGroup (SampleGroup *group)
SampleGroup * getSampleGroup (std::string name)
int update () override
Updates this instance in the updating thread.
Public Member Functions inherited from Atlas::BProject
BProject ()
This is a default constructor that will initialize Atlas and the user's project.
ScriptingLibraryRegistry & getLuaLibraries ()
Returns the currently active libraries for lua.
ScriptingFunctionRegistry & getLuaFunctions ()
Gets the lua functions.
WindowDecorations & getWindowDecorations ()
Gets the window decorations. This includes the window title, icon, size, etc.
void setWindowDecorations (WindowDecorations &windowDecorations)
Sets the window decorations.
template<typename T >
void setProject (T *project)
This function is used to set the ProjectReference singleton to the project.
virtual void preInit () override
This is the first function that will be called on startup.
virtual void init (int argc, char *argv[]) override
Initializes your project. This will be called after preInit and window initialization, meaning that this is the earliest point that you can use raylib. THIS MUST BE OVERRIDEN BY YOUR PROJECT CLASS!
virtual void initRenderer () override
Initializes the renderer and should be called after initWindow.
virtual int run (int argc, char *argv[]) override
Runs the actual game and is called after the init functions.
virtual int workingUpdate () override
virtual int prePhysicsUpdate () override
Pre-update step that is called in the physics or update thread (depending on thread count)
virtual int physicsUpdate () override
This is where the actual physics update happens. Please note that this will run on the physics thread!
virtual int postPhysicsUpdate () override
Post physics update that is called after physicsUpdate() in the physics or update thread (depending on thread count).
virtual int preObjectUpdate () override
Any preparation code for updating the scene's game objects. Use this if you need to do something after the physics update, but before the GameObject update. Please note that this will run on the update thread!
virtual int objectUpdate () override
This is where the actual GameObject update happens, and is called after preObjectUpdate(). Please note that this will run on the update thread!
virtual int postObjectUpdate () override
Called right after objectUpdate(). Use this to do anything after the GameObject update. Please note that this will run on the update thread!
virtual int texture () override
Textures all GameObjects before render() is called and after update functions are called. This is essentially where the scene is rendered. Please note that this will run on the render thread!
virtual int render () override
Assuming that the FBO is enabled, this will render the FBO and apply any post-processing effects to the FBO. Please note that this will run on the update thread!
virtual int draw () override
virtual int cleanup (int exitCode) override
Cleans up anything that may need to be cleaned up.
ThreadSafeVariable< AtlasEngine * > getAtlasEngine () override
Get the Atlas Engine object.
Static Private Attributes
static std::unordered_map< std::string, SampleGroup * > mSamples
Additional Inherited Members
Static Public Member Functions inherited from Atlas::BProject
static std::shared_ptr< BProject > GetProject ()
Get the Project object.
Public Attributes inherited from Atlas::BProject
GameSettings settings
Static Public Attributes inherited from Atlas::BProject
static ThreadSafeVariable< AtlasEngine * > mAtlas = nullptr
Protected Member Functions inherited from Atlas::BProject
virtual ThreadSafeVariable< AtlasEngine * > setupAtlas () override
Protected Attributes inherited from Atlas::BProject
bool mHasCleanedUp = false
A flag that indicates whether or not the project has been cleaned up.
WindowDecorations mWindowDecorations
ScriptingLibraryRegistry mLuaLibraries
ScriptingFunctionRegistry mLuaFunctions
Static Protected Attributes inherited from Atlas::BProject
static std::shared_ptr< BProject > mProject = nullptr
Detailed Description
Definition at line 10 of file SamplesProject.h.
Constructor & Destructor Documentation
SamplesProject()
SamplesProject::SamplesProject () [inline]
Definition at line 13 of file SamplesProject.h.
Member Function Documentation
addSampleGroup()
void SamplesProject::addSampleGroup (SampleGroup * group) [inline]
Definition at line 19 of file SamplesProject.h.
References SampleGroup::getName(), and mSamples.
Referenced by postInit().
getSampleGroup()
SampleGroup * SamplesProject::getSampleGroup (std::string name) [inline]
Definition at line 23 of file SamplesProject.h.
References mSamples.
postInit()
void SamplesProject::postInit () [inline], [override], [virtual]
Does a post initialization of the project. This is empty because it is not neccesary to override.
Reimplemented from Atlas::BProject.
Definition at line 15 of file SamplesProject.h.
References addSampleGroup().
update()
int SamplesProject::update () [inline], [override], [virtual]
Updates this instance in the updating thread.
Returns
Reimplemented from Atlas::BProject.
Definition at line 27 of file SamplesProject.h.
Member Data Documentation
mSamples
std::unordered_map<std::string, SampleGroup*> SamplesProject::mSamples [inline], [static], [private]
Definition at line 32 of file SamplesProject.h.
Referenced by addSampleGroup(), and getSampleGroup().
The documentation for this class was generated from the following file:
C:/Dev/Techstorm-v5/src/project/samples/SamplesProject.h