Atlas::VulkanRenderer Class Reference
#include <VulkanRenderer.h>
Public Member Functions
VulkanRenderer (AGameWindow *gameWindow, VulkanRenderingBackend *backend)
VulkanRenderer (AGameWindow *gameWindow)
void init () override
This is one of the most important methods in this class. It is responsible for initializing the renderer, ensuring that all setup is done correctly. It should initialize the main game window using whatever methods are needed to do so. It should also initialize the rendering backend.
void update () override
void cleanup () override
bool shouldExit () override
ARenderer (AGameWindow *gameWindow, RenderingBackend *backend, bool canBeMultiThreaded)
ARenderer (AGameWindow *gameWindow, RenderingBackend *backend)
Sets the main game window and rendering backend to the specified parameters.
Public Member Functions inherited from Atlas::ARenderer
ARenderer (AGameWindow *gameWindow, RenderingBackend *backend)
Sets the main game window and rendering backend to the specified parameters.
bool canBeMultiThreaded () const
bool isInitialized () const
template<typename T_BACKEND_TYPE >
T_BACKEND_TYPE * castRenderingBackendAs ()
Public Member Functions inherited from Atlas::EngineModule
virtual bool isReady ()
virtual bool isEnabled ()
Public Member Functions inherited from Atlas::ScriptedObject
virtual void exposeScriptingSymbols ()
A virtual function that is called when scripting is initializing. Override this if the child class needs to contribute symbols to the overall scripting API. This can include functions, globals, etc.
bool isScriptingAllowed () const
Returns whether or not this object is allowed to be scripted.
void disallowScripting ()
void allowScripting ()
void toggleScripting ()
void setScriptingAllowed (const bool cbAllowed)
Static Private Member Functions
static bool WindowShouldClose (AGameWindow *gameWindow)
Additional Inherited Members
Public Attributes inherited from Atlas::ARenderer
AGameWindow * mainGameWindow = nullptr
A polymorphic pointer to the main window that the renderer is rendering to.
RenderingBackend * renderingBackend = nullptr
A polymorphic pointer to the rendering backend that the renderer is using.
Protected Member Functions inherited from Atlas::ARenderer
ARenderer (AGameWindow *gameWindow, RenderingBackend *backend, bool canBeMultiThreaded)
Protected Attributes inherited from Atlas::ARenderer
bool mIsInitialized = false
Whether or not the renderer has been initialized.
const bool mCanBeMultiThreaded = false
Signals to Atlas whether or not the renderer can be multi-threaded. By default it is set to false.
Detailed Description
Definition at line 12 of file VulkanRenderer.h.
Constructor & Destructor Documentation
VulkanRenderer() [1/2]
Atlas::VulkanRenderer::VulkanRenderer (AGameWindow * gameWindow, VulkanRenderingBackend * backend)
Definition at line 5 of file VulkanRenderer.cpp.
VulkanRenderer() [2/2]
Atlas::VulkanRenderer::VulkanRenderer (AGameWindow * gameWindow) [explicit]
Definition at line 10 of file VulkanRenderer.cpp.
Member Function Documentation
ARenderer() [1/2]
Atlas::ARenderer::ARenderer (AGameWindow * gameWindow, RenderingBackend * backend)
Sets the main game window and rendering backend to the specified parameters.
Parameters
gameWindow
backend
Since
v
Definition at line 99 of file Renderer.cpp.
ARenderer() [2/2]
Atlas::ARenderer::ARenderer (AGameWindow * gameWindow, RenderingBackend * backend, bool canBeMultiThreaded)
Definition at line 63 of file Renderer.cpp.
cleanup()
void Atlas::VulkanRenderer::cleanup () [override], [virtual]
Implements Atlas::ARenderer.
Definition at line 60 of file VulkanRenderer.cpp.
init()
void Atlas::VulkanRenderer::init () [override], [virtual]
This is one of the most important methods in this class. It is responsible for initializing the renderer, ensuring that all setup is done correctly. It should initialize the main game window using whatever methods are needed to do so. It should also initialize the rendering backend.
Since
v
Implements Atlas::ARenderer.
Definition at line 15 of file VulkanRenderer.cpp.
References init().
Referenced by init().
shouldExit()
bool Atlas::VulkanRenderer::shouldExit () [override], [virtual]
Implements Atlas::ARenderer.
Definition at line 68 of file VulkanRenderer.cpp.
update()
void Atlas::VulkanRenderer::update () [override], [virtual]
Implements Atlas::ARenderer.
Definition at line 25 of file VulkanRenderer.cpp.
WindowShouldClose()
static bool Atlas::VulkanRenderer::WindowShouldClose (AGameWindow * gameWindow) [inline], [static], [private]
Definition at line 14 of file VulkanRenderer.h.
References Atlas::AGameWindow::shouldClose().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/graphics/VulkanRenderer.h
C:/Dev/Techstorm-v5/src/engine/graphics/VulkanRenderer.cpp