C:/Dev/Techstorm-v5/src/application/add_on/datetime/datetime.cpp File Reference
#include "datetime.h"
#include "../autowrapper/aswrappedcall.h"
#include <string.h>
#include <assert.h>
#include <new>
Functions
static BEGIN_AS_NAMESPACE tm time_point_to_tm (const std::chrono::time_point< std::chrono::system_clock > &tp)
static bool tm_to_time_point (const tm &_tm, std::chrono::time_point< std::chrono::system_clock > &tp)
CDateTime operator+ (asINT64 seconds, const CDateTime &other)
CDateTime operator- (asINT64 seconds, const CDateTime &other)
static int opCmp (const CDateTime &a, const CDateTime &b)
static void Construct (CDateTime *mem)
static void ConstructCopy (CDateTime *mem, const CDateTime &o)
static void ConstructSet (CDateTime *mem, asUINT year, asUINT month, asUINT day, asUINT hour, asUINT minute, asUINT second)
static void ConstructSet_Generic (asIScriptGeneric *gen)
void RegisterScriptDateTime (asIScriptEngine *engine)
Function Documentation
Construct()
static void Construct (CDateTime * mem) [static]
Definition at line 208 of file datetime.cpp.
Referenced by RegisterScriptDateTime().
ConstructCopy()
static void ConstructCopy (CDateTime * mem, const CDateTime & o) [static]
Definition at line 213 of file datetime.cpp.
Referenced by RegisterScriptDateTime().
ConstructSet()
static void ConstructSet (CDateTime * mem, asUINT year, asUINT month, asUINT day, asUINT hour, asUINT minute, asUINT second) [static]
Definition at line 218 of file datetime.cpp.
Referenced by ConstructSet_Generic(), and RegisterScriptDateTime().
ConstructSet_Generic()
static void ConstructSet_Generic (asIScriptGeneric * gen) [static]
Definition at line 223 of file datetime.cpp.
References ConstructSet().
Referenced by RegisterScriptDateTime().
opCmp()
static int opCmp (const CDateTime & a, const CDateTime & b) [static]
Definition at line 201 of file datetime.cpp.
Referenced by RegisterScriptDateTime().
operator+()
CDateTime operator+ (asINT64 seconds, const CDateTime & other)
Definition at line 171 of file datetime.cpp.
operator-()
CDateTime operator- (asINT64 seconds, const CDateTime & other)
Definition at line 186 of file datetime.cpp.
RegisterScriptDateTime()
void RegisterScriptDateTime (asIScriptEngine * engine)
Definition at line 235 of file datetime.cpp.
References Construct(), ConstructCopy(), ConstructSet(), ConstructSet_Generic(), opCmp(), WRAP_MFN, WRAP_MFN_PR, WRAP_OBJ_FIRST, WRAP_OBJ_LAST, and WRAP_OBJ_LAST_PR.
time_point_to_tm()
static BEGIN_AS_NAMESPACE tm time_point_to_tm (const std::chrono::time_point< std::chrono::system_clock > & tp) [static]
Definition at line 14 of file datetime.cpp.
Referenced by CDateTime::getDay(), CDateTime::getHour(), CDateTime::getMinute(), CDateTime::getMonth(), CDateTime::getSecond(), CDateTime::getYear(), CDateTime::setDate(), and CDateTime::setTime().
tm_to_time_point()
static bool tm_to_time_point (const tm & _tm, std::chrono::time_point< std::chrono::system_clock > & tp) [static]
Definition at line 30 of file datetime.cpp.
Referenced by CDateTime::setDate(), and CDateTime::setTime().