Atlas::HandleWrapperBase< T_WRAPS > Class Template Reference
#include <Common.h>
Public Member Functions
HandleWrapperBase (T_WRAPS handle, T_WRAPS invalidHandle)
explicit (false) HandleWrapperBase(T_WRAPS handle)
HandleWrapperBase ()=default
virtual bool hasValidHandle () const
virtual bool isValid () const override
T_WRAPS getHandle () const
explicit (false) operator const T_WRAPS &() const
explicit (false) operator T_WRAPS &()
Public Member Functions inherited from Atlas::InitializableAndValidatable
InitializableAndValidatable (bool bIsInit, bool bIsValid)
InitializableAndValidatable ()=default
Public Member Functions inherited from Atlas::Initializable
ATLAS_EXPLICIT Initializable (bool bIsInit)
Initializable ()=default
virtual ~Initializable ()=default
virtual bool isInit () const
Public Member Functions inherited from Atlas::Validatable
ATLAS_EXPLICIT Validatable (bool bIsValid)
Validatable ()=default
virtual ~Validatable ()=default
virtual ATLAS_IMPLICIT operator bool () const
Protected Member Functions
T_WRAPS & getInternalHandleValue ()
void setHandle (T_WRAPS handle)
Protected Member Functions inherited from Atlas::Initializable
bool & getInternalInitValue ()
virtual void setInitState (bool bNewInitState)
virtual void setInit ()
virtual void setNotInit ()
Protected Member Functions inherited from Atlas::Validatable
bool & getInternalValidityValue ()
virtual void setValidity (bool bIsValid)
virtual void setValid ()
virtual void setInvalid ()
Private Attributes
T_WRAPS mHandle
const T_WRAPS mInvalidHandle
Detailed Description
template<typename T_WRAPS>
class Atlas::HandleWrapperBase< T_WRAPS >
Definition at line 344 of file Common.h.
Constructor & Destructor Documentation
HandleWrapperBase() [1/2]
template<typename T_WRAPS >
Atlas::HandleWrapperBase< T_WRAPS >::HandleWrapperBase (T_WRAPS handle, T_WRAPS invalidHandle) [inline]
Definition at line 373 of file Common.h.
HandleWrapperBase() [2/2]
template<typename T_WRAPS >
Atlas::HandleWrapperBase< T_WRAPS >::HandleWrapperBase () [default]
Member Function Documentation
explicit() [1/3]
template<typename T_WRAPS >
Atlas::HandleWrapperBase< T_WRAPS >::explicit (false) [inline]
Definition at line 375 of file Common.h.
explicit() [2/3]
template<typename T_WRAPS >
Atlas::HandleWrapperBase< T_WRAPS >::explicit (false) const & [inline]
Definition at line 391 of file Common.h.
References Atlas::HandleWrapperBase< T_WRAPS >::mHandle.
explicit() [3/3]
template<typename T_WRAPS >
Atlas::HandleWrapperBase< T_WRAPS >::explicit (false) & [inline]
Definition at line 395 of file Common.h.
References Atlas::HandleWrapperBase< T_WRAPS >::mHandle.
getHandle()
template<typename T_WRAPS >
T_WRAPS Atlas::HandleWrapperBase< T_WRAPS >::getHandle () const [inline]
Definition at line 387 of file Common.h.
References Atlas::HandleWrapperBase< T_WRAPS >::mHandle.
getInternalHandleValue()
template<typename T_WRAPS >
T_WRAPS & Atlas::HandleWrapperBase< T_WRAPS >::getInternalHandleValue () [inline], [protected]
Definition at line 352 of file Common.h.
References Atlas::HandleWrapperBase< T_WRAPS >::mHandle.
hasValidHandle()
template<typename T_WRAPS >
virtual bool Atlas::HandleWrapperBase< T_WRAPS >::hasValidHandle () const [inline], [virtual]
Definition at line 379 of file Common.h.
References Atlas::HandleWrapperBase< T_WRAPS >::mHandle, and Atlas::HandleWrapperBase< T_WRAPS >::mInvalidHandle.
Referenced by Atlas::HandleWrapperBase< T_WRAPS >::isValid().
isValid()
template<typename T_WRAPS >
virtual bool Atlas::HandleWrapperBase< T_WRAPS >::isValid () const [inline], [override], [virtual]
Reimplemented from Atlas::InitializableAndValidatable.
Definition at line 383 of file Common.h.
References Atlas::HandleWrapperBase< T_WRAPS >::hasValidHandle(), and Atlas::InitializableAndValidatable::isValid().
setHandle()
template<typename T_WRAPS >
void Atlas::HandleWrapperBase< T_WRAPS >::setHandle (T_WRAPS handle) [inline], [protected]
Definition at line 356 of file Common.h.
References Atlas::HandleWrapperBase< T_WRAPS >::mHandle, Atlas::HandleWrapperBase< T_WRAPS >::mInvalidHandle, Atlas::Initializable::setInit(), Atlas::Validatable::setInvalid(), Atlas::Initializable::setNotInit(), and Atlas::Validatable::setValid().
Member Data Documentation
mHandle
template<typename T_WRAPS >
T_WRAPS Atlas::HandleWrapperBase< T_WRAPS >::mHandle [private]
Definition at line 349 of file Common.h.
Referenced by Atlas::HandleWrapperBase< T_WRAPS >::explicit(), Atlas::HandleWrapperBase< T_WRAPS >::explicit(), Atlas::HandleWrapperBase< T_WRAPS >::getHandle(), Atlas::HandleWrapperBase< T_WRAPS >::getInternalHandleValue(), Atlas::HandleWrapperBase< T_WRAPS >::hasValidHandle(), and Atlas::HandleWrapperBase< T_WRAPS >::setHandle().
mInvalidHandle
template<typename T_WRAPS >
const T_WRAPS Atlas::HandleWrapperBase< T_WRAPS >::mInvalidHandle [private]
Definition at line 350 of file Common.h.
Referenced by Atlas::HandleWrapperBase< T_WRAPS >::hasValidHandle(), and Atlas::HandleWrapperBase< T_WRAPS >::setHandle().
The documentation for this class was generated from the following file:
C:/Dev/Techstorm-v5/src/engine/core/Common.h