Atlas::AGameWindow Class Reference
An interface that allows the creation of custom window classes in an API-agnostic way. It contains some general pure virtual functions that are required to create a window. This interface is what Atlas stores a pointer as when creating a window.
#include <Window.h>
Public Member Functions
AGameWindow (const uint32_t cGraphicsAPIFlag)
AGameWindow ()=default
virtual ~AGameWindow ()=default
virtual void init (const uint32_t cInitFlags)=0
virtual void update ()=0
virtual void open (const uint32_t cOpenFlags)=0
virtual bool isOpen () const =0
virtual void close ()=0
virtual bool shouldClose ()=0
virtual void cleanup ()=0
virtual bool isInitialized () const =0
virtual void setHint (WindowHint const &hint)=0
virtual void setIcon (std::string const &newIconPath)=0
virtual void setWindowTitle (std::string const &newWindowTitle)=0
virtual void setWindowPosition (int newX, int newY)=0
virtual void setWindowSize (int16_t newWidth, int16_t newHeight)=0
virtual void setTargetFPS (int16_t newTargetFPS)=0
virtual void * getUncastWindowHandle ()=0
virtual WindowDescription getWindowDescription () const
Protected Attributes
std::string mWindowTitle
std::string mIconPath
WindowRectangle mWindowRect
int16_t mTargetFPS
bool mIsInitialized = false
bool mIsOpen = false
bool mShouldClose = false
Static Protected Attributes
static bool sHasSetGraphicsAPIFlag = false
static uint32_t sGraphicsAPIFlag = -1
Detailed Description
An interface that allows the creation of custom window classes in an API-agnostic way. It contains some general pure virtual functions that are required to create a window. This interface is what Atlas stores a pointer as when creating a window.
Note
If you want to make your own window class and you don't want to use the NullGameWindow class, you should inherit from this interface instead.
Since
v0.0.1
Definition at line 87 of file Window.h.
Constructor & Destructor Documentation
AGameWindow() [1/2]
Atlas::AGameWindow::AGameWindow (const uint32_t cGraphicsAPIFlag) [inline], [explicit]
Definition at line 107 of file Window.h.
References sGraphicsAPIFlag, and sHasSetGraphicsAPIFlag.
AGameWindow() [2/2]
Atlas::AGameWindow::AGameWindow () [default]
~AGameWindow()
virtual Atlas::AGameWindow::~AGameWindow () [virtual], [default]
Member Function Documentation
cleanup()
virtual void Atlas::AGameWindow::cleanup () [pure virtual]
Implemented in Atlas::SDLGameWindow.
close()
virtual void Atlas::AGameWindow::close () [pure virtual]
Implemented in Atlas::SDLGameWindow.
getUncastWindowHandle()
virtual void * Atlas::AGameWindow::getUncastWindowHandle () [pure virtual]
Implemented in Atlas::SDLGameWindow.
Referenced by Atlas::VulkanRenderingBackend::init(), and Atlas::VulkanRenderingBackend::initIMGUI().
getWindowDescription()
virtual WindowDescription Atlas::AGameWindow::getWindowDescription () const [inline], [virtual]
Definition at line 149 of file Window.h.
References mIconPath, mTargetFPS, mWindowRect, mWindowTitle, and Atlas::WindowDescription::title.
Referenced by Atlas::VulkanRenderingBackend::initSwapchain().
init()
virtual void Atlas::AGameWindow::init (const uint32_t cInitFlags) [pure virtual]
Implemented in Atlas::SDLGameWindow.
isInitialized()
virtual bool Atlas::AGameWindow::isInitialized () const [pure virtual]
Implemented in Atlas::SDLGameWindow.
Referenced by Atlas::VulkanRenderingBackend::canInitialize().
isOpen()
virtual bool Atlas::AGameWindow::isOpen () const [pure virtual]
Implemented in Atlas::SDLGameWindow.
Referenced by Atlas::VulkanRenderingBackend::canInitialize().
open()
virtual void Atlas::AGameWindow::open (const uint32_t cOpenFlags) [pure virtual]
Implemented in Atlas::SDLGameWindow.
setHint()
virtual void Atlas::AGameWindow::setHint (WindowHint const & hint) [pure virtual]
Implemented in Atlas::SDLGameWindow.
setIcon()
virtual void Atlas::AGameWindow::setIcon (std::string const & newIconPath) [pure virtual]
Implemented in Atlas::SDLGameWindow.
setTargetFPS()
virtual void Atlas::AGameWindow::setTargetFPS (int16_t newTargetFPS) [pure virtual]
Implemented in Atlas::SDLGameWindow.
setWindowPosition()
virtual void Atlas::AGameWindow::setWindowPosition (int newX, int newY) [pure virtual]
Implemented in Atlas::SDLGameWindow.
setWindowSize()
virtual void Atlas::AGameWindow::setWindowSize (int16_t newWidth, int16_t newHeight) [pure virtual]
Implemented in Atlas::SDLGameWindow.
setWindowTitle()
virtual void Atlas::AGameWindow::setWindowTitle (std::string const & newWindowTitle) [pure virtual]
Implemented in Atlas::SDLGameWindow.
shouldClose()
virtual bool Atlas::AGameWindow::shouldClose () [pure virtual]
Implemented in Atlas::SDLGameWindow.
Referenced by Atlas::VulkanRenderer::WindowShouldClose().
update()
virtual void Atlas::AGameWindow::update () [pure virtual]
Implemented in Atlas::SDLGameWindow.
Member Data Documentation
mIconPath
std::string Atlas::AGameWindow::mIconPath [protected]
Definition at line 93 of file Window.h.
Referenced by getWindowDescription().
mIsInitialized
bool Atlas::AGameWindow::mIsInitialized = false [protected]
Definition at line 99 of file Window.h.
Referenced by Atlas::SDLGameWindow::init().
mIsOpen
bool Atlas::AGameWindow::mIsOpen = false [protected]
Definition at line 101 of file Window.h.
mShouldClose
bool Atlas::AGameWindow::mShouldClose = false [protected]
Definition at line 103 of file Window.h.
mTargetFPS
int16_t Atlas::AGameWindow::mTargetFPS [protected]
Definition at line 97 of file Window.h.
Referenced by getWindowDescription().
mWindowRect
WindowRectangle Atlas::AGameWindow::mWindowRect [protected]
Definition at line 95 of file Window.h.
Referenced by getWindowDescription().
mWindowTitle
std::string Atlas::AGameWindow::mWindowTitle [protected]
Definition at line 92 of file Window.h.
Referenced by getWindowDescription().
sGraphicsAPIFlag
uint32_t Atlas::AGameWindow::sGraphicsAPIFlag = -1 [inline], [static], [protected]
Definition at line 90 of file Window.h.
Referenced by AGameWindow().
sHasSetGraphicsAPIFlag
bool Atlas::AGameWindow::sHasSetGraphicsAPIFlag = false [inline], [static], [protected]
Definition at line 89 of file Window.h.
Referenced by AGameWindow().
The documentation for this class was generated from the following file:
C:/Dev/Techstorm-v5/src/engine/graphics/window/Window.h