C:/Dev/Techstorm-v5/src/engine/modding/add_on/scriptstdstring/scriptstdstring.cpp File Reference
#include "scriptstdstring.h"
#include <assert.h>
#include <sstream>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <locale.h>
#include <map>
Classes
class CStdStringFactory
class CStdStringFactoryCleaner
Macros
#define UNUSED_VAR(x) (void)(x)
Functions
CStdStringFactory * GetStdStringFactorySingleton ()
double parseFloat (const string &val, asUINT *byteCount)
void RegisterStdString_Native (asIScriptEngine *engine)
void RegisterStdString_Generic (asIScriptEngine *engine)
void RegisterStdString (asIScriptEngine *engine)
Variables
BEGIN_AS_NAMESPACE typedef map< string, int > map_t
Macro Definition Documentation
UNUSED_VAR
#define UNUSED_VAR(x) (void)(x)
Definition at line 15 of file scriptstdstring.cpp.
Function Documentation
GetStdStringFactorySingleton()
CStdStringFactory * GetStdStringFactorySingleton ()
Definition at line 110 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Generic(), and RegisterStdString_Native().
parseFloat()
double parseFloat (const string & val, asUINT * byteCount)
Definition at line 696 of file scriptstdstring.cpp.
Referenced by RegisterStdString_Native().
RegisterStdString()
void RegisterStdString (asIScriptEngine * engine)
Definition at line 1367 of file scriptstdstring.cpp.
References RegisterStdString_Generic(), and RegisterStdString_Native().
RegisterStdString_Generic()
void RegisterStdString_Generic (asIScriptEngine * engine)
Definition at line 1284 of file scriptstdstring.cpp.
References GetStdStringFactorySingleton(), and UNUSED_VAR.
Referenced by RegisterStdString().
RegisterStdString_Native()
void RegisterStdString_Native (asIScriptEngine * engine)
Definition at line 749 of file scriptstdstring.cpp.
References GetStdStringFactorySingleton(), parseFloat(), and UNUSED_VAR.
Referenced by RegisterStdString().
Variable Documentation
map_t
BEGIN_AS_NAMESPACE typedef map<string, int> map_t
Definition at line 27 of file scriptstdstring.cpp.