CScriptBuilder Class Reference
#include <scriptbuilder.h>
Classes
struct SClassMetadata
struct SMetadataDecl
Public Member Functions
CScriptBuilder ()
int StartNewModule (asIScriptEngine *engine, const char *moduleName)
int AddSectionFromFile (const char *filename)
int AddSectionFromMemory (const char *sectionName, const char *scriptCode, unsigned int scriptLength=0, int lineOffset=0)
int BuildModule ()
asIScriptEngine * GetEngine ()
asIScriptModule * GetModule ()
void SetIncludeCallback (INCLUDECALLBACK_t callback, void *userParam)
void SetPragmaCallback (PRAGMACALLBACK_t callback, void *userParam)
void DefineWord (const char *word)
unsigned int GetSectionCount () const
std::string GetSectionName (unsigned int idx) const
std::vector< std::string > GetMetadataForType (int typeId)
std::vector< std::string > GetMetadataForFunc (asIScriptFunction *func)
std::vector< std::string > GetMetadataForVar (int varIdx)
std::vector< std::string > GetMetadataForTypeProperty (int typeId, int varIdx)
std::vector< std::string > GetMetadataForTypeMethod (int typeId, asIScriptFunction *method)
CScriptBuilder ()
int StartNewModule (asIScriptEngine *engine, const char *moduleName)
int AddSectionFromFile (const char *filename)
int AddSectionFromMemory (const char *sectionName, const char *scriptCode, unsigned int scriptLength=0, int lineOffset=0)
int BuildModule ()
asIScriptEngine * GetEngine ()
asIScriptModule * GetModule ()
void SetIncludeCallback (INCLUDECALLBACK_t callback, void *userParam)
void SetPragmaCallback (PRAGMACALLBACK_t callback, void *userParam)
void DefineWord (const char *word)
unsigned int GetSectionCount () const
std::string GetSectionName (unsigned int idx) const
std::vector< std::string > GetMetadataForType (int typeId)
std::vector< std::string > GetMetadataForFunc (asIScriptFunction *func)
std::vector< std::string > GetMetadataForVar (int varIdx)
std::vector< std::string > GetMetadataForTypeProperty (int typeId, int varIdx)
std::vector< std::string > GetMetadataForTypeMethod (int typeId, asIScriptFunction *method)
Protected Types
enum METADATATYPE {
MDT_TYPE = 1
, MDT_FUNC = 2
, MDT_VAR = 3
, MDT_VIRTPROP = 4
,
MDT_FUNC_OR_VAR = 5
, MDT_TYPE = 1
, MDT_FUNC = 2
, MDT_VAR = 3
,
MDT_VIRTPROP = 4
, MDT_FUNC_OR_VAR = 5
 }
enum METADATATYPE {
MDT_TYPE = 1
, MDT_FUNC = 2
, MDT_VAR = 3
, MDT_VIRTPROP = 4
,
MDT_FUNC_OR_VAR = 5
, MDT_TYPE = 1
, MDT_FUNC = 2
, MDT_VAR = 3
,
MDT_VIRTPROP = 4
, MDT_FUNC_OR_VAR = 5
 }
Protected Member Functions
void ClearAll ()
int Build ()
int ProcessScriptSection (const char *script, unsigned int length, const char *sectionname, int lineOffset)
int LoadScriptSection (const char *filename)
bool IncludeIfNotAlreadyIncluded (const char *filename)
int SkipStatement (int pos)
int ExcludeCode (int start)
void OverwriteCode (int start, int len)
int ExtractMetadata (int pos, std::vector< std::string > &outMetadata)
int ExtractDeclaration (int pos, std::string &outName, std::string &outDeclaration, int &outType)
void ClearAll ()
int Build ()
int ProcessScriptSection (const char *script, unsigned int length, const char *sectionname, int lineOffset)
int LoadScriptSection (const char *filename)
bool IncludeIfNotAlreadyIncluded (const char *filename)
int SkipStatement (int pos)
int ExcludeCode (int start)
void OverwriteCode (int start, int len)
int ExtractMetadata (int pos, std::vector< std::string > &outMetadata)
int ExtractDeclaration (int pos, std::string &outName, std::string &outDeclaration, int &outType)
Protected Attributes
asIScriptEngine * engine
asIScriptModule *std::string modifiedScript
INCLUDECALLBACK_t includeCallback
void * includeParam
PRAGMACALLBACK_t pragmaCallback
void * pragmaParam
std::vector< SMetadataDecl > foundDeclarations
std::string currentClass
std::string currentNamespace
std::map< int, std::vector< std::string > > typeMetadataMap
std::map< int, std::vector< std::string > > funcMetadataMap
std::map< int, std::vector< std::string > > varMetadataMap
std::map< int, SClassMetadata > classMetadataMap
std::set< std::string > includedScripts
std::set< std::string > definedWords
Detailed Description
Definition at line 57 of file scriptbuilder.h.
Member Enumeration Documentation
METADATATYPE [1/2]
enum CScriptBuilder::METADATATYPE [protected]
Enumerator
MDT_TYPE
MDT_FUNC
MDT_VAR
MDT_VIRTPROP
MDT_FUNC_OR_VAR
MDT_TYPE
MDT_FUNC
MDT_VAR
MDT_VIRTPROP
MDT_FUNC_OR_VAR
Definition at line 145 of file scriptbuilder.h.
METADATATYPE [2/2]
enum CScriptBuilder::METADATATYPE [protected]
Enumerator
MDT_TYPE
MDT_FUNC
MDT_VAR
MDT_VIRTPROP
MDT_FUNC_OR_VAR
MDT_TYPE
MDT_FUNC
MDT_VAR
MDT_VIRTPROP
MDT_FUNC_OR_VAR
Definition at line 145 of file scriptbuilder.h.
Constructor & Destructor Documentation
CScriptBuilder() [1/2]
CScriptBuilder::CScriptBuilder ()
Definition at line 28 of file scriptbuilder.cpp.
References engine, includeCallback, includeParam, pragmaCallback, and pragmaParam.
CScriptBuilder() [2/2]
CScriptBuilder::CScriptBuilder ()
Member Function Documentation
AddSectionFromFile() [1/2]
int CScriptBuilder::AddSectionFromFile (const char * filename)
Definition at line 97 of file scriptbuilder.cpp.
References GetAbsolutePath(), IncludeIfNotAlreadyIncluded(), and LoadScriptSection().
Referenced by ProcessScriptSection().
AddSectionFromFile() [2/2]
int CScriptBuilder::AddSectionFromFile (const char * filename)
AddSectionFromMemory() [1/2]
int CScriptBuilder::AddSectionFromMemory (const char * sectionName, const char * scriptCode, unsigned int scriptLength = 0, int lineOffset = 0)
Definition at line 118 of file scriptbuilder.cpp.
References IncludeIfNotAlreadyIncluded(), and ProcessScriptSection().
AddSectionFromMemory() [2/2]
int CScriptBuilder::AddSectionFromMemory (const char * sectionName, const char * scriptCode, unsigned int scriptLength = 0, int lineOffset = 0)
Build() [1/2]
int CScriptBuilder::Build () [protected]
Definition at line 597 of file scriptbuilder.cpp.
References classMetadataMap, CScriptBuilder::SMetadataDecl::declaration, engine, foundDeclarations, funcMetadataMap, MDT_FUNC, MDT_FUNC_OR_VAR, MDT_TYPE, MDT_VAR, MDT_VIRTPROP, CScriptBuilder::SMetadataDecl::metadata, CScriptBuilder::SMetadataDecl::name, CScriptBuilder::SMetadataDecl::parentClass, CScriptBuilder::SMetadataDecl::type, typeMetadataMap, and varMetadataMap.
Referenced by BuildModule().
Build() [2/2]
int CScriptBuilder::Build () [protected]
BuildModule() [1/2]
int CScriptBuilder::BuildModule ()
Definition at line 132 of file scriptbuilder.cpp.
References Build().
BuildModule() [2/2]
int CScriptBuilder::BuildModule ()
ClearAll() [1/2]
void CScriptBuilder::ClearAll () [protected]
Definition at line 146 of file scriptbuilder.cpp.
References currentClass, currentNamespace, foundDeclarations, funcMetadataMap, includedScripts, typeMetadataMap, and varMetadataMap.
Referenced by StartNewModule().
ClearAll() [2/2]
void CScriptBuilder::ClearAll () [protected]
DefineWord() [1/2]
void CScriptBuilder::DefineWord (const char * word)
Definition at line 137 of file scriptbuilder.cpp.
References definedWords.
DefineWord() [2/2]
void CScriptBuilder::DefineWord (const char * word)
ExcludeCode() [1/2]
int CScriptBuilder::ExcludeCode (int start) [protected]
Definition at line 828 of file scriptbuilder.cpp.
References engine, modifiedScript, and OverwriteCode().
Referenced by ProcessScriptSection().
ExcludeCode() [2/2]
int CScriptBuilder::ExcludeCode (int start) [protected]
ExtractDeclaration() [1/2]
int CScriptBuilder::ExtractDeclaration (int pos, std::string & outName, std::string & outDeclaration, int & outType) [protected]
Definition at line 938 of file scriptbuilder.cpp.
References engine, MDT_FUNC, MDT_FUNC_OR_VAR, MDT_TYPE, MDT_VAR, MDT_VIRTPROP, and modifiedScript.
Referenced by ProcessScriptSection().
ExtractDeclaration() [2/2]
int CScriptBuilder::ExtractDeclaration (int pos, std::string & outName, std::string & outDeclaration, int & outType) [protected]
ExtractMetadata() [1/2]
int CScriptBuilder::ExtractMetadata (int pos, std::vector< std::string > & outMetadata) [protected]
Definition at line 882 of file scriptbuilder.cpp.
References engine, modifiedScript, and OverwriteCode().
Referenced by ProcessScriptSection().
ExtractMetadata() [2/2]
int CScriptBuilder::ExtractMetadata (int pos, std::vector< std::string > & outMetadata) [protected]
GetEngine() [1/2]
asIScriptEngine * CScriptBuilder::GetEngine ()
Definition at line 66 of file scriptbuilder.cpp.
References engine.
GetEngine() [2/2]
asIScriptEngine * CScriptBuilder::GetEngine ()
GetMetadataForFunc() [1/2]
vector< string > CScriptBuilder::GetMetadataForFunc (asIScriptFunction * func)
Definition at line 1070 of file scriptbuilder.cpp.
References funcMetadataMap.
GetMetadataForFunc() [2/2]
std::vector< std::string > CScriptBuilder::GetMetadataForFunc (asIScriptFunction * func)
GetMetadataForType() [1/2]
vector< string > CScriptBuilder::GetMetadataForType (int typeId)
Definition at line 1061 of file scriptbuilder.cpp.
References typeMetadataMap.
GetMetadataForType() [2/2]
std::vector< std::string > CScriptBuilder::GetMetadataForType (int typeId)
GetMetadataForTypeMethod() [1/2]
vector< string > CScriptBuilder::GetMetadataForTypeMethod (int typeId, asIScriptFunction * method)
Definition at line 1102 of file scriptbuilder.cpp.
References classMetadataMap.
GetMetadataForTypeMethod() [2/2]
std::vector< std::string > CScriptBuilder::GetMetadataForTypeMethod (int typeId, asIScriptFunction * method)
GetMetadataForTypeProperty() [1/2]
vector< string > CScriptBuilder::GetMetadataForTypeProperty (int typeId, int varIdx)
Definition at line 1091 of file scriptbuilder.cpp.
References classMetadataMap.
GetMetadataForTypeProperty() [2/2]
std::vector< std::string > CScriptBuilder::GetMetadataForTypeProperty (int typeId, int varIdx)
GetMetadataForVar() [1/2]
vector< string > CScriptBuilder::GetMetadataForVar (int varIdx)
Definition at line 1082 of file scriptbuilder.cpp.
References varMetadataMap.
GetMetadataForVar() [2/2]
std::vector< std::string > CScriptBuilder::GetMetadataForVar (int varIdx)
GetModule() [1/2]
asIScriptModule * CScriptBuilder::GetModule ()
Definition at line 71 of file scriptbuilder.cpp.
GetModule() [2/2]
asIScriptModule * CScriptBuilder::GetModule ()
GetSectionCount() [1/2]
unsigned int CScriptBuilder::GetSectionCount () const
Definition at line 76 of file scriptbuilder.cpp.
References includedScripts.
GetSectionCount() [2/2]
unsigned int CScriptBuilder::GetSectionCount () const
GetSectionName() [1/2]
string CScriptBuilder::GetSectionName (unsigned int idx) const
Definition at line 81 of file scriptbuilder.cpp.
References includedScripts.
GetSectionName() [2/2]
std::string CScriptBuilder::GetSectionName (unsigned int idx) const
IncludeIfNotAlreadyIncluded() [1/2]
bool CScriptBuilder::IncludeIfNotAlreadyIncluded (const char * filename) [protected]
Definition at line 161 of file scriptbuilder.cpp.
References includedScripts.
Referenced by AddSectionFromFile(), and AddSectionFromMemory().
IncludeIfNotAlreadyIncluded() [2/2]
bool CScriptBuilder::IncludeIfNotAlreadyIncluded (const char * filename) [protected]
LoadScriptSection() [1/2]
int CScriptBuilder::LoadScriptSection (const char * filename) [protected]
Definition at line 176 of file scriptbuilder.cpp.
References engine, GetAbsolutePath(), and ProcessScriptSection().
Referenced by AddSectionFromFile().
LoadScriptSection() [2/2]
int CScriptBuilder::LoadScriptSection (const char * filename) [protected]
OverwriteCode() [1/2]
void CScriptBuilder::OverwriteCode (int start, int len) [protected]
Definition at line 870 of file scriptbuilder.cpp.
References modifiedScript.
Referenced by ExcludeCode(), ExtractMetadata(), and ProcessScriptSection().
OverwriteCode() [2/2]
void CScriptBuilder::OverwriteCode (int start, int len) [protected]
ProcessScriptSection() [1/2]
int CScriptBuilder::ProcessScriptSection (const char * script, unsigned int length, const char * sectionname, int lineOffset) [protected]
Definition at line 239 of file scriptbuilder.cpp.
References AddSectionFromFile(), currentClass, currentNamespace, definedWords, engine, ExcludeCode(), ExtractDeclaration(), ExtractMetadata(), foundDeclarations, includeCallback, includeParam, modifiedScript, OverwriteCode(), pragmaCallback, pragmaParam, and SkipStatement().
Referenced by AddSectionFromMemory(), and LoadScriptSection().
ProcessScriptSection() [2/2]
int CScriptBuilder::ProcessScriptSection (const char * script, unsigned int length, const char * sectionname, int lineOffset) [protected]
SetIncludeCallback() [1/2]
void CScriptBuilder::SetIncludeCallback (INCLUDECALLBACK_t callback, void * userParam)
Definition at line 40 of file scriptbuilder.cpp.
References includeCallback, and includeParam.
SetIncludeCallback() [2/2]
void CScriptBuilder::SetIncludeCallback (INCLUDECALLBACK_t callback, void * userParam)
SetPragmaCallback() [1/2]
void CScriptBuilder::SetPragmaCallback (PRAGMACALLBACK_t callback, void * userParam)
Definition at line 46 of file scriptbuilder.cpp.
References pragmaCallback, and pragmaParam.
SetPragmaCallback() [2/2]
void CScriptBuilder::SetPragmaCallback (PRAGMACALLBACK_t callback, void * userParam)
SkipStatement() [1/2]
int CScriptBuilder::SkipStatement (int pos) [protected]
Definition at line 789 of file scriptbuilder.cpp.
References engine, and modifiedScript.
Referenced by ProcessScriptSection().
SkipStatement() [2/2]
int CScriptBuilder::SkipStatement (int pos) [protected]
StartNewModule() [1/2]
int CScriptBuilder::StartNewModule (asIScriptEngine * engine, const char * moduleName)
Definition at line 52 of file scriptbuilder.cpp.
References ClearAll(), and engine.
StartNewModule() [2/2]
int CScriptBuilder::StartNewModule (asIScriptEngine * engine, const char * moduleName)
Member Data Documentation
classMetadataMap
std::map< int, SClassMetadata > CScriptBuilder::classMetadataMap [protected]
Definition at line 182 of file scriptbuilder.h.
Referenced by Build(), GetMetadataForTypeMethod(), and GetMetadataForTypeProperty().
currentClass
std::string CScriptBuilder::currentClass [protected]
Definition at line 166 of file scriptbuilder.h.
Referenced by ClearAll(), and ProcessScriptSection().
currentNamespace
std::string CScriptBuilder::currentNamespace [protected]
Definition at line 167 of file scriptbuilder.h.
Referenced by ClearAll(), and ProcessScriptSection().
definedWords
std::set< std::string > CScriptBuilder::definedWords [protected]
Definition at line 211 of file scriptbuilder.h.
Referenced by DefineWord(), and ProcessScriptSection().
engine
asIScriptEngine * CScriptBuilder::engine [protected]
Definition at line 131 of file scriptbuilder.h.
Referenced by Build(), CScriptBuilder(), ExcludeCode(), ExtractDeclaration(), ExtractMetadata(), GetEngine(), LoadScriptSection(), ProcessScriptSection(), SkipStatement(), and StartNewModule().
foundDeclarations
std::vector< SMetadataDecl > CScriptBuilder::foundDeclarations [protected]
Definition at line 165 of file scriptbuilder.h.
Referenced by Build(), ClearAll(), and ProcessScriptSection().
funcMetadataMap
std::map< int, std::vector< std::string > > CScriptBuilder::funcMetadataMap [protected]
Definition at line 171 of file scriptbuilder.h.
Referenced by Build(), ClearAll(), and GetMetadataForFunc().
includeCallback
INCLUDECALLBACK_t CScriptBuilder::includeCallback [protected]
Definition at line 135 of file scriptbuilder.h.
Referenced by CScriptBuilder(), ProcessScriptSection(), and SetIncludeCallback().
includedScripts
std::set< std::string > CScriptBuilder::includedScripts [protected]
Definition at line 208 of file scriptbuilder.h.
Referenced by ClearAll(), GetSectionCount(), GetSectionName(), and IncludeIfNotAlreadyIncluded().
includeParam
void * CScriptBuilder::includeParam [protected]
Definition at line 136 of file scriptbuilder.h.
Referenced by CScriptBuilder(), ProcessScriptSection(), and SetIncludeCallback().
modifiedScript
asIScriptModule *std::string CScriptBuilder::modifiedScript [protected]
Definition at line 133 of file scriptbuilder.h.
Referenced by ExcludeCode(), ExtractDeclaration(), ExtractMetadata(), OverwriteCode(), ProcessScriptSection(), and SkipStatement().
pragmaCallback
PRAGMACALLBACK_t CScriptBuilder::pragmaCallback [protected]
Definition at line 138 of file scriptbuilder.h.
Referenced by CScriptBuilder(), ProcessScriptSection(), and SetPragmaCallback().
pragmaParam
void * CScriptBuilder::pragmaParam [protected]
Definition at line 139 of file scriptbuilder.h.
Referenced by CScriptBuilder(), ProcessScriptSection(), and SetPragmaCallback().
typeMetadataMap
std::map< int, std::vector< std::string > > CScriptBuilder::typeMetadataMap [protected]
Definition at line 170 of file scriptbuilder.h.
Referenced by Build(), ClearAll(), and GetMetadataForType().
varMetadataMap
std::map< int, std::vector< std::string > > CScriptBuilder::varMetadataMap [protected]
Definition at line 172 of file scriptbuilder.h.
Referenced by Build(), ClearAll(), and GetMetadataForVar().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/application/add_on/scriptbuilder/scriptbuilder.h
C:/Dev/Techstorm-v5/src/engine/modding/add_on/scriptbuilder/scriptbuilder.h
C:/Dev/Techstorm-v5/src/application/add_on/scriptbuilder/scriptbuilder.cpp
C:/Dev/Techstorm-v5/src/engine/modding/add_on/scriptbuilder/scriptbuilder.cpp