C:/Dev/Techstorm-v5/src/engine/modding/add_on/weakref/weakref.cpp File Reference
#include "weakref.h"
#include <new>
#include <assert.h>
#include <string.h>
Functions
static BEGIN_AS_NAMESPACE void ScriptWeakRefConstruct (asITypeInfo *type, void *mem)
static void ScriptWeakRefConstruct2 (asITypeInfo *type, void *ref, void *mem)
static void ScriptWeakRefDestruct (CScriptWeakRef *obj)
static bool ScriptWeakRefTemplateCallback (asITypeInfo *ti, bool &)
void RegisterScriptWeakRef_Native (asIScriptEngine *engine)
static void ScriptWeakRefConstruct_Generic (asIScriptGeneric *gen)
static void ScriptWeakRefConstruct2_Generic (asIScriptGeneric *gen)
static void ScriptWeakRefDestruct_Generic (asIScriptGeneric *gen)
void CScriptWeakRef_Get_Generic (asIScriptGeneric *gen)
void CScriptWeakRef_Assign_Generic (asIScriptGeneric *gen)
void CScriptWeakRef_Assign2_Generic (asIScriptGeneric *gen)
void CScriptWeakRef_Equals_Generic (asIScriptGeneric *gen)
void CScriptWeakRef_Equals2_Generic (asIScriptGeneric *gen)
static void ScriptWeakRefTemplateCallback_Generic (asIScriptGeneric *gen)
void RegisterScriptWeakRef_Generic (asIScriptEngine *engine)
void RegisterScriptWeakRef (asIScriptEngine *engine)
Function Documentation
CScriptWeakRef_Assign2_Generic()
void CScriptWeakRef_Assign2_Generic (asIScriptGeneric * gen)
Definition at line 297 of file weakref.cpp.
References CScriptWeakRef::Set().
Referenced by RegisterScriptWeakRef_Generic().
CScriptWeakRef_Assign_Generic()
void CScriptWeakRef_Assign_Generic (asIScriptGeneric * gen)
Definition at line 289 of file weakref.cpp.
Referenced by RegisterScriptWeakRef_Generic().
CScriptWeakRef_Equals2_Generic()
void CScriptWeakRef_Equals2_Generic (asIScriptGeneric * gen)
Definition at line 312 of file weakref.cpp.
References CScriptWeakRef::Equals().
CScriptWeakRef_Equals_Generic()
void CScriptWeakRef_Equals_Generic (asIScriptGeneric * gen)
Definition at line 305 of file weakref.cpp.
CScriptWeakRef_Get_Generic()
void CScriptWeakRef_Get_Generic (asIScriptGeneric * gen)
Definition at line 283 of file weakref.cpp.
References CScriptWeakRef::Get().
RegisterScriptWeakRef()
void RegisterScriptWeakRef (asIScriptEngine * engine)
Definition at line 368 of file weakref.cpp.
References RegisterScriptWeakRef_Generic(), and RegisterScriptWeakRef_Native().
RegisterScriptWeakRef_Generic()
void RegisterScriptWeakRef_Generic (asIScriptEngine * engine)
Definition at line 327 of file weakref.cpp.
References CScriptWeakRef_Assign2_Generic(), CScriptWeakRef_Assign_Generic(), CScriptWeakRef_Equals2_Generic(), CScriptWeakRef_Equals_Generic(), CScriptWeakRef_Get_Generic(), ScriptWeakRefConstruct2_Generic(), ScriptWeakRefConstruct_Generic(), ScriptWeakRefDestruct_Generic(), and ScriptWeakRefTemplateCallback_Generic().
Referenced by RegisterScriptWeakRef().
RegisterScriptWeakRef_Native()
void RegisterScriptWeakRef_Native (asIScriptEngine * engine)
Definition at line 221 of file weakref.cpp.
References ScriptWeakRefConstruct(), ScriptWeakRefConstruct2(), ScriptWeakRefDestruct(), and ScriptWeakRefTemplateCallback().
Referenced by RegisterScriptWeakRef().
ScriptWeakRefConstruct()
static BEGIN_AS_NAMESPACE void ScriptWeakRefConstruct (asITypeInfo * type, void * mem) [static]
Definition at line 11 of file weakref.cpp.
Referenced by RegisterScriptWeakRef_Native(), and ScriptWeakRefConstruct_Generic().
ScriptWeakRefConstruct2()
static void ScriptWeakRefConstruct2 (asITypeInfo * type, void * ref, void * mem) [static]
Definition at line 16 of file weakref.cpp.
ScriptWeakRefConstruct2_Generic()
static void ScriptWeakRefConstruct2_Generic (asIScriptGeneric * gen) [static]
Definition at line 269 of file weakref.cpp.
References ScriptWeakRefConstruct2().
Referenced by RegisterScriptWeakRef_Generic().
ScriptWeakRefConstruct_Generic()
static void ScriptWeakRefConstruct_Generic (asIScriptGeneric * gen) [static]
Definition at line 262 of file weakref.cpp.
References ScriptWeakRefConstruct().
ScriptWeakRefDestruct()
static void ScriptWeakRefDestruct (CScriptWeakRef * obj) [static]
Definition at line 27 of file weakref.cpp.
References CScriptWeakRef::~CScriptWeakRef().
Referenced by RegisterScriptWeakRef_Native().
ScriptWeakRefDestruct_Generic()
static void ScriptWeakRefDestruct_Generic (asIScriptGeneric * gen) [static]
Definition at line 277 of file weakref.cpp.
References CScriptWeakRef::~CScriptWeakRef().
ScriptWeakRefTemplateCallback()
static bool ScriptWeakRefTemplateCallback (asITypeInfo * ti, bool &) [static]
Definition at line 32 of file weakref.cpp.
ScriptWeakRefTemplateCallback_Generic()
static void ScriptWeakRefTemplateCallback_Generic (asIScriptGeneric * gen) [static]
Definition at line 320 of file weakref.cpp.
References ScriptWeakRefTemplateCallback().
Referenced by RegisterScriptWeakRef_Generic().