Atlas::InputRegistry::InputActionRegistry Class Reference
#include <InputRegistry.h>
Public Member Functions
void registerAction (InputAction *action, std::function< void(InputAction *)> callback)
void unregisterAction (InputAction *action)
void checkAll ()
bool checkPressedAction (InputAction *action)
bool checkReleasedAction (InputAction *action)
bool checkDownAction (InputAction *action)
bool checkUpAction (InputAction *action)
bool checkRepeatAction (InputAction *action)
Public Attributes
std::unordered_map< InputAction *, std::unordered_map< InputActionCallbackID, std::function< void(InputAction *)> > > mActions
Detailed Description
Definition at line 27 of file InputRegistry.h.
Member Function Documentation
checkAll()
void Atlas::InputRegistry::InputActionRegistry::checkAll () [inline]
Definition at line 49 of file InputRegistry.h.
References checkDownAction(), checkPressedAction(), checkReleasedAction(), checkRepeatAction(), checkUpAction(), Atlas::INPUT_TRIGGER_DOWN, Atlas::INPUT_TRIGGER_PRESSED, Atlas::INPUT_TRIGGER_RELEASED, Atlas::INPUT_TRIGGER_REPEAT, Atlas::INPUT_TRIGGER_UP, and mActions.
checkDownAction()
bool Atlas::InputRegistry::InputActionRegistry::checkDownAction (InputAction * action) [inline]
Definition at line 159 of file InputRegistry.h.
References Atlas::InputAction::controllerID, Atlas::INPUT_CONTROLLER, Atlas::INPUT_KEYBOARD, Atlas::INPUT_MOUSE, Atlas::InputAction::key, and Atlas::InputAction::type.
Referenced by checkAll().
checkPressedAction()
bool Atlas::InputRegistry::InputActionRegistry::checkPressedAction (InputAction * action) [inline]
Definition at line 89 of file InputRegistry.h.
References Atlas::InputAction::controllerID, Atlas::INPUT_CONTROLLER, Atlas::INPUT_KEYBOARD, Atlas::INPUT_MOUSE, Atlas::InputAction::key, and Atlas::InputAction::type.
Referenced by checkAll().
checkReleasedAction()
bool Atlas::InputRegistry::InputActionRegistry::checkReleasedAction (InputAction * action) [inline]
Definition at line 124 of file InputRegistry.h.
References Atlas::InputAction::controllerID, Atlas::INPUT_CONTROLLER, Atlas::INPUT_KEYBOARD, Atlas::INPUT_MOUSE, Atlas::InputAction::key, and Atlas::InputAction::type.
Referenced by checkAll().
checkRepeatAction()
bool Atlas::InputRegistry::InputActionRegistry::checkRepeatAction (InputAction * action) [inline]
Definition at line 229 of file InputRegistry.h.
References Atlas::INPUT_CONTROLLER, Atlas::INPUT_KEYBOARD, Atlas::INPUT_MOUSE, Atlas::InputAction::key, and Atlas::InputAction::type.
Referenced by checkAll().
checkUpAction()
bool Atlas::InputRegistry::InputActionRegistry::checkUpAction (InputAction * action) [inline]
Definition at line 194 of file InputRegistry.h.
References Atlas::InputAction::controllerID, Atlas::INPUT_CONTROLLER, Atlas::INPUT_KEYBOARD, Atlas::INPUT_MOUSE, Atlas::InputAction::key, and Atlas::InputAction::type.
Referenced by checkAll().
registerAction()
void Atlas::InputRegistry::InputActionRegistry::registerAction (InputAction * action, std::function< void(InputAction *)> callback) [inline]
Definition at line 31 of file InputRegistry.h.
References mActions.
unregisterAction()
void Atlas::InputRegistry::InputActionRegistry::unregisterAction (InputAction * action) [inline]
Definition at line 45 of file InputRegistry.h.
References mActions.
Member Data Documentation
mActions
std::unordered_map<InputAction*, std::unordered_map<InputActionCallbackID, std::function<void(InputAction*)> > > Atlas::InputRegistry::InputActionRegistry::mActions
Definition at line 29 of file InputRegistry.h.
Referenced by checkAll(), registerAction(), and unregisterAction().
The documentation for this class was generated from the following file:
C:/Dev/Techstorm-v5/src/engine/input/InputRegistry.h