CScriptFileSystem Class Reference
#include <scriptfilesystem.h>
Public Member Functions
CScriptFileSystem ()
void AddRef () const
void Release () const
bool ChangeCurrentPath (const std::string &path)
std::string GetCurrentPath () const
bool IsDir (const std::string &path) const
bool IsLink (const std::string &path) const
asINT64 GetSize (const std::string &path) const
CScriptArray * GetFiles () const
CScriptArray * GetDirs () const
int MakeDir (const std::string &path)
int RemoveDir (const std::string &path)
int DeleteFile (const std::string &path)
int CopyFile (const std::string &source, const std::string &target)
int Move (const std::string &source, const std::string &target)
CDateTime GetCreateDateTime (const std::string &path) const
CDateTime GetModifyDateTime (const std::string &path) const
Protected Member Functions
~CScriptFileSystem ()
Protected Attributes
int refCount
std::string currentPath
Detailed Description
Definition at line 17 of file scriptfilesystem.h.
Constructor & Destructor Documentation
CScriptFileSystem()
CScriptFileSystem::CScriptFileSystem ()
Definition at line 97 of file scriptfilesystem.cpp.
References currentPath, and refCount.
~CScriptFileSystem()
CScriptFileSystem::~CScriptFileSystem () [protected]
Definition at line 118 of file scriptfilesystem.cpp.
Member Function Documentation
AddRef()
void CScriptFileSystem::AddRef () const
Definition at line 122 of file scriptfilesystem.cpp.
References refCount.
ChangeCurrentPath()
bool CScriptFileSystem::ChangeCurrentPath (const std::string & path)
Definition at line 277 of file scriptfilesystem.cpp.
References currentPath, and IsDir().
CopyFile()
int CScriptFileSystem::CopyFile (const std::string & source, const std::string & target)
Definition at line 473 of file scriptfilesystem.cpp.
References currentPath.
DeleteFile()
int CScriptFileSystem::DeleteFile (const std::string & path)
Definition at line 450 of file scriptfilesystem.cpp.
References currentPath.
GetCreateDateTime()
CDateTime CScriptFileSystem::GetCreateDateTime (const std::string & path) const
Definition at line 556 of file scriptfilesystem.cpp.
References currentPath.
GetCurrentPath()
string CScriptFileSystem::GetCurrentPath () const
Definition at line 551 of file scriptfilesystem.cpp.
References currentPath.
GetDirs()
CScriptArray * CScriptFileSystem::GetDirs () const
Definition at line 203 of file scriptfilesystem.cpp.
References CScriptArray::At(), CScriptArray::Create(), currentPath, CScriptArray::GetSize(), and CScriptArray::Resize().
GetFiles()
CScriptArray * CScriptFileSystem::GetFiles () const
Definition at line 133 of file scriptfilesystem.cpp.
References CScriptArray::At(), CScriptArray::Create(), currentPath, CScriptArray::GetSize(), and CScriptArray::Resize().
GetModifyDateTime()
CDateTime CScriptFileSystem::GetModifyDateTime (const std::string & path) const
Definition at line 599 of file scriptfilesystem.cpp.
References currentPath.
GetSize()
asINT64 CScriptFileSystem::GetSize (const std::string & path) const
Definition at line 363 of file scriptfilesystem.cpp.
References currentPath.
IsDir()
bool CScriptFileSystem::IsDir (const std::string & path) const
Definition at line 303 of file scriptfilesystem.cpp.
References currentPath.
Referenced by ChangeCurrentPath().
IsLink()
bool CScriptFileSystem::IsLink (const std::string & path) const
Definition at line 333 of file scriptfilesystem.cpp.
References currentPath.
MakeDir()
int CScriptFileSystem::MakeDir (const std::string & path)
Definition at line 399 of file scriptfilesystem.cpp.
References currentPath.
Move()
int CScriptFileSystem::Move (const std::string & source, const std::string & target)
Definition at line 519 of file scriptfilesystem.cpp.
References currentPath.
Release()
void CScriptFileSystem::Release () const
Definition at line 127 of file scriptfilesystem.cpp.
References refCount.
RemoveDir()
int CScriptFileSystem::RemoveDir (const std::string & path)
Definition at line 427 of file scriptfilesystem.cpp.
References currentPath.
Member Data Documentation
currentPath
std::string CScriptFileSystem::currentPath [protected]
Definition at line 71 of file scriptfilesystem.h.
Referenced by ChangeCurrentPath(), CopyFile(), CScriptFileSystem(), DeleteFile(), GetCreateDateTime(), GetCurrentPath(), GetDirs(), GetFiles(), GetModifyDateTime(), GetSize(), IsDir(), IsLink(), MakeDir(), Move(), and RemoveDir().
refCount
int CScriptFileSystem::refCount [mutable], [protected]
Definition at line 70 of file scriptfilesystem.h.
Referenced by AddRef(), CScriptFileSystem(), and Release().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/application/add_on/scriptfile/scriptfilesystem.h
C:/Dev/Techstorm-v5/src/application/add_on/scriptfile/scriptfilesystem.cpp