C:/Dev/Techstorm-v5/src/application/AngelScriptTest.h File Reference
#include <iostream>
#include <assert.h>
#include <string.h>
#include <conio.h>
#include <windows.h>
#include <angelscript.h>
#include "add_on/scriptstdstring/scriptstdstring.h"
Functions
int RunApplication ()
void ConfigureEngine (asIScriptEngine *engine)
int CompileScript (asIScriptEngine *engine)
void PrintString (string &str)
void PrintString_Generic (asIScriptGeneric *gen)
void timeGetTime_Generic (asIScriptGeneric *gen)
void LineCallback (asIScriptContext *ctx, DWORD *timeOut)
int RunAngelScript ()
void MessageCallback (const asSMessageInfo *msg, void *param)
Function Documentation
CompileScript()
int CompileScript (asIScriptEngine * engine)
Definition at line 211 of file AngelScriptTest.h.
Referenced by RunApplication().
ConfigureEngine()
void ConfigureEngine (asIScriptEngine * engine)
Definition at line 175 of file AngelScriptTest.h.
References PrintString(), PrintString_Generic(), RegisterStdString(), and timeGetTime_Generic().
Referenced by RunApplication().
LineCallback()
void LineCallback (asIScriptContext * ctx, DWORD * timeOut)
Definition at line 280 of file AngelScriptTest.h.
Referenced by RunApplication().
MessageCallback()
void MessageCallback (const asSMessageInfo * msg, void * param)
Definition at line 39 of file AngelScriptTest.h.
Referenced by RunApplication().
PrintString()
void PrintString (string & str)
Definition at line 293 of file AngelScriptTest.h.
Referenced by ConfigureEngine().
PrintString_Generic()
void PrintString_Generic (asIScriptGeneric * gen)
Definition at line 299 of file AngelScriptTest.h.
Referenced by ConfigureEngine().
RunAngelScript()
int RunAngelScript ()
Definition at line 29 of file AngelScriptTest.h.
References RunApplication().
Referenced by main().
RunApplication()
int RunApplication ()
Definition at line 51 of file AngelScriptTest.h.
References CompileScript(), ConfigureEngine(), LineCallback(), and MessageCallback().
Referenced by RunAngelScript().
timeGetTime_Generic()
void timeGetTime_Generic (asIScriptGeneric * gen)
Definition at line 306 of file AngelScriptTest.h.
Referenced by ConfigureEngine().