Atlas::BProject Class Reference
This is the interface for the user's project. This is the only interface that Atlas will call.
#include <Project.h>
Classes
class ProjectReference
Represents a polymorphic singleton reference to the user's project instance through a pointer of Atlas::BProject. This is mandatory for Atlas to run the user's engine.
Public Member Functions
BProject ()
This is a default constructor that will initialize Atlas and the user's project.
ScriptingLibraryRegistry & getLuaLibraries ()
Returns the currently active libraries for lua.
ScriptingFunctionRegistry & getLuaFunctions ()
Gets the lua functions.
WindowDecorations & getWindowDecorations ()
Gets the window decorations. This includes the window title, icon, size, etc.
void setWindowDecorations (WindowDecorations &windowDecorations)
Sets the window decorations.
template<typename T >
void setProject (T *project)
This function is used to set the ProjectReference singleton to the project.
virtual void preInit () override
This is the first function that will be called on startup.
virtual void init (int argc, char *argv[]) override
Initializes your project. This will be called after preInit and window initialization, meaning that this is the earliest point that you can use raylib. THIS MUST BE OVERRIDEN BY YOUR PROJECT CLASS!
virtual void postInit () override
Does a post initialization of the project. This is empty because it is not neccesary to override.
virtual void initRenderer () override
Initializes the renderer and should be called after initWindow.
virtual int run (int argc, char *argv[]) override
Runs the actual game and is called after the init functions.
virtual int update () override
Updates this instance in the updating thread.
virtual int workingUpdate () override
virtual int prePhysicsUpdate () override
Pre-update step that is called in the physics or update thread (depending on thread count)
virtual int physicsUpdate () override
This is where the actual physics update happens. Please note that this will run on the physics thread!
virtual int postPhysicsUpdate () override
Post physics update that is called after physicsUpdate() in the physics or update thread (depending on thread count).
virtual int preObjectUpdate () override
Any preparation code for updating the scene's game objects. Use this if you need to do something after the physics update, but before the GameObject update. Please note that this will run on the update thread!
virtual int objectUpdate () override
This is where the actual GameObject update happens, and is called after preObjectUpdate(). Please note that this will run on the update thread!
virtual int postObjectUpdate () override
Called right after objectUpdate(). Use this to do anything after the GameObject update. Please note that this will run on the update thread!
virtual int texture () override
Textures all GameObjects before render() is called and after update functions are called. This is essentially where the scene is rendered. Please note that this will run on the render thread!
virtual int render () override
Assuming that the FBO is enabled, this will render the FBO and apply any post-processing effects to the FBO. Please note that this will run on the update thread!
virtual int draw () override
virtual int cleanup (int exitCode) override
Cleans up anything that may need to be cleaned up.
ThreadSafeVariable< AtlasEngine * > getAtlasEngine () override
Get the Atlas Engine object.
Static Public Member Functions
static std::shared_ptr< BProject > GetProject ()
Get the Project object.
Public Attributes
GameSettings settings
Static Public Attributes
static ThreadSafeVariable< AtlasEngine * > mAtlas = nullptr
Protected Member Functions
virtual ThreadSafeVariable< AtlasEngine * > setupAtlas () override
Protected Attributes
bool mHasCleanedUp = false
A flag that indicates whether or not the project has been cleaned up.
WindowDecorations mWindowDecorations
ScriptingLibraryRegistry mLuaLibraries
ScriptingFunctionRegistry mLuaFunctions
Static Protected Attributes
static std::shared_ptr< BProject > mProject = nullptr
Detailed Description
This is the interface for the user's project. This is the only interface that Atlas will call.
Remarks
This is an abstract interface singleton that all projects must implement and set the ProjectReference singleton to their project. In terms of functionality, this interface just holds the functions and variables that Atlas will call (besides some initialization).
Note
If this boilerplate code is not done, Atlas will not know what to run.
Warning
Do not directly call window code in here or your project will crash!
Since
v0.0.1
Definition at line 34 of file Project.h.
Constructor & Destructor Documentation
BProject()
Atlas::BProject::BProject ()
This is a default constructor that will initialize Atlas and the user's project.
Since
v0.0.1
Definition at line 54 of file Project.cpp.
References mAtlas, mProject, and setupAtlas().
Member Function Documentation
cleanup()
int Atlas::BProject::cleanup (int exitCode) [override], [virtual]
Cleans up anything that may need to be cleaned up.
Parameters
exitCode The code that the engine has exited with
Returns
The cleanup exit code.
Cleans up anything that may need to be cleaned up.
Parameters
exitCode The code that the engine has exited with
Returns
The cleanup exit code.
Implements Atlas::IProject.
Definition at line 268 of file Project.cpp.
References Atlas::ThreadSafeVariable< T_VARIABLE_TYPE, T_MUTEX, T_LOCK_GUARD >::get().
draw()
int Atlas::BProject::draw () [override], [virtual]
Implements Atlas::IProject.
Definition at line 258 of file Project.cpp.
getAtlasEngine()
ThreadSafeVariable< AtlasEngine * > Atlas::BProject::getAtlasEngine () [override], [virtual]
Get the Atlas Engine object.
Returns
std::shared_ptr<AtlasEngine>
Implements Atlas::IProject.
Definition at line 284 of file Project.cpp.
Referenced by Project::postInit().
getLuaFunctions()
ScriptingFunctionRegistry & Atlas::BProject::getLuaFunctions () [inline]
Gets the lua functions.
Returns
A reference to mLuaFunctions
Definition at line 96 of file Project.h.
References mLuaFunctions.
getLuaLibraries()
ScriptingLibraryRegistry & Atlas::BProject::getLuaLibraries () [inline]
Returns the currently active libraries for lua.
Returns
A reference to mLuaLibraries
Definition at line 90 of file Project.h.
References mLuaLibraries.
GetProject()
std::shared_ptr< BProject > Atlas::BProject::GetProject () [inline], [static]
Get the Project object.
Returns
std::shared_ptr<BProject>
Definition at line 279 of file Project.cpp.
Referenced by Atlas::GetAtlasEngine().
getWindowDecorations()
WindowDecorations & Atlas::BProject::getWindowDecorations ()
Gets the window decorations. This includes the window title, icon, size, etc.
Returns
A reference to mWindowDecorations
Definition at line 65 of file Project.cpp.
init()
void Atlas::BProject::init (int argc, char * argv[]) [override], [virtual]
Initializes your project. This will be called after preInit and window initialization, meaning that this is the earliest point that you can use raylib. THIS MUST BE OVERRIDEN BY YOUR PROJECT CLASS!
Parameters
argc Command line argument count int
argv Command line arguments array
Initializes your project.
Remarks
This will be called after preInit and window initialization, meaning that this is the earliest point that you can use raylib.
Warning
THIS MUST BE OVERRIDEN BY YOUR PROJECT CLASS!
Parameters
argc
argv
Implements Atlas::IProject.
Definition at line 163 of file Project.cpp.
initRenderer()
void Atlas::BProject::initRenderer () [override], [virtual]
Initializes the renderer and should be called after initWindow.
Initializes the renderer and should be called after initWindow.
Implements Atlas::IProject.
Definition at line 181 of file Project.cpp.
objectUpdate()
int Atlas::BProject::objectUpdate () [override], [virtual]
This is where the actual GameObject update happens, and is called after preObjectUpdate(). Please note that this will run on the update thread!
Returns
The exit code of the step
This is where the actual GameObject update happens, and is called after preObjectUpdate(). Please note that this will run on the update thread!
Returns
The exit code of the step
Implements Atlas::IProject.
Definition at line 240 of file Project.cpp.
physicsUpdate()
int Atlas::BProject::physicsUpdate () [override], [virtual]
This is where the actual physics update happens. Please note that this will run on the physics thread!
Returns
The exit code of the step
This is where the actual physics update happens. Please note that this will run on the physics thread!
Returns
The exit code of the step
Implements Atlas::IProject.
Definition at line 224 of file Project.cpp.
postInit()
void Atlas::BProject::postInit () [override], [virtual]
Does a post initialization of the project. This is empty because it is not neccesary to override.
Implements Atlas::IProject.
Reimplemented in Project, and SamplesProject.
Definition at line 167 of file Project.cpp.
References Atlas::Renderer::init(), and Atlas::IWindow::init().
Referenced by Project::postInit().
postObjectUpdate()
int Atlas::BProject::postObjectUpdate () [override], [virtual]
Called right after objectUpdate(). Use this to do anything after the GameObject update. Please note that this will run on the update thread!
Returns
Called right after objectUpdate(). Use this to do anything after the GameObject update. Please note that this will run on the update thread!
Returns
Implements Atlas::IProject.
Definition at line 244 of file Project.cpp.
postPhysicsUpdate()
int Atlas::BProject::postPhysicsUpdate () [override], [virtual]
Post physics update that is called after physicsUpdate() in the physics or update thread (depending on thread count).
Returns
The exit code of the step
Post physics update that is called after physicsUpdate() in the physics or update thread (depending on thread count).
Returns
The exit code of the step
Implements Atlas::IProject.
Definition at line 232 of file Project.cpp.
preInit()
void Atlas::BProject::preInit () [override], [virtual]
This is the first function that will be called on startup.
This is the first function that will be called on startup.
Since
v0.0.1
Implements Atlas::IProject.
Reimplemented in Project.
Definition at line 73 of file Project.cpp.
References Atlas::AddFileRegistryLoadFunction(), ATLAS_GAME_DIR, Atlas::GetFilePath(), Atlas::ConfigFileRegistry::init(), Atlas::FileSystemRegistry::init(), and Atlas::Log().
Referenced by Project::preInit().
preObjectUpdate()
int Atlas::BProject::preObjectUpdate () [override], [virtual]
Any preparation code for updating the scene's game objects. Use this if you need to do something after the physics update, but before the GameObject update. Please note that this will run on the update thread!
Returns
The exit code of the step
Any preparation code for updating the scene's game objects. Use this if you need to do something after the physics update, but before the GameObject update. Please note that this will run on the update thread!
Returns
The exit code of the step
Implements Atlas::IProject.
Definition at line 236 of file Project.cpp.
prePhysicsUpdate()
int Atlas::BProject::prePhysicsUpdate () [override], [virtual]
Pre-update step that is called in the physics or update thread (depending on thread count)
Returns
The exit code of the step
Pre-update step that is called in the physics or update thread (depending on thread count)
Returns
The exit code of the step
Implements Atlas::IProject.
Definition at line 218 of file Project.cpp.
render()
int Atlas::BProject::render () [override], [virtual]
Assuming that the FBO is enabled, this will render the FBO and apply any post-processing effects to the FBO. Please note that this will run on the update thread!
Returns
An integer that is the exit code for this rendering frame.
Assuming that the FBO is enabled, this will render the FBO and apply any post-processing effects to the FBO. Please note that this will run on the update thread!
Returns
An integer that is the exit code for this rendering frame.
Implements Atlas::IProject.
Definition at line 253 of file Project.cpp.
run()
int Atlas::BProject::run (int argc, char * argv[]) [override], [virtual]
Runs the actual game and is called after the init functions.
Parameters
argc Command line argument count int
argv Command line arguments array
Returns
The game loop's exit code
Runs the actual game and is called after the init functions.
Parameters
argc Command line argument count int
argv Command line arguments array
Returns
The game loop's exit code
Implements Atlas::IProject.
Definition at line 184 of file Project.cpp.
setProject()
template<typename T >
void Atlas::BProject::setProject (T * project)
This function is used to set the ProjectReference singleton to the project.
Template Parameters
T The typename for what the user's project is
Parameters
project The pointer to the user's project
setupAtlas()
Atlas::ThreadSafeVariable< AtlasEngine * > Atlas::BProject::setupAtlas () [override], [protected], [virtual]
Implements Atlas::IProject.
Definition at line 30 of file Project.cpp.
Referenced by BProject().
setWindowDecorations()
void Atlas::BProject::setWindowDecorations (WindowDecorations & windowDecorations)
Sets the window decorations.
See also
Atlas::WindowDecorations
Parameters
windowDecorations The window decorations.
Definition at line 69 of file Project.cpp.
texture()
int Atlas::BProject::texture () [override], [virtual]
Textures all GameObjects before render() is called and after update functions are called. This is essentially where the scene is rendered. Please note that this will run on the render thread!
Returns
An integer that is the exit code for this texturing frame.
Textures all GameObjects before render() is called and after update functions are called. This is essentially where the scene is rendered. Please note that this will run on the render thread!
Returns
An integer that is the exit code for this texturing frame.
Implements Atlas::IProject.
Reimplemented in Project.
Definition at line 248 of file Project.cpp.
Referenced by Project::texture().
update()
int Atlas::BProject::update () [override], [virtual]
Updates this instance in the updating thread.
Returns
Implements Atlas::IProject.
Reimplemented in Project, and SamplesProject.
Definition at line 200 of file Project.cpp.
Referenced by Project::update().
workingUpdate()
int Atlas::BProject::workingUpdate () [override], [virtual]
Implements Atlas::IProject.
Definition at line 209 of file Project.cpp.
Member Data Documentation
mAtlas
ThreadSafeVariable<AtlasEngine*> Atlas::BProject::mAtlas = nullptr [inline], [static]
Definition at line 77 of file Project.h.
Referenced by BProject().
mHasCleanedUp
bool Atlas::BProject::mHasCleanedUp = false [protected]
A flag that indicates whether or not the project has been cleaned up.
Definition at line 39 of file Project.h.
mLuaFunctions
ScriptingFunctionRegistry Atlas::BProject::mLuaFunctions [protected]
Definition at line 42 of file Project.h.
Referenced by getLuaFunctions().
mLuaLibraries
ScriptingLibraryRegistry Atlas::BProject::mLuaLibraries [protected]
Definition at line 41 of file Project.h.
Referenced by getLuaLibraries().
mProject
std::shared_ptr<BProject> Atlas::BProject::mProject = nullptr [inline], [static], [protected]
Definition at line 70 of file Project.h.
Referenced by BProject().
mWindowDecorations
WindowDecorations Atlas::BProject::mWindowDecorations [protected]
Definition at line 40 of file Project.h.
settings
GameSettings Atlas::BProject::settings
Definition at line 76 of file Project.h.
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/Project.h
C:/Dev/Techstorm-v5/src/engine/Project.cpp