C:/Dev/Techstorm-v5/src/application/add_on/scriptfile/scriptfile.cpp File Reference
#include "scriptfile.h"
#include <new>
#include <assert.h>
#include <string>
#include <string.h>
#include <stdio.h>
Functions
BEGIN_AS_NAMESPACE CScriptFile * ScriptFile_Factory ()
void ScriptFile_Factory_Generic (asIScriptGeneric *gen)
void ScriptFile_AddRef_Generic (asIScriptGeneric *gen)
void ScriptFile_Release_Generic (asIScriptGeneric *gen)
void ScriptFile_Open_Generic (asIScriptGeneric *gen)
void ScriptFile_Close_Generic (asIScriptGeneric *gen)
void ScriptFile_GetSize_Generic (asIScriptGeneric *gen)
void ScriptFile_ReadString_Generic (asIScriptGeneric *gen)
void ScriptFile_ReadLine_Generic (asIScriptGeneric *gen)
void ScriptFile_ReadInt_Generic (asIScriptGeneric *gen)
void ScriptFile_ReadUInt_Generic (asIScriptGeneric *gen)
void ScriptFile_ReadFloat_Generic (asIScriptGeneric *gen)
void ScriptFile_ReadDouble_Generic (asIScriptGeneric *gen)
void ScriptFile_WriteString_Generic (asIScriptGeneric *gen)
void ScriptFile_WriteInt_Generic (asIScriptGeneric *gen)
void ScriptFile_WriteUInt_Generic (asIScriptGeneric *gen)
void ScriptFile_WriteFloat_Generic (asIScriptGeneric *gen)
void ScriptFile_WriteDouble_Generic (asIScriptGeneric *gen)
void ScriptFile_IsEOF_Generic (asIScriptGeneric *gen)
void ScriptFile_GetPos_Generic (asIScriptGeneric *gen)
void ScriptFile_SetPos_Generic (asIScriptGeneric *gen)
void ScriptFile_MovePos_Generic (asIScriptGeneric *gen)
void RegisterScriptFile_Native (asIScriptEngine *engine)
void RegisterScriptFile_Generic (asIScriptEngine *engine)
void RegisterScriptFile (asIScriptEngine *engine)
Function Documentation
RegisterScriptFile()
void RegisterScriptFile (asIScriptEngine * engine)
Definition at line 235 of file scriptfile.cpp.
References RegisterScriptFile_Generic(), and RegisterScriptFile_Native().
RegisterScriptFile_Generic()
void RegisterScriptFile_Generic (asIScriptEngine * engine)
Definition at line 202 of file scriptfile.cpp.
References ScriptFile_AddRef_Generic(), ScriptFile_Close_Generic(), ScriptFile_Factory_Generic(), ScriptFile_GetPos_Generic(), ScriptFile_GetSize_Generic(), ScriptFile_IsEOF_Generic(), ScriptFile_MovePos_Generic(), ScriptFile_Open_Generic(), ScriptFile_ReadDouble_Generic(), ScriptFile_ReadFloat_Generic(), ScriptFile_ReadInt_Generic(), ScriptFile_ReadLine_Generic(), ScriptFile_ReadString_Generic(), ScriptFile_ReadUInt_Generic(), ScriptFile_Release_Generic(), ScriptFile_SetPos_Generic(), ScriptFile_WriteDouble_Generic(), ScriptFile_WriteFloat_Generic(), ScriptFile_WriteInt_Generic(), ScriptFile_WriteString_Generic(), and ScriptFile_WriteUInt_Generic().
Referenced by RegisterScriptFile().
RegisterScriptFile_Native()
void RegisterScriptFile_Native (asIScriptEngine * engine)
Definition at line 169 of file scriptfile.cpp.
References ScriptFile_Factory().
Referenced by RegisterScriptFile().
ScriptFile_AddRef_Generic()
void ScriptFile_AddRef_Generic (asIScriptGeneric * gen)
Definition at line 29 of file scriptfile.cpp.
References CScriptFile::AddRef().
Referenced by RegisterScriptFile_Generic().
ScriptFile_Close_Generic()
void ScriptFile_Close_Generic (asIScriptGeneric * gen)
Definition at line 50 of file scriptfile.cpp.
References CScriptFile::Close().
Referenced by RegisterScriptFile_Generic().
ScriptFile_Factory()
BEGIN_AS_NAMESPACE CScriptFile * ScriptFile_Factory ()
Definition at line 19 of file scriptfile.cpp.
Referenced by RegisterScriptFile_Native(), and ScriptFile_Factory_Generic().
ScriptFile_Factory_Generic()
void ScriptFile_Factory_Generic (asIScriptGeneric * gen)
Definition at line 24 of file scriptfile.cpp.
References ScriptFile_Factory().
Referenced by RegisterScriptFile_Generic().
ScriptFile_GetPos_Generic()
void ScriptFile_GetPos_Generic (asIScriptGeneric * gen)
Definition at line 149 of file scriptfile.cpp.
References CScriptFile::GetPos().
Referenced by RegisterScriptFile_Generic().
ScriptFile_GetSize_Generic()
void ScriptFile_GetSize_Generic (asIScriptGeneric * gen)
Definition at line 57 of file scriptfile.cpp.
References CScriptFile::GetSize().
Referenced by RegisterScriptFile_Generic().
ScriptFile_IsEOF_Generic()
void ScriptFile_IsEOF_Generic (asIScriptGeneric * gen)
Definition at line 142 of file scriptfile.cpp.
References CScriptFile::IsEOF().
Referenced by RegisterScriptFile_Generic().
ScriptFile_MovePos_Generic()
void ScriptFile_MovePos_Generic (asIScriptGeneric * gen)
Definition at line 162 of file scriptfile.cpp.
References CScriptFile::MovePos().
Referenced by RegisterScriptFile_Generic().
ScriptFile_Open_Generic()
void ScriptFile_Open_Generic (asIScriptGeneric * gen)
Definition at line 41 of file scriptfile.cpp.
References CScriptFile::Open().
Referenced by RegisterScriptFile_Generic().
ScriptFile_ReadDouble_Generic()
void ScriptFile_ReadDouble_Generic (asIScriptGeneric * gen)
Definition at line 99 of file scriptfile.cpp.
References CScriptFile::ReadDouble().
Referenced by RegisterScriptFile_Generic().
ScriptFile_ReadFloat_Generic()
void ScriptFile_ReadFloat_Generic (asIScriptGeneric * gen)
Definition at line 93 of file scriptfile.cpp.
References CScriptFile::ReadFloat().
Referenced by RegisterScriptFile_Generic().
ScriptFile_ReadInt_Generic()
void ScriptFile_ReadInt_Generic (asIScriptGeneric * gen)
Definition at line 79 of file scriptfile.cpp.
References CScriptFile::ReadInt().
Referenced by RegisterScriptFile_Generic().
ScriptFile_ReadLine_Generic()
void ScriptFile_ReadLine_Generic (asIScriptGeneric * gen)
Definition at line 72 of file scriptfile.cpp.
References CScriptFile::ReadLine().
Referenced by RegisterScriptFile_Generic().
ScriptFile_ReadString_Generic()
void ScriptFile_ReadString_Generic (asIScriptGeneric * gen)
Definition at line 64 of file scriptfile.cpp.
References CScriptFile::ReadString().
Referenced by RegisterScriptFile_Generic().
ScriptFile_ReadUInt_Generic()
void ScriptFile_ReadUInt_Generic (asIScriptGeneric * gen)
Definition at line 86 of file scriptfile.cpp.
References CScriptFile::ReadUInt().
Referenced by RegisterScriptFile_Generic().
ScriptFile_Release_Generic()
void ScriptFile_Release_Generic (asIScriptGeneric * gen)
Definition at line 35 of file scriptfile.cpp.
References CScriptFile::Release().
Referenced by RegisterScriptFile_Generic().
ScriptFile_SetPos_Generic()
void ScriptFile_SetPos_Generic (asIScriptGeneric * gen)
Definition at line 155 of file scriptfile.cpp.
References CScriptFile::SetPos().
Referenced by RegisterScriptFile_Generic().
ScriptFile_WriteDouble_Generic()
void ScriptFile_WriteDouble_Generic (asIScriptGeneric * gen)
Definition at line 135 of file scriptfile.cpp.
References CScriptFile::WriteDouble().
Referenced by RegisterScriptFile_Generic().
ScriptFile_WriteFloat_Generic()
void ScriptFile_WriteFloat_Generic (asIScriptGeneric * gen)
Definition at line 128 of file scriptfile.cpp.
References CScriptFile::WriteFloat().
Referenced by RegisterScriptFile_Generic().
ScriptFile_WriteInt_Generic()
void ScriptFile_WriteInt_Generic (asIScriptGeneric * gen)
Definition at line 112 of file scriptfile.cpp.
References CScriptFile::WriteInt().
Referenced by RegisterScriptFile_Generic().
ScriptFile_WriteString_Generic()
void ScriptFile_WriteString_Generic (asIScriptGeneric * gen)
Definition at line 105 of file scriptfile.cpp.
References CScriptFile::WriteString().
Referenced by RegisterScriptFile_Generic().
ScriptFile_WriteUInt_Generic()
void ScriptFile_WriteUInt_Generic (asIScriptGeneric * gen)
Definition at line 120 of file scriptfile.cpp.
References CScriptFile::WriteUInt().
Referenced by RegisterScriptFile_Generic().