Atlas::VulkanRenderingBackend Class Reference
A wrapper class for the usage of Vulkan as a rendering backend. This class handles the lifecycle of Vulkan and simplifies the usage of Vulkan to a simple API.
#include <VKDevice.h>
Public Member Functions
VulkanRenderingBackend ()=default
Default constructor.
void init (AGameWindow *gameWindow) override
Initializes Vulkan.
void initDefaultData ()
void initPhysicalDevice ()
void initSwapchain (AGameWindow *gameWindow)
void initCommands ()
void initIMGUI (AGameWindow *gameWindow)
void resetFences (const uint32_t cFenceCount, FrameData &currentFrame)
void beginDrawingMode ()
void endDrawingMode ()
void draw ()
void drawIMGUI (VkCommandBuffer cmd, VkImageView targetImageView)
void drawBackground (VkCommandBuffer cmd)
void drawGeometry (VkCommandBuffer cmd)
void present ()
void shutdown () override
void shouldUseDefaultInstanceBuilder (bool bUseDefaultInstanceBuilder)
void setApplicationName (std::string_view applicationName)
void setFenceTimeout (uint64_t lengthInNS)
void setNextImageTimeout (uint64_t lengthInNS)
AllocatedBuffer createBuffer (size_t allocSize, VkBufferUsageFlags usage, VmaMemoryUsage memoryUsage)
void destroyBuffer (const AllocatedBuffer &buffer)
void createSwapchain (uint32_t width, uint32_t height)
void destroySwapchain ()
GPUMeshBuffers UploadMesh (std::span< uint32_t > indices, std::span< Vertex > vertices)
void ImmediateSubmit (std::function< void(VkCommandBuffer cmd)> &&function)
bool checkValidationLayerSupport ()
bool canInitialize (AGameWindow *gameWindow)
std::string getApplicationName ()
FrameData & getCurrentFrame ()
RenderingBackend ()=default
Public Member Functions inherited from Atlas::RenderingBackend
RenderingBackend ()=default
virtual ~RenderingBackend ()
virtual void beginDrawing ()
virtual void endDrawing ()
virtual void setAPIVersion (uint32_t major, uint32_t minor, uint32_t patch)
virtual void setAPIVersion (Version version)
virtual Version getAPIVersion () const
bool areDebuggingToolsEnabled () const
bool isErrorCheckingEnabled () const
template<typename T_CAST_TO >
T_CAST_TO * castAs ()
Private Member Functions
uint16_t initInstance (const APIVersion &cAPIVersionRef, const bool cbEnableValidationLayers, std::string const &appName)
void initDescriptors ()
void initPipelines ()
void initBackgroundPipelines ()
void initTrianglePipeline ()
void initMeshPipeline ()
void initVMAAllocator (vkb::Instance const &cVkBootstrapInstanceRef)
Private Attributes
std::vector< ComputeEffect > mBackgroundEffects
int mCurrentBackgroundEffect = 0
CurrentDrawData mCurrentDrawData
std::vector< std::shared_ptr< MeshAsset > > testMeshes
int mCurrentFrameNumber = 0
bool mIsInitialized = false
bool mbUseDefaultInstanceBuilder = true
ImmediateSubmitInfo mImmediateSubmitInfo
VulkanInstanceWrapper mInstance {}
PhysicalDevice mPhysicalDevice
VkSurfaceKHR mSurface = VK_NULL_HANDLE
Device mDevice
VkSwapchainKHR mSwapchain = VK_NULL_HANDLE
VkFormat mSwapchainImageFormat
std::vector< VkImage > mSwapchainImages
std::vector< VkImageView > mSwapchainImageViews
VkExtent2D mSwapchainExtent
std::array< FrameData, FRAME_OVERLAP > mFrameDataArray
AllocatedImage mDrawImage
VkExtent2D mDrawExtent
VkQueue mGraphicsQueue = VK_NULL_HANDLE
uint32_t mGraphicsQueueFamily
DeletionQueue mMainDeletionQueue
VmaAllocator mVMAAllocator = VK_NULL_HANDLE
uint64_t mFencesTimeoutNS = ATLAS_1_SECOND_IN_NS
uint64_t mNextImageTimeoutNS = ATLAS_1_SECOND_IN_NS
DescriptorAllocator mGlobalDescriptorAllocator
VkDescriptorSet mDrawImageDescriptors
VkDescriptorSetLayout mDrawImageDescriptorLayout
VkPipeline mGradientPipeline
VkPipelineLayout mGradientPipelineLayout
VkPipelineLayout _trianglePipelineLayout
VkPipeline _trianglePipeline
VkPipelineLayout _meshPipelineLayout
VkPipeline _meshPipeline
GPUMeshBuffers rectangle
std::string mApplicationName
Static Private Attributes
static std::shared_ptr< VulkanRenderingBackend > sInstance = nullptr
static std::mutex sInstanceMutex
Friends
class SDLGameWindow
Additional Inherited Members
Public Types inherited from Atlas::RenderingBackend
using APIVersion = Version
Protected Attributes inherited from Atlas::RenderingBackend
std::shared_ptr< State > mState
std::shared_mutex mStateMutex
Version mAPIVersion
bool mbIsInitialized = false
bool mbUseDebuggingTools = false
bool mbEnableErrorChecking = false
Detailed Description
A wrapper class for the usage of Vulkan as a rendering backend. This class handles the lifecycle of Vulkan and simplifies the usage of Vulkan to a simple API.
Precondition
The window must be set up and open prior to initializing Vulkan (and therefore this class!).
Warning
This class requires the user's device to support Vulkan!
Since
v0.0.1
Definition at line 382 of file VKDevice.h.
Constructor & Destructor Documentation
VulkanRenderingBackend()
Atlas::VulkanRenderingBackend::VulkanRenderingBackend () [default]
Default constructor.
Note
This constructor is not intended to be used because the mAppInfo and mCreateInfo are required to create a Vulkan instance (and they are declared as a const!). Additionally, the variable mCreateInfo requires information on extensions and such, and since Atlas does not mandate any specific window management system (ie. GLFW), the mAppInfo MUST be set prior to calling this.
Since
v0.0.1
See also
mAppInfo
mCreateInfo
Member Function Documentation
beginDrawingMode()
void Atlas::VulkanRenderingBackend::beginDrawingMode ()
Definition at line 944 of file VKDevice.cpp.
References Atlas::CreateCommandBufferBeginInfo(), Atlas::ComputeEffect::data, Atlas::ComputePushConstants::data1, Atlas::ComputePushConstants::data2, Atlas::ComputePushConstants::data3, Atlas::ComputePushConstants::data4, ImGui_ImplSDL2_NewFrame(), ImGui_ImplVulkan_NewFrame(), Atlas::FrameData::mainCommandBuffer, Atlas::ComputeEffect::name, and Atlas::FrameData::swapchainSemaphore.
canInitialize()
bool Atlas::VulkanRenderingBackend::canInitialize (AGameWindow * gameWindow)
Definition at line 1259 of file VKDevice.cpp.
References Atlas::AGameWindow::isInitialized(), and Atlas::AGameWindow::isOpen().
checkValidationLayerSupport()
bool Atlas::VulkanRenderingBackend::checkValidationLayerSupport ()
Definition at line 1233 of file VKDevice.cpp.
createBuffer()
AllocatedBuffer Atlas::VulkanRenderingBackend::createBuffer (size_t allocSize, VkBufferUsageFlags usage, VmaMemoryUsage memoryUsage)
Definition at line 154 of file VKDevice.cpp.
References Atlas::AllocatedBuffer::allocation, Atlas::AllocatedBuffer::buffer, and Atlas::AllocatedBuffer::info.
createSwapchain()
void Atlas::VulkanRenderingBackend::createSwapchain (uint32_t width, uint32_t height)
Definition at line 602 of file VKDevice.cpp.
destroyBuffer()
void Atlas::VulkanRenderingBackend::destroyBuffer (const AllocatedBuffer & buffer)
Definition at line 175 of file VKDevice.cpp.
destroySwapchain()
void Atlas::VulkanRenderingBackend::destroySwapchain ()
Definition at line 633 of file VKDevice.cpp.
draw()
void Atlas::VulkanRenderingBackend::draw () [virtual]
Reimplemented from Atlas::RenderingBackend.
Definition at line 1045 of file VKDevice.cpp.
References Atlas::CopyImageToImage(), and Atlas::TransitionImage().
drawBackground()
void Atlas::VulkanRenderingBackend::drawBackground (VkCommandBuffer cmd)
Definition at line 1087 of file VKDevice.cpp.
References Atlas::ComputeEffect::data, and Atlas::ComputeEffect::pipeline.
drawGeometry()
void Atlas::VulkanRenderingBackend::drawGeometry (VkCommandBuffer cmd)
Definition at line 1135 of file VKDevice.cpp.
References Atlas::CreateAttachmentInfo(), Atlas::CreateRenderingInfo(), Atlas::GPUDrawPushConstants::vertexBuffer, and Atlas::GPUDrawPushConstants::worldMatrix.
drawIMGUI()
void Atlas::VulkanRenderingBackend::drawIMGUI (VkCommandBuffer cmd, VkImageView targetImageView)
Definition at line 1073 of file VKDevice.cpp.
References Atlas::CreateAttachmentInfo(), Atlas::CreateRenderingInfo(), and ImGui_ImplVulkan_RenderDrawData().
endDrawingMode()
void Atlas::VulkanRenderingBackend::endDrawingMode ()
Definition at line 999 of file VKDevice.cpp.
References Atlas::FrameData::renderFence, Atlas::FrameData::renderSemaphore, Atlas::SubmitCommandBufferInfo(), Atlas::SubmitInfo(), Atlas::SubmitSemaphoreInfo(), and Atlas::FrameData::swapchainSemaphore.
getApplicationName()
std::string Atlas::VulkanRenderingBackend::getApplicationName ()
Definition at line 142 of file VKDevice.cpp.
getCurrentFrame()
Atlas::FrameData & Atlas::VulkanRenderingBackend::getCurrentFrame ()
Definition at line 181 of file VKDevice.cpp.
References Atlas::FRAME_OVERLAP.
ImmediateSubmit()
void Atlas::VulkanRenderingBackend::ImmediateSubmit (std::function< void(VkCommandBuffer cmd)> && function)
Definition at line 694 of file VKDevice.cpp.
References Atlas::CreateCommandBufferBeginInfo(), Atlas::SubmitCommandBufferInfo(), and Atlas::SubmitInfo().
init()
void Atlas::VulkanRenderingBackend::init (AGameWindow * gameWindow) [override], [virtual]
Initializes Vulkan.
Parameters
windowHandle The currently initialized and open window pointer.
Precondition
You must make sure that the window is initialized and open before calling this!
Note
This can take some time to complete. Further testing should be done to see if this is a problem.
Since
v0.0.1
Implements Atlas::RenderingBackend.
Definition at line 723 of file VKDevice.cpp.
References ATLAS_ASSERT, Atlas::ErrorLog(), Atlas::AGameWindow::getUncastWindowHandle(), Atlas::InfoLog(), Atlas::Version::major, Atlas::Version::minor, and Atlas::Version::patch.
initBackgroundPipelines()
void Atlas::VulkanRenderingBackend::initBackgroundPipelines () [private]
Definition at line 256 of file VKDevice.cpp.
References Atlas::ComputeEffect::data, Atlas::ComputePushConstants::data1, Atlas::ComputePushConstants::data2, Atlas::ComputeEffect::layout, Atlas::LoadShaderModule(), Atlas::ComputeEffect::name, and Atlas::ComputeEffect::pipeline.
initCommands()
void Atlas::VulkanRenderingBackend::initCommands ()
Definition at line 484 of file VKDevice.cpp.
References Atlas::CreateCommandBufferAllocateInfo(), Atlas::CreateCommandPoolCreateInfo(), Atlas::CreateFenceCreateInfo(), Atlas::CreateSemaphoreCreateInfo(), and Atlas::FRAME_OVERLAP.
initDefaultData()
void Atlas::VulkanRenderingBackend::initDefaultData ()
Definition at line 808 of file VKDevice.cpp.
References Atlas::loadGltfMeshes().
initDescriptors()
void Atlas::VulkanRenderingBackend::initDescriptors () [private]
Definition at line 204 of file VKDevice.cpp.
References Atlas::DescriptorLayoutBuilder::addBinding(), and Atlas::DescriptorLayoutBuilder::build().
initIMGUI()
void Atlas::VulkanRenderingBackend::initIMGUI (AGameWindow * gameWindow)
Definition at line 537 of file VKDevice.cpp.
References ImGui_ImplVulkan_InitInfo::DescriptorPool, ImGui_ImplVulkan_InitInfo::Device, Atlas::AGameWindow::getUncastWindowHandle(), ImGui_ImplVulkan_InitInfo::ImageCount, ImGui_ImplSDL2_InitForVulkan(), ImGui_ImplVulkan_Init(), ImGui_ImplVulkan_Shutdown(), ImGui_ImplVulkan_InitInfo::Instance, ImGui_ImplVulkan_InitInfo::MinImageCount, ImGui_ImplVulkan_InitInfo::MSAASamples, ImGui_ImplVulkan_InitInfo::PhysicalDevice, ImGui_ImplVulkan_InitInfo::Queue, and ImGui_ImplVulkan_InitInfo::UseDynamicRendering.
initInstance()
uint16_t Atlas::VulkanRenderingBackend::initInstance (const APIVersion & cAPIVersionRef, const bool cbEnableValidationLayers, std::string const & appName) [private]
Definition at line 186 of file VKDevice.cpp.
initMeshPipeline()
void Atlas::VulkanRenderingBackend::initMeshPipeline () [private]
Definition at line 398 of file VKDevice.cpp.
References Atlas::PipelineBuilder::buildPipeline(), Atlas::CreatePipelineLayoutCreateInfo(), Atlas::PipelineBuilder::disableBlending(), Atlas::PipelineBuilder::disableDepthTest(), Atlas::ErrorLog(), Atlas::LoadShaderModule(), Atlas::PipelineBuilderSettings::pipelineLayout, Atlas::PipelineBuilder::setColorAttachmentFormat(), Atlas::PipelineBuilder::setCullMode(), Atlas::PipelineBuilder::setDepthFormat(), Atlas::PipelineBuilder::setInputTopography(), Atlas::PipelineBuilder::setMultisamplingNone(), Atlas::PipelineBuilder::setPolygonMode(), Atlas::PipelineBuilder::setShaders(), Atlas::PipelineBuilder::settings, and Atlas::TraceLog().
initPhysicalDevice()
void Atlas::VulkanRenderingBackend::initPhysicalDevice ()
Definition at line 843 of file VKDevice.cpp.
References Atlas::InfoLog(), and Atlas::PhysicalDeviceSelectionConstraints::minimumAPIVersion.
initPipelines()
void Atlas::VulkanRenderingBackend::initPipelines () [private]
Definition at line 249 of file VKDevice.cpp.
initSwapchain()
void Atlas::VulkanRenderingBackend::initSwapchain (AGameWindow * gameWindow)
Definition at line 888 of file VKDevice.cpp.
References Atlas::CreateImageCreateInfo(), Atlas::CreateImageViewCreateInfo(), Atlas::AGameWindow::getWindowDescription(), Atlas::Rectangle< T_NUMERIC_TYPE >::height, Atlas::Rectangle< T_NUMERIC_TYPE >::width, and Atlas::WindowDescription::windowRectangle.
initTrianglePipeline()
void Atlas::VulkanRenderingBackend::initTrianglePipeline () [private]
Definition at line 339 of file VKDevice.cpp.
References Atlas::PipelineBuilder::buildPipeline(), Atlas::CreatePipelineLayoutCreateInfo(), Atlas::PipelineBuilder::disableBlending(), Atlas::PipelineBuilder::disableDepthTest(), Atlas::ErrorLog(), Atlas::LoadShaderModule(), Atlas::PipelineBuilderSettings::pipelineLayout, Atlas::PipelineBuilder::setColorAttachmentFormat(), Atlas::PipelineBuilder::setCullMode(), Atlas::PipelineBuilder::setDepthFormat(), Atlas::PipelineBuilder::setInputTopography(), Atlas::PipelineBuilder::setMultisamplingNone(), Atlas::PipelineBuilder::setPolygonMode(), Atlas::PipelineBuilder::setShaders(), Atlas::PipelineBuilder::settings, and Atlas::TraceLog().
initVMAAllocator()
void Atlas::VulkanRenderingBackend::initVMAAllocator (vkb::Instance const & cVkBootstrapInstanceRef) [private]
Definition at line 469 of file VKDevice.cpp.
present()
void Atlas::VulkanRenderingBackend::present ()
Definition at line 1189 of file VKDevice.cpp.
RenderingBackend()
Atlas::RenderingBackend::RenderingBackend () [default]
resetFences()
void Atlas::VulkanRenderingBackend::resetFences (const uint32_t cFenceCount, FrameData & currentFrame)
Definition at line 935 of file VKDevice.cpp.
References Atlas::FrameData::deletionQueue, Atlas::DeletionQueue::flush(), and Atlas::FrameData::renderFence.
setApplicationName()
void Atlas::VulkanRenderingBackend::setApplicationName (std::string_view applicationName)
Definition at line 138 of file VKDevice.cpp.
setFenceTimeout()
void Atlas::VulkanRenderingBackend::setFenceTimeout (uint64_t lengthInNS)
Definition at line 146 of file VKDevice.cpp.
setNextImageTimeout()
void Atlas::VulkanRenderingBackend::setNextImageTimeout (uint64_t lengthInNS)
Definition at line 150 of file VKDevice.cpp.
shouldUseDefaultInstanceBuilder()
void Atlas::VulkanRenderingBackend::shouldUseDefaultInstanceBuilder (bool bUseDefaultInstanceBuilder)
Definition at line 1228 of file VKDevice.cpp.
shutdown()
void Atlas::VulkanRenderingBackend::shutdown () [override], [virtual]
Reimplemented from Atlas::RenderingBackend.
Definition at line 1193 of file VKDevice.cpp.
References Atlas::FRAME_OVERLAP.
Referenced by Atlas::setLoadedRenderingBackend().
UploadMesh()
GPUMeshBuffers Atlas::VulkanRenderingBackend::UploadMesh (std::span< uint32_t > indices, std::span< Vertex > vertices)
Definition at line 644 of file VKDevice.cpp.
References Atlas::AllocatedBuffer::allocation, Atlas::AllocatedBuffer::buffer, Atlas::GPUMeshBuffers::indexBuffer, Atlas::GPUMeshBuffers::vertexBuffer, and Atlas::GPUMeshBuffers::vertexBufferAddress.
Referenced by Atlas::loadGltfMeshes().
Friends And Related Symbol Documentation
SDLGameWindow
friend class SDLGameWindow [friend]
Definition at line 470 of file VKDevice.h.
Member Data Documentation
_meshPipeline
VkPipeline Atlas::VulkanRenderingBackend::_meshPipeline [private]
Definition at line 453 of file VKDevice.h.
_meshPipelineLayout
VkPipelineLayout Atlas::VulkanRenderingBackend::_meshPipelineLayout [private]
Definition at line 452 of file VKDevice.h.
_trianglePipeline
VkPipeline Atlas::VulkanRenderingBackend::_trianglePipeline [private]
Definition at line 450 of file VKDevice.h.
_trianglePipelineLayout
VkPipelineLayout Atlas::VulkanRenderingBackend::_trianglePipelineLayout [private]
Definition at line 449 of file VKDevice.h.
mApplicationName
std::string Atlas::VulkanRenderingBackend::mApplicationName [private]
Definition at line 457 of file VKDevice.h.
mBackgroundEffects
std::vector<ComputeEffect> Atlas::VulkanRenderingBackend::mBackgroundEffects [private]
Definition at line 388 of file VKDevice.h.
mbUseDefaultInstanceBuilder
bool Atlas::VulkanRenderingBackend::mbUseDefaultInstanceBuilder = true [private]
Definition at line 400 of file VKDevice.h.
mCurrentBackgroundEffect
int Atlas::VulkanRenderingBackend::mCurrentBackgroundEffect = 0 [private]
Definition at line 389 of file VKDevice.h.
mCurrentDrawData
CurrentDrawData Atlas::VulkanRenderingBackend::mCurrentDrawData [private]
Definition at line 391 of file VKDevice.h.
mCurrentFrameNumber
int Atlas::VulkanRenderingBackend::mCurrentFrameNumber = 0 [private]
Definition at line 397 of file VKDevice.h.
mDevice
Device Atlas::VulkanRenderingBackend::mDevice [private]
Definition at line 415 of file VKDevice.h.
mDrawExtent
VkExtent2D Atlas::VulkanRenderingBackend::mDrawExtent [private]
Definition at line 428 of file VKDevice.h.
mDrawImage
AllocatedImage Atlas::VulkanRenderingBackend::mDrawImage [private]
Definition at line 427 of file VKDevice.h.
mDrawImageDescriptorLayout
VkDescriptorSetLayout Atlas::VulkanRenderingBackend::mDrawImageDescriptorLayout [private]
Definition at line 444 of file VKDevice.h.
mDrawImageDescriptors
VkDescriptorSet Atlas::VulkanRenderingBackend::mDrawImageDescriptors [private]
Definition at line 443 of file VKDevice.h.
mFencesTimeoutNS
uint64_t Atlas::VulkanRenderingBackend::mFencesTimeoutNS = ATLAS_1_SECOND_IN_NS [private]
Definition at line 438 of file VKDevice.h.
mFrameDataArray
std::array<FrameData, FRAME_OVERLAP> Atlas::VulkanRenderingBackend::mFrameDataArray [private]
Definition at line 425 of file VKDevice.h.
mGlobalDescriptorAllocator
DescriptorAllocator Atlas::VulkanRenderingBackend::mGlobalDescriptorAllocator [private]
Definition at line 441 of file VKDevice.h.
mGradientPipeline
VkPipeline Atlas::VulkanRenderingBackend::mGradientPipeline [private]
Definition at line 446 of file VKDevice.h.
mGradientPipelineLayout
VkPipelineLayout Atlas::VulkanRenderingBackend::mGradientPipelineLayout [private]
Definition at line 447 of file VKDevice.h.
mGraphicsQueue
VkQueue Atlas::VulkanRenderingBackend::mGraphicsQueue = VK_NULL_HANDLE [private]
Definition at line 432 of file VKDevice.h.
mGraphicsQueueFamily
uint32_t Atlas::VulkanRenderingBackend::mGraphicsQueueFamily [private]
Definition at line 433 of file VKDevice.h.
mImmediateSubmitInfo
ImmediateSubmitInfo Atlas::VulkanRenderingBackend::mImmediateSubmitInfo [private]
Definition at line 402 of file VKDevice.h.
mInstance
VulkanInstanceWrapper Atlas::VulkanRenderingBackend::mInstance {} [private]
Definition at line 404 of file VKDevice.h.
mIsInitialized
bool Atlas::VulkanRenderingBackend::mIsInitialized = false [private]
Definition at line 399 of file VKDevice.h.
mMainDeletionQueue
DeletionQueue Atlas::VulkanRenderingBackend::mMainDeletionQueue [private]
Definition at line 435 of file VKDevice.h.
mNextImageTimeoutNS
uint64_t Atlas::VulkanRenderingBackend::mNextImageTimeoutNS = ATLAS_1_SECOND_IN_NS [private]
Definition at line 439 of file VKDevice.h.
mPhysicalDevice
PhysicalDevice Atlas::VulkanRenderingBackend::mPhysicalDevice [private]
Definition at line 409 of file VKDevice.h.
mSurface
VkSurfaceKHR Atlas::VulkanRenderingBackend::mSurface = VK_NULL_HANDLE [private]
Definition at line 413 of file VKDevice.h.
mSwapchain
VkSwapchainKHR Atlas::VulkanRenderingBackend::mSwapchain = VK_NULL_HANDLE [private]
Definition at line 417 of file VKDevice.h.
mSwapchainExtent
VkExtent2D Atlas::VulkanRenderingBackend::mSwapchainExtent [private]
Definition at line 422 of file VKDevice.h.
mSwapchainImageFormat
VkFormat Atlas::VulkanRenderingBackend::mSwapchainImageFormat [private]
Definition at line 418 of file VKDevice.h.
mSwapchainImages
std::vector<VkImage> Atlas::VulkanRenderingBackend::mSwapchainImages [private]
Definition at line 420 of file VKDevice.h.
mSwapchainImageViews
std::vector<VkImageView> Atlas::VulkanRenderingBackend::mSwapchainImageViews [private]
Definition at line 421 of file VKDevice.h.
mVMAAllocator
VmaAllocator Atlas::VulkanRenderingBackend::mVMAAllocator = VK_NULL_HANDLE [private]
Definition at line 436 of file VKDevice.h.
rectangle
GPUMeshBuffers Atlas::VulkanRenderingBackend::rectangle [private]
Definition at line 455 of file VKDevice.h.
sInstance
std::shared_ptr<VulkanRenderingBackend> Atlas::VulkanRenderingBackend::sInstance = nullptr [inline], [static], [private]
Definition at line 385 of file VKDevice.h.
sInstanceMutex
std::mutex Atlas::VulkanRenderingBackend::sInstanceMutex [inline], [static], [private]
Definition at line 386 of file VKDevice.h.
testMeshes
std::vector<std::shared_ptr<MeshAsset> > Atlas::VulkanRenderingBackend::testMeshes [private]
Definition at line 393 of file VKDevice.h.
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/graphics/backend/VKDevice.h
C:/Dev/Techstorm-v5/src/engine/graphics/backend/VKDevice.cpp