Atlas::AtlasEngine Class Reference
This is the core and heart of Atlas; it is responsible for just about everything that is required to run the engine. It contains multiple different modules that can be used to extend the engine. If you want to extend the engine, you can simply inherit the respective module and utilize the concepts of polymorphism to your advantage. Keep in mind that the modules are stored as a ThreadSafeVariable and can be used concurrently. That means the user can multi-thread these modules if they so choose. This is just a default implementation of the IAtlasEngine and you do not have to use this class. However, if you would like to use a different implementation, you can simply inherit from IAtlasEngine and override the virtual functions. But one thing must remain: the class must inherit from IAtlasEngine or be a child of IAtlasEngine.
#include <AtlasEngine.h>
Public Member Functions
AtlasEngine (ThreadSafeVariable< ConfigFileRegistry * > configFileRegistry, ThreadSafeVariable< ScriptingAPI * > scriptingAPI, ThreadSafeVariable< IWindow * > window, ThreadSafeVariable< Renderer * > renderer, ThreadSafeVariable< GameSettings * > gameSettings, ThreadSafeVariable< FileSystemRegistry * > fileSystemRegistry, ThreadSafeVariable< PhysicsEngine * > physicsEngine, ThreadSafeVariable< InputRegistry * > inputRegistry, ThreadSafeVariable< Logger * > logger)
Constructs a new AtlasEngine object.
AtlasEngine ()=default
The default constructor.
ThreadSafeVariable< ConfigFileRegistry * > getConfigFileRegistry () override
Gets the config file registry.
ThreadSafeVariable< ScriptingAPI * > getScriptingAPI () override
Gets the scripting API.
ThreadSafeVariable< IWindow * > getWindow () override
Gets the window.
ThreadSafeVariable< Renderer * > getRenderer () override
Gets the renderer.
ThreadSafeVariable< GameSettings * > getGameSettings () override
ThreadSafeVariable< FileSystemRegistry * > getFileSystemRegistry () override
ThreadSafeVariable< PhysicsEngine * > getPhysicsEngine () override
ThreadSafeVariable< InputRegistry * > getInputRegistry () override
ThreadSafeVariable< Logger * > getLogger () override
void setConfigFileRegistry (ThreadSafeVariable< ConfigFileRegistry * > configFileRegistry) override
void setScriptingAPI (ThreadSafeVariable< ScriptingAPI * > scriptingAPI) override
void setWindow (ThreadSafeVariable< IWindow * > window) override
void setRenderer (ThreadSafeVariable< Renderer * > renderer) override
void setGameSettings (ThreadSafeVariable< GameSettings * > gameSettings) override
void setFileSystemRegistry (ThreadSafeVariable< FileSystemRegistry * > fileSystemRegistry) override
void setPhysicsEngine (ThreadSafeVariable< PhysicsEngine * > physicsEngine) override
void setInputRegistry (ThreadSafeVariable< InputRegistry * > inputRegistry) override
void setLogger (ThreadSafeVariable< Logger * > logger) override
Private Attributes
ThreadSafeVariable< ConfigFileRegistry * > configFileRegistry = ThreadSafeVariable<ConfigFileRegistry*>(nullptr)
A pointer to the config file registry. This is used to allow the user to register their own config files if they so choose.
ThreadSafeVariable< ScriptingAPI * > scriptingAPI = ThreadSafeVariable<ScriptingAPI*>(nullptr)
A pointer to the scripting API. This is used to allow the user to register their own API if they so choose.
ThreadSafeVariable< IWindow * > window = ThreadSafeVariable<IWindow*>(nullptr)
A pointer to the window. This is used to allow the user to register their own window if they so choose.
ThreadSafeVariable< Renderer * > renderer = ThreadSafeVariable<Renderer*>(nullptr)
A pointer to the renderer. This is used to allow the user to register their own renderer if they so choose.
ThreadSafeVariable< GameSettings * > gameSettings = ThreadSafeVariable<GameSettings*>(nullptr)
A pointer to the game settings. This is used to allow the user to register their own game settings if they so choose.
ThreadSafeVariable< FileSystemRegistry * > fileSystemRegistry = ThreadSafeVariable<FileSystemRegistry*>(nullptr)
A pointer to the file system registry. This is used to allow the user to register their own file system if they so choose.
ThreadSafeVariable< PhysicsEngine * > physicsEngine = ThreadSafeVariable<PhysicsEngine*>(nullptr)
A pointer to the physics engine. This is used to allow the user to register their own physics engine if they so choose.
ThreadSafeVariable< InputRegistry * > inputRegistry = ThreadSafeVariable<InputRegistry*>(nullptr)
A pointer to the input registry. This is used to allow the user to register their own input registry if they so choose.
ThreadSafeVariable< Logger * > logger = ThreadSafeVariable<Logger*>(nullptr)
A pointer to the logger. This is used to allow the user to register their own logger if they so choose.
Detailed Description
This is the core and heart of Atlas; it is responsible for just about everything that is required to run the engine. It contains multiple different modules that can be used to extend the engine. If you want to extend the engine, you can simply inherit the respective module and utilize the concepts of polymorphism to your advantage. Keep in mind that the modules are stored as a ThreadSafeVariable and can be used concurrently. That means the user can multi-thread these modules if they so choose. This is just a default implementation of the IAtlasEngine and you do not have to use this class. However, if you would like to use a different implementation, you can simply inherit from IAtlasEngine and override the virtual functions. But one thing must remain: the class must inherit from IAtlasEngine or be a child of IAtlasEngine.
Note
There should not be more than one instance of this object.
Since
v0.0.1
Definition at line 37 of file AtlasEngine.h.
Constructor & Destructor Documentation
AtlasEngine() [1/2]
Atlas::AtlasEngine::AtlasEngine (ThreadSafeVariable< ConfigFileRegistry * > configFileRegistry, ThreadSafeVariable< ScriptingAPI * > scriptingAPI, ThreadSafeVariable< IWindow * > window, ThreadSafeVariable< Renderer * > renderer, ThreadSafeVariable< GameSettings * > gameSettings, ThreadSafeVariable< FileSystemRegistry * > fileSystemRegistry, ThreadSafeVariable< PhysicsEngine * > physicsEngine, ThreadSafeVariable< InputRegistry * > inputRegistry, ThreadSafeVariable< Logger * > logger)
Constructs a new AtlasEngine object.
Parameters
configFileRegistry A pointer to the config file registry object that Atlas will use
scriptingAPI A pointer to the scripting API object that Atlas will use
window A pointer to the window object that Atlas will use
renderer A pointer to the renderer object that Atlas will use
gameSettings A pointer to the game settings object that Atlas will use
fileSystemRegistry A pointer to the file system registry object that Atlas will use
physicsEngine A pointer to the physics engine object that Atlas will use
inputRegistry A pointer to the input registry object that Atlas will use
logger A pointer to the logger object that Atlas will use
Since
v0.0.8
Definition at line 19 of file AtlasEngine.cpp.
References configFileRegistry, fileSystemRegistry, gameSettings, inputRegistry, logger, physicsEngine, renderer, scriptingAPI, setConfigFileRegistry(), setFileSystemRegistry(), setGameSettings(), setInputRegistry(), setLogger(), setPhysicsEngine(), setRenderer(), setScriptingAPI(), setWindow(), and window.
AtlasEngine() [2/2]
Atlas::AtlasEngine::AtlasEngine () [default]
The default constructor.
Member Function Documentation
getConfigFileRegistry()
Atlas::ThreadSafeVariable< Atlas::ConfigFileRegistry * > Atlas::AtlasEngine::getConfigFileRegistry () [override], [virtual]
Gets the config file registry.
Remarks
This is a virtual function.
Note
This will return a nullptr if the config file registry is not set. This is done through the ATLAS_GENERATED_NULL_CHECK macro
Returns
A pointer to the config file registry
Since
v0.0.8
Implements Atlas::IAtlasEngine.
Definition at line 32 of file AtlasEngine.cpp.
getFileSystemRegistry()
Atlas::ThreadSafeVariable< Atlas::FileSystemRegistry * > Atlas::AtlasEngine::getFileSystemRegistry () [override], [virtual]
Returns
Implements Atlas::IAtlasEngine.
Definition at line 57 of file AtlasEngine.cpp.
getGameSettings()
Atlas::ThreadSafeVariable< Atlas::GameSettings * > Atlas::AtlasEngine::getGameSettings () [override], [virtual]
Returns
Implements Atlas::IAtlasEngine.
Definition at line 52 of file AtlasEngine.cpp.
getInputRegistry()
Atlas::ThreadSafeVariable< Atlas::InputRegistry * > Atlas::AtlasEngine::getInputRegistry () [override], [virtual]
Returns
Implements Atlas::IAtlasEngine.
Definition at line 67 of file AtlasEngine.cpp.
getLogger()
Atlas::ThreadSafeVariable< Atlas::Logger * > Atlas::AtlasEngine::getLogger () [override], [virtual]
Returns
Implements Atlas::IAtlasEngine.
Definition at line 72 of file AtlasEngine.cpp.
getPhysicsEngine()
Atlas::ThreadSafeVariable< Atlas::PhysicsEngine * > Atlas::AtlasEngine::getPhysicsEngine () [override], [virtual]
Returns
Implements Atlas::IAtlasEngine.
Definition at line 62 of file AtlasEngine.cpp.
getRenderer()
Atlas::ThreadSafeVariable< Atlas::Renderer * > Atlas::AtlasEngine::getRenderer () [override], [virtual]
Gets the renderer.
Remarks
This is a virtual function.
Note
This will return a nullptr if the renderer is not set. This is done through the ATLAS_GENERATED_NULL_CHECK macro
Returns
A pointer to the renderer
Since
v0.0.8
Implements Atlas::IAtlasEngine.
Definition at line 47 of file AtlasEngine.cpp.
getScriptingAPI()
Atlas::ThreadSafeVariable< Atlas::ScriptingAPI * > Atlas::AtlasEngine::getScriptingAPI () [override], [virtual]
Gets the scripting API.
Remarks
This is a virtual function.
Note
This will return a nullptr if the scripting API is not set. This is done through the ATLAS_GENERATED_NULL_CHECK macro
Returns
A pointer to the scripting API
Since
v0.0.8
Implements Atlas::IAtlasEngine.
Definition at line 37 of file AtlasEngine.cpp.
getWindow()
Atlas::ThreadSafeVariable< Atlas::IWindow * > Atlas::AtlasEngine::getWindow () [override], [virtual]
Gets the window.
Remarks
This is a virtual function.
Note
This will return a nullptr if the window is not set. This is done through the ATLAS_GENERATED_NULL_CHECK macro
Returns
A pointer to the window
Since
v0.0.8
Implements Atlas::IAtlasEngine.
Definition at line 42 of file AtlasEngine.cpp.
setConfigFileRegistry()
void Atlas::AtlasEngine::setConfigFileRegistry (Atlas::ThreadSafeVariable< ConfigFileRegistry * > configFileRegistry) [override], [virtual]
Parameters
configFileRegistry
Implements Atlas::IAtlasEngine.
Definition at line 77 of file AtlasEngine.cpp.
Referenced by AtlasEngine().
setFileSystemRegistry()
void Atlas::AtlasEngine::setFileSystemRegistry (Atlas::ThreadSafeVariable< FileSystemRegistry * > fileSystemRegistry) [override], [virtual]
Parameters
fileSystemRegistry
Implements Atlas::IAtlasEngine.
Definition at line 107 of file AtlasEngine.cpp.
Referenced by AtlasEngine().
setGameSettings()
void Atlas::AtlasEngine::setGameSettings (Atlas::ThreadSafeVariable< GameSettings * > gameSettings) [override], [virtual]
Parameters
gameSettings
Implements Atlas::IAtlasEngine.
Definition at line 101 of file AtlasEngine.cpp.
Referenced by AtlasEngine().
setInputRegistry()
void Atlas::AtlasEngine::setInputRegistry (Atlas::ThreadSafeVariable< InputRegistry * > inputRegistry) [override], [virtual]
Parameters
inputRegistry
Implements Atlas::IAtlasEngine.
Definition at line 119 of file AtlasEngine.cpp.
Referenced by AtlasEngine().
setLogger()
void Atlas::AtlasEngine::setLogger (Atlas::ThreadSafeVariable< Logger * > logger) [override], [virtual]
Parameters
logger
Implements Atlas::IAtlasEngine.
Definition at line 125 of file AtlasEngine.cpp.
Referenced by AtlasEngine().
setPhysicsEngine()
void Atlas::AtlasEngine::setPhysicsEngine (Atlas::ThreadSafeVariable< PhysicsEngine * > physicsEngine) [override], [virtual]
Parameters
physicsEngine
Implements Atlas::IAtlasEngine.
Definition at line 113 of file AtlasEngine.cpp.
Referenced by AtlasEngine().
setRenderer()
void Atlas::AtlasEngine::setRenderer (Atlas::ThreadSafeVariable< Renderer * > renderer) [override], [virtual]
Parameters
renderer
Implements Atlas::IAtlasEngine.
Definition at line 95 of file AtlasEngine.cpp.
Referenced by AtlasEngine().
setScriptingAPI()
void Atlas::AtlasEngine::setScriptingAPI (Atlas::ThreadSafeVariable< ScriptingAPI * > scriptingAPI) [override], [virtual]
Parameters
scriptingAPI
Implements Atlas::IAtlasEngine.
Definition at line 83 of file AtlasEngine.cpp.
Referenced by AtlasEngine().
setWindow()
void Atlas::AtlasEngine::setWindow (Atlas::ThreadSafeVariable< IWindow * > window) [override], [virtual]
Parameters
window
Implements Atlas::IAtlasEngine.
Definition at line 89 of file AtlasEngine.cpp.
Referenced by AtlasEngine().
Member Data Documentation
configFileRegistry
ThreadSafeVariable<ConfigFileRegistry*> Atlas::AtlasEngine::configFileRegistry = ThreadSafeVariable<ConfigFileRegistry*>(nullptr) [private]
A pointer to the config file registry. This is used to allow the user to register their own config files if they so choose.
Note
This starts as a nullptr
Since
v0.0.8
Definition at line 47 of file AtlasEngine.h.
Referenced by AtlasEngine().
fileSystemRegistry
ThreadSafeVariable<FileSystemRegistry*> Atlas::AtlasEngine::fileSystemRegistry = ThreadSafeVariable<FileSystemRegistry*>(nullptr) [private]
A pointer to the file system registry. This is used to allow the user to register their own file system if they so choose.
Note
This starts as a nullptr
Warning
This is not currently implemented nor used at the moment.
Since
v0.0.8
Definition at line 100 of file AtlasEngine.h.
Referenced by AtlasEngine().
gameSettings
ThreadSafeVariable<GameSettings*> Atlas::AtlasEngine::gameSettings = ThreadSafeVariable<GameSettings*>(nullptr) [private]
A pointer to the game settings. This is used to allow the user to register their own game settings if they so choose.
Note
This starts as a nullptr
Warning
This is not currently implemented nor used at the moment.
Since
v0.0.8
Definition at line 88 of file AtlasEngine.h.
Referenced by AtlasEngine().
inputRegistry
ThreadSafeVariable<InputRegistry*> Atlas::AtlasEngine::inputRegistry = ThreadSafeVariable<InputRegistry*>(nullptr) [private]
A pointer to the input registry. This is used to allow the user to register their own input registry if they so choose.
Note
This starts as a nullptr
Since
v0.0.8
Definition at line 120 of file AtlasEngine.h.
Referenced by AtlasEngine().
logger
ThreadSafeVariable<Logger*> Atlas::AtlasEngine::logger = ThreadSafeVariable<Logger*>(nullptr) [private]
A pointer to the logger. This is used to allow the user to register their own logger if they so choose.
Note
This starts as a nullptr
Since
v0.0.8
Definition at line 130 of file AtlasEngine.h.
Referenced by AtlasEngine().
physicsEngine
ThreadSafeVariable<PhysicsEngine*> Atlas::AtlasEngine::physicsEngine = ThreadSafeVariable<PhysicsEngine*>(nullptr) [private]
A pointer to the physics engine. This is used to allow the user to register their own physics engine if they so choose.
Note
This starts as a nullptr
Since
v0.0.8
Definition at line 110 of file AtlasEngine.h.
Referenced by AtlasEngine().
renderer
ThreadSafeVariable<Renderer*> Atlas::AtlasEngine::renderer = ThreadSafeVariable<Renderer*>(nullptr) [private]
A pointer to the renderer. This is used to allow the user to register their own renderer if they so choose.
Note
This starts as a nullptr
Since
v0.0.8
Definition at line 76 of file AtlasEngine.h.
Referenced by AtlasEngine().
scriptingAPI
ThreadSafeVariable<ScriptingAPI*> Atlas::AtlasEngine::scriptingAPI = ThreadSafeVariable<ScriptingAPI*>(nullptr) [private]
A pointer to the scripting API. This is used to allow the user to register their own API if they so choose.
Note
This starts as a nullptr
Since
v0.0.8
Definition at line 56 of file AtlasEngine.h.
Referenced by AtlasEngine().
window
ThreadSafeVariable<IWindow*> Atlas::AtlasEngine::window = ThreadSafeVariable<IWindow*>(nullptr) [private]
A pointer to the window. This is used to allow the user to register their own window if they so choose.
Note
This starts as a nullptr
Since
v0.0.8
Definition at line 66 of file AtlasEngine.h.
Referenced by AtlasEngine().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/core/AtlasEngine.h
C:/Dev/Techstorm-v5/src/engine/core/AtlasEngine.cpp