CScriptFile Class Reference
#include <scriptfile.h>
Public Member Functions
CScriptFile ()
void AddRef () const
void Release () const
int Open (const std::string &filename, const std::string &mode)
int Close ()
int GetSize () const
bool IsEOF () const
std::string ReadString (unsigned int length)
std::string ReadLine ()
asINT64 ReadInt (asUINT bytes)
asQWORD ReadUInt (asUINT bytes)
float ReadFloat ()
double ReadDouble ()
int WriteString (const std::string &str)
int WriteInt (asINT64 v, asUINT bytes)
int WriteUInt (asQWORD v, asUINT bytes)
int WriteFloat (float v)
int WriteDouble (double v)
int GetPos () const
int SetPos (int pos)
int MovePos (int delta)
CScriptFile ()
void AddRef () const
void Release () const
int Open (const std::string &filename, const std::string &mode)
int Close ()
int GetSize () const
bool IsEOF () const
std::string ReadString (unsigned int length)
std::string ReadLine ()
asINT64 ReadInt (asUINT bytes)
asQWORD ReadUInt (asUINT bytes)
float ReadFloat ()
double ReadDouble ()
int WriteString (const std::string &str)
int WriteInt (asINT64 v, asUINT bytes)
int WriteUInt (asQWORD v, asUINT bytes)
int WriteFloat (float v)
int WriteDouble (double v)
int GetPos () const
int SetPos (int pos)
int MovePos (int delta)
Public Attributes
bool mostSignificantByteFirst
Protected Member Functions
~CScriptFile ()
~CScriptFile ()
Protected Attributes
int refCount
FILE * file
Detailed Description
Definition at line 40 of file scriptfile.h.
Constructor & Destructor Documentation
CScriptFile() [1/2]
CScriptFile::CScriptFile ()
Definition at line 243 of file scriptfile.cpp.
References file, mostSignificantByteFirst, and refCount.
~CScriptFile() [1/2]
CScriptFile::~CScriptFile () [protected]
Definition at line 250 of file scriptfile.cpp.
References Close().
CScriptFile() [2/2]
CScriptFile::CScriptFile ()
~CScriptFile() [2/2]
CScriptFile::~CScriptFile () [protected]
Member Function Documentation
AddRef() [1/2]
void CScriptFile::AddRef () const
Definition at line 255 of file scriptfile.cpp.
References refCount.
Referenced by ScriptFile_AddRef_Generic().
AddRef() [2/2]
void CScriptFile::AddRef () const
Close() [1/2]
int CScriptFile::Close ()
Definition at line 330 of file scriptfile.cpp.
References file.
Referenced by Open(), ScriptFile_Close_Generic(), and ~CScriptFile().
Close() [2/2]
int CScriptFile::Close ()
GetPos() [1/2]
int CScriptFile::GetPos () const
Definition at line 354 of file scriptfile.cpp.
References file.
Referenced by ScriptFile_GetPos_Generic().
GetPos() [2/2]
int CScriptFile::GetPos () const
GetSize() [1/2]
int CScriptFile::GetSize () const
Definition at line 341 of file scriptfile.cpp.
References file.
Referenced by ScriptFile_GetSize_Generic().
GetSize() [2/2]
int CScriptFile::GetSize () const
IsEOF() [1/2]
bool CScriptFile::IsEOF () const
Definition at line 560 of file scriptfile.cpp.
References file.
Referenced by ScriptFile_IsEOF_Generic().
IsEOF() [2/2]
bool CScriptFile::IsEOF () const
MovePos() [1/2]
int CScriptFile::MovePos (int delta)
Definition at line 373 of file scriptfile.cpp.
References file.
Referenced by ScriptFile_MovePos_Generic().
MovePos() [2/2]
int CScriptFile::MovePos (int delta)
Open() [1/2]
int CScriptFile::Open (const std::string & filename, const std::string & mode)
Definition at line 266 of file scriptfile.cpp.
References Close(), and file.
Referenced by ScriptFile_Open_Generic().
Open() [2/2]
int CScriptFile::Open (const std::string & filename, const std::string & mode)
ReadDouble() [1/2]
double CScriptFile::ReadDouble ()
Definition at line 530 of file scriptfile.cpp.
References file, and mostSignificantByteFirst.
Referenced by ScriptFile_ReadDouble_Generic().
ReadDouble() [2/2]
double CScriptFile::ReadDouble ()
ReadFloat() [1/2]
float CScriptFile::ReadFloat ()
Definition at line 500 of file scriptfile.cpp.
References file, and mostSignificantByteFirst.
Referenced by ScriptFile_ReadFloat_Generic().
ReadFloat() [2/2]
float CScriptFile::ReadFloat ()
ReadInt() [1/2]
asINT64 CScriptFile::ReadInt (asUINT bytes)
Definition at line 430 of file scriptfile.cpp.
References file, and mostSignificantByteFirst.
Referenced by ScriptFile_ReadInt_Generic().
ReadInt() [2/2]
asINT64 CScriptFile::ReadInt (asUINT bytes)
ReadLine() [1/2]
string CScriptFile::ReadLine ()
Definition at line 398 of file scriptfile.cpp.
References file.
Referenced by ScriptFile_ReadLine_Generic().
ReadLine() [2/2]
std::string CScriptFile::ReadLine ()
ReadString() [1/2]
string CScriptFile::ReadString (unsigned int length)
Definition at line 384 of file scriptfile.cpp.
References file.
Referenced by ScriptFile_ReadString_Generic().
ReadString() [2/2]
std::string CScriptFile::ReadString (unsigned int length)
ReadUInt() [1/2]
asQWORD CScriptFile::ReadUInt (asUINT bytes)
Definition at line 471 of file scriptfile.cpp.
References file, and mostSignificantByteFirst.
Referenced by ScriptFile_ReadUInt_Generic().
ReadUInt() [2/2]
asQWORD CScriptFile::ReadUInt (asUINT bytes)
Release() [1/2]
void CScriptFile::Release () const
Definition at line 260 of file scriptfile.cpp.
References refCount.
Referenced by ScriptFile_Release_Generic().
Release() [2/2]
void CScriptFile::Release () const
SetPos() [1/2]
int CScriptFile::SetPos (int pos)
Definition at line 362 of file scriptfile.cpp.
References file.
Referenced by ScriptFile_SetPos_Generic().
SetPos() [2/2]
int CScriptFile::SetPos (int pos)
WriteDouble() [1/2]
int CScriptFile::WriteDouble (double v)
Definition at line 649 of file scriptfile.cpp.
References file, and mostSignificantByteFirst.
Referenced by ScriptFile_WriteDouble_Generic().
WriteDouble() [2/2]
int CScriptFile::WriteDouble (double v)
WriteFloat() [1/2]
int CScriptFile::WriteFloat (float v)
Definition at line 622 of file scriptfile.cpp.
References file, and mostSignificantByteFirst.
Referenced by ScriptFile_WriteFloat_Generic().
WriteFloat() [2/2]
int CScriptFile::WriteFloat (float v)
WriteInt() [1/2]
int CScriptFile::WriteInt (asINT64 v, asUINT bytes)
Definition at line 580 of file scriptfile.cpp.
References file, and mostSignificantByteFirst.
Referenced by ScriptFile_WriteInt_Generic().
WriteInt() [2/2]
int CScriptFile::WriteInt (asINT64 v, asUINT bytes)
WriteString() [1/2]
int CScriptFile::WriteString (const std::string & str)
Definition at line 569 of file scriptfile.cpp.
References file.
Referenced by ScriptFile_WriteString_Generic().
WriteString() [2/2]
int CScriptFile::WriteString (const std::string & str)
WriteUInt() [1/2]
int CScriptFile::WriteUInt (asQWORD v, asUINT bytes)
Definition at line 601 of file scriptfile.cpp.
References file, and mostSignificantByteFirst.
Referenced by ScriptFile_WriteUInt_Generic().
WriteUInt() [2/2]
int CScriptFile::WriteUInt (asQWORD v, asUINT bytes)
Member Data Documentation
file
FILE * CScriptFile::file [protected]
Definition at line 84 of file scriptfile.h.
Referenced by Close(), CScriptFile(), GetPos(), GetSize(), IsEOF(), MovePos(), Open(), ReadDouble(), ReadFloat(), ReadInt(), ReadLine(), ReadString(), ReadUInt(), SetPos(), WriteDouble(), WriteFloat(), WriteInt(), WriteString(), and WriteUInt().
mostSignificantByteFirst
bool CScriptFile::mostSignificantByteFirst
Definition at line 78 of file scriptfile.h.
Referenced by CScriptFile(), ReadDouble(), ReadFloat(), ReadInt(), ReadUInt(), WriteDouble(), WriteFloat(), WriteInt(), and WriteUInt().
refCount
int CScriptFile::refCount [mutable], [protected]
Definition at line 83 of file scriptfile.h.
Referenced by AddRef(), CScriptFile(), and Release().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/application/add_on/scriptfile/scriptfile.h
C:/Dev/Techstorm-v5/src/engine/modding/add_on/scriptfile/scriptfile.h
C:/Dev/Techstorm-v5/src/application/add_on/scriptfile/scriptfile.cpp
C:/Dev/Techstorm-v5/src/engine/modding/add_on/scriptfile/scriptfile.cpp