C:/Dev/Techstorm-v5/src/bindings/imgui_impl_osx.mm File Reference
import "imgui.h"
import "imgui_impl_osx.h"
import <Cocoa/Cocoa.h>
import <Carbon/Carbon.h>
import <GameController/GameController.h>
import <time.h>
Classes
struct ImGui_ImplOSX_Data
class KeyEventResponder
class ImGuiObserver
Macros
#define APPLE_HAS_BUTTON_OPTIONS (__IPHONE_OS_VERSION_MIN_REQUIRED >= 130000 || __MAC_OS_X_VERSION_MIN_REQUIRED >= 101500 || __TV_OS_VERSION_MIN_REQUIRED >= 130000)
#define APPLE_HAS_CONTROLLER (__IPHONE_OS_VERSION_MIN_REQUIRED >= 140000 || __MAC_OS_X_VERSION_MIN_REQUIRED >= 110000 || __TV_OS_VERSION_MIN_REQUIRED >= 140000)
#define APPLE_HAS_THUMBSTICKS (__IPHONE_OS_VERSION_MIN_REQUIRED >= 120100 || __MAC_OS_X_VERSION_MIN_REQUIRED >= 101401 || __TV_OS_VERSION_MIN_REQUIRED >= 120100)
#define IM_SATURATE(V) (V < 0.0f ? 0.0f : V > 1.0f ? 1.0f : V)
#define MAP_BUTTON(KEY_NO, BUTTON_NAME) { io.AddKeyEvent(KEY_NO, gp.BUTTON_NAME.isPressed); }
#define MAP_ANALOG(KEY_NO, AXIS_NAME, V0, V1) { float vn = (float)(gp.AXIS_NAME.value - V0) / (float)(V1 - V0); vn = IM_SATURATE(vn); io.AddKeyAnalogEvent(KEY_NO, vn > 0.1f, vn); }
Functions
static ImGui_ImplOSX_Data * ImGui_ImplOSX_GetBackendData ()
static void ImGui_ImplOSX_DestroyBackendData ()
static CFTimeInterval GetMachAbsoluteTimeInSeconds ()
static void ImGui_ImplOSX_AddTrackingArea (NSView *_Nonnull view)
static bool ImGui_ImplOSX_HandleEvent (NSEvent *event, NSView *view)
ImGuiKey ImGui_ImplOSX_KeyCodeToImGuiKey (int key_code)
bool ImGui_ImplOSX_Init (NSView *view)
void ImGui_ImplOSX_Shutdown ()
static void ImGui_ImplOSX_UpdateMouseCursor ()
static void ImGui_ImplOSX_UpdateGamepads ()
static void ImGui_ImplOSX_UpdateImePosWithView (NSView *view)
void ImGui_ImplOSX_NewFrame (NSView *view)
static ImGuiMouseSource GetMouseSource (NSEvent *event)
Variables
float _posY
NSRect _imeRect
Macro Definition Documentation
APPLE_HAS_BUTTON_OPTIONS
#define APPLE_HAS_BUTTON_OPTIONS (__IPHONE_OS_VERSION_MIN_REQUIRED >= 130000 || __MAC_OS_X_VERSION_MIN_REQUIRED >= 101500 || __TV_OS_VERSION_MIN_REQUIRED >= 130000)
Definition at line 71 of file imgui_impl_osx.mm.
APPLE_HAS_CONTROLLER
#define APPLE_HAS_CONTROLLER (__IPHONE_OS_VERSION_MIN_REQUIRED >= 140000 || __MAC_OS_X_VERSION_MIN_REQUIRED >= 110000 || __TV_OS_VERSION_MIN_REQUIRED >= 140000)
Definition at line 72 of file imgui_impl_osx.mm.
APPLE_HAS_THUMBSTICKS
#define APPLE_HAS_THUMBSTICKS (__IPHONE_OS_VERSION_MIN_REQUIRED >= 120100 || __MAC_OS_X_VERSION_MIN_REQUIRED >= 101401 || __TV_OS_VERSION_MIN_REQUIRED >= 120100)
Definition at line 73 of file imgui_impl_osx.mm.
IM_SATURATE
#define IM_SATURATE(V) (V < 0.0f ? 0.0f : V > 1.0f ? 1.0f : V)
MAP_ANALOG
#define MAP_ANALOG(KEY_NO, AXIS_NAME, V0, V1) { float vn = (float)(gp.AXIS_NAME.value - V0) / (float)(V1 - V0); vn = IM_SATURATE(vn); io.AddKeyAnalogEvent(KEY_NO, vn > 0.1f, vn); }
MAP_BUTTON
#define MAP_BUTTON(KEY_NO, BUTTON_NAME) { io.AddKeyEvent(KEY_NO, gp.BUTTON_NAME.isPressed); }
Function Documentation
GetMachAbsoluteTimeInSeconds()
static CFTimeInterval GetMachAbsoluteTimeInSeconds () [inline], [static]
Definition at line 96 of file imgui_impl_osx.mm.
Referenced by ImGui_ImplOSX_NewFrame().
GetMouseSource()
static ImGuiMouseSource GetMouseSource (NSEvent * event) [static]
Definition at line 643 of file imgui_impl_osx.mm.
Referenced by ImGui_ImplOSX_HandleEvent().
ImGui_ImplOSX_AddTrackingArea()
static void ImGui_ImplOSX_AddTrackingArea (NSView *_Nonnull view) [static]
Definition at line 800 of file imgui_impl_osx.mm.
References ImGui_ImplOSX_GetBackendData(), and ImGui_ImplOSX_Data::Monitor.
Referenced by ImGui_ImplOSX_Init().
ImGui_ImplOSX_DestroyBackendData()
static void ImGui_ImplOSX_DestroyBackendData () [static]
Definition at line 94 of file imgui_impl_osx.mm.
References ImGui_ImplOSX_GetBackendData().
Referenced by ImGui_ImplOSX_Shutdown().
ImGui_ImplOSX_GetBackendData()
static ImGui_ImplOSX_Data * ImGui_ImplOSX_GetBackendData () [static]
Definition at line 93 of file imgui_impl_osx.mm.
Referenced by ImGui_ImplOSX_AddTrackingArea(), ImGui_ImplOSX_DestroyBackendData(), ImGui_ImplOSX_Init(), ImGui_ImplOSX_NewFrame(), ImGui_ImplOSX_Shutdown(), ImGui_ImplOSX_UpdateImePosWithView(), and ImGui_ImplOSX_UpdateMouseCursor().
ImGui_ImplOSX_HandleEvent()
static bool ImGui_ImplOSX_HandleEvent (NSEvent * event, NSView * view) [static]
Definition at line 661 of file imgui_impl_osx.mm.
References GetMouseSource(), and ImGui_ImplOSX_KeyCodeToImGuiKey().
ImGui_ImplOSX_Init()
bool ImGui_ImplOSX_Init (NSView * view)
Definition at line 400 of file imgui_impl_osx.mm.
References ImGui_ImplOSX_AddTrackingArea(), ImGui_ImplOSX_GetBackendData(), ImGui_ImplOSX_Data::InputContext, ImGui_ImplOSX_Data::KeyEventResponder, ImGui_ImplOSX_Data::MouseCursorHidden, ImGui_ImplOSX_Data::MouseCursors, ImGui_ImplOSX_Data::Observer, and ImGui_ImplOSX_Data::Window.
ImGui_ImplOSX_KeyCodeToImGuiKey()
ImGuiKey ImGui_ImplOSX_KeyCodeToImGuiKey (int key_code)
Definition at line 265 of file imgui_impl_osx.mm.
Referenced by ImGui_ImplOSX_HandleEvent().
ImGui_ImplOSX_NewFrame()
void ImGui_ImplOSX_NewFrame (NSView * view)
Definition at line 614 of file imgui_impl_osx.mm.
References GetMachAbsoluteTimeInSeconds(), ImGui_ImplOSX_GetBackendData(), ImGui_ImplOSX_UpdateGamepads(), ImGui_ImplOSX_UpdateImePosWithView(), ImGui_ImplOSX_UpdateMouseCursor(), and ImGui_ImplOSX_Data::Time.
ImGui_ImplOSX_Shutdown()
void ImGui_ImplOSX_Shutdown ()
Definition at line 495 of file imgui_impl_osx.mm.
References ImGui_ImplOSX_DestroyBackendData(), ImGui_ImplOSX_GetBackendData(), ImGui_ImplOSX_Data::Monitor, and ImGui_ImplOSX_Data::Observer.
ImGui_ImplOSX_UpdateGamepads()
static void ImGui_ImplOSX_UpdateGamepads () [static]
Definition at line 548 of file imgui_impl_osx.mm.
References MAP_ANALOG, and MAP_BUTTON.
Referenced by ImGui_ImplOSX_NewFrame().
ImGui_ImplOSX_UpdateImePosWithView()
static void ImGui_ImplOSX_UpdateImePosWithView (NSView * view) [static]
Definition at line 606 of file imgui_impl_osx.mm.
References ImGui_ImplOSX_GetBackendData().
Referenced by ImGui_ImplOSX_NewFrame().
ImGui_ImplOSX_UpdateMouseCursor()
static void ImGui_ImplOSX_UpdateMouseCursor () [static]
Definition at line 515 of file imgui_impl_osx.mm.
References ImGui_ImplOSX_GetBackendData(), ImGui_ImplOSX_Data::MouseCursorHidden, and ImGui_ImplOSX_Data::MouseCursors.
Referenced by ImGui_ImplOSX_NewFrame().
Variable Documentation
_imeRect
NSRect _imeRect
Definition at line 129 of file imgui_impl_osx.mm.
_posY
float _posY
Initial value:
{
    float _posX
Definition at line 128 of file imgui_impl_osx.mm.