Atlas::IMGUIRenderable Class Reference
#include <VKDevice.h>
Public Member Functions
void beginDrawingStage (VkCommandBuffer cmd, EffectManager &computeEffects) override
void draw (VkCommandBuffer cmd) override
void endDrawingStage (VkCommandBuffer cmd) override
Protected Member Functions
virtual void setupElements (EffectManager &computeEffects)
Static Private Member Functions
static void NewIMGUIFrame ()
Additional Inherited Members
Static Public Member Functions inherited from Atlas::Renderable
static void SetCurrentDrawData (CurrentDrawData const &currentFrame)
Detailed Description
Definition at line 315 of file VKDevice.h.
Member Function Documentation
beginDrawingStage()
void Atlas::IMGUIRenderable::beginDrawingStage (VkCommandBuffer cmd, EffectManager & computeEffects) [override], [virtual]
Reimplemented from Atlas::Renderable.
Definition at line 1477 of file VKDevice.cpp.
draw()
void Atlas::IMGUIRenderable::draw (VkCommandBuffer cmd) [override], [virtual]
Reimplemented from Atlas::Renderable.
Definition at line 1486 of file VKDevice.cpp.
endDrawingStage()
void Atlas::IMGUIRenderable::endDrawingStage (VkCommandBuffer cmd) [override], [virtual]
Reimplemented from Atlas::Renderable.
Definition at line 1490 of file VKDevice.cpp.
NewIMGUIFrame()
void Atlas::IMGUIRenderable::NewIMGUIFrame () [inline], [static], [private]
Definition at line 1452 of file VKDevice.cpp.
References ImGui_ImplSDL2_NewFrame(), and ImGui_ImplVulkan_NewFrame().
setupElements()
void Atlas::IMGUIRenderable::setupElements (EffectManager & computeEffects) [protected], [virtual]
Definition at line 1458 of file VKDevice.cpp.
References Atlas::ComputeEffect::data, Atlas::ComputePushConstants::data1, Atlas::ComputePushConstants::data2, Atlas::ComputePushConstants::data3, Atlas::ComputePushConstants::data4, Atlas::EffectManager::getCurrentEffect(), Atlas::EffectManager::getCurrentEffectIndex(), Atlas::EffectManager::getEffectCount(), and Atlas::ComputeEffect::name.
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/graphics/backend/VKDevice.h
C:/Dev/Techstorm-v5/src/engine/graphics/backend/VKDevice.cpp