Atlas::abstract< ConsoleSink > Class Template Reference
Represents a base abstract class for errors.
#include <Console.h>
Classes
class ProjectReference
Represents a polymorphic singleton reference to the user's project instance through a pointer of Atlas::IProject. This is mandatory for Atlas to run the user's engine.
Public Member Functions
IConsole (ConsoleSink &sink)
virtual void parseInput (const std::string &input)=0
virtual std::string & getPrompt ()=0
virtual void draw ()=0
virtual void update ()=0
virtual void clear ()=0
IError (std::string const &message, std::source_location location=std::source_location::current())
virtual ~IError () noexcept
virtual const char * what () const noexcept=0
virtual void parseLog (const std::string &message, ELogLevel level, const std::source_location &location)=0
virtual void parsePrompt (const std::string &message)=0
virtual std::vector< std::string > & getBuffer ()=0
virtual void init ()=0
virtual std::string getFormat ()=0
virtual int preInit ()=0
virtual int init ()=0
virtual int postInit ()=0
virtual int start ()=0
virtual int stop ()=0
virtual int cleanup ()=0
IGameObject ()=default
Default constructor that initializes a new instance of the IGameObject class.
virtual ~IGameObject ()=default
Default destructor that finalizes an instance of the IGameObject class.
virtual void texture ()=0
This is a pure virtual function that is the drawing function for when objects are being textured to the render texture. If you do not have anything different to do here, then you may just call render() instead, but this must be implemented in order for the object to be rendered.
virtual void render ()
Renders this instance. This is not a pure virtual and is empty because it is up to the user to use this as they see fit without forcing them to implement it.
virtual void destroy ()=0
Destroys this instance, and is called right before the object is removed from memory.
virtual void cleanup ()=0
Cleanups this instance.
IPhysicsGameObject (JPH::BodyCreationSettings const &bodySettings, JPH::EActivation activationState)
~IPhysicsGameObject () override
virtual void onCollisionValidation (IGameObject *other)=0
Action on collision validation.
virtual void onCollisionEnter (IGameObject *other)=0
Action upon entering collision. This is called the frame the collision happens.
virtual void onCollisionExit (IGameObject *other)=0
Action upon exiting collision.
virtual void onCollisionStay (IGameObject *other)=0
Action upon remaining in collision.
ScriptingLibraryRegistry & getLuaLibraries ()
Returns the currently active libraries for lua.
ScriptingFunctionRegistry & getLuaFunctions ()
Gets the lua functions.
WindowDecorations & getWindowDecorations ()
Gets the window decorations. This includes the window title, icon, size, etc.
void setWindowDecorations (WindowDecorations &windowDecorations)
Sets the window decorations.
Renderer & getRenderer ()
Gets the renderer instance.
template<typename T >
void setProject (T *project)
This function is used to set the ProjectReference singleton to the project.
virtual void preInit ()
This is the first function that will be called on startup.
virtual void init (int argc, char *argv[])
Initializes your project. This will be called after preInit and window initialization, meaning that this is the earliest point that you can use raylib. THIS MUST BE OVERRIDEN BY YOUR PROJECT CLASS!
virtual void postInit ()
Does a post initialization of the project. This is empty because it is not neccesary to override.
virtual void initRenderer ()
Initializes the renderer and should be called after initWindow.
virtual int run (int argc, char *argv[])
Runs the actual game and is called after the init functions.
virtual int update ()
virtual int prePhysicsUpdate ()
Pre-update step that is called in the physics or update thread (depending on thread count)
virtual int physicsUpdate ()
This is where the actual physics update happens. Please note that this will run on the physics thread!
virtual int postPhysicsUpdate ()
Post physics update that is called after physicsUpdate() in the physics or update thread (depending on thread count).
virtual int preObjectUpdate ()
Any preparation code for updating the scene's game objects. Use this if you need to do something after the physics update, but before the GameObject update. Please note that this will run on the update thread!
virtual int objectUpdate ()
This is where the actual GameObject update happens, and is called after preObjectUpdate(). Please note that this will run on the update thread!
virtual int postObjectUpdate ()
Called right after objectUpdate(). Use this to do anything after the GameObject update. Please note that this will run on the update thread!
virtual int texture ()
Textures all GameObjects before render() is called and after update functions are called. This is essentially where the scene is rendered. Please note that this will run on the render thread!
virtual int render ()
Assuming that the FBO is enabled, this will render the FBO and apply any post-processing effects to the FBO. Please note that this will run on the update thread!
virtual int cleanup (int exitCode)
Cleans up anything that may need to be cleaned up.
virtual void update ()=0
Updates this instance and is called every frame before texturing/rendering.
virtual void postUpdate ()=0
Called right after the update function, but before texturing/rendering.
virtual void process (T entree)=0
Processes the specified entree.
virtual void generate ()=0
virtual void generate ()=0
Public Member Functions inherited from Atlas::IException
IException (std::string const &message, std::source_location location=std::source_location::current())
virtual ~IException () noexcept
Static Public Member Functions
static IProject * GetProject ()
Gets the current project instance.
Public Attributes
int depth = 0
Model model
Vector3 position = Vector3Zero()
Vector3 rotationAxis
Vector3 scale
float rotationAngle
Color tint = WHITE
JPH::BodyID id
JPH::BodyInterface & bodyInterface
GameSettings settings
Protected Attributes
ConsoleSink & mSink
ColorSinkType mColorSink
Renderer mRenderer
WindowDecorations mWindowDecorations
ScriptingLibraryRegistry mLuaLibraries
ScriptingFunctionRegistry mLuaFunctions
Protected Attributes inherited from Atlas::IException
std::string mMessage
Detailed Description
template<typename ConsoleSink>
class Atlas::abstract< ConsoleSink >
Represents a base abstract class for errors.
A class that acts as, well, a gate! It is essentially as a piece of machinery on an assembly line. Please do note, that this is a template class and is not meant to be used directly. Please see GameObjectRegistry for more information and an example.
This is an abstract interface singleton that all projects must implement and set the ProjectReference singleton to their project. In terms of functionality, this interface just holds the functions and variables that Atlas will call (besides some initialization).
Same thing as a gate, but for game objects.
Represents an object that can be rendered in the screen. This is an abstract class that contains all the common properties of a game object.
This is NOT what will print to the terminal, rather this is an interface where the logger will pass logging messages to. Use this for in-game consoles or something like that.
Warning
Unlike an exception, an error is not recoverable!
See also
IException
You may implement this yourself to create your own game objects and drawing code, or you can inherit from Atlas::GameObject to use the default implementation. However, if you inherit from this class, be sure you have a basic understanding of Raylib's and OpenGL's rendering system. If not, see https://learnopengl.com/ and https://www.raylib.com/ for a good place to start. In addition, it is not advised for you to inherit this yourself because it will require you to implement rendering code. However, it is recommended if your game requires a rendering system that is not provided by default.
The IGameObject class is abstract and cannot be instantiated directly. Instead, you should inherit from this class and implement the pure virtual functions. As of version 0.0.3, the pure virtual functions are: render(), texture(), update(), prePhysicsUpdate(), postUpdate(), destroy(), and cleanup().
See also
Gate<GameObject*>
Note
If this boilerplate code is not done, Atlas will not know what to run.
Warning
Do not directly call window code in here or your project will crash!
Template Parameters
T
See also
GameObjectRegistry
Definition at line 7 of file Console.h.
Constructor & Destructor Documentation
~IError()
template<typename ConsoleSink >
virtual Atlas::abstract< ConsoleSink >::~IError () [inline], [virtual], [noexcept]
Definition at line 55 of file Errors.h.
~IGameObject()
template<typename ConsoleSink >
virtual Atlas::abstract< ConsoleSink >::~IGameObject () [virtual], [default]
Default destructor that finalizes an instance of the IGameObject class.
~IPhysicsGameObject()
template<typename ConsoleSink >
Atlas::abstract< ConsoleSink >::~IPhysicsGameObject () [inline], [override]
Definition at line 17 of file PhysicsObject.h.
Member Function Documentation
cleanup() [1/3]
template<typename ConsoleSink >
virtual int Atlas::abstract< ConsoleSink >::cleanup () [pure virtual]
cleanup() [2/3]
template<typename ConsoleSink >
virtual void Atlas::abstract< ConsoleSink >::cleanup () [pure virtual]
Cleanups this instance.
Note
This must be implemented by the user.
cleanup() [3/3]
template<typename ConsoleSink >
virtual int Atlas::abstract< ConsoleSink >::cleanup (int exitCode) [virtual]
Cleans up anything that may need to be cleaned up.
Parameters
exitCode The code that the engine has exited with
Returns
The cleanup exit code.
clear()
template<typename ConsoleSink >
virtual void Atlas::abstract< ConsoleSink >::clear () [pure virtual]
destroy()
template<typename ConsoleSink >
virtual void Atlas::abstract< ConsoleSink >::destroy () [pure virtual]
Destroys this instance, and is called right before the object is removed from memory.
Note
This must be implemented by the user.
draw()
template<typename ConsoleSink >
virtual void Atlas::abstract< ConsoleSink >::draw () [pure virtual]
generate() [1/2]
template<typename ConsoleSink >
virtual void Atlas::abstract< ConsoleSink >::generate () [pure virtual]
generate() [2/2]
template<typename ConsoleSink >
virtual void Atlas::abstract< ConsoleSink >::generate () [pure virtual]
getBuffer()
template<typename ConsoleSink >
virtual std::vector< std::string > & Atlas::abstract< ConsoleSink >::getBuffer () [pure virtual]
getFormat()
template<typename ConsoleSink >
virtual std::string Atlas::abstract< ConsoleSink >::getFormat () [pure virtual]
getLuaFunctions()
template<typename ConsoleSink >
ScriptingFunctionRegistry & Atlas::abstract< ConsoleSink >::getLuaFunctions () [inline]
Gets the lua functions.
Returns
A reference to mLuaFunctions
Definition at line 62 of file Project.h.
getLuaLibraries()
template<typename ConsoleSink >
ScriptingLibraryRegistry & Atlas::abstract< ConsoleSink >::getLuaLibraries () [inline]
Returns the currently active libraries for lua.
Returns
A reference to mLuaLibraries
Definition at line 56 of file Project.h.
GetProject()
template<typename ConsoleSink >
static IProject * Atlas::abstract< ConsoleSink >::GetProject () [static]
Gets the current project instance.
Returns
An IProject pointer of the current project reference instance
getPrompt()
template<typename ConsoleSink >
virtual std::string & Atlas::abstract< ConsoleSink >::getPrompt () [pure virtual]
getRenderer()
template<typename ConsoleSink >
Renderer & Atlas::abstract< ConsoleSink >::getRenderer () [inline]
Gets the renderer instance.
Returns
This project's mRenderer variable
Definition at line 81 of file Project.h.
getWindowDecorations()
template<typename ConsoleSink >
WindowDecorations & Atlas::abstract< ConsoleSink >::getWindowDecorations ()
Gets the window decorations. This includes the window title, icon, size, etc.
Returns
A reference to mWindowDecorations
IConsole()
template<typename ConsoleSink >
Atlas::abstract< ConsoleSink >::IConsole (ConsoleSink & sink) [inline], [explicit]
Definition at line 9 of file Console.h.
IError()
template<typename ConsoleSink >
Atlas::abstract< ConsoleSink >::IError (std::string const & message, std::source_location location = std::source_location::current()) [inline]
Definition at line 53 of file Errors.h.
IGameObject()
template<typename ConsoleSink >
Atlas::abstract< ConsoleSink >::IGameObject () [default]
Default constructor that initializes a new instance of the IGameObject class.
init() [1/3]
template<typename ConsoleSink >
virtual void Atlas::abstract< ConsoleSink >::init () [pure virtual]
init() [2/3]
template<typename ConsoleSink >
virtual int Atlas::abstract< ConsoleSink >::init () [pure virtual]
init() [3/3]
template<typename ConsoleSink >
virtual void Atlas::abstract< ConsoleSink >::init (int argc, char * argv[]) [virtual]
Initializes your project. This will be called after preInit and window initialization, meaning that this is the earliest point that you can use raylib. THIS MUST BE OVERRIDEN BY YOUR PROJECT CLASS!
Parameters
argc Command line argument count int
argv Command line arguments array
initRenderer()
template<typename ConsoleSink >
virtual void Atlas::abstract< ConsoleSink >::initRenderer () [virtual]
Initializes the renderer and should be called after initWindow.
IPhysicsGameObject()
template<typename ConsoleSink >
Atlas::abstract< ConsoleSink >::IPhysicsGameObject (JPH::BodyCreationSettings const & bodySettings, JPH::EActivation activationState) [inline]
Definition at line 13 of file PhysicsObject.h.
objectUpdate()
template<typename ConsoleSink >
virtual int Atlas::abstract< ConsoleSink >::objectUpdate () [virtual]
This is where the actual GameObject update happens, and is called after preObjectUpdate(). Please note that this will run on the update thread!
Returns
The exit code of the step
onCollisionEnter()
template<typename ConsoleSink >
virtual void Atlas::abstract< ConsoleSink >::onCollisionEnter (IGameObject * other) [pure virtual]
Action upon entering collision. This is called the frame the collision happens.
Parameters
other The other game object.
onCollisionExit()
template<typename ConsoleSink >
virtual void Atlas::abstract< ConsoleSink >::onCollisionExit (IGameObject * other) [pure virtual]
Action upon exiting collision.
Parameters
other The other game object.
onCollisionStay()
template<typename ConsoleSink >
virtual void Atlas::abstract< ConsoleSink >::onCollisionStay (IGameObject * other) [pure virtual]
Action upon remaining in collision.
Parameters
other The other game object.
onCollisionValidation()
template<typename ConsoleSink >
virtual void Atlas::abstract< ConsoleSink >::onCollisionValidation (IGameObject * other) [pure virtual]
Action on collision validation.
Parameters
other The other game object.
parseInput()
template<typename ConsoleSink >
virtual void Atlas::abstract< ConsoleSink >::parseInput (const std::string & input) [pure virtual]
parseLog()
template<typename ConsoleSink >
virtual void Atlas::abstract< ConsoleSink >::parseLog (const std::string & message, ELogLevel level, const std::source_location & location) [pure virtual]
parsePrompt()
template<typename ConsoleSink >
virtual void Atlas::abstract< ConsoleSink >::parsePrompt (const std::string & message) [pure virtual]
physicsUpdate()
template<typename ConsoleSink >
virtual int Atlas::abstract< ConsoleSink >::physicsUpdate () [virtual]
This is where the actual physics update happens. Please note that this will run on the physics thread!
Returns
The exit code of the step
postInit() [1/2]
template<typename ConsoleSink >
virtual void Atlas::abstract< ConsoleSink >::postInit () [virtual]
Does a post initialization of the project. This is empty because it is not neccesary to override.
postInit() [2/2]
template<typename ConsoleSink >
virtual int Atlas::abstract< ConsoleSink >::postInit () [pure virtual]
postObjectUpdate()
template<typename ConsoleSink >
virtual int Atlas::abstract< ConsoleSink >::postObjectUpdate () [virtual]
Called right after objectUpdate(). Use this to do anything after the GameObject update. Please note that this will run on the update thread!
Returns
postPhysicsUpdate()
template<typename ConsoleSink >
virtual int Atlas::abstract< ConsoleSink >::postPhysicsUpdate () [virtual]
Post physics update that is called after physicsUpdate() in the physics or update thread (depending on thread count).
Returns
The exit code of the step
postUpdate()
template<typename ConsoleSink >
virtual void Atlas::abstract< ConsoleSink >::postUpdate () [pure virtual]
Called right after the update function, but before texturing/rendering.
Note
Keep in mind that this will run on the update thread, so make sure what you are doing is thread safe.
preInit() [1/2]
template<typename ConsoleSink >
virtual void Atlas::abstract< ConsoleSink >::preInit () [inline], [virtual]
This is the first function that will be called on startup.
Definition at line 95 of file Project.h.
References Atlas::AddFileRegistryLoadFunction(), ATLAS_GAME_DIR, Atlas::Logger::init(), Atlas::InitializeFileRegistry(), Atlas::Singleton< Logger >::Instance(), and Atlas::Log().
preInit() [2/2]
template<typename ConsoleSink >
virtual int Atlas::abstract< ConsoleSink >::preInit () [pure virtual]
preObjectUpdate()
template<typename ConsoleSink >
virtual int Atlas::abstract< ConsoleSink >::preObjectUpdate () [virtual]
Any preparation code for updating the scene's game objects. Use this if you need to do something after the physics update, but before the GameObject update. Please note that this will run on the update thread!
Returns
The exit code of the step
prePhysicsUpdate()
template<typename ConsoleSink >
virtual int Atlas::abstract< ConsoleSink >::prePhysicsUpdate () [virtual]
Pre-update step that is called in the physics or update thread (depending on thread count)
Returns
The exit code of the step
process()
template<typename ConsoleSink >
virtual void Atlas::abstract< ConsoleSink >::process (T entree) [pure virtual]
Processes the specified entree.
Parameters
entree The entree to process.
Template Parameters
T The type of the entree. It is already set by the gate's template.
render() [1/2]
template<typename ConsoleSink >
virtual void Atlas::abstract< ConsoleSink >::render () [inline], [virtual]
Renders this instance. This is not a pure virtual and is empty because it is up to the user to use this as they see fit without forcing them to implement it.
Definition at line 57 of file IGameObject.h.
render() [2/2]
template<typename ConsoleSink >
virtual int Atlas::abstract< ConsoleSink >::render () [virtual]
Assuming that the FBO is enabled, this will render the FBO and apply any post-processing effects to the FBO. Please note that this will run on the update thread!
Returns
An integer that is the exit code for this rendering frame.
run()
template<typename ConsoleSink >
virtual int Atlas::abstract< ConsoleSink >::run (int argc, char * argv[]) [virtual]
Runs the actual game and is called after the init functions.
Parameters
argc Command line argument count int
argv Command line arguments array
Returns
The game loop's exit code
setProject()
template<typename ConsoleSink >
template<typename T >
void Atlas::abstract< ConsoleSink >::setProject (T * project)
This function is used to set the ProjectReference singleton to the project.
Template Parameters
T The typename for what the user's project is
Parameters
project The pointer to the user's project
setWindowDecorations()
template<typename ConsoleSink >
void Atlas::abstract< ConsoleSink >::setWindowDecorations (WindowDecorations & windowDecorations)
Sets the window decorations.
See also
Atlas::WindowDecorations
Parameters
windowDecorations The window decorations.
start()
template<typename ConsoleSink >
virtual int Atlas::abstract< ConsoleSink >::start () [pure virtual]
stop()
template<typename ConsoleSink >
virtual int Atlas::abstract< ConsoleSink >::stop () [pure virtual]
texture() [1/2]
template<typename ConsoleSink >
virtual int Atlas::abstract< ConsoleSink >::texture () [virtual]
Textures all GameObjects before render() is called and after update functions are called. This is essentially where the scene is rendered. Please note that this will run on the render thread!
Returns
An integer that is the exit code for this texturing frame.
texture() [2/2]
template<typename ConsoleSink >
virtual void Atlas::abstract< ConsoleSink >::texture () [pure virtual]
This is a pure virtual function that is the drawing function for when objects are being textured to the render texture. If you do not have anything different to do here, then you may just call render() instead, but this must be implemented in order for the object to be rendered.
update() [1/3]
template<typename ConsoleSink >
virtual int Atlas::abstract< ConsoleSink >::update () [virtual]
update() [2/3]
template<typename ConsoleSink >
virtual void Atlas::abstract< ConsoleSink >::update () [pure virtual]
update() [3/3]
template<typename ConsoleSink >
virtual void Atlas::abstract< ConsoleSink >::update () [pure virtual]
Updates this instance and is called every frame before texturing/rendering.
Note
Keep in mind that this will run on the update thread, so make sure what you are doing is thread safe.
what()
template<typename ConsoleSink >
virtual const char * Atlas::abstract< ConsoleSink >::what () const [pure virtual], [noexcept]
Implements Atlas::IException.
Member Data Documentation
bodyInterface
template<typename ConsoleSink >
JPH::BodyInterface& Atlas::abstract< ConsoleSink >::bodyInterface
Definition at line 11 of file PhysicsObject.h.
depth
template<typename ConsoleSink >
int Atlas::abstract< ConsoleSink >::depth = 0
Todo
Todo add support for multiple layers.
Definition at line 28 of file IGameObject.h.
id
template<typename ConsoleSink >
JPH::BodyID Atlas::abstract< ConsoleSink >::id
Definition at line 10 of file PhysicsObject.h.
mColorSink
template<typename ConsoleSink >
ColorSinkType Atlas::abstract< ConsoleSink >::mColorSink [protected]
Definition at line 47 of file Logging.h.
mLuaFunctions
template<typename ConsoleSink >
ScriptingFunctionRegistry Atlas::abstract< ConsoleSink >::mLuaFunctions [protected]
Definition at line 32 of file Project.h.
mLuaLibraries
template<typename ConsoleSink >
ScriptingLibraryRegistry Atlas::abstract< ConsoleSink >::mLuaLibraries [protected]
Definition at line 31 of file Project.h.
model
template<typename ConsoleSink >
Model Atlas::abstract< ConsoleSink >::model
Definition at line 29 of file IGameObject.h.
mRenderer
template<typename ConsoleSink >
Renderer Atlas::abstract< ConsoleSink >::mRenderer [protected]
Definition at line 29 of file Project.h.
mSink
template<typename ConsoleSink >
ConsoleSink& Atlas::abstract< ConsoleSink >::mSink [protected]
Definition at line 19 of file Console.h.
mWindowDecorations
template<typename ConsoleSink >
WindowDecorations Atlas::abstract< ConsoleSink >::mWindowDecorations [protected]
Definition at line 30 of file Project.h.
position
template<typename ConsoleSink >
Vector3 Atlas::abstract< ConsoleSink >::position = Vector3Zero()
Definition at line 32 of file IGameObject.h.
rotationAngle
template<typename ConsoleSink >
float Atlas::abstract< ConsoleSink >::rotationAngle
Definition at line 35 of file IGameObject.h.
rotationAxis
template<typename ConsoleSink >
Vector3 Atlas::abstract< ConsoleSink >::rotationAxis
Definition at line 33 of file IGameObject.h.
scale
template<typename ConsoleSink >
Vector3 Atlas::abstract< ConsoleSink >::scale
Definition at line 34 of file IGameObject.h.
settings
template<typename ConsoleSink >
GameSettings Atlas::abstract< ConsoleSink >::settings
Definition at line 50 of file Project.h.
tint
template<typename ConsoleSink >
Color Atlas::abstract< ConsoleSink >::tint = WHITE
Definition at line 36 of file IGameObject.h.
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/dbg/Console.h
C:/Dev/Techstorm-v5/src/engine/dbg/Logging.h
C:/Dev/Techstorm-v5/src/engine/objects/IGameObject.h
C:/Dev/Techstorm-v5/src/engine/objects/PhysicsObject.h
C:/Dev/Techstorm-v5/src/engine/Project.h
C:/Dev/Techstorm-v5/src/engine/dbg/Errors.h
C:/Dev/Techstorm-v5/src/engine/EngineComponent.h
C:/Dev/Techstorm-v5/src/engine/renderer/IEntity.h
C:/Dev/Techstorm-v5/src/engine/utils/Gate.h
C:/Dev/Techstorm-v5/src/engine/world/IChunk.h
C:/Dev/Techstorm-v5/src/engine/world/IWorldGenerator.h