gw::Proxy< T > Class Template Reference
#include <aswrappedcall.h>
Public Member Functions
Proxy (T value)
Proxy (T value)
Static Public Member Functions
static T cast (void *ptr)
static T cast (void *ptr)
Public Attributes
T value
Private Member Functions
Proxy (const Proxy &)
Proxy & operator= (const Proxy &)
Proxy (const Proxy &)
Proxy & operator= (const Proxy &)
Detailed Description
template<typename T>
class gw::Proxy< T >
Definition at line 12 of file aswrappedcall.h.
Constructor & Destructor Documentation
Proxy() [1/4]
template<typename T >
gw::Proxy< T >::Proxy (T value) [inline]
Definition at line 15 of file aswrappedcall.h.
Proxy() [2/4]
template<typename T >
gw::Proxy< T >::Proxy (const Proxy< T > &) [private]
Proxy() [3/4]
template<typename T >
gw::Proxy< T >::Proxy (T value) [inline]
Definition at line 15 of file aswrappedcall.h.
Proxy() [4/4]
template<typename T >
gw::Proxy< T >::Proxy (const Proxy< T > &) [private]
Member Function Documentation
cast() [1/2]
template<typename T >
static T gw::Proxy< T >::cast (void * ptr) [inline], [static]
Definition at line 16 of file aswrappedcall.h.
Referenced by gw::ObjFirst< R(*)(T, A0, A1, A2, A3)>::f(), gw::ObjFirst< R(*)(T)>::f(), gw::ObjLast< R(*)(T)>::f(), gw::ObjFirst< R(*)(T, A0)>::f(), gw::ObjLast< void(*)(A0, T)>::f(), gw::ObjFirst< R(*)(T, A0, A1)>::f(), and gw::ObjFirst< R(*)(T, A0, A1, A2)>::f().
cast() [2/2]
template<typename T >
static T gw::Proxy< T >::cast (void * ptr) [inline], [static]
Definition at line 16 of file aswrappedcall.h.
operator=() [1/2]
template<typename T >
Proxy & gw::Proxy< T >::operator= (const Proxy< T > &) [private]
operator=() [2/2]
template<typename T >
Proxy & gw::Proxy< T >::operator= (const Proxy< T > &) [private]
Member Data Documentation
value
template<typename T >
T gw::Proxy< T >::value
Definition at line 14 of file aswrappedcall.h.
Referenced by gw::Wrapper< void(*)(A0)>::f(), gw::Constructor< T(A0)>::f(), gw::Wrapper< void(*)(A0, A1)>::f(), gw::Wrapper< void(*)(A0, A1, A2)>::f(), gw::ObjLast< void(*)(A0, A1, A2, A3, T)>::f(), gw::Constructor< T(A0, A1, A2, A3)>::f(), gw::ObjLast< void(*)(A0, T)>::f(), gw::ObjLast< void(*)(A0, A1, T)>::f(), gw::Constructor< T(A0, A1)>::f(), gw::ObjLast< void(*)(A0, A1, A2, T)>::f(), gw::Constructor< T(A0, A1, A2)>::f(), and gw::Wrapper< void(*)(A0, A1, A2, A3)>::f().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/application/add_on/autowrapper/aswrappedcall.h
C:/Dev/Techstorm-v5/src/engine/modding/add_on/autowrapper/aswrappedcall.h