C:/Dev/Techstorm-v5/src/application/add_on/scriptmath/scriptmath.cpp File Reference
#include <assert.h>
#include <math.h>
#include <float.h>
#include <string.h>
#include "scriptmath.h"
Macros
#define AS_USE_FLOAT 1
#define GENERICff(x)
Functions
float fractionf (float v)
float fpFromIEEE (asUINT raw)
asUINT fpToIEEE (float fp)
double fpFromIEEE (asQWORD raw)
asQWORD fpToIEEE (double fp)
bool closeTo (float a, float b, float epsilon)
bool closeTo (double a, double b, double epsilon)
void RegisterScriptMath_Native (asIScriptEngine *engine)
GENERICff (cosf) GENERICff(sinf) GENERICff(tanf) GENERICff(acosf) GENERICff(asinf) GENERICff(atanf) GENERICff(coshf) GENERICff(sinhf) GENERICff(tanhf) GENERICff(logf) GENERICff(log10f) GENERICff(sqrtf) GENERICff(ceilf) GENERICff(fabsf) GENERICff(floorf) GENERICff(fractionf) void powf_generic(asIScriptGeneric *gen)
void atan2f_generic (asIScriptGeneric *gen)
void RegisterScriptMath_Generic (asIScriptEngine *engine)
void RegisterScriptMath (asIScriptEngine *engine)
Macro Definition Documentation
AS_USE_FLOAT
#define AS_USE_FLOAT 1
Definition at line 55 of file scriptmath.cpp.
GENERICff
#define GENERICff(x)
Value:
void x##_generic(asIScriptGeneric *gen) \
{ \
    float f = *(float*)gen->GetAddressOfArg(0); \
    *(float*)gen->GetAddressOfReturnLocation() = x(f); \
}
Definition at line 227 of file scriptmath.cpp.
Function Documentation
atan2f_generic()
void atan2f_generic (asIScriptGeneric * gen)
Definition at line 257 of file scriptmath.cpp.
Referenced by RegisterScriptMath_Generic().
closeTo() [1/2]
bool closeTo (double a, double b, double epsilon)
Definition at line 146 of file scriptmath.cpp.
closeTo() [2/2]
bool closeTo (float a, float b, float epsilon)
Definition at line 132 of file scriptmath.cpp.
Referenced by RegisterScriptMath_Native().
fpFromIEEE() [1/2]
double fpFromIEEE (asQWORD raw)
Definition at line 101 of file scriptmath.cpp.
fpFromIEEE() [2/2]
float fpFromIEEE (asUINT raw)
Definition at line 79 of file scriptmath.cpp.
Referenced by RegisterScriptMath_Native().
fpToIEEE() [1/2]
asQWORD fpToIEEE (double fp)
Definition at line 111 of file scriptmath.cpp.
fpToIEEE() [2/2]
asUINT fpToIEEE (float fp)
Definition at line 91 of file scriptmath.cpp.
Referenced by RegisterScriptMath_Native().
fractionf()
float fractionf (float v)
Definition at line 62 of file scriptmath.cpp.
Referenced by RegisterScriptMath_Native().
GENERICff()
GENERICff (cosf)
Definition at line 234 of file scriptmath.cpp.
RegisterScriptMath()
void RegisterScriptMath (asIScriptEngine * engine)
Definition at line 361 of file scriptmath.cpp.
References RegisterScriptMath_Generic(), and RegisterScriptMath_Native().
RegisterScriptMath_Generic()
void RegisterScriptMath_Generic (asIScriptEngine * engine)
Definition at line 303 of file scriptmath.cpp.
References atan2f_generic().
Referenced by RegisterScriptMath().
RegisterScriptMath_Native()
void RegisterScriptMath_Native (asIScriptEngine * engine)
Definition at line 157 of file scriptmath.cpp.
References closeTo(), fpFromIEEE(), fpToIEEE(), and fractionf().
Referenced by RegisterScriptMath().