CScriptArray Class Reference
#include <scriptarray.h>
Public Member Functions
void AddRef () const
void Release () const
asITypeInfo * GetArrayObjectType () const
int GetArrayTypeId () const
int GetElementTypeId () const
asUINT GetSize () const
bool IsEmpty () const
void Reserve (asUINT maxElements)
void Resize (asUINT numElements)
void * At (asUINT index)
const void * At (asUINT index) const
void SetValue (asUINT index, void *value)
CScriptArray & operator= (const CScriptArray &)
bool operator== (const CScriptArray &) const
void InsertAt (asUINT index, void *value)
void InsertAt (asUINT index, const CScriptArray &arr)
void InsertLast (void *value)
void RemoveAt (asUINT index)
void RemoveLast ()
void RemoveRange (asUINT start, asUINT count)
void SortAsc ()
void SortDesc ()
void SortAsc (asUINT startAt, asUINT count)
void SortDesc (asUINT startAt, asUINT count)
void Sort (asUINT startAt, asUINT count, bool asc)
void Sort (asIScriptFunction *less, asUINT startAt, asUINT count)
void Reverse ()
int Find (const void *value) const
int Find (asUINT startAt, const void *value) const
int FindByRef (const void *ref) const
int FindByRef (asUINT startAt, const void *ref) const
void * GetBuffer ()
int GetRefCount ()
void SetFlag ()
bool GetFlag ()
void EnumReferences (asIScriptEngine *engine)
void ReleaseAllHandles (asIScriptEngine *engine)
void AddRef () const
void Release () const
asITypeInfo * GetArrayObjectType () const
int GetArrayTypeId () const
int GetElementTypeId () const
asUINT GetSize () const
bool IsEmpty () const
void Reserve (asUINT maxElements)
void Resize (asUINT numElements)
void * At (asUINT index)
const void * At (asUINT index) const
void SetValue (asUINT index, void *value)
CScriptArray & operator= (const CScriptArray &)
bool operator== (const CScriptArray &) const
void InsertAt (asUINT index, void *value)
void InsertAt (asUINT index, const CScriptArray &arr)
void InsertLast (void *value)
void RemoveAt (asUINT index)
void RemoveLast ()
void RemoveRange (asUINT start, asUINT count)
void SortAsc ()
void SortDesc ()
void SortAsc (asUINT startAt, asUINT count)
void SortDesc (asUINT startAt, asUINT count)
void Sort (asUINT startAt, asUINT count, bool asc)
void Sort (asIScriptFunction *less, asUINT startAt, asUINT count)
void Reverse ()
int Find (const void *value) const
int Find (asUINT startAt, const void *value) const
int FindByRef (const void *ref) const
int FindByRef (asUINT startAt, const void *ref) const
void * GetBuffer ()
int GetRefCount ()
void SetFlag ()
bool GetFlag ()
void EnumReferences (asIScriptEngine *engine)
void ReleaseAllHandles (asIScriptEngine *engine)
Static Public Member Functions
static void SetMemoryFunctions (asALLOCFUNC_t allocFunc, asFREEFUNC_t freeFunc)
static CScriptArray * Create (asITypeInfo *ot)
static CScriptArray * Create (asITypeInfo *ot, asUINT length)
static CScriptArray * Create (asITypeInfo *ot, asUINT length, void *defaultValue)
static CScriptArray * Create (asITypeInfo *ot, void *listBuffer)
static void SetMemoryFunctions (asALLOCFUNC_t allocFunc, asFREEFUNC_t freeFunc)
static CScriptArray * Create (asITypeInfo *ot)
static CScriptArray * Create (asITypeInfo *ot, asUINT length)
static CScriptArray * Create (asITypeInfo *ot, asUINT length, void *defaultValue)
static CScriptArray * Create (asITypeInfo *ot, void *listBuffer)
Protected Member Functions
CScriptArray (asITypeInfo *ot, void *initBuf)
CScriptArray (asUINT length, asITypeInfo *ot)
CScriptArray (asUINT length, void *defVal, asITypeInfo *ot)
CScriptArray (const CScriptArray &other)
virtual ~CScriptArray ()
bool Less (const void *a, const void *b, bool asc)
void * GetArrayItemPointer (int index)
void * GetDataPointer (void *buffer)
void Copy (void *dst, void *src)
void Swap (void *a, void *b)
void Precache ()
bool CheckMaxSize (asUINT numElements)
void Resize (int delta, asUINT at)
void CreateBuffer (SArrayBuffer **buf, asUINT numElements)
void DeleteBuffer (SArrayBuffer *buf)
void CopyBuffer (SArrayBuffer *dst, SArrayBuffer *src)
void Construct (SArrayBuffer *buf, asUINT start, asUINT end)
void Destruct (SArrayBuffer *buf, asUINT start, asUINT end)
bool Equals (const void *a, const void *b, asIScriptContext *ctx, SArrayCache *cache) const
CScriptArray (asITypeInfo *ot, void *initBuf)
CScriptArray (asUINT length, asITypeInfo *ot)
CScriptArray (asUINT length, void *defVal, asITypeInfo *ot)
CScriptArray (const CScriptArray &other)
virtual ~CScriptArray ()
bool Less (const void *a, const void *b, bool asc)
void * GetArrayItemPointer (int index)
void * GetDataPointer (void *buffer)
void Copy (void *dst, void *src)
void Swap (void *a, void *b)
void Precache ()
bool CheckMaxSize (asUINT numElements)
void Resize (int delta, asUINT at)
void CreateBuffer (SArrayBuffer **buf, asUINT numElements)
void DeleteBuffer (SArrayBuffer *buf)
void CopyBuffer (SArrayBuffer *dst, SArrayBuffer *src)
void Construct (SArrayBuffer *buf, asUINT start, asUINT end)
void Destruct (SArrayBuffer *buf, asUINT start, asUINT end)
bool Equals (const void *a, const void *b, asIScriptContext *ctx, SArrayCache *cache) const
Protected Attributes
int refCount
bool gcFlag
asITypeInfo * objType
SArrayBuffer * buffer
int elementSize
int subTypeId
Detailed Description
Definition at line 30 of file scriptarray.h.
Constructor & Destructor Documentation
CScriptArray() [1/8]
CScriptArray::CScriptArray (asITypeInfo * ot, void * initBuf) [protected]
Definition at line 374 of file scriptarray.cpp.
References At(), CheckMaxSize(), CreateBuffer(), elementSize, gcFlag, objType, Precache(), refCount, and subTypeId.
CScriptArray() [2/8]
CScriptArray::CScriptArray (asUINT length, asITypeInfo * ot) [protected]
Definition at line 467 of file scriptarray.cpp.
References CheckMaxSize(), CreateBuffer(), elementSize, gcFlag, objType, Precache(), refCount, and subTypeId.
CScriptArray() [3/8]
CScriptArray::CScriptArray (asUINT length, void * defVal, asITypeInfo * ot) [protected]
Definition at line 521 of file scriptarray.cpp.
References CheckMaxSize(), CreateBuffer(), elementSize, gcFlag, GetSize(), objType, Precache(), refCount, SetValue(), and subTypeId.
CScriptArray() [4/8]
CScriptArray::CScriptArray (const CScriptArray & other) [protected]
Definition at line 500 of file scriptarray.cpp.
References CreateBuffer(), elementSize, gcFlag, objType, Precache(), and refCount.
~CScriptArray() [1/2]
CScriptArray::~CScriptArray () [protected], [virtual]
Definition at line 622 of file scriptarray.cpp.
References DeleteBuffer(), and objType.
Referenced by Release().
CScriptArray() [5/8]
CScriptArray::CScriptArray (asITypeInfo * ot, void * initBuf) [protected]
CScriptArray() [6/8]
CScriptArray::CScriptArray (asUINT length, asITypeInfo * ot) [protected]
CScriptArray() [7/8]
CScriptArray::CScriptArray (asUINT length, void * defVal, asITypeInfo * ot) [protected]
CScriptArray() [8/8]
CScriptArray::CScriptArray (const CScriptArray & other) [protected]
~CScriptArray() [2/2]
virtual CScriptArray::~CScriptArray () [protected], [virtual]
Member Function Documentation
AddRef() [1/2]
void CScriptArray::AddRef () const
Definition at line 1914 of file scriptarray.cpp.
References gcFlag, and refCount.
Referenced by ScriptArrayAddRef_Generic().
AddRef() [2/2]
void CScriptArray::AddRef () const
At() [1/4]
void * CScriptArray::At (asUINT index)
Definition at line 937 of file scriptarray.cpp.
References At().
Referenced by At(), CScriptArray(), Find(), FindByRef(), CScriptFileSystem::GetDirs(), CScriptFileSystem::GetFiles(), CScriptDictionary::GetKeys(), InsertAt(), operator==(), ScriptArrayAt_Generic(), SetValue(), Sort(), Sort(), StringJoin(), and StringSplit().
At() [2/4]
void * CScriptArray::At (asUINT index)
At() [3/4]
const void * CScriptArray::At (asUINT index) const
Definition at line 921 of file scriptarray.cpp.
References elementSize, and subTypeId.
At() [4/4]
const void * CScriptArray::At (asUINT index) const
CheckMaxSize() [1/2]
bool CScriptArray::CheckMaxSize (asUINT numElements) [protected]
Definition at line 785 of file scriptarray.cpp.
References elementSize.
Referenced by CScriptArray(), CScriptArray(), CScriptArray(), Reserve(), Resize(), and Resize().
CheckMaxSize() [2/2]
bool CScriptArray::CheckMaxSize (asUINT numElements) [protected]
Construct() [1/2]
void CScriptArray::Construct (SArrayBuffer * buf, asUINT start, asUINT end) [protected]
Definition at line 978 of file scriptarray.cpp.
References SArrayBuffer::data, elementSize, objType, and subTypeId.
Referenced by CreateBuffer(), and Resize().
Construct() [2/2]
void CScriptArray::Construct (SArrayBuffer * buf, asUINT start, asUINT end) [protected]
Copy() [1/2]
void CScriptArray::Copy (void * dst, void * src) [protected]
Definition at line 1362 of file scriptarray.cpp.
References elementSize.
Referenced by Reverse(), Sort(), and Swap().
Copy() [2/2]
void CScriptArray::Copy (void * dst, void * src) [protected]
CopyBuffer() [1/2]
void CScriptArray::CopyBuffer (SArrayBuffer * dst, SArrayBuffer * src) [protected]
Definition at line 1666 of file scriptarray.cpp.
References SArrayBuffer::data, elementSize, SArrayBuffer::numElements, objType, and subTypeId.
Referenced by operator=().
CopyBuffer() [2/2]
void CScriptArray::CopyBuffer (SArrayBuffer * dst, SArrayBuffer * src) [protected]
Create() [1/8]
CScriptArray * CScriptArray::Create (asITypeInfo * ot) [static]
Definition at line 121 of file scriptarray.cpp.
References Create().
Referenced by Create(), CScriptFileSystem::GetDirs(), CScriptFileSystem::GetFiles(), CScriptDictionary::GetKeys(), RegisterScriptArray_Native(), ScriptArrayFactory2_Generic(), ScriptArrayFactory_Generic(), ScriptArrayFactoryDefVal_Generic(), ScriptArrayListFactory_Generic(), and StringSplit().
Create() [2/8]
static CScriptArray * CScriptArray::Create (asITypeInfo * ot) [static]
Create() [3/8]
CScriptArray * CScriptArray::Create (asITypeInfo * ot, asUINT length) [static]
Definition at line 64 of file scriptarray.cpp.
References userAlloc.
Create() [4/8]
static CScriptArray * CScriptArray::Create (asITypeInfo * ot, asUINT length) [static]
Create() [5/8]
CScriptArray * CScriptArray::Create (asITypeInfo * ot, asUINT length, void * defaultValue) [static]
Definition at line 102 of file scriptarray.cpp.
References userAlloc.
Create() [6/8]
static CScriptArray * CScriptArray::Create (asITypeInfo * ot, asUINT length, void * defaultValue) [static]
Create() [7/8]
CScriptArray * CScriptArray::Create (asITypeInfo * ot, void * listBuffer) [static]
Definition at line 83 of file scriptarray.cpp.
References userAlloc.
Create() [8/8]
static CScriptArray * CScriptArray::Create (asITypeInfo * ot, void * listBuffer) [static]
CreateBuffer() [1/2]
void CScriptArray::CreateBuffer (SArrayBuffer ** buf, asUINT numElements) [protected]
Definition at line 949 of file scriptarray.cpp.
References Construct(), elementSize, SArrayBuffer::numElements, and userAlloc.
Referenced by CScriptArray(), CScriptArray(), CScriptArray(), and CScriptArray().
CreateBuffer() [2/2]
void CScriptArray::CreateBuffer (SArrayBuffer ** buf, asUINT numElements) [protected]
DeleteBuffer() [1/2]
void CScriptArray::DeleteBuffer (SArrayBuffer * buf) [protected]
Definition at line 969 of file scriptarray.cpp.
References Destruct(), SArrayBuffer::numElements, and userFree.
Referenced by ~CScriptArray().
DeleteBuffer() [2/2]
void CScriptArray::DeleteBuffer (SArrayBuffer * buf) [protected]
Destruct() [1/2]
void CScriptArray::Destruct (SArrayBuffer * buf, asUINT start, asUINT end) [protected]
Definition at line 1013 of file scriptarray.cpp.
References SArrayBuffer::data, objType, and subTypeId.
Referenced by DeleteBuffer(), RemoveRange(), and Resize().
Destruct() [2/2]
void CScriptArray::Destruct (SArrayBuffer * buf, asUINT start, asUINT end) [protected]
EnumReferences() [1/2]
void CScriptArray::EnumReferences (asIScriptEngine * engine)
Definition at line 1874 of file scriptarray.cpp.
References subTypeId.
Referenced by ScriptArrayEnumReferences_Generic().
EnumReferences() [2/2]
void CScriptArray::EnumReferences (asIScriptEngine * engine)
Equals() [1/2]
bool CScriptArray::Equals (const void * a, const void * b, asIScriptContext * ctx, SArrayCache * cache) const [protected]
Definition at line 1142 of file scriptarray.cpp.
References SArrayCache::cmpFunc, COMPARE, SArrayCache::eqFunc, and subTypeId.
Referenced by Find(), and operator==().
Equals() [2/2]
bool CScriptArray::Equals (const void * a, const void * b, asIScriptContext * ctx, SArrayCache * cache) const [protected]
Find() [1/4]
int CScriptArray::Find (asUINT startAt, const void * value) const
Definition at line 1266 of file scriptarray.cpp.
References ARRAY_CACHE, At(), SArrayCache::cmpFunc, SArrayCache::eqFunc, SArrayCache::eqFuncReturnCode, Equals(), GetSize(), objType, and subTypeId.
Find() [2/4]
int CScriptArray::Find (asUINT startAt, const void * value) const
Find() [3/4]
int CScriptArray::Find (const void * value) const
Definition at line 1261 of file scriptarray.cpp.
References Find().
Referenced by Find(), ScriptArrayFind2_Generic(), and ScriptArrayFind_Generic().
Find() [4/4]
int CScriptArray::Find (const void * value) const
FindByRef() [1/4]
int CScriptArray::FindByRef (asUINT startAt, const void * ref) const
Definition at line 1234 of file scriptarray.cpp.
References At(), GetSize(), and subTypeId.
FindByRef() [2/4]
int CScriptArray::FindByRef (asUINT startAt, const void * ref) const
FindByRef() [3/4]
int CScriptArray::FindByRef (const void * ref) const
Definition at line 1229 of file scriptarray.cpp.
References FindByRef().
Referenced by FindByRef(), ScriptArrayFindByRef2_Generic(), and ScriptArrayFindByRef_Generic().
FindByRef() [4/4]
int CScriptArray::FindByRef (const void * ref) const
GetArrayItemPointer() [1/2]
void * CScriptArray::GetArrayItemPointer (int index) [protected]
Definition at line 1383 of file scriptarray.cpp.
References elementSize.
Referenced by Reverse(), Sort(), and Sort().
GetArrayItemPointer() [2/2]
void * CScriptArray::GetArrayItemPointer (int index) [protected]
GetArrayObjectType() [1/2]
asITypeInfo * CScriptArray::GetArrayObjectType () const
Definition at line 807 of file scriptarray.cpp.
References objType.
Referenced by operator=().
GetArrayObjectType() [2/2]
asITypeInfo * CScriptArray::GetArrayObjectType () const
GetArrayTypeId() [1/2]
int CScriptArray::GetArrayTypeId () const
Definition at line 812 of file scriptarray.cpp.
References objType.
GetArrayTypeId() [2/2]
int CScriptArray::GetArrayTypeId () const
GetBuffer() [1/2]
void * CScriptArray::GetBuffer ()
Definition at line 942 of file scriptarray.cpp.
GetBuffer() [2/2]
void * CScriptArray::GetBuffer ()
GetDataPointer() [1/2]
void * CScriptArray::GetDataPointer (void * buffer) [protected]
Definition at line 1390 of file scriptarray.cpp.
References subTypeId.
Referenced by Sort().
GetDataPointer() [2/2]
void * CScriptArray::GetDataPointer (void * buffer) [protected]
GetElementTypeId() [1/2]
int CScriptArray::GetElementTypeId () const
Definition at line 817 of file scriptarray.cpp.
References subTypeId.
GetElementTypeId() [2/2]
int CScriptArray::GetElementTypeId () const
GetFlag() [1/2]
bool CScriptArray::GetFlag ()
Definition at line 1947 of file scriptarray.cpp.
References gcFlag.
Referenced by ScriptArrayGetFlag_Generic().
GetFlag() [2/2]
bool CScriptArray::GetFlag ()
GetRefCount() [1/2]
int CScriptArray::GetRefCount ()
Definition at line 1935 of file scriptarray.cpp.
References refCount.
Referenced by ScriptArrayGetRefCount_Generic().
GetRefCount() [2/2]
int CScriptArray::GetRefCount ()
GetSize() [1/2]
asUINT CScriptArray::GetSize () const
Definition at line 632 of file scriptarray.cpp.
Referenced by CScriptArray(), Find(), FindByRef(), CScriptFileSystem::GetDirs(), CScriptFileSystem::GetFiles(), InsertAt(), operator==(), Reverse(), ScriptArrayLength_Generic(), SortAsc(), SortDesc(), StringJoin(), and StringSplit().
GetSize() [2/2]
asUINT CScriptArray::GetSize () const
InsertAt() [1/4]
void CScriptArray::InsertAt (asUINT index, const CScriptArray & arr)
Definition at line 840 of file scriptarray.cpp.
References At(), GetSize(), objType, Resize(), and SetValue().
InsertAt() [2/4]
void CScriptArray::InsertAt (asUINT index, const CScriptArray & arr)
InsertAt() [3/4]
void CScriptArray::InsertAt (asUINT index, void * value)
Definition at line 822 of file scriptarray.cpp.
References Resize(), and SetValue().
Referenced by InsertLast(), ScriptArrayInsertAt_Generic(), and ScriptArrayInsertAtArray_Generic().
InsertAt() [4/4]
void CScriptArray::InsertAt (asUINT index, void * value)
InsertLast() [1/2]
void CScriptArray::InsertLast (void * value)
Definition at line 895 of file scriptarray.cpp.
References InsertAt().
Referenced by ScriptArrayInsertLast_Generic().
InsertLast() [2/2]
void CScriptArray::InsertLast (void * value)
IsEmpty() [1/2]
bool CScriptArray::IsEmpty () const
Definition at line 637 of file scriptarray.cpp.
Referenced by ScriptArrayIsEmpty_Generic().
IsEmpty() [2/2]
bool CScriptArray::IsEmpty () const
Less() [1/2]
bool CScriptArray::Less (const void * a, const void * b, bool asc) [protected]
Definition at line 1032 of file scriptarray.cpp.
References COMPARE, and subTypeId.
Referenced by Sort().
Less() [2/2]
bool CScriptArray::Less (const void * a, const void * b, bool asc) [protected]
operator=() [1/2]
CScriptArray & CScriptArray::operator= (const CScriptArray & other)
Definition at line 358 of file scriptarray.cpp.
References buffer, CopyBuffer(), GetArrayObjectType(), SArrayBuffer::numElements, and Resize().
operator=() [2/2]
CScriptArray & CScriptArray::operator= (const CScriptArray &)
operator==() [1/2]
bool CScriptArray::operator== (const CScriptArray & other) const
Definition at line 1084 of file scriptarray.cpp.
References ARRAY_CACHE, At(), Equals(), GetSize(), objType, and subTypeId.
operator==() [2/2]
bool CScriptArray::operator== (const CScriptArray &) const
Precache() [1/2]
void CScriptArray::Precache () [protected]
Definition at line 1748 of file scriptarray.cpp.
References ARRAY_CACHE, SArrayCache::cmpFunc, SArrayCache::cmpFuncReturnCode, SArrayCache::eqFunc, SArrayCache::eqFuncReturnCode, objType, subTypeId, and userAlloc.
Referenced by CScriptArray(), CScriptArray(), CScriptArray(), and CScriptArray().
Precache() [2/2]
void CScriptArray::Precache () [protected]
Release() [1/2]
void CScriptArray::Release () const
Definition at line 1921 of file scriptarray.cpp.
References gcFlag, refCount, userFree, and ~CScriptArray().
Referenced by ScriptArrayRelease_Generic().
Release() [2/2]
void CScriptArray::Release () const
ReleaseAllHandles() [1/2]
void CScriptArray::ReleaseAllHandles (asIScriptEngine * engine)
Definition at line 1908 of file scriptarray.cpp.
References Resize().
Referenced by ScriptArrayReleaseAllHandles_Generic().
ReleaseAllHandles() [2/2]
void CScriptArray::ReleaseAllHandles (asIScriptEngine * engine)
RemoveAt() [1/2]
void CScriptArray::RemoveAt (asUINT index)
Definition at line 900 of file scriptarray.cpp.
References Resize().
Referenced by RemoveLast(), and ScriptArrayRemoveAt_Generic().
RemoveAt() [2/2]
void CScriptArray::RemoveAt (asUINT index)
RemoveLast() [1/2]
void CScriptArray::RemoveLast ()
Definition at line 915 of file scriptarray.cpp.
References RemoveAt().
Referenced by ScriptArrayRemoveLast_Generic().
RemoveLast() [2/2]
void CScriptArray::RemoveLast ()
RemoveRange() [1/2]
void CScriptArray::RemoveRange (asUINT start, asUINT count)
Definition at line 684 of file scriptarray.cpp.
References Destruct(), and elementSize.
Referenced by ScriptArrayRemoveRange_Generic().
RemoveRange() [2/2]
void CScriptArray::RemoveRange (asUINT start, asUINT count)
Reserve() [1/2]
void CScriptArray::Reserve (asUINT maxElements)
Definition at line 642 of file scriptarray.cpp.
References CheckMaxSize(), SArrayBuffer::data, elementSize, SArrayBuffer::maxElements, SArrayBuffer::numElements, userAlloc, and userFree.
Referenced by ScriptArrayReserve_Generic().
Reserve() [2/2]
void CScriptArray::Reserve (asUINT maxElements)
Resize() [1/4]
void CScriptArray::Resize (asUINT numElements)
Definition at line 676 of file scriptarray.cpp.
References CheckMaxSize(), and Resize().
Referenced by CScriptFileSystem::GetDirs(), CScriptFileSystem::GetFiles(), InsertAt(), InsertAt(), operator=(), ReleaseAllHandles(), RemoveAt(), Resize(), ScriptArrayResize_Generic(), and StringSplit().
Resize() [2/4]
void CScriptArray::Resize (asUINT numElements)
Resize() [3/4]
void CScriptArray::Resize (int delta, asUINT at) [protected]
Definition at line 713 of file scriptarray.cpp.
References CheckMaxSize(), Construct(), SArrayBuffer::data, Destruct(), elementSize, SArrayBuffer::maxElements, SArrayBuffer::numElements, userAlloc, and userFree.
Resize() [4/4]
void CScriptArray::Resize (int delta, asUINT at) [protected]
Reverse() [1/2]
void CScriptArray::Reverse ()
Definition at line 1067 of file scriptarray.cpp.
References Copy(), GetArrayItemPointer(), and GetSize().
Referenced by ScriptArrayReverse_Generic().
Reverse() [2/2]
void CScriptArray::Reverse ()
SetFlag() [1/2]
void CScriptArray::SetFlag ()
Definition at line 1941 of file scriptarray.cpp.
References gcFlag.
Referenced by ScriptArraySetFlag_Generic().
SetFlag() [2/2]
void CScriptArray::SetFlag ()
SetMemoryFunctions() [1/2]
void CScriptArray::SetMemoryFunctions (asALLOCFUNC_t allocFunc, asFREEFUNC_t freeFunc) [static]
Definition at line 25 of file scriptarray.cpp.
References userAlloc, and userFree.
SetMemoryFunctions() [2/2]
static void CScriptArray::SetMemoryFunctions (asALLOCFUNC_t allocFunc, asFREEFUNC_t freeFunc) [static]
SetValue() [1/2]
void CScriptArray::SetValue (asUINT index, void * value)
Definition at line 558 of file scriptarray.cpp.
References At(), objType, and subTypeId.
Referenced by CScriptArray(), InsertAt(), and InsertAt().
SetValue() [2/2]
void CScriptArray::SetValue (asUINT index, void * value)
Sort() [1/4]
void CScriptArray::Sort (asIScriptFunction * less, asUINT startAt, asUINT count)
Definition at line 1586 of file scriptarray.cpp.
References At(), GetArrayItemPointer(), objType, and Swap().
Sort() [2/4]
void CScriptArray::Sort (asIScriptFunction * less, asUINT startAt, asUINT count)
Sort() [3/4]
void CScriptArray::Sort (asUINT startAt, asUINT count, bool asc)
Definition at line 1431 of file scriptarray.cpp.
References ARRAY_CACHE, At(), SArrayCache::cmpFunc, SArrayCache::cmpFuncReturnCode, Copy(), GetArrayItemPointer(), GetDataPointer(), Less(), objType, and subTypeId.
Referenced by ScriptArraySortCallback_Generic(), SortAsc(), SortAsc(), SortDesc(), and SortDesc().
Sort() [4/4]
void CScriptArray::Sort (asUINT startAt, asUINT count, bool asc)
SortAsc() [1/4]
void CScriptArray::SortAsc ()
Definition at line 1406 of file scriptarray.cpp.
References GetSize(), and Sort().
Referenced by ScriptArraySortAsc2_Generic(), and ScriptArraySortAsc_Generic().
SortAsc() [2/4]
void CScriptArray::SortAsc ()
SortAsc() [3/4]
void CScriptArray::SortAsc (asUINT startAt, asUINT count)
Definition at line 1412 of file scriptarray.cpp.
References Sort().
SortAsc() [4/4]
void CScriptArray::SortAsc (asUINT startAt, asUINT count)
SortDesc() [1/4]
void CScriptArray::SortDesc ()
Definition at line 1418 of file scriptarray.cpp.
References GetSize(), and Sort().
Referenced by ScriptArraySortDesc2_Generic(), and ScriptArraySortDesc_Generic().
SortDesc() [2/4]
void CScriptArray::SortDesc ()
SortDesc() [3/4]
void CScriptArray::SortDesc (asUINT startAt, asUINT count)
Definition at line 1424 of file scriptarray.cpp.
References Sort().
SortDesc() [4/4]
void CScriptArray::SortDesc (asUINT startAt, asUINT count)
Swap() [1/2]
void CScriptArray::Swap (void * a, void * b) [protected]
Definition at line 1372 of file scriptarray.cpp.
References Copy().
Referenced by Sort().
Swap() [2/2]
void CScriptArray::Swap (void * a, void * b) [protected]
Member Data Documentation
buffer
SArrayBuffer * CScriptArray::buffer [protected]
Definition at line 112 of file scriptarray.h.
Referenced by operator=().
elementSize
int CScriptArray::elementSize [protected]
Definition at line 113 of file scriptarray.h.
Referenced by At(), CheckMaxSize(), Construct(), Copy(), CopyBuffer(), CreateBuffer(), CScriptArray(), CScriptArray(), CScriptArray(), CScriptArray(), GetArrayItemPointer(), RemoveRange(), Reserve(), and Resize().
gcFlag
bool CScriptArray::gcFlag [mutable], [protected]
Definition at line 110 of file scriptarray.h.
Referenced by AddRef(), CScriptArray(), CScriptArray(), CScriptArray(), CScriptArray(), GetFlag(), Release(), and SetFlag().
objType
asITypeInfo * CScriptArray::objType [protected]
Definition at line 111 of file scriptarray.h.
Referenced by Construct(), CopyBuffer(), CScriptArray(), CScriptArray(), CScriptArray(), CScriptArray(), Destruct(), Find(), GetArrayObjectType(), GetArrayTypeId(), InsertAt(), operator==(), Precache(), SetValue(), Sort(), Sort(), and ~CScriptArray().
refCount
int CScriptArray::refCount [mutable], [protected]
Definition at line 109 of file scriptarray.h.
Referenced by AddRef(), CScriptArray(), CScriptArray(), CScriptArray(), CScriptArray(), GetRefCount(), and Release().
subTypeId
int CScriptArray::subTypeId [protected]
Definition at line 114 of file scriptarray.h.
Referenced by At(), Construct(), CopyBuffer(), CScriptArray(), CScriptArray(), CScriptArray(), Destruct(), EnumReferences(), Equals(), Find(), FindByRef(), GetDataPointer(), GetElementTypeId(), Less(), operator==(), Precache(), SetValue(), and Sort().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/application/add_on/scriptarray/scriptarray.h
C:/Dev/Techstorm-v5/src/engine/modding/add_on/scriptarray/scriptarray.h
C:/Dev/Techstorm-v5/src/application/add_on/scriptarray/scriptarray.cpp
C:/Dev/Techstorm-v5/src/engine/modding/add_on/scriptarray/scriptarray.cpp