Atlas::AVulkanHandleWrapper< T_WRAPS > Class Template Reference
#include <RenderCommon.h>
Public Member Functions
explicit (false) AVulkanHandleWrapper(T_WRAPS &handle)
AVulkanHandleWrapper ()=default
virtual ~AVulkanHandleWrapper () override=default
virtual bool hasValidHandle () const
virtual bool isValid () const override
T_WRAPS getHandle () const
explicit (false) operator const T_WRAPS &() const
explicit (false) operator T_WRAPS &()
explicit (false) operator bool() const
Public Member Functions inherited from Atlas::InitializableAndValidatable
InitializableAndValidatable (bool bIsInit, bool bIsValid)
InitializableAndValidatable ()=default
Public Member Functions inherited from Atlas::Initializable
ATLAS_EXPLICIT Initializable (bool bIsInit)
Initializable ()=default
virtual ~Initializable ()=default
virtual bool isInit () const
Public Member Functions inherited from Atlas::Validatable
ATLAS_EXPLICIT Validatable (bool bIsValid)
Validatable ()=default
virtual ~Validatable ()=default
virtual ATLAS_IMPLICIT operator bool () const
Protected Member Functions
void setHandle (T_WRAPS handle)
T_WRAPS & getHandleRef ()
Protected Member Functions inherited from Atlas::Initializable
bool & getInternalInitValue ()
virtual void setInitState (bool bNewInitState)
virtual void setInit ()
virtual void setNotInit ()
Protected Member Functions inherited from Atlas::Validatable
bool & getInternalValidityValue ()
virtual void setValidity (bool bIsValid)
virtual void setValid ()
virtual void setInvalid ()
Private Attributes
T_WRAPS mHandle { VK_NULL_HANDLE }
Detailed Description
template<typename T_WRAPS>
class Atlas::AVulkanHandleWrapper< T_WRAPS >
Definition at line 149 of file RenderCommon.h.
Constructor & Destructor Documentation
AVulkanHandleWrapper()
template<typename T_WRAPS >
Atlas::AVulkanHandleWrapper< T_WRAPS >::AVulkanHandleWrapper () [default]
~AVulkanHandleWrapper()
template<typename T_WRAPS >
virtual Atlas::AVulkanHandleWrapper< T_WRAPS >::~AVulkanHandleWrapper () [override], [virtual], [default]
Member Function Documentation
explicit() [1/4]
template<typename T_WRAPS >
Atlas::AVulkanHandleWrapper< T_WRAPS >::explicit (false) & [inline]
Definition at line 168 of file RenderCommon.h.
explicit() [2/4]
template<typename T_WRAPS >
Atlas::AVulkanHandleWrapper< T_WRAPS >::explicit (false) const [inline]
Definition at line 191 of file RenderCommon.h.
References Atlas::AVulkanHandleWrapper< T_WRAPS >::isValid().
explicit() [3/4]
template<typename T_WRAPS >
Atlas::AVulkanHandleWrapper< T_WRAPS >::explicit (false) const & [inline]
Definition at line 183 of file RenderCommon.h.
References Atlas::AVulkanHandleWrapper< T_WRAPS >::mHandle.
explicit() [4/4]
template<typename T_WRAPS >
Atlas::AVulkanHandleWrapper< T_WRAPS >::explicit (false) & [inline]
Definition at line 187 of file RenderCommon.h.
References Atlas::AVulkanHandleWrapper< T_WRAPS >::mHandle.
getHandle()
template<typename T_WRAPS >
T_WRAPS Atlas::AVulkanHandleWrapper< T_WRAPS >::getHandle () const [inline]
Definition at line 181 of file RenderCommon.h.
References Atlas::AVulkanHandleWrapper< T_WRAPS >::mHandle.
getHandleRef()
template<typename T_WRAPS >
T_WRAPS & Atlas::AVulkanHandleWrapper< T_WRAPS >::getHandleRef () [inline], [protected]
Definition at line 157 of file RenderCommon.h.
References Atlas::AVulkanHandleWrapper< T_WRAPS >::mHandle.
hasValidHandle()
template<typename T_WRAPS >
virtual bool Atlas::AVulkanHandleWrapper< T_WRAPS >::hasValidHandle () const [inline], [virtual]
Definition at line 174 of file RenderCommon.h.
References Atlas::AVulkanHandleWrapper< T_WRAPS >::mHandle.
Referenced by Atlas::AVulkanHandleWrapper< T_WRAPS >::isValid().
isValid()
template<typename T_WRAPS >
virtual bool Atlas::AVulkanHandleWrapper< T_WRAPS >::isValid () const [inline], [override], [virtual]
Reimplemented from Atlas::InitializableAndValidatable.
Reimplemented in Atlas::PhysicalDevice, Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >, and Atlas::AVulkanCompositeHandleWrapper< VkPhysicalDevice, vkb::PhysicalDevice, vkb::PhysicalDeviceSelector >.
Definition at line 176 of file RenderCommon.h.
References Atlas::AVulkanHandleWrapper< T_WRAPS >::hasValidHandle(), and Atlas::InitializableAndValidatable::isValid().
Referenced by Atlas::AVulkanHandleWrapper< T_WRAPS >::explicit(), Atlas::PhysicalDevice::isValid(), and Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::isValid().
setHandle()
template<typename T_WRAPS >
void Atlas::AVulkanHandleWrapper< T_WRAPS >::setHandle (T_WRAPS handle) [inline], [protected]
Definition at line 155 of file RenderCommon.h.
References Atlas::AVulkanHandleWrapper< T_WRAPS >::mHandle.
Member Data Documentation
mHandle
template<typename T_WRAPS >
T_WRAPS Atlas::AVulkanHandleWrapper< T_WRAPS >::mHandle { VK_NULL_HANDLE } [private]
Definition at line 151 of file RenderCommon.h.
Referenced by Atlas::AVulkanHandleWrapper< T_WRAPS >::explicit(), Atlas::AVulkanHandleWrapper< T_WRAPS >::explicit(), Atlas::AVulkanHandleWrapper< T_WRAPS >::getHandle(), Atlas::AVulkanHandleWrapper< T_WRAPS >::getHandleRef(), Atlas::AVulkanHandleWrapper< T_WRAPS >::hasValidHandle(), and Atlas::AVulkanHandleWrapper< T_WRAPS >::setHandle().
The documentation for this class was generated from the following file:
C:/Dev/Techstorm-v5/src/engine/graphics/RenderCommon.h