C:/Dev/Techstorm-v5/src/bindings/imgui_impl_dx10.cpp File Reference
#include "imgui.h"
#include "imgui_impl_dx10.h"
#include <stdio.h>
#include <d3d10_1.h>
#include <d3d10.h>
#include <d3dcompiler.h>
Classes
struct ImGui_ImplDX10_Data
struct VERTEX_CONSTANT_BUFFER_DX10
Functions
void ImGui_ImplDX10_RenderDrawData (ImDrawData *draw_data)
bool ImGui_ImplDX10_CreateDeviceObjects ()
void ImGui_ImplDX10_InvalidateDeviceObjects ()
bool ImGui_ImplDX10_Init (ID3D10Device *device)
void ImGui_ImplDX10_Shutdown ()
void ImGui_ImplDX10_NewFrame ()
Function Documentation
ImGui_ImplDX10_CreateDeviceObjects()
bool ImGui_ImplDX10_CreateDeviceObjects ()
Definition at line 362 of file imgui_impl_dx10.cpp.
References ImGui_ImplDX10_InvalidateDeviceObjects(), ImGui_ImplDX10_Data::pBlendState, ImGui_ImplDX10_Data::pd3dDevice, ImGui_ImplDX10_Data::pDepthStencilState, ImGui_ImplDX10_Data::pFontSampler, ImGui_ImplDX10_Data::pInputLayout, ImGui_ImplDX10_Data::pPixelShader, ImGui_ImplDX10_Data::pRasterizerState, ImGui_ImplDX10_Data::pVertexConstantBuffer, and ImGui_ImplDX10_Data::pVertexShader.
Referenced by ImGui_ImplDX10_NewFrame().
ImGui_ImplDX10_Init()
bool ImGui_ImplDX10_Init (ID3D10Device * device)
Definition at line 535 of file imgui_impl_dx10.cpp.
References ImGui_ImplDX10_Data::pd3dDevice, and ImGui_ImplDX10_Data::pFactory.
ImGui_ImplDX10_InvalidateDeviceObjects()
void ImGui_ImplDX10_InvalidateDeviceObjects ()
Definition at line 516 of file imgui_impl_dx10.cpp.
References ImGui_ImplDX10_Data::pBlendState, ImGui_ImplDX10_Data::pd3dDevice, ImGui_ImplDX10_Data::pDepthStencilState, ImGui_ImplDX10_Data::pFontSampler, ImGui_ImplDX10_Data::pFontTextureView, ImGui_ImplDX10_Data::pIB, ImGui_ImplDX10_Data::pInputLayout, ImGui_ImplDX10_Data::pPixelShader, ImGui_ImplDX10_Data::pRasterizerState, ImGui_ImplDX10_Data::pVB, ImGui_ImplDX10_Data::pVertexConstantBuffer, and ImGui_ImplDX10_Data::pVertexShader.
Referenced by ImGui_ImplDX10_CreateDeviceObjects(), and ImGui_ImplDX10_Shutdown().
ImGui_ImplDX10_NewFrame()
void ImGui_ImplDX10_NewFrame ()
Definition at line 580 of file imgui_impl_dx10.cpp.
References ImGui_ImplDX10_CreateDeviceObjects(), and ImGui_ImplDX10_Data::pFontSampler.
ImGui_ImplDX10_RenderDrawData()
void ImGui_ImplDX10_RenderDrawData (ImDrawData * draw_data)
Definition at line 119 of file imgui_impl_dx10.cpp.
References ImGui_ImplDX10_Data::IndexBufferSize, VERTEX_CONSTANT_BUFFER_DX10::mvp, ImGui_ImplDX10_Data::pd3dDevice, ImGui_ImplDX10_Data::pIB, ImGui_ImplDX10_Data::pVB, ImGui_ImplDX10_Data::pVertexConstantBuffer, and ImGui_ImplDX10_Data::VertexBufferSize.
ImGui_ImplDX10_Shutdown()
void ImGui_ImplDX10_Shutdown ()
Definition at line 565 of file imgui_impl_dx10.cpp.
References ImGui_ImplDX10_InvalidateDeviceObjects(), ImGui_ImplDX10_Data::pd3dDevice, and ImGui_ImplDX10_Data::pFactory.