Atlas::Window Class Reference
#include <Window.h>
Public Member Functions
~Window ()
WindowDecorations const & GetDecorations () const
void init (WindowDecorations *windowDecorations) override
void update () override
bool shouldClose () override
void close () override
Private Attributes
WindowDecorations mDecorations
Detailed Description
Definition at line 6 of file Window.h.
Constructor & Destructor Documentation
~Window()
Atlas::Window::~Window ()
Definition at line 11 of file Window.cpp.
References close().
Member Function Documentation
close()
void Atlas::Window::close () [override], [virtual]
Implements Atlas::IWindow.
Definition at line 56 of file Window.cpp.
Referenced by ~Window().
GetDecorations()
WindowDecorations const & Atlas::Window::GetDecorations () const [inline]
Definition at line 14 of file Window.h.
References mDecorations.
init()
void Atlas::Window::init (WindowDecorations * windowDecorations) [override], [virtual]
Implements Atlas::IWindow.
Definition at line 13 of file Window.cpp.
References ATLAS_ASSET_DIR, Atlas::GetAtlasEngine(), Atlas::FileSystemRegistry::getFile(), Atlas::WindowDecorations::height, Atlas::WindowDecorations::icon, Atlas::Log(), Atlas::LookupConfig(), Atlas::WindowDecorations::targetFPS, Atlas::WindowDecorations::title, and Atlas::WindowDecorations::width.
shouldClose()
bool Atlas::Window::shouldClose () [override], [virtual]
Implements Atlas::IWindow.
Definition at line 51 of file Window.cpp.
update()
void Atlas::Window::update () [override], [virtual]
Implements Atlas::IWindow.
Definition at line 46 of file Window.cpp.
Member Data Documentation
mDecorations
WindowDecorations Atlas::Window::mDecorations [private]
Definition at line 8 of file Window.h.
Referenced by GetDecorations().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/engine/renderer/window/Window.h
C:/Dev/Techstorm-v5/src/engine/renderer/window/Window.cpp