C:/Dev/Techstorm-v5/src/bindings/imgui_impl_sdlrenderer3.cpp File Reference
#include "imgui.h"
#include "imgui_impl_sdlrenderer3.h"
#include <stdint.h>
#include <SDL3/SDL.h>
Classes
struct ImGui_ImplSDLRenderer3_Data
Functions
static ImGui_ImplSDLRenderer3_Data * ImGui_ImplSDLRenderer3_GetBackendData ()
bool ImGui_ImplSDLRenderer3_Init (SDL_Renderer *renderer)
void ImGui_ImplSDLRenderer3_Shutdown ()
static void ImGui_ImplSDLRenderer3_SetupRenderState (SDL_Renderer *renderer)
void ImGui_ImplSDLRenderer3_NewFrame ()
static int SDL_RenderGeometryRaw8BitColor (SDL_Renderer *renderer, ImVector< SDL_FColor > &colors_out, SDL_Texture *texture, const float *xy, int xy_stride, const SDL_Color *color, int color_stride, const float *uv, int uv_stride, int num_vertices, const void *indices, int num_indices, int size_indices)
void ImGui_ImplSDLRenderer3_RenderDrawData (ImDrawData *draw_data, SDL_Renderer *renderer)
bool ImGui_ImplSDLRenderer3_CreateFontsTexture ()
void ImGui_ImplSDLRenderer3_DestroyFontsTexture ()
bool ImGui_ImplSDLRenderer3_CreateDeviceObjects ()
void ImGui_ImplSDLRenderer3_DestroyDeviceObjects ()
Function Documentation
ImGui_ImplSDLRenderer3_CreateDeviceObjects()
bool ImGui_ImplSDLRenderer3_CreateDeviceObjects ()
Definition at line 278 of file imgui_impl_sdlrenderer3.cpp.
References ImGui_ImplSDLRenderer3_CreateFontsTexture().
Referenced by ImGui_ImplSDLRenderer3_NewFrame().
ImGui_ImplSDLRenderer3_CreateFontsTexture()
bool ImGui_ImplSDLRenderer3_CreateFontsTexture ()
Definition at line 238 of file imgui_impl_sdlrenderer3.cpp.
References ImGui_ImplSDLRenderer3_Data::FontTexture, ImGui_ImplSDLRenderer3_GetBackendData(), and ImGui_ImplSDLRenderer3_Data::Renderer.
Referenced by ImGui_ImplSDLRenderer3_CreateDeviceObjects().
ImGui_ImplSDLRenderer3_DestroyDeviceObjects()
void ImGui_ImplSDLRenderer3_DestroyDeviceObjects ()
Definition at line 283 of file imgui_impl_sdlrenderer3.cpp.
References ImGui_ImplSDLRenderer3_DestroyFontsTexture().
Referenced by ImGui_ImplSDLRenderer3_Shutdown().
ImGui_ImplSDLRenderer3_DestroyFontsTexture()
void ImGui_ImplSDLRenderer3_DestroyFontsTexture ()
Definition at line 266 of file imgui_impl_sdlrenderer3.cpp.
References ImGui_ImplSDLRenderer3_Data::FontTexture, and ImGui_ImplSDLRenderer3_GetBackendData().
Referenced by ImGui_ImplSDLRenderer3_DestroyDeviceObjects().
ImGui_ImplSDLRenderer3_GetBackendData()
static ImGui_ImplSDLRenderer3_Data * ImGui_ImplSDLRenderer3_GetBackendData () [static]
Definition at line 61 of file imgui_impl_sdlrenderer3.cpp.
Referenced by ImGui_ImplSDLRenderer3_CreateFontsTexture(), ImGui_ImplSDLRenderer3_DestroyFontsTexture(), ImGui_ImplSDLRenderer3_NewFrame(), ImGui_ImplSDLRenderer3_RenderDrawData(), and ImGui_ImplSDLRenderer3_Shutdown().
ImGui_ImplSDLRenderer3_Init()
bool ImGui_ImplSDLRenderer3_Init (SDL_Renderer * renderer)
Definition at line 67 of file imgui_impl_sdlrenderer3.cpp.
References ImGui_ImplSDLRenderer3_Data::Renderer.
ImGui_ImplSDLRenderer3_NewFrame()
void ImGui_ImplSDLRenderer3_NewFrame ()
Definition at line 107 of file imgui_impl_sdlrenderer3.cpp.
References ImGui_ImplSDLRenderer3_Data::FontTexture, ImGui_ImplSDLRenderer3_CreateDeviceObjects(), and ImGui_ImplSDLRenderer3_GetBackendData().
ImGui_ImplSDLRenderer3_RenderDrawData()
void ImGui_ImplSDLRenderer3_RenderDrawData (ImDrawData * draw_data, SDL_Renderer * renderer)
Definition at line 134 of file imgui_impl_sdlrenderer3.cpp.
References ImGui_ImplSDLRenderer3_Data::ColorBuffer, ImGui_ImplSDLRenderer3_GetBackendData(), ImGui_ImplSDLRenderer3_SetupRenderState(), ImGui_ImplSDLRenderer3_RenderState::Renderer, and SDL_RenderGeometryRaw8BitColor().
ImGui_ImplSDLRenderer3_SetupRenderState()
static void ImGui_ImplSDLRenderer3_SetupRenderState (SDL_Renderer * renderer) [static]
Definition at line 99 of file imgui_impl_sdlrenderer3.cpp.
Referenced by ImGui_ImplSDLRenderer3_RenderDrawData().
ImGui_ImplSDLRenderer3_Shutdown()
void ImGui_ImplSDLRenderer3_Shutdown ()
Definition at line 85 of file imgui_impl_sdlrenderer3.cpp.
References ImGui_ImplSDLRenderer3_DestroyDeviceObjects(), and ImGui_ImplSDLRenderer3_GetBackendData().
SDL_RenderGeometryRaw8BitColor()
static int SDL_RenderGeometryRaw8BitColor (SDL_Renderer * renderer, ImVector< SDL_FColor > & colors_out, SDL_Texture * texture, const float * xy, int xy_stride, const SDL_Color * color, int color_stride, const float * uv, int uv_stride, int num_vertices, const void * indices, int num_indices, int size_indices) [static]
Definition at line 117 of file imgui_impl_sdlrenderer3.cpp.
Referenced by ImGui_ImplSDLRenderer3_RenderDrawData().