Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER > Class Template Reference
#include <RenderCommon.h>
Public Member Functions
AVulkanCompositeHandleWrapper (T_WRAPS handle, T_VKB_EQUIVALENT vkbHandle)
AVulkanCompositeHandleWrapper (T_VKB_EQUIVALENT_BUILDER builder)
AVulkanCompositeHandleWrapper ()=default
virtual ~AVulkanCompositeHandleWrapper () override=default
virtual bool isValid () const override
T_VKB_EQUIVALENT & getVkbHandle ()
T_VKB_EQUIVALENT * getVkbHandlePtr ()
T_VKB_EQUIVALENT * safeGetVkbHandlePtr ()
explicit (false) operator const T_VKB_EQUIVALENT &() const
T_VKB_EQUIVALENT * operator-> ()
Public Member Functions inherited from Atlas::AVulkanHandleWrapper< T_WRAPS >
explicit (false) AVulkanHandleWrapper(T_WRAPS &handle)
AVulkanHandleWrapper ()=default
virtual ~AVulkanHandleWrapper () override=default
virtual bool hasValidHandle () const
T_WRAPS getHandle () const
explicit (false) operator const T_WRAPS &() const
explicit (false) operator T_WRAPS &()
explicit (false) operator bool() const
Public Member Functions inherited from Atlas::InitializableAndValidatable
InitializableAndValidatable (bool bIsInit, bool bIsValid)
InitializableAndValidatable ()=default
Public Member Functions inherited from Atlas::Initializable
ATLAS_EXPLICIT Initializable (bool bIsInit)
Initializable ()=default
virtual ~Initializable ()=default
virtual bool isInit () const
Public Member Functions inherited from Atlas::Validatable
ATLAS_EXPLICIT Validatable (bool bIsValid)
Validatable ()=default
virtual ~Validatable ()=default
virtual ATLAS_IMPLICIT operator bool () const
Protected Member Functions
void setVkbHandle (T_VKB_EQUIVALENT vkbHandle)
bool hasValidVkbHandle () const
Protected Member Functions inherited from Atlas::AVulkanHandleWrapper< T_WRAPS >
void setHandle (T_WRAPS handle)
T_WRAPS & getHandleRef ()
Protected Member Functions inherited from Atlas::Initializable
bool & getInternalInitValue ()
virtual void setInitState (bool bNewInitState)
virtual void setInit ()
virtual void setNotInit ()
Protected Member Functions inherited from Atlas::Validatable
bool & getInternalValidityValue ()
virtual void setValidity (bool bIsValid)
virtual void setValid ()
virtual void setInvalid ()
Private Attributes
T_VKB_EQUIVALENT mVkbHandle
Detailed Description
template<VulkanHandle T_WRAPS, typename T_VKB_EQUIVALENT, typename T_VKB_EQUIVALENT_BUILDER>
class Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >
Definition at line 195 of file RenderCommon.h.
Constructor & Destructor Documentation
AVulkanCompositeHandleWrapper() [1/3]
template<VulkanHandle T_WRAPS, typename T_VKB_EQUIVALENT , typename T_VKB_EQUIVALENT_BUILDER >
Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::AVulkanCompositeHandleWrapper (T_WRAPS handle, T_VKB_EQUIVALENT vkbHandle) [inline]
Definition at line 212 of file RenderCommon.h.
AVulkanCompositeHandleWrapper() [2/3]
template<VulkanHandle T_WRAPS, typename T_VKB_EQUIVALENT , typename T_VKB_EQUIVALENT_BUILDER >
Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::AVulkanCompositeHandleWrapper (T_VKB_EQUIVALENT_BUILDER builder) [inline], [explicit]
Definition at line 218 of file RenderCommon.h.
AVulkanCompositeHandleWrapper() [3/3]
template<VulkanHandle T_WRAPS, typename T_VKB_EQUIVALENT , typename T_VKB_EQUIVALENT_BUILDER >
Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::AVulkanCompositeHandleWrapper () [default]
~AVulkanCompositeHandleWrapper()
template<VulkanHandle T_WRAPS, typename T_VKB_EQUIVALENT , typename T_VKB_EQUIVALENT_BUILDER >
virtual Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::~AVulkanCompositeHandleWrapper () [override], [virtual], [default]
Member Function Documentation
explicit()
template<VulkanHandle T_WRAPS, typename T_VKB_EQUIVALENT , typename T_VKB_EQUIVALENT_BUILDER >
Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::explicit (false) const & [inline]
Definition at line 245 of file RenderCommon.h.
References Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::getVkbHandle().
getVkbHandle()
template<VulkanHandle T_WRAPS, typename T_VKB_EQUIVALENT , typename T_VKB_EQUIVALENT_BUILDER >
T_VKB_EQUIVALENT & Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::getVkbHandle () [inline]
Definition at line 229 of file RenderCommon.h.
References Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::mVkbHandle.
Referenced by Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::explicit().
getVkbHandlePtr()
template<VulkanHandle T_WRAPS, typename T_VKB_EQUIVALENT , typename T_VKB_EQUIVALENT_BUILDER >
T_VKB_EQUIVALENT * Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::getVkbHandlePtr () [inline]
Definition at line 233 of file RenderCommon.h.
References Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::mVkbHandle.
Referenced by Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::safeGetVkbHandlePtr().
hasValidVkbHandle()
template<VulkanHandle T_WRAPS, typename T_VKB_EQUIVALENT , typename T_VKB_EQUIVALENT_BUILDER >
bool Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::hasValidVkbHandle () const [inline], [protected]
Definition at line 205 of file RenderCommon.h.
References Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::mVkbHandle.
Referenced by Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::isValid().
isValid()
template<VulkanHandle T_WRAPS, typename T_VKB_EQUIVALENT , typename T_VKB_EQUIVALENT_BUILDER >
virtual bool Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::isValid () const [inline], [override], [virtual]
Reimplemented from Atlas::AVulkanHandleWrapper< T_WRAPS >.
Reimplemented in Atlas::PhysicalDevice.
Definition at line 225 of file RenderCommon.h.
References Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::hasValidVkbHandle(), and Atlas::AVulkanHandleWrapper< T_WRAPS >::isValid().
operator->()
template<VulkanHandle T_WRAPS, typename T_VKB_EQUIVALENT , typename T_VKB_EQUIVALENT_BUILDER >
T_VKB_EQUIVALENT * Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::operator-> () [inline]
Definition at line 247 of file RenderCommon.h.
References Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::safeGetVkbHandlePtr().
safeGetVkbHandlePtr()
template<VulkanHandle T_WRAPS, typename T_VKB_EQUIVALENT , typename T_VKB_EQUIVALENT_BUILDER >
T_VKB_EQUIVALENT * Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::safeGetVkbHandlePtr () [inline]
Definition at line 237 of file RenderCommon.h.
References ATLAS_ASSERT, and Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::getVkbHandlePtr().
Referenced by Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::operator->().
setVkbHandle()
template<VulkanHandle T_WRAPS, typename T_VKB_EQUIVALENT , typename T_VKB_EQUIVALENT_BUILDER >
void Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::setVkbHandle (T_VKB_EQUIVALENT vkbHandle) [inline], [protected]
Definition at line 203 of file RenderCommon.h.
References Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::mVkbHandle.
Member Data Documentation
mVkbHandle
template<VulkanHandle T_WRAPS, typename T_VKB_EQUIVALENT , typename T_VKB_EQUIVALENT_BUILDER >
T_VKB_EQUIVALENT Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::mVkbHandle [private]
Definition at line 197 of file RenderCommon.h.
Referenced by Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::getVkbHandle(), Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::getVkbHandlePtr(), Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::hasValidVkbHandle(), and Atlas::AVulkanCompositeHandleWrapper< T_WRAPS, T_VKB_EQUIVALENT, T_VKB_EQUIVALENT_BUILDER >::setVkbHandle().
The documentation for this class was generated from the following file:
C:/Dev/Techstorm-v5/src/engine/graphics/RenderCommon.h