Atlas::Initializable Class Reference
#include <Common.h>
Public Member Functions
ATLAS_EXPLICIT Initializable (bool bIsInit)
Initializable ()=default
virtual ~Initializable ()=default
virtual bool isInit () const
Protected Member Functions
bool & getInternalInitValue ()
virtual void setInitState (bool bNewInitState)
virtual void setInit ()
virtual void setNotInit ()
Private Attributes
bool mbIsInit { false }
Detailed Description
Definition at line 296 of file Common.h.
Constructor & Destructor Documentation
Initializable() [1/2]
ATLAS_EXPLICIT Atlas::Initializable::Initializable (bool bIsInit) [inline]
Definition at line 319 of file Common.h.
Initializable() [2/2]
Atlas::Initializable::Initializable () [default]
~Initializable()
virtual Atlas::Initializable::~Initializable () [virtual], [default]
Member Function Documentation
getInternalInitValue()
bool & Atlas::Initializable::getInternalInitValue () [inline], [protected]
Definition at line 302 of file Common.h.
References mbIsInit.
isInit()
virtual bool Atlas::Initializable::isInit () const [inline], [virtual]
Definition at line 325 of file Common.h.
References mbIsInit.
Referenced by Atlas::InitializableAndValidatable::isValid().
setInit()
virtual void Atlas::Initializable::setInit () [inline], [protected], [virtual]
Definition at line 310 of file Common.h.
References setInitState().
Referenced by Atlas::HandleWrapperBase< T_WRAPS >::setHandle().
setInitState()
virtual void Atlas::Initializable::setInitState (bool bNewInitState) [inline], [protected], [virtual]
Definition at line 306 of file Common.h.
References mbIsInit.
Referenced by setInit(), and setNotInit().
setNotInit()
virtual void Atlas::Initializable::setNotInit () [inline], [protected], [virtual]
Definition at line 314 of file Common.h.
References setInitState().
Referenced by Atlas::SurfaceBase< T_SURFACE_HANDLE >::destroySurface(), and Atlas::HandleWrapperBase< T_WRAPS >::setHandle().
Member Data Documentation
mbIsInit
bool Atlas::Initializable::mbIsInit { false } [private]
Definition at line 299 of file Common.h.
Referenced by getInternalInitValue(), isInit(), and setInitState().
The documentation for this class was generated from the following file:
C:/Dev/Techstorm-v5/src/engine/core/Common.h