C:/Dev/Techstorm-v5/src/engine/modding/add_on/scriptstdstring/scriptstdstring.h File Reference
#include <angelscript.h>
#include <string>
Macros
#define AS_USE_STLNAMES 0
#define AS_USE_ACCESSORS 0
#define AS_NO_IMPL_OPS_WITH_STRING_AND_PRIMITIVE 0
Functions
BEGIN_AS_NAMESPACE void RegisterStdString (asIScriptEngine *engine)
void RegisterStdStringUtils (asIScriptEngine *engine)
Macro Definition Documentation
AS_NO_IMPL_OPS_WITH_STRING_AND_PRIMITIVE
#define AS_NO_IMPL_OPS_WITH_STRING_AND_PRIMITIVE 0
Definition at line 43 of file scriptstdstring.h.
AS_USE_ACCESSORS
#define AS_USE_ACCESSORS 0
Definition at line 38 of file scriptstdstring.h.
AS_USE_STLNAMES
#define AS_USE_STLNAMES 0
Definition at line 32 of file scriptstdstring.h.
Function Documentation
RegisterStdString()
BEGIN_AS_NAMESPACE void RegisterStdString (asIScriptEngine * engine)
Definition at line 1367 of file scriptstdstring.cpp.
References RegisterStdString_Generic(), and RegisterStdString_Native().
Referenced by ConfigureEngine().
RegisterStdStringUtils()
void RegisterStdStringUtils (asIScriptEngine * engine)
Definition at line 114 of file scriptstdstring_utils.cpp.