C:/Dev/Techstorm-v5/src/application/add_on/scriptbuilder/scriptbuilder.cpp File Reference
#include "scriptbuilder.h"
#include <vector>
#include <assert.h>
#include <stdio.h>
Functions
static BEGIN_AS_NAMESPACE string GetCurrentDir ()
static string GetAbsolutePath (const string &path)
Function Documentation
GetAbsolutePath()
string GetAbsolutePath (const string & path) [static]
Definition at line 1119 of file scriptbuilder.cpp.
References GetCurrentDir().
Referenced by CScriptBuilder::AddSectionFromFile(), and CScriptBuilder::LoadScriptSection().
GetCurrentDir()
string GetCurrentDir () [static]
Definition at line 1157 of file scriptbuilder.cpp.
Referenced by GetAbsolutePath().