C:/Dev/Techstorm-v5/src/application/add_on/scriptmath/scriptmathcomplex.cpp File Reference
#include <assert.h>
#include <string.h>
#include <new>
#include <math.h>
#include "scriptmathcomplex.h"
Functions
static void ComplexDefaultConstructor (Complex *self)
static void ComplexCopyConstructor (const Complex &other, Complex *self)
static void ComplexConvConstructor (float r, Complex *self)
static void ComplexInitConstructor (float r, float i, Complex *self)
static void ComplexListConstructor (float *list, Complex *self)
static void RegisterScriptMathComplex_Native (asIScriptEngine *engine)
void RegisterScriptMathComplex (asIScriptEngine *engine)
Function Documentation
ComplexConvConstructor()
static void ComplexConvConstructor (float r, Complex * self) [static]
Definition at line 145 of file scriptmathcomplex.cpp.
Referenced by RegisterScriptMathComplex_Native().
ComplexCopyConstructor()
static void ComplexCopyConstructor (const Complex & other, Complex * self) [static]
Definition at line 140 of file scriptmathcomplex.cpp.
Referenced by RegisterScriptMathComplex_Native().
ComplexDefaultConstructor()
static void ComplexDefaultConstructor (Complex * self) [static]
Definition at line 135 of file scriptmathcomplex.cpp.
Referenced by RegisterScriptMathComplex_Native().
ComplexInitConstructor()
static void ComplexInitConstructor (float r, float i, Complex * self) [static]
Definition at line 150 of file scriptmathcomplex.cpp.
Referenced by RegisterScriptMathComplex_Native().
ComplexListConstructor()
static void ComplexListConstructor (float * list, Complex * self) [static]
Definition at line 155 of file scriptmathcomplex.cpp.
Referenced by RegisterScriptMathComplex_Native().
RegisterScriptMathComplex()
void RegisterScriptMathComplex (asIScriptEngine * engine)
Definition at line 208 of file scriptmathcomplex.cpp.
References RegisterScriptMathComplex_Native().
RegisterScriptMathComplex_Native()
static void RegisterScriptMathComplex_Native (asIScriptEngine * engine) [static]
Definition at line 164 of file scriptmathcomplex.cpp.
References ComplexConvConstructor(), ComplexCopyConstructor(), ComplexDefaultConstructor(), ComplexInitConstructor(), and ComplexListConstructor().
Referenced by RegisterScriptMathComplex().