CDebugger Class Reference
#include <debugger.h>
Classes
struct BreakPoint
Public Types
typedef std::string(* ToStringCallback) (void *obj, int expandMembersLevel, CDebugger *dbg)
typedef std::string(* ToStringCallback) (void *obj, int expandMembersLevel, CDebugger *dbg)
Public Member Functions
CDebugger ()
virtual ~CDebugger ()
virtual void RegisterToStringCallback (const asITypeInfo *ti, ToStringCallback callback)
virtual void TakeCommands (asIScriptContext *ctx)
virtual void Output (const std::string &str)
virtual void LineCallback (asIScriptContext *ctx)
virtual void PrintHelp ()
virtual void AddFileBreakPoint (const std::string &file, int lineNbr)
virtual void AddFuncBreakPoint (const std::string &func)
virtual void ListBreakPoints ()
virtual void ListLocalVariables (asIScriptContext *ctx)
virtual void ListGlobalVariables (asIScriptContext *ctx)
virtual void ListMemberProperties (asIScriptContext *ctx)
virtual void ListStatistics (asIScriptContext *ctx)
virtual void PrintCallstack (asIScriptContext *ctx)
virtual void PrintValue (const std::string &expr, asIScriptContext *ctx)
virtual bool InterpretCommand (const std::string &cmd, asIScriptContext *ctx)
virtual bool CheckBreakPoint (asIScriptContext *ctx)
virtual std::string ToString (void *value, asUINT typeId, int expandMembersLevel, asIScriptEngine *engine)
virtual void SetEngine (asIScriptEngine *engine)
virtual asIScriptEngine * GetEngine ()
CDebugger ()
virtual ~CDebugger ()
virtual void RegisterToStringCallback (const asITypeInfo *ti, ToStringCallback callback)
virtual void TakeCommands (asIScriptContext *ctx)
virtual void Output (const std::string &str)
virtual void LineCallback (asIScriptContext *ctx)
virtual void PrintHelp ()
virtual void AddFileBreakPoint (const std::string &file, int lineNbr)
virtual void AddFuncBreakPoint (const std::string &func)
virtual void ListBreakPoints ()
virtual void ListLocalVariables (asIScriptContext *ctx)
virtual void ListGlobalVariables (asIScriptContext *ctx)
virtual void ListMemberProperties (asIScriptContext *ctx)
virtual void ListStatistics (asIScriptContext *ctx)
virtual void PrintCallstack (asIScriptContext *ctx)
virtual void PrintValue (const std::string &expr, asIScriptContext *ctx)
virtual bool InterpretCommand (const std::string &cmd, asIScriptContext *ctx)
virtual bool CheckBreakPoint (asIScriptContext *ctx)
virtual std::string ToString (void *value, asUINT typeId, int expandMembersLevel, asIScriptEngine *engine)
virtual void SetEngine (asIScriptEngine *engine)
virtual asIScriptEngine * GetEngine ()
Protected Types
enum DebugAction {
CONTINUE
, STEP_INTO
, STEP_OVER
, STEP_OUT
,
CONTINUE
, STEP_INTO
, STEP_OVER
, STEP_OUT
 }
enum DebugAction {
CONTINUE
, STEP_INTO
, STEP_OVER
, STEP_OUT
,
CONTINUE
, STEP_INTO
, STEP_OVER
, STEP_OUT
 }
Protected Attributes
DebugAction m_action
asUINT m_lastCommandAtStackLevel
asIScriptFunction * m_lastFunction
std::vector< BreakPoint > m_breakPoints
asIScriptEngine * m_engine
std::map< const asITypeInfo *, ToStringCallback > m_toStringCallbacks
Detailed Description
Definition at line 15 of file debugger.h.
Member Typedef Documentation
ToStringCallback [1/2]
typedef std::string(* CDebugger::ToStringCallback) (void *obj, int expandMembersLevel, CDebugger *dbg)
Definition at line 25 of file debugger.h.
ToStringCallback [2/2]
typedef std::string(* CDebugger::ToStringCallback) (void *obj, int expandMembersLevel, CDebugger *dbg)
Definition at line 25 of file debugger.h.
Member Enumeration Documentation
DebugAction [1/2]
enum CDebugger::DebugAction [protected]
Enumerator
CONTINUE
STEP_INTO
STEP_OVER
STEP_OUT
CONTINUE
STEP_INTO
STEP_OVER
STEP_OUT
Definition at line 58 of file debugger.h.
DebugAction [2/2]
enum CDebugger::DebugAction [protected]
Enumerator
CONTINUE
STEP_INTO
STEP_OVER
STEP_OUT
CONTINUE
STEP_INTO
STEP_OVER
STEP_OUT
Definition at line 58 of file debugger.h.
Constructor & Destructor Documentation
CDebugger() [1/2]
BEGIN_AS_NAMESPACE CDebugger::CDebugger ()
Definition at line 12 of file debugger.cpp.
References CONTINUE, m_action, m_engine, and m_lastFunction.
~CDebugger() [1/2]
CDebugger::~CDebugger () [virtual]
Definition at line 19 of file debugger.cpp.
References SetEngine().
CDebugger() [2/2]
CDebugger::CDebugger ()
~CDebugger() [2/2]
virtual CDebugger::~CDebugger () [virtual]
Member Function Documentation
AddFileBreakPoint() [1/2]
void CDebugger::AddFileBreakPoint (const std::string & file, int lineNbr) [virtual]
Definition at line 802 of file debugger.cpp.
References m_breakPoints, and Output().
Referenced by InterpretCommand().
AddFileBreakPoint() [2/2]
virtual void CDebugger::AddFileBreakPoint (const std::string & file, int lineNbr) [virtual]
AddFuncBreakPoint() [1/2]
void CDebugger::AddFuncBreakPoint (const std::string & func) [virtual]
Definition at line 787 of file debugger.cpp.
References m_breakPoints, and Output().
Referenced by InterpretCommand().
AddFuncBreakPoint() [2/2]
virtual void CDebugger::AddFuncBreakPoint (const std::string & func) [virtual]
CheckBreakPoint() [1/2]
bool CDebugger::CheckBreakPoint (asIScriptContext * ctx) [virtual]
Definition at line 218 of file debugger.cpp.
References m_breakPoints, m_lastFunction, and Output().
Referenced by LineCallback().
CheckBreakPoint() [2/2]
virtual bool CDebugger::CheckBreakPoint (asIScriptContext * ctx) [virtual]
GetEngine() [1/2]
asIScriptEngine * CDebugger::GetEngine () [virtual]
Definition at line 858 of file debugger.cpp.
References m_engine.
GetEngine() [2/2]
virtual asIScriptEngine * CDebugger::GetEngine () [virtual]
InterpretCommand() [1/2]
bool CDebugger::InterpretCommand (const std::string & cmd, asIScriptContext * ctx) [virtual]
Definition at line 316 of file debugger.cpp.
References AddFileBreakPoint(), AddFuncBreakPoint(), CONTINUE, ListBreakPoints(), ListGlobalVariables(), ListLocalVariables(), ListMemberProperties(), ListStatistics(), m_action, m_breakPoints, m_lastCommandAtStackLevel, Output(), PrintCallstack(), PrintHelp(), PrintValue(), STEP_INTO, STEP_OUT, and STEP_OVER.
Referenced by TakeCommands().
InterpretCommand() [2/2]
virtual bool CDebugger::InterpretCommand (const std::string & cmd, asIScriptContext * ctx) [virtual]
LineCallback() [1/2]
void CDebugger::LineCallback (asIScriptContext * ctx) [virtual]
Definition at line 166 of file debugger.cpp.
References CheckBreakPoint(), CONTINUE, m_action, m_lastCommandAtStackLevel, Output(), STEP_INTO, STEP_OUT, STEP_OVER, and TakeCommands().
LineCallback() [2/2]
virtual void CDebugger::LineCallback (asIScriptContext * ctx) [virtual]
ListBreakPoints() [1/2]
void CDebugger::ListBreakPoints () [virtual]
Definition at line 653 of file debugger.cpp.
References m_breakPoints, and Output().
Referenced by InterpretCommand().
ListBreakPoints() [2/2]
virtual void CDebugger::ListBreakPoints () [virtual]
ListGlobalVariables() [1/2]
void CDebugger::ListGlobalVariables (asIScriptContext * ctx) [virtual]
Definition at line 717 of file debugger.cpp.
References Output(), and ToString().
Referenced by InterpretCommand().
ListGlobalVariables() [2/2]
virtual void CDebugger::ListGlobalVariables (asIScriptContext * ctx) [virtual]
ListLocalVariables() [1/2]
void CDebugger::ListLocalVariables (asIScriptContext * ctx) [virtual]
Definition at line 684 of file debugger.cpp.
References Output(), and ToString().
Referenced by InterpretCommand().
ListLocalVariables() [2/2]
virtual void CDebugger::ListLocalVariables (asIScriptContext * ctx) [virtual]
ListMemberProperties() [1/2]
void CDebugger::ListMemberProperties (asIScriptContext * ctx) [virtual]
Definition at line 665 of file debugger.cpp.
References Output(), and ToString().
Referenced by InterpretCommand().
ListMemberProperties() [2/2]
virtual void CDebugger::ListMemberProperties (asIScriptContext * ctx) [virtual]
ListStatistics() [1/2]
void CDebugger::ListStatistics (asIScriptContext * ctx) [virtual]
Definition at line 744 of file debugger.cpp.
References Output().
Referenced by InterpretCommand().
ListStatistics() [2/2]
virtual void CDebugger::ListStatistics (asIScriptContext * ctx) [virtual]
Output() [1/2]
void CDebugger::Output (const std::string & str) [virtual]
Definition at line 840 of file debugger.cpp.
Referenced by AddFileBreakPoint(), AddFuncBreakPoint(), CheckBreakPoint(), InterpretCommand(), LineCallback(), ListBreakPoints(), ListGlobalVariables(), ListLocalVariables(), ListMemberProperties(), ListStatistics(), PrintCallstack(), PrintHelp(), PrintValue(), and TakeCommands().
Output() [2/2]
virtual void CDebugger::Output (const std::string & str) [virtual]
PrintCallstack() [1/2]
void CDebugger::PrintCallstack (asIScriptContext * ctx) [virtual]
Definition at line 768 of file debugger.cpp.
References Output().
Referenced by InterpretCommand().
PrintCallstack() [2/2]
virtual void CDebugger::PrintCallstack (asIScriptContext * ctx) [virtual]
PrintHelp() [1/2]
void CDebugger::PrintHelp () [virtual]
Definition at line 825 of file debugger.cpp.
References Output().
Referenced by InterpretCommand().
PrintHelp() [2/2]
virtual void CDebugger::PrintHelp () [virtual]
PrintValue() [1/2]
void CDebugger::PrintValue (const std::string & expr, asIScriptContext * ctx) [virtual]
Definition at line 501 of file debugger.cpp.
References Output(), and ToString().
Referenced by InterpretCommand().
PrintValue() [2/2]
virtual void CDebugger::PrintValue (const std::string & expr, asIScriptContext * ctx) [virtual]
RegisterToStringCallback() [1/2]
void CDebugger::RegisterToStringCallback (const asITypeInfo * ti, ToStringCallback callback) [virtual]
Definition at line 160 of file debugger.cpp.
References m_toStringCallbacks.
RegisterToStringCallback() [2/2]
virtual void CDebugger::RegisterToStringCallback (const asITypeInfo * ti, ToStringCallback callback) [virtual]
SetEngine() [1/2]
void CDebugger::SetEngine (asIScriptEngine * engine) [virtual]
Definition at line 846 of file debugger.cpp.
References m_engine.
Referenced by ~CDebugger().
SetEngine() [2/2]
virtual void CDebugger::SetEngine (asIScriptEngine * engine) [virtual]
TakeCommands() [1/2]
void CDebugger::TakeCommands (asIScriptContext * ctx) [virtual]
Definition at line 302 of file debugger.cpp.
References InterpretCommand(), and Output().
Referenced by LineCallback().
TakeCommands() [2/2]
virtual void CDebugger::TakeCommands (asIScriptContext * ctx) [virtual]
ToString() [1/2]
string CDebugger::ToString (void * value, asUINT typeId, int expandMembersLevel, asIScriptEngine * engine) [virtual]
Definition at line 24 of file debugger.cpp.
References m_engine, m_toStringCallbacks, and ToString().
Referenced by ListGlobalVariables(), ListLocalVariables(), ListMemberProperties(), PrintValue(), and ToString().
ToString() [2/2]
virtual std::string CDebugger::ToString (void * value, asUINT typeId, int expandMembersLevel, asIScriptEngine * engine) [virtual]
Member Data Documentation
m_action
DebugAction CDebugger::m_action [protected]
Definition at line 65 of file debugger.h.
Referenced by CDebugger(), InterpretCommand(), and LineCallback().
m_breakPoints
std::vector< BreakPoint > CDebugger::m_breakPoints [protected]
Definition at line 77 of file debugger.h.
Referenced by AddFileBreakPoint(), AddFuncBreakPoint(), CheckBreakPoint(), InterpretCommand(), and ListBreakPoints().
m_engine
asIScriptEngine * CDebugger::m_engine [protected]
Definition at line 79 of file debugger.h.
Referenced by CDebugger(), GetEngine(), SetEngine(), and ToString().
m_lastCommandAtStackLevel
asUINT CDebugger::m_lastCommandAtStackLevel [protected]
Definition at line 66 of file debugger.h.
Referenced by InterpretCommand(), and LineCallback().
m_lastFunction
asIScriptFunction * CDebugger::m_lastFunction [protected]
Definition at line 67 of file debugger.h.
Referenced by CDebugger(), and CheckBreakPoint().
m_toStringCallbacks
std::map< const asITypeInfo *, ToStringCallback > CDebugger::m_toStringCallbacks [protected]
Definition at line 82 of file debugger.h.
Referenced by RegisterToStringCallback(), and ToString().
The documentation for this class was generated from the following files:
C:/Dev/Techstorm-v5/src/application/add_on/debugger/debugger.h
C:/Dev/Techstorm-v5/src/engine/modding/add_on/debugger/debugger.h
C:/Dev/Techstorm-v5/src/application/add_on/debugger/debugger.cpp
C:/Dev/Techstorm-v5/src/engine/modding/add_on/debugger/debugger.cpp