Atlas::GameThreadScheduler Class Reference
Scheduler for running tasks on separate threads. It will take given tasks, and distribute them across threads.
#include <GameThreadScheduler.h>
Public Member Functions
GameThreadScheduler (const GameThreadScheduler &)=delete
GameThreadScheduler ()=default
Default constructor.
GameThreadScheduler (uint8_t numThreads, bool callInit=true)
Initializes this class with the specified amount of threads.
~GameThreadScheduler ()
The default deconstructor that joins all threads (if they are joinable) and cleans up everything.
void init (uint8_t numThreads)
Initializes this class with the specified amount of threads.
template<typename Func , typename... Args>
auto schedule (Func &&func, Args &&... args) -> std::future< std::invoke_result_t< Func, Args... > >
Schedules a task to be executed. The templates are not really necessary, see this function's details section in the documentation for more information.
void joinAll ()
Joins all worker threads in this scheduler if they are joinable.
bool isRunning () const
Checks if this scheduler is running. The outcome of this function is based on the value of the mIsRunning member variable and does not imply that there are tasks to be done, just that the scheduler is running and initialized.
uint8_t getThreadCount () const
Returns the number of worker threads in this scheduler.
GameThreadScheduler & operator= (const GameThreadScheduler &)=delete
Private Types
using Task = std::function< void()>
A task to be executed.
Private Member Functions
bool isTaskQueueEmpty () const
Returns whether or not the task queue is empty.
void setStatus (EGameThreadSchedulerStatus status)
Private Attributes
EGameThreadSchedulerStatus mStatus = EGameThreadSchedulerStatus::Unknown
The current status of the scheduler.
uint8_t mThreadCount
Number of threads in this scheduler.
std::vector< std::thread > mWorkersVector
A vector that contains all the worker threads.
std::queue< Task > mTaskQueue
A queue of tasks assigned to this scheduler. All tasks are executed in the order they are added to the queue. Additionally, the threads get their tasks from this queue.
std::mutex mQueueMutex
The mutex that is used to the tasks queue to be thread-safe.
std::condition_variable mWorkAvailableConditional
Signals to workers that there are tasks available in the task queue.
std::atomic< bool > mIsRunning
Whether or not this scheduler is running. This does not necessarily mean that there are tasks being executed or in the queue.
Detailed Description
Scheduler for running tasks on separate threads. It will take given tasks, and distribute them across threads.
Precondition
Atlas must have multi-threading enabled for this to even be used.
Note
Everything is thread-safe.
This class CANNOT be copied.
@important This class does not ensure the proper order of execution of tasks, so be careful when using it.
Since
v0.0.10
Todo
Todo Refactor this so that it works with Atlas::GameThread instead of std::thread. See mWorkersVector for the todo comment
Definition at line 92 of file GameThreadScheduler.h.
Member Typedef Documentation
Task
using Atlas::GameThreadScheduler::Task = std::function<void()> [private]
A task to be executed.
Since
v0.0.10
Definition at line 99 of file GameThreadScheduler.h.
Constructor & Destructor Documentation
GameThreadScheduler() [1/3]
Atlas::GameThreadScheduler::GameThreadScheduler (const GameThreadScheduler &) [delete]
GameThreadScheduler() [2/3]
Atlas::GameThreadScheduler::GameThreadScheduler () [default]
Default constructor.
Note
This constructor is simply defined by = default because there is nothing that can be done without knowing how many threads to create.
Since
v0.0.10
GameThreadScheduler() [3/3]
Atlas::GameThreadScheduler::GameThreadScheduler (uint8_t numThreads, bool callInit = true) [inline], [explicit]
Initializes this class with the specified amount of threads.
Parameters
numThreads How many worker threads should be made?
Todo
Todo Call the init function here. Also, add a boolean parameter that the user can use to define whether or not they want to call said function
Since
v0.0.10
Definition at line 194 of file GameThreadScheduler.h.
References init().
~GameThreadScheduler()
Atlas::GameThreadScheduler::~GameThreadScheduler () [inline]
The default deconstructor that joins all threads (if they are joinable) and cleans up everything.
Todo
Todo Check to see if this completes the rest of the tasks before shutting down. I suspect that it will not complete the tasks in the queue, and this is something that must be fixed if it is true.
Since
v0.0.10
Definition at line 208 of file GameThreadScheduler.h.
References joinAll(), mIsRunning, mQueueMutex, and mWorkAvailableConditional.
Member Function Documentation
getThreadCount()
uint8_t Atlas::GameThreadScheduler::getThreadCount () const [inline]
Returns the number of worker threads in this scheduler.
Returns
An 8-bit unsigned integer representing the number of worker threads that this scheduler created on initialization.
Since
v0.0.10
Definition at line 374 of file GameThreadScheduler.h.
References mThreadCount.
init()
void Atlas::GameThreadScheduler::init (uint8_t numThreads) [inline]
Initializes this class with the specified amount of threads.
Note
This must be called before this class can be used.
Parameters
numThreads The amount of worker threads to create.
Since
v0.0.10
Definition at line 228 of file GameThreadScheduler.h.
References Atlas::Initializing, isTaskQueueEmpty(), mIsRunning, mQueueMutex, mTaskQueue, mWorkAvailableConditional, mWorkersVector, Atlas::Running, and setStatus().
Referenced by GameThreadScheduler().
isRunning()
bool Atlas::GameThreadScheduler::isRunning () const [inline]
Checks if this scheduler is running. The outcome of this function is based on the value of the mIsRunning member variable and does not imply that there are tasks to be done, just that the scheduler is running and initialized.
Returns
true if the scheduler is running, false otherwise
Since
v0.0.10
Definition at line 363 of file GameThreadScheduler.h.
References mIsRunning.
isTaskQueueEmpty()
bool Atlas::GameThreadScheduler::isTaskQueueEmpty () const [inline], [private]
Returns whether or not the task queue is empty.
Since
v0.0.10
Definition at line 163 of file GameThreadScheduler.h.
References mTaskQueue.
Referenced by init().
joinAll()
void Atlas::GameThreadScheduler::joinAll () [inline]
Joins all worker threads in this scheduler if they are joinable.
Precondition
Atlas must have multi-threading enabled and this scheduler must have been initialized
Since
v0.0.10
Definition at line 347 of file GameThreadScheduler.h.
References mWorkersVector.
Referenced by ~GameThreadScheduler().
operator=()
GameThreadScheduler & Atlas::GameThreadScheduler::operator= (const GameThreadScheduler &) [delete]
schedule()
template<typename Func , typename... Args>
auto Atlas::GameThreadScheduler::schedule (Func && func, Args &&... args) -> std::future<std::invoke_result_t<Func, Args...>> [inline]
Schedules a task to be executed. The templates are not really necessary, see this function's details section in the documentation for more information.
This function does not require you to use the templates. You can simply pass the function and the function's arguments when you call this function. For example, consider the following:
scheduler.schedule(add, 5, 7);
or
scheduler.schedule([](int a, int b) { return a + b; }, 5, 7);
Precondition
For this function to work, the below must be true:
The function must be callable. This means that it must have a return type and it must have arguments.
Atlas must have multi-threading enabled
Atlas must be initialized
Atlas must not be shutting down or in the process of shutting down
This scheduler must be initialized
This scheduler must not be shutting down or in the process of shutting down
Exceptions
std::runtime_error if any of the above conditions are not met
Note
This can be described as a template task scheduler with future return
This class is thread-safe
Parameters
func The function to be executed. It can be any callable object
...args The arguments to be passed to the function
Returns
A future that will contain the return value of the function
Since
v0.0.10
Todo
Todo Review the code in this function to see where some checks need to be added to avoid problems.
Definition at line 300 of file GameThreadScheduler.h.
References mIsRunning, mQueueMutex, mTaskQueue, mWorkAvailableConditional, and void().
setStatus()
void Atlas::GameThreadScheduler::setStatus (EGameThreadSchedulerStatus status) [inline], [private]
Definition at line 167 of file GameThreadScheduler.h.
References mStatus.
Referenced by init().
Member Data Documentation
mIsRunning
std::atomic<bool> Atlas::GameThreadScheduler::mIsRunning [private]
Whether or not this scheduler is running. This does not necessarily mean that there are tasks being executed or in the queue.
Since
v0.0.10
Definition at line 156 of file GameThreadScheduler.h.
Referenced by init(), isRunning(), schedule(), and ~GameThreadScheduler().
mQueueMutex
std::mutex Atlas::GameThreadScheduler::mQueueMutex [private]
The mutex that is used to the tasks queue to be thread-safe.
Since
v0.0.10
Definition at line 142 of file GameThreadScheduler.h.
Referenced by init(), schedule(), and ~GameThreadScheduler().
mStatus
EGameThreadSchedulerStatus Atlas::GameThreadScheduler::mStatus = EGameThreadSchedulerStatus::Unknown [private]
The current status of the scheduler.
Since
v0.0.10
Definition at line 106 of file GameThreadScheduler.h.
Referenced by setStatus().
mTaskQueue
std::queue<Task> Atlas::GameThreadScheduler::mTaskQueue [private]
A queue of tasks assigned to this scheduler. All tasks are executed in the order they are added to the queue. Additionally, the threads get their tasks from this queue.
Since
v0.0.10
See also
mQueueMutex The mutex that is used to make this object thread-safe.
mWorkAvailableConditional The way threads know if there are tasks in the queue available.
Definition at line 135 of file GameThreadScheduler.h.
Referenced by init(), isTaskQueueEmpty(), and schedule().
mThreadCount
uint8_t Atlas::GameThreadScheduler::mThreadCount [private]
Number of threads in this scheduler.
Since
v0.0.10
Definition at line 113 of file GameThreadScheduler.h.
Referenced by getThreadCount().
mWorkAvailableConditional
std::condition_variable Atlas::GameThreadScheduler::mWorkAvailableConditional [private]
Signals to workers that there are tasks available in the task queue.
Since
v0.0.10
Definition at line 149 of file GameThreadScheduler.h.
Referenced by init(), schedule(), and ~GameThreadScheduler().
mWorkersVector
std::vector<std::thread> Atlas::GameThreadScheduler::mWorkersVector [private]
A vector that contains all the worker threads.
Note
The size of this vector is equal to mThreadCount. If not, something is wrong.
Todo
Todo Instead of using std::thread, implement this so that it works with Atlas::GameThread
Since
v0.0.10
Definition at line 124 of file GameThreadScheduler.h.
Referenced by init(), and joinAll().
The documentation for this class was generated from the following file:
C:/Dev/Techstorm-v5/src/engine/core/threading/GameThreadScheduler.h