C:/Dev/Techstorm-v5/src/bindings/imgui_impl_wgpu.cpp File Reference
#include "imgui.h"
#include "imgui_impl_wgpu.h"
#include <limits.h>
#include <webgpu/webgpu.h>
Classes
struct RenderResources
struct FrameResources
struct Uniforms
struct ImGui_ImplWGPU_Data
Macros
#define MEMALIGN(_SIZE, _ALIGN) (((_SIZE) + ((_ALIGN) - 1)) & ~((_ALIGN) - 1))
Functions
ImGuiID ImHashData (const void *data_p, size_t data_size, ImU32 seed=0)
static ImGui_ImplWGPU_Data * ImGui_ImplWGPU_GetBackendData ()
static void SafeRelease (ImDrawIdx *&res)
static void SafeRelease (ImDrawVert *&res)
static void SafeRelease (WGPUBindGroupLayout &res)
static void SafeRelease (WGPUBindGroup &res)
static void SafeRelease (WGPUBuffer &res)
static void SafeRelease (WGPUPipelineLayout &res)
static void SafeRelease (WGPURenderPipeline &res)
static void SafeRelease (WGPUSampler &res)
static void SafeRelease (WGPUShaderModule &res)
static void SafeRelease (WGPUTextureView &res)
static void SafeRelease (WGPUTexture &res)
static void SafeRelease (RenderResources &res)
static void SafeRelease (FrameResources &res)
static WGPUProgrammableStageDescriptor ImGui_ImplWGPU_CreateShaderModule (const char *wgsl_source)
static WGPUBindGroup ImGui_ImplWGPU_CreateImageBindGroup (WGPUBindGroupLayout layout, WGPUTextureView texture)
static void ImGui_ImplWGPU_SetupRenderState (ImDrawData *draw_data, WGPURenderPassEncoder ctx, FrameResources *fr)
void ImGui_ImplWGPU_RenderDrawData (ImDrawData *draw_data, WGPURenderPassEncoder pass_encoder)
static void ImGui_ImplWGPU_CreateFontsTexture ()
static void ImGui_ImplWGPU_CreateUniformBuffer ()
bool ImGui_ImplWGPU_CreateDeviceObjects ()
void ImGui_ImplWGPU_InvalidateDeviceObjects ()
bool ImGui_ImplWGPU_Init (ImGui_ImplWGPU_InitInfo *init_info)
void ImGui_ImplWGPU_Shutdown ()
void ImGui_ImplWGPU_NewFrame ()
Variables
static const char __shader_vert_wgsl []
static const char __shader_frag_wgsl []
Macro Definition Documentation
MEMALIGN
#define MEMALIGN(_SIZE, _ALIGN) (((_SIZE) + ((_ALIGN) - 1)) & ~((_ALIGN) - 1))
Definition at line 63 of file imgui_impl_wgpu.cpp.
Function Documentation
ImGui_ImplWGPU_CreateDeviceObjects()
bool ImGui_ImplWGPU_CreateDeviceObjects ()
Definition at line 613 of file imgui_impl_wgpu.cpp.
References __shader_frag_wgsl, __shader_vert_wgsl, RenderResources::CommonBindGroup, ImGui_ImplWGPU_Data::depthStencilFormat, RenderResources::FontTextureView, RenderResources::ImageBindGroup, RenderResources::ImageBindGroupLayout, RenderResources::ImageBindGroups, ImGui_ImplWGPU_CreateFontsTexture(), ImGui_ImplWGPU_CreateImageBindGroup(), ImGui_ImplWGPU_CreateShaderModule(), ImGui_ImplWGPU_CreateUniformBuffer(), ImGui_ImplWGPU_GetBackendData(), ImGui_ImplWGPU_InvalidateDeviceObjects(), ImHashData(), ImGui_ImplWGPU_Data::initInfo, MEMALIGN, ImGui_ImplWGPU_InitInfo::PipelineMultisampleState, ImGui_ImplWGPU_Data::pipelineState, ImGui_ImplWGPU_Data::renderResources, ImGui_ImplWGPU_Data::renderTargetFormat, SafeRelease(), RenderResources::Sampler, RenderResources::Uniforms, and ImGui_ImplWGPU_Data::wgpuDevice.
Referenced by ImGui_ImplWGPU_NewFrame().
ImGui_ImplWGPU_CreateFontsTexture()
static void ImGui_ImplWGPU_CreateFontsTexture () [static]
Definition at line 524 of file imgui_impl_wgpu.cpp.
References ImGui_ImplWGPU_Data::defaultQueue, RenderResources::FontTexture, RenderResources::FontTextureView, ImGui_ImplWGPU_GetBackendData(), ImGui_ImplWGPU_Data::renderResources, RenderResources::Sampler, and ImGui_ImplWGPU_Data::wgpuDevice.
Referenced by ImGui_ImplWGPU_CreateDeviceObjects().
ImGui_ImplWGPU_CreateImageBindGroup()
static WGPUBindGroup ImGui_ImplWGPU_CreateImageBindGroup (WGPUBindGroupLayout layout, WGPUTextureView texture) [static]
Definition at line 287 of file imgui_impl_wgpu.cpp.
References ImGui_ImplWGPU_GetBackendData(), and ImGui_ImplWGPU_Data::wgpuDevice.
Referenced by ImGui_ImplWGPU_CreateDeviceObjects(), and ImGui_ImplWGPU_RenderDrawData().
ImGui_ImplWGPU_CreateShaderModule()
static WGPUProgrammableStageDescriptor ImGui_ImplWGPU_CreateShaderModule (const char * wgsl_source) [static]
Definition at line 260 of file imgui_impl_wgpu.cpp.
References ImGui_ImplWGPU_GetBackendData(), and ImGui_ImplWGPU_Data::wgpuDevice.
Referenced by ImGui_ImplWGPU_CreateDeviceObjects().
ImGui_ImplWGPU_CreateUniformBuffer()
static void ImGui_ImplWGPU_CreateUniformBuffer () [static]
Definition at line 596 of file imgui_impl_wgpu.cpp.
References ImGui_ImplWGPU_GetBackendData(), MEMALIGN, ImGui_ImplWGPU_Data::renderResources, RenderResources::Uniforms, and ImGui_ImplWGPU_Data::wgpuDevice.
Referenced by ImGui_ImplWGPU_CreateDeviceObjects().
ImGui_ImplWGPU_GetBackendData()
static ImGui_ImplWGPU_Data * ImGui_ImplWGPU_GetBackendData () [static]
Definition at line 111 of file imgui_impl_wgpu.cpp.
Referenced by ImGui_ImplWGPU_CreateDeviceObjects(), ImGui_ImplWGPU_CreateFontsTexture(), ImGui_ImplWGPU_CreateImageBindGroup(), ImGui_ImplWGPU_CreateShaderModule(), ImGui_ImplWGPU_CreateUniformBuffer(), ImGui_ImplWGPU_InvalidateDeviceObjects(), ImGui_ImplWGPU_NewFrame(), ImGui_ImplWGPU_RenderDrawData(), ImGui_ImplWGPU_SetupRenderState(), and ImGui_ImplWGPU_Shutdown().
ImGui_ImplWGPU_Init()
bool ImGui_ImplWGPU_Init (ImGui_ImplWGPU_InitInfo * init_info)
Definition at line 776 of file imgui_impl_wgpu.cpp.
References RenderResources::CommonBindGroup, ImGui_ImplWGPU_Data::defaultQueue, ImGui_ImplWGPU_Data::depthStencilFormat, ImGui_ImplWGPU_InitInfo::DepthStencilFormat, ImGui_ImplWGPU_InitInfo::Device, RenderResources::FontTexture, RenderResources::FontTextureView, ImGui_ImplWGPU_Data::frameIndex, RenderResources::ImageBindGroup, RenderResources::ImageBindGroupLayout, RenderResources::ImageBindGroups, FrameResources::IndexBuffer, FrameResources::IndexBufferHost, FrameResources::IndexBufferSize, ImGui_ImplWGPU_Data::initInfo, ImGui_ImplWGPU_Data::numFramesInFlight, ImGui_ImplWGPU_InitInfo::NumFramesInFlight, ImGui_ImplWGPU_Data::pFrameResources, ImGui_ImplWGPU_Data::renderResources, ImGui_ImplWGPU_Data::renderTargetFormat, ImGui_ImplWGPU_InitInfo::RenderTargetFormat, RenderResources::Sampler, RenderResources::Uniforms, FrameResources::VertexBuffer, FrameResources::VertexBufferHost, FrameResources::VertexBufferSize, and ImGui_ImplWGPU_Data::wgpuDevice.
ImGui_ImplWGPU_InvalidateDeviceObjects()
void ImGui_ImplWGPU_InvalidateDeviceObjects ()
Definition at line 760 of file imgui_impl_wgpu.cpp.
References ImGui_ImplWGPU_GetBackendData(), ImGui_ImplWGPU_Data::numFramesInFlight, ImGui_ImplWGPU_Data::pFrameResources, ImGui_ImplWGPU_Data::pipelineState, ImGui_ImplWGPU_Data::renderResources, SafeRelease(), and ImGui_ImplWGPU_Data::wgpuDevice.
Referenced by ImGui_ImplWGPU_CreateDeviceObjects(), and ImGui_ImplWGPU_Shutdown().
ImGui_ImplWGPU_NewFrame()
void ImGui_ImplWGPU_NewFrame ()
Definition at line 849 of file imgui_impl_wgpu.cpp.
References ImGui_ImplWGPU_CreateDeviceObjects(), ImGui_ImplWGPU_GetBackendData(), and ImGui_ImplWGPU_Data::pipelineState.
ImGui_ImplWGPU_RenderDrawData()
void ImGui_ImplWGPU_RenderDrawData (ImDrawData * draw_data, WGPURenderPassEncoder pass_encoder)
Definition at line 367 of file imgui_impl_wgpu.cpp.
References ImGui_ImplWGPU_Data::defaultQueue, ImGui_ImplWGPU_RenderState::Device, ImGui_ImplWGPU_Data::frameIndex, RenderResources::ImageBindGroupLayout, RenderResources::ImageBindGroups, ImGui_ImplWGPU_CreateImageBindGroup(), ImGui_ImplWGPU_GetBackendData(), ImGui_ImplWGPU_SetupRenderState(), ImHashData(), FrameResources::IndexBuffer, FrameResources::IndexBufferHost, FrameResources::IndexBufferSize, MEMALIGN, ImGui_ImplWGPU_Data::numFramesInFlight, ImGui_ImplWGPU_Data::pFrameResources, ImGui_ImplWGPU_RenderState::RenderPassEncoder, ImGui_ImplWGPU_Data::renderResources, SafeRelease(), FrameResources::VertexBuffer, FrameResources::VertexBufferHost, FrameResources::VertexBufferSize, and ImGui_ImplWGPU_Data::wgpuDevice.
ImGui_ImplWGPU_SetupRenderState()
static void ImGui_ImplWGPU_SetupRenderState (ImDrawData * draw_data, WGPURenderPassEncoder ctx, FrameResources * fr) [static]
Definition at line 299 of file imgui_impl_wgpu.cpp.
References RenderResources::CommonBindGroup, ImGui_ImplWGPU_Data::defaultQueue, Uniforms::Gamma, ImGui_ImplWGPU_GetBackendData(), FrameResources::IndexBuffer, FrameResources::IndexBufferSize, Uniforms::MVP, ImGui_ImplWGPU_Data::pipelineState, ImGui_ImplWGPU_Data::renderResources, ImGui_ImplWGPU_Data::renderTargetFormat, RenderResources::Uniforms, FrameResources::VertexBuffer, and FrameResources::VertexBufferSize.
Referenced by ImGui_ImplWGPU_RenderDrawData().
ImGui_ImplWGPU_Shutdown()
void ImGui_ImplWGPU_Shutdown ()
Definition at line 829 of file imgui_impl_wgpu.cpp.
References ImGui_ImplWGPU_Data::defaultQueue, ImGui_ImplWGPU_Data::frameIndex, ImGui_ImplWGPU_GetBackendData(), ImGui_ImplWGPU_InvalidateDeviceObjects(), ImGui_ImplWGPU_Data::numFramesInFlight, ImGui_ImplWGPU_Data::pFrameResources, and ImGui_ImplWGPU_Data::wgpuDevice.
ImHashData()
ImGuiID ImHashData (const void * data_p, size_t data_size, ImU32 seed = 0) [extern]
Referenced by ImGui_ImplWGPU_CreateDeviceObjects(), and ImGui_ImplWGPU_RenderDrawData().
SafeRelease() [1/13]
static void SafeRelease (FrameResources & res) [static]
Definition at line 252 of file imgui_impl_wgpu.cpp.
References FrameResources::IndexBuffer, FrameResources::IndexBufferHost, SafeRelease(), FrameResources::VertexBuffer, and FrameResources::VertexBufferHost.
SafeRelease() [2/13]
static void SafeRelease (ImDrawIdx *& res) [static]
Definition at line 174 of file imgui_impl_wgpu.cpp.
Referenced by ImGui_ImplWGPU_CreateDeviceObjects(), ImGui_ImplWGPU_InvalidateDeviceObjects(), ImGui_ImplWGPU_RenderDrawData(), SafeRelease(), and SafeRelease().
SafeRelease() [3/13]
static void SafeRelease (ImDrawVert *& res) [static]
Definition at line 180 of file imgui_impl_wgpu.cpp.
SafeRelease() [4/13]
static void SafeRelease (RenderResources & res) [static]
Definition at line 241 of file imgui_impl_wgpu.cpp.
References RenderResources::CommonBindGroup, RenderResources::FontTexture, RenderResources::FontTextureView, RenderResources::ImageBindGroup, RenderResources::ImageBindGroupLayout, SafeRelease(), RenderResources::Sampler, and RenderResources::Uniforms.
SafeRelease() [5/13]
static void SafeRelease (WGPUBindGroup & res) [static]
Definition at line 192 of file imgui_impl_wgpu.cpp.
SafeRelease() [6/13]
static void SafeRelease (WGPUBindGroupLayout & res) [static]
Definition at line 186 of file imgui_impl_wgpu.cpp.
SafeRelease() [7/13]
static void SafeRelease (WGPUBuffer & res) [static]
Definition at line 198 of file imgui_impl_wgpu.cpp.
SafeRelease() [8/13]
static void SafeRelease (WGPUPipelineLayout & res) [static]
Definition at line 204 of file imgui_impl_wgpu.cpp.
SafeRelease() [9/13]
static void SafeRelease (WGPURenderPipeline & res) [static]
Definition at line 210 of file imgui_impl_wgpu.cpp.
SafeRelease() [10/13]
static void SafeRelease (WGPUSampler & res) [static]
Definition at line 216 of file imgui_impl_wgpu.cpp.
SafeRelease() [11/13]
static void SafeRelease (WGPUShaderModule & res) [static]
Definition at line 222 of file imgui_impl_wgpu.cpp.
SafeRelease() [12/13]
static void SafeRelease (WGPUTexture & res) [static]
Definition at line 234 of file imgui_impl_wgpu.cpp.
SafeRelease() [13/13]
static void SafeRelease (WGPUTextureView & res) [static]
Definition at line 228 of file imgui_impl_wgpu.cpp.
Variable Documentation
__shader_frag_wgsl
const char __shader_frag_wgsl[] [static]
Initial value:
= R"(
struct VertexOutput {
    @builtin(position) position: vec4<f32>,
    @location(0) color: vec4<f32>,
    @location(1) uv: vec2<f32>,
};
struct Uniforms {
    mvp: mat4x4<f32>,
    gamma: f32,
};
@group(0) @binding(0) var<uniform> uniforms: Uniforms;
@group(0) @binding(1) var s: sampler;
@group(1) @binding(0) var t: texture_2d<f32>;
@fragment
fn main(in: VertexOutput) -> @location(0) vec4<f32> {
    let color = in.color * textureSample(t, s, in.uv);
    let corrected_color = pow(color.rgb, vec3<f32>(uniforms.gamma));
    return vec4<f32>(corrected_color, color.a);
}
)"
Definition at line 150 of file imgui_impl_wgpu.cpp.
Referenced by ImGui_ImplWGPU_CreateDeviceObjects().
__shader_vert_wgsl
const char __shader_vert_wgsl[] [static]
Initial value:
= R"(
struct VertexInput {
    @location(0) position: vec2<f32>,
    @location(1) uv: vec2<f32>,
    @location(2) color: vec4<f32>,
};
struct VertexOutput {
    @builtin(position) position: vec4<f32>,
    @location(0) color: vec4<f32>,
    @location(1) uv: vec2<f32>,
};
struct Uniforms {
    mvp: mat4x4<f32>,
    gamma: f32,
};
@group(0) @binding(0) var<uniform> uniforms: Uniforms;
@vertex
fn main(in: VertexInput) -> VertexOutput {
    var out: VertexOutput;
    out.position = uniforms.mvp * vec4<f32>(in.position, 0.0, 1.0);
    out.color = in.color;
    out.uv = in.uv;
    return out;
}
)"
Definition at line 120 of file imgui_impl_wgpu.cpp.
Referenced by ImGui_ImplWGPU_CreateDeviceObjects().